### ISSUE TITLE
MYpal 68 on windows vista sp2 observations.

### ISSUE THREAD

**Issue by cartdude54** [Feodor2/Mypal68#1]
I decided to try this browser on windows vista 64 bit with just service pack 2 no updates installed or extended kernel and I must say it performed very nicely. Most facebook games that do not currently load on windows xp load and play on vista with the exception of uno which just goes to a black screen. The older version of mypal does load all the facebook games on windows xp so I can use it when running xp to play those non working games.

**Comment by Lovecatsandyou** [comment]
I think I have service pack 2 and I installed mypal68 and it gives me problems logging into sites like Facebook...what is your mypal 68 version?
