### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by NoNameNeeded2** [Feodor2/Mypal68#10]
On this site the comments section (below the articles) won't be loaded most of the times.
(you won't be able to see it unless you register there, AFAIK)
https://www.derstandard.at/

HOWEVER, that's not a Mypal68 problem, it happens on Firefox 68 as well.

So even though I really appreciate that Feodor was able to get a more recent version of Firefox to work on Windows XP, I wonder if Firefox 68 is the best solution since compatibility issues already start to appear.

**Comment by rjjiii** [comment]
Building 68 for XP is a step towards building current versions for XP. Once 68 is stable on XP, then changes for the next releases can be tested on Mypal.
