### ISSUE TITLE
MDN Web Docs -  100% RAM usage

### ISSUE THREAD

**Issue by AstroSkipper** [Feodor2/Mypal68#100]
Hi Feodor2, this site has an extreme problem loading in Mypal 68: https://developer.mozilla.org/de/docs/Web/CSS/appearance 
Most docs at **MDN Web Docs** are loading as expected, but the doc with information about **-moz-appearance** leads to an usage of 100% of RAM and an unresponsiveness of Mypal 68 on my computer. I tested this site in roytam1's browser releases and it loads as it should be. There are elements and a lot of demos relating to the property **moz-appearance** in this doc, and maybe interesting to find further bugs in Mypal 68. That's the reason I didn't list it in the issue **NOT WORKING SITES LIST [POST HERE ONLY!] #82**.

Cheers, AstroSkipper [![surmene.gif](https://i.postimg.cc/x1mb7X9x/surmene.gif)](https://postimg.cc/LJHXg6YL)

**Comment by NoNameNeeded2** [comment]
In my case the cpu load is quite high but sinks after a few seconds.

**Comment by AstroSkipper** [comment]
> In my case the cpu load is quite high but sinks after a few seconds.

I run Mypal 68 in a fully updated Windows XP Pro on an old computer with low hardware resources, a Pentium 4 single core CPU and 1.5 GB RAM only. The site mentioned above is locking my browser and my complete system unlike in roytam1 browsers. Presumably, this problem is less serious on modern computers.

**Comment by NoNameNeeded2** [comment]
Oh, I see.
Well, to be honest, this computer is probably just too old to use the new mypal version.
My mother's computer is a similar machine, a Pentium 4 (with HT) and 1GB of RAM:
I was trying to run 360 explorer but it takes ages before it even starts, it's completely useless.
I assume it's similar with Mypal68.
It's probably not AS bad as with 360 explorer but as soon as you try to load a page with loads of stuff to be loaded it won't be much fun to use anymore.

Roytam's browsers are based on much older versions of Firefox. THESE work pretty nicely on old computers but they're completely outdated.

**Comment by AstroSkipper** [comment]
> Oh, I see. Well, to be honest, this computer is probably just too old to use the new mypal version. My mother's computer is a similar machine, a Pentium 4 (with HT) and 1GB of RAM: I was trying to run 360 explorer but it takes ages before it even starts, it's completely useless. I assume it's similar with Mypal68. It's probably not AS bad as with 360 explorer but as soon as you try to load a page with loads of stuff to be loaded it won't be much fun to use anymore.
> 
> Roytam's browsers are based on much older versions of Firefox. THESE work pretty nicely on old computers but they're completely outdated.

**Yes**, my computer is very old, and **no**, Mypal 68 runs **like a charm** on my old Windows XP computer with low hardware resources, a Pentium 4 2.8 GHz single core CPU and 1.5 GB RAM only. And 360Chrome v11 **too**. As I already mentioned, this particular site doesn't load properly in Mypal 68 **unlike** roytam1's browsers. It's an infinity load **up to 100% of RAM**. In **Iceape-UXP** for example, this site is loaded in a few seconds and works.  I think Mypal 68 has problems with the code on this particular site, and maybe, it's interesting for finding further bugs in Mypal's code. Nothing else.

**Comment by Feodor2** [comment]
Checked on the original 68 firefox, it takes 1gb memory when loads and 600 after loaded.
Also checked on 91 firefox - 1gb and 500mb respectively.
The Сonclusion to newer firefoxes this is normal memory usage for this site.

**Comment by AstroSkipper** [comment]
> Checked on the original 68 firefox, it takes 1gb memory when loads and 600 after loaded. Also checked on 91 firefox - 1gb and 500mb respectively. The Сonclusion to newer firefoxes this is normal memory usage for this site.

Thanks, Feodor2, for checking this misbehavior! Unfortunately, no good news. Any ideas why this misbehavior can't be observed in roytam1's browser editions? I tested Iceape-UXP and New Moon, and both are able to load this site normally with a small amount of RAM usage, less than 50 MB. Do you think there is a chance to fix it, beside blocking scripts or images? Maybe, some settings in about:config?

Kindest regards, AstroSkipper [![surmene.gif](https://i.postimg.cc/x1mb7X9x/surmene.gif)](https://postimg.cc/LJHXg6YL)

**Comment by NoNameNeeded2** [comment]
I think there seems to be some kind of memory leak on this website.
On Mypal29 the RAM usage just skyrocketed, on Mypal68 it's not as bad (comparable to more recent browsers).
On NewMoon 28 everything is fine though.
Maybe it's not able to load the stuff which needs so much RAM, that would explain it.
