### ISSUE TITLE
Added search engines don't persist between restarts

### ISSUE THREAD

**Issue by Nosen92** [Feodor2/Mypal68#102]
Adding google using this site: [link](https://mycroftproject.com/install.html?id=14909&basename=google&icontype=ico&name=Google)
The added search engine disappears when closing and reopening Mypal 68.
Mypal version: 68.12.4b (32-bit)
OS version: Windows XP Integral Edition 2022.6.18
[DxDiag.txt](https://github.com/Feodor2/Mypal68/files/8959786/DxDiag.txt)

**Comment by Feodor2** [comment]
For me did not disappears ]

**Comment by Nosen92** [comment]
Did a reinstall, seems to have solved the issue. Closing

**Comment by Nosen92** [comment]
Closing

**Comment by Feodor2** [comment]
"your comment cannot be blank."
i got this shit and may not close.

**Comment by Feodor2** [comment]
is the github something messed - shithedas

**Comment by danielmcardle** [comment]
I'm having the exact same issue, a reinstall did not fix the issue. Any ideas?
