### ISSUE TITLE
Add-ons Manager - Manage Your Extensions - New issue

### ISSUE THREAD

**Issue by AstroSkipper** [Feodor2/Mypal68#104]
Hi Feodor2. When clicking an add-on in the Add-ons Manager, a new problem occurs in your latest version **68.12.4b**. Instead of showing the page containing **Details** and **Permissions**, I get this error:

> **The address wasn’t understood.** Mypal doesn’t know how to open this address, because one of the following protocols (addons) isn’t associated with any program or is not allowed in this context. You might need to install other software to open this address.

Never seen before! The menu item **More Options** works as expected. In your previous version **68.12.3b**, there was no such issue. I tested it with two different profiles. I seriously hope the problem won't be on my side, what would mean, I'd have an issue in my system. [![grattermenton.gif](https://i.postimg.cc/3Nw3kxMh/grattermenton.gif)](https://postimg.cc/gX1C5dkt)

Cheers, AstroSkipper [![jexplique.gif](https://i.postimg.cc/1RTXQyCL/jexplique.gif)](https://postimg.cc/23QrdNfw)

**Comment by Feodor2** [comment]
I did not reproduce this, lets somebody else check.

**Comment by AstroSkipper** [comment]
> I did not reproduce this, lets somebody else check.

Hi Feodor2, I created a new profile, deactivated my style sheets settings, and I found the cause of this problem. I prefer using Mypal 68 in single process mode, and therefore, I set **browser.tabs.remote.autostart** to **false**. When doing this, your recent version **68.12.4b** shows the described misbehaviour above. Something must have been changed since previous release **68.12.3b**. In this previous version, I didn't observe this issue. Hope, this will help you find a solution.

Cheers, AstroSkipper [![ordi1fun.gif](https://i.postimg.cc/k4q8W73j/ordi1fun.gif)](https://postimg.cc/FfC745Kc)

**Comment by NoNameNeeded2** [comment]
Try this little application.

https://www.rizonesoft.com/downloads/firemin/

It reduces the RAM usage of Firefox (or Mypal...) 
I didn't really think it would work without tremendously slowing down the browser but for some strange reason, it really works very well.
At least on a relatively new computer.
My RAM usage on Firefox 91 dropped to about 400MB max, even with HD youtube videos playing.
I've also tried it with Mypal. It works as well.
However, there might be some audio dropouts in videos when "Enable extended processes" is ticked.

I have no clue how well it works on ancient computers like yours but don't give up too soon.
You can try different settings (you'll see it if/when you install it) and maybe it'll help to reduce the RAM usage drastically without slowing down Mypal noticeably.

**Comment by AstroSkipper** [comment]
> Try this little application.
> 
> https://www.rizonesoft.com/downloads/firemin/
> 
> It reduces the RAM usage of Firefox (or Mypal...) I didn't really think it would work without tremendously slowing down the browser but for some strange reason, it really works very well. At least on a relatively new computer. My RAM usage on Firefox 91 dropped to about 400MB max, even with HD youtube videos playing. I've also tried it with Mypal. It works as well. However, there might be some audio dropouts in videos when "Enable extended processes" is ticked.
> 
> I have no clue how well it works on ancient computers like yours but don't give up too soon. You can try different settings (you'll see it if/when you install it) and maybe it'll help to reduce the RAM usage drastically without slowing down Mypal noticeably.

Thanks for your reply! **Firemin** is already present for years. But it won't help in the case of Mypal 68. On my old machine, Mypal 68 can be used only in single process mode, otherwise I can only open two tabs at most. More recent browsers are awful in RAM consumption. My only hope is that Feodor2 can revert the code associated with this issue as it was in the previous version 68.12.3b.

Cheers, AstroSkipper

**Comment by Feodor2** [comment]
I switched **browser.tabs.remote.autostart** and still did not get the error.
You may do this: launch the browser - open the console - there will be errors of course - ignore them - open the errorful addon options - look for new errors in the console - tell me what is the addon and put the error data.

**Comment by AstroSkipper** [comment]
Here is a screenshot after setting **browser.tabs.remote.autostart** to **true** and restarting the browser:

[![Add-ons-Manager-No-issue.png](https://i.postimg.cc/jd2kR3mt/Add-ons-Manager-No-issue.png)](https://postimg.cc/zVmkj7qc)

In this case, the only message I can see is **"Stylesheets without CSSOM changes reparsed to check for errors. Refresh the page to also see errors from stylesheets changed from CSSOM and from style attributes. 4"**

And now a screenshot after setting **browser.tabs.remote.autostart** to **false** and restarting the browser:

[![Add-ons-Manager-Issue.png](https://i.postimg.cc/ncf6pfB7/Add-ons-Manager-Issue.png)](https://postimg.cc/QVS6JP6x)

In this case, the only message I can see is **"Stylesheets without CSSOM changes reparsed to check for errors. Refresh the page to also see errors from stylesheets changed from CSSOM and from style attributes. 3"**

Tested in a fresh profile with only one extension installed. What kind of extension, doesn't matter. Clicking in the **Add-ons Manager** onto the extension's entry, leads to this issue when the variable **browser.tabs.remote.autostart** was set to **false**. This issue can be reproduced in each of my profiles. Unfortunately, I can't see further errors in the web console. Please, let me know what I can do to provide more data associated with this issue!

Kindest regards, AstroSkipper [![matrix.gif](https://i.postimg.cc/9XNRQdMg/matrix.gif)](https://postimg.cc/RqKVPnww)

**Comment by NoNameNeeded2** [comment]
I just tried this and I can't confirm this problem.
The settings page of the Addon (I even installed the same one) is still displayed normally after setting browser.tabs.remote.autostart to false.

Very strange.

**Comment by AstroSkipper** [comment]
Thanks, NoNameNeeded2, for your reply and test! I totally agree with your statement that this is a bit strange.
Therefore, I checked again and did a deeper investigation of this issue. I examined all variables and combinations of them in about:config, but without any success. But **Goddess Fortuna** unexpectedly came to my aid. Here are the instructions to reproduce the issue ultimately (at least I do hope so):
1. Set the **variable browser.tabs.remote.autostart** to **false**.
2. **Restart** the browser.
3. Open Add-ons Manager and ensure you see the **list** of the installed extensions.
4. Now, do **not** click onto the image of each extension outside left, **but** onto the extension's link right next to it.
5. Now the issue should occur, actually.
If you click onto the image of each extension outside left, the page with the **Details** and **Permissions** will be shown as expected.
**My personal conclusion:** If the **variable browser.tabs.remote.autostart** is set to **false**, i.e., using **single process mode**, the extension's link isn't associated as it should be. When setting back the variable **browser.tabs.remote.autostart** to **true**, i.e., reverting to **multiprocess mode**, and restarting the browser, the extension's link is associated as it has to be. Hope, this will help you, Feodor2.

Kindest regards, AstroSkipper [![matrix.gif](https://i.postimg.cc/9XNRQdMg/matrix.gif)](https://postimg.cc/RqKVPnww)

**Comment by NoNameNeeded2** [comment]
Ok, now I can confirm it.

It's very strange, though.
Sometimes the problem occurs when you click on the name of the addon (it is in fact more likely to occur when you click on the name than on the decription below or the picture beside the name) or sometimes it doesn't occur.
All the other stuff (themes, settings) won't be available either when the problem occurs.

But you can just close the tab and re-open it and avoid to click on the name.

**Comment by AstroSkipper** [comment]
> Ok, now I can confirm it.

Hi Feodor2, thanks for your confirmation! I am glad you could reproduce it finally.

> But you can just close the tab and re-open it and avoid to click on the name.

Reloading the page works either. Of course, avoiding a click on the extension's link is a suitable, temporary solution. Do you think it can be fixed in the future? In your previous release **68.12.3b**, this issue doesn't occur. Something in your code must have been changed since then. Anyway, I am really glad that I am not the only one observing this issue.

Cheers, AstroSkipper [![ecrire-ordi.gif](https://i.postimg.cc/g0mccjP2/ecrire-ordi.gif)](https://postimg.cc/1871J9tk)

**Comment by NoNameNeeded2** [comment]
I'm afraid I'm not Feodor.

**Comment by AstroSkipper** [comment]
> I'm afraid I'm not Feodor.

You're right. There is only one Feodor2. But, anyway, thanks again for your efforts!

Cheers, AstroSkipper [![ordi1fun.gif](https://i.postimg.cc/k4q8W73j/ordi1fun.gif)](https://postimg.cc/FfC745Kc)

**Comment by Feodor2** [comment]
The protocol **addons://** seems broken with single process. Interesting what it supposed to do and why it works when click image even in the single process. Anyway this is a minor error i shall not hurry to fix it.
