### ISSUE TITLE
Some sites don't work: Bitchute / Google Help Forum

### ISSUE THREAD

**Issue by sirrooster** [Feodor2/Mypal68#106]
Google help community site does not full open in MyPal68.
https://support.google.com/accounts/thread/168513255
It does not show the posting (forum-thread) and has not full functionallity.

Also www.bitchute.com does not play Videos

**Comment by NoNameNeeded2** [comment]
That's a problem inherited from Firefox 68.
There isn't much you can do about it.

**Comment by Feodor2** [comment]
#82
