### ISSUE TITLE
Github Notifikation cannot be set anymore

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#107]
Github Notifikation Linking cannot be set anymore in MyPal68, and some other Github Links can only be addressed by opening them as/in a NEW Window:
![mypal_gihub_problem](https://user-images.githubusercontent.com/12776547/175817261-afdc24bf-5863-4808-829f-72febe85de03.png)

**Comment by Feodor2** [comment]
try #74

**Comment by IP-CAM** [comment]
Works perfect, thanks a lot!
