### ISSUE TITLE
Nothing works on Github anymore

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#109]
All of a sudden, about since one hour ago, nothing works on Gighub anymore, I cannot even upload an error image to my Postings.

**Comment by Feodor2** [comment]
The actual shits are #60 which may not be simple enabled.  Still 360 Chrome 13 works.
The thing is that i am busy these days and don't attend to the browser.

**Comment by IP-CAM** [comment]
Just downloaded and installed the 360 Chrome Browser, and it does not work on Github either with my XP.

**Comment by NoNameNeeded2000** [comment]
It does work with version 13 of 360 Chrome.

**Comment by NoNameNeeded2** [comment]
However, it doesn't work in Waterfox Classic either so they obviously weren't able to port newer stuff to Waterfox Classic.

**Comment by Vangelis66** [comment]
> nothing works on **Gighub** anymore

LOL 😅 ; and I initially thought OP was referring to:  

https://www.gighub.com/

Then realised "**g**" is just below "**t**" in my keyboard... 😊
