### ISSUE TITLE
LinkedIn access

### ISSUE THREAD

**Issue by fastnetcom** [Feodor2/Mypal68#111]
Hello
Is it expected to fix access to LinkedIn site? It seems it checks version of the browser and OS and prevent access...

**Comment by 0x8008** [comment]
> Is it expected to fix access to LinkedIn site? It seems it checks version of the browser and OS and prevent access...

Try changing your useragent to the one below:

`Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0 Mypal/68.12.4`

**Comment by fastnetcom** [comment]
Did you try it? It does not work for me.
