### ISSUE TITLE
Mypal's built-in Task Manager

### ISSUE THREAD

**Issue by AstroSkipper** [Feodor2/Mypal68#112]
Hi Feodor2, opening the built-in Task Manager leads to a tab with the correct columns, but no processes are show. Is it not implemented yet? Or doesn't it work? [![grattermenton.gif](https://i.postimg.cc/3Nw3kxMh/grattermenton.gif)](https://postimg.cc/gX1C5dkt)

Kind regards, AstroSkipper [![surmene.gif](https://i.postimg.cc/x1mb7X9x/surmene.gif)](https://postimg.cc/LJHXg6YL)

**Comment by NoNameNeeded2** [comment]
It works fine for me BUT you should really forget about the task manager anyway, since the RAM usage displayed is way lower than it really is. The data is therefore not accurate.
(I can only guess about the performance/CPU data though)

**Comment by AstroSkipper** [comment]
> It works fine for me BUT you should really forget about the task manager anyway, since the RAM usage displayed is way lower than it really is. The data is therefore not accurate. (I can only guess about the performance/CPU data though)

Hi, thanks for your reply! In which mode did you check it, single or multiprocess mode?

**Comment by NoNameNeeded2** [comment]
Both.
It works in both modes.

**Comment by AstroSkipper** [comment]
> Both. It works in both modes.

I can't confirm this. In multiprocess mode, it works, in single-process mode, it doesn't.
