### ISSUE TITLE
Problems on GitHub

### ISSUE THREAD

**Issue by AstroSkipper** [Feodor2/Mypal68#113]
GitHub seems broken since today or some days before. I don't know exactly. A couple of days before, no problems to access and manage my account on GitHub using Mypal 68. But now, the personal account menu in the corner right above is inaccessible. A warning pops up, saying "**Sorry, something went wrong**". The editors preview doesn't work either. And any GIF animation has stopped although **layout.css.resizeobserver.enabled** is set to **true**.  I don't know whether it is temporary or not. All of that just doesn't work anymore..

Cheers, AstroSkipper [![pcwut.gif](https://i.postimg.cc/qR1tnnGR/pcwut.gif)](https://postimg.cc/XGy76rmS)

**Comment by IP-CAM** [comment]
I already posted about this severe Github Problem a couple of days ago, and Feodor2 informed to check on the matter as soon as possible.

**Comment by AstroSkipper** [comment]
> I already posted about this severe Github Problem a couple of days ago, and Feodor2 informed to check on the matter as soon as possible.

I saw your post, but it was about **GigHub** and not **GitHub**. So where did you post about the new GitHub problems?

**Comment by IP-CAM** [comment]
Well, I could not fix the writing error, due to the scripting problem we all face ... :) :)

**Comment by AstroSkipper** [comment]
> Well, I could not fix the writing error, due to the scripting problem we all face ... :) :)

Sorry, I really thought you meant GigHub. But anyway, thanks for the information!
