### ISSUE TITLE
68.12.4b - any HTML content is invisible (completely transparent)

### ISSUE THREAD

**Issue by zanud** [Feodor2/Mypal68#116]
On my Windows XP SP3 Mypal 68.12.4b is completely unusable. After launching it, Windows displays sequentially two identical message windows ("Error found. Application will be closed."), and program's window appears but empty:
![1](https://user-images.githubusercontent.com/76625744/178105840-5f9a16f7-d5c0-42c8-b787-025fdf0d9abd.png)
And then attempts to open any Web page after some status bar activity end with the same empty window.
But in fact, window is not empty. Its content is there, but it is invisible (completely transparent). Lets look closely at start page:
![2](https://user-images.githubusercontent.com/76625744/178105841-834c9cf0-68f3-41ce-ba2d-3ceafd8344d5.png)
![3](https://user-images.githubusercontent.com/76625744/178105842-99408e8c-1c90-41f2-b169-814d1c3ab9be.png)
As a base point how this start page looks after "Restart with Add-ons Disabled":
![0](https://user-images.githubusercontent.com/76625744/178105843-810c733a-58d2-4638-9675-6e61c14a8519.png)

It is a "first run" situation (no "Mypal68" subdirectory in the "Application Data" directories), so no influence from data leaved by previous runs of Mypal68. And version 68.12.3b works fine on the same computer.

Most probably, the issue is tied with video drivers. What settings in about:config should I try to change in order to locate the cause of problem?

**Comment by zanud** [comment]
As I have discovered, the problem appears only if both multiprocessing and hardware acceleration are enabled (regardless of allowed number of processes).

If any of above mentioned parameters is disabled ("`browser.tabs.remote.autostart` = false" or "`layers.acceleration.disabled` = true") the browser works normally.

**Comment by NEO-SPECTRUMAN** [comment]
@Feodor2 
маякну, что есть описание решения проблем
которое можно добавить в readme.md
тк под бессмысленным потоком списка нерабочих сайтов от нуб0в хрен что видно

**Comment by Feodor2** [comment]
Yes hardware acceleration added first in 68.12.4 and has many errors.

**Comment by stanrames** [comment]
browser.tabs.remote.autostart was false
layers.acceleration.disabled was false, set to true
No change.

**Comment by Feodor2** [comment]
provide drwatson.log or at least zip like in #136

**Comment by zanud** [comment]
Is is necessary still? Reported problem was in the version 68.12.4b, and not present in the version 68.12.5b. So, I think, this issue may be closed.
