### ISSUE TITLE
Mypal68 add a language that is not officially supported?

### ISSUE THREAD

**Issue by XPMilkChan** [Feodor2/Mypal68#119]
Will mypal add languages that are not officially supported? I'm interested in adding my language.

THAI (Thailand) (041e)
I may not be very good at programming.

example
![bandicam 2022-07-14 19-11-42-692](https://user-images.githubusercontent.com/106049626/178979781-0e883b4a-0d1a-4d9a-9fb4-78c3e10bc13a.jpg)

**Comment by zanud** [comment]
Regular Firefox 68 language file ([http://ftp.mozilla.org/pub/firefox/releases/68.12.0esr/win32/xpi/th.xpi](http://ftp.mozilla.org/pub/firefox/releases/68.12.0esr/win32/xpi/th.xpi)) should be usable for Mypal68 too.

**Comment by XPMilkChan** [comment]
> Regular Firefox 68 language file (http://ftp.mozilla.org/pub/firefox/releases/68.12.0esr/win32/xpi/th.xpi) should be usable for Mypal68 too. Just click on this link.

Thanks, it works, but it looks like it's still a translation of Firefox, which might need to be fixed.
![bandicam 2022-07-15 18-22-47-376](https://user-images.githubusercontent.com/106049626/179214201-89fb4b62-f18c-44fd-af4c-fe2196153464.jpg)

**Comment by zanud** [comment]
> it's still a translation of Firefox

Who cares? :smile:
Mypal68 itself is a Firefox 68 build tweaked to be compilable and runnable on Windows XP

> which might need to be fixed.

On the other hand, .xpi is just a .zip archive containing plain text files (with unusual filename extensions: .dtd, .properties, .ftl...), so anyone can edit any of these files, and then use fixed translation and even share it with other users.
But... who cares? :smiling_face_with_tear:

**Comment by XPMilkChan** [comment]
> > it's still a translation of Firefox
> 
> Who cares? 😄 Mypal68 itself is a Firefox 68 build tweaked to be compilable and runnable on Windows XP
> 
> > which might need to be fixed.
> 
> On the other hand, .xpi is just a .zip archive containing plain text files (with unusual filename extensions: .dtd, .properties, .ftl...), so anyone can edit any of these files, and then use fixed translation and even share it with other users. But... who cares? 🥲

No one cares as much as me

**Comment by Feodor2** [comment]
Told that languages are not important now and will be done after all other important things.
