### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by RickzDO** [Feodor2/Mypal68#120]
Regards,

tested netflix, don't work, after some minutes closed MyPal and bummmm BSOD... has happend couple of times already..
attached screen
![IMG_20220714_171443](https://user-images.githubusercontent.com/93270734/179090075-063971be-0d3c-4565-9950-137e83dd9b24.jpg)

OS: XP PRO x86 SP3 (with all updates)

**Comment by Feodor2** [comment]
#3
