### ISSUE TITLE
File dialogs do not work, clipboard uploading is broken and the address bar does not work correctly. 

### ISSUE THREAD

**Issue by dragogos-6432** [Feodor2/Mypal68#121]
I'm using MyPal 68.12.4b on Windows XP Professional with Service Pack 4. I can't post screenshots or any type of files on any website because the file dialogs do not work and clipboard uploading doesn't work too. The address bar search function is broken too, when I try to search for something, the thing thinks that I'm trying to access a link instead of opening up Google. 

Any help is appreciated.

**Comment by Matiasgroen** [comment]
For the address bar search see #54

**Comment by Feodor2** [comment]
#109 for screenshots
