### ISSUE TITLE
Crash without Blue Screen

### ISSUE THREAD

**Issue by hhoonj** [Feodor2/Mypal68#123]
crash when shut down Mypal. I am running XP SP3. 
I was unable to attached my log file drwtsn32.log

**Comment by Feodor2** [comment]
Attachment feature likely will be fixed soon on new version 68.12.5

**Comment by hhoonj** [comment]
Thank for the great new and your hard work!

**Comment by stanrames** [comment]
Not on shutdown for me. XP32, OLD Sony Vaio with XP Media Center Edition.
Often, I get a small window, MyPal has experienced a problem an will shut down.
But it doesn't.
Then, just now, to get the device code, opened that account and the entire program was gone. No warning. Not in "task manager" to bring to front.
Re-launched, and all tabs opened back up, including this one.
I have 28 opened also so I can go there when this happens.
FireFox has NEVER worked on this machine. MyPal, both versions, does.
68.12.1 on this machine. Afraid to go higher until I know it works. 68.12.4b works great on my XP-64 desktop,
DrWatson was NOT launched, is now, so there are no logs to post.
I have other issues, will search for a thread that covers it, if not:
Ghostery and UBlock Origin load, click on them to actually USE them, you get small empty windows. No ability to use them.

**Comment by hhoonj** [comment]
Installed Mypal 68.12.5b and no more system crush and everything do far so good! Thanks Feodor2!!

**Comment by Feodor2** [comment]
You are welcome

**Comment by hhoonj** [comment]
I run the Mypal 68.12.5b yesterday the whole day and so far so good. At the end of the day before I shut the PC, while I close Mypal, the PC shut down and then restart. Not sure if this has anything to do with the 68.12.5b or not. I will try is again for a few more day to find out if the same event repeat.

**Comment by hhoonj** [comment]
Tried again and when I shut down Mypal 68.12.5b, the PC shut down too. I am on XP SP3.

**Comment by hhoonj** [comment]
ZIP file for 68.12.5b refused to open.

**Comment by hhoonj** [comment]
Tried running Mypal 68.12.5b again. After I completed a session and I close Mypal, it caused the PC to shut down as well. Using XP SP3.
