### ISSUE TITLE
[SUGGESTION] Renaming Mypal/Mypal 68 to Mypal Quantum and Bringing Firefox like Version and Naming Scheme

### ISSUE THREAD

**Issue by SaranSDS008** [Feodor2/Mypal68#124]
Hi,
So basically, i'm making a request to rename New Mypal or Mypal 68 to Mypal Quantum.
It not alone sounds cosmetically nice in my opinion, but also, it does serve some important purpose underneath as well. Basically, if you decide to upgrade from version 68 to version 78, you might have to change this whole repository's name or create new one, browser's name, etc, which becomes tedious job. But having the name as Mypal Quantum, it does reflect the engine that its being powered by (aka Firefox Quantum, Reference: https://www.mozilla.org/en-US/firefox/browsers/quantum/). Also, you dont need to change the name of whole browser if you are upgrading versions of browser.

So, basically, the browser can be called in general by public as Mypal Quantum and denoted as Mypal Quantum (Version String) [Release Channel] similar to Firefox. Eg: Mypal Quantum 68.0.10 ESR (Not a real version, but just a mock-up of naming scheme, which is similar to Firefox). The about screen could be similar to Firefox 60 ESR's Format as shown in pic, with the Mypal Logo instead of Firefox one, The text being written as Mypal Quantum instead of Firefox Quantum and having another colored Color scheme (i suggest Dark Forest Green, but its upto the dev) as well instead of violet ff color scheme.

![image](https://user-images.githubusercontent.com/88842885/180070397-af059e7d-f76d-4ca5-9b87-5fa6ce21a528.png)

And the GitHub release page could be: Feodor2/MypalQuantum instead of Mypal68, so it would be easy to switch versions and not change the whole name.
Also, im suggesting having build Channels similar to firefox like Dev, Nightly, Stable (aka Rapid Release) and ESR in future if possible.

And also, thx a lot for  bringing a Modern Firefox based off of Quantum Engine to Windows Xp.

**Comment by SaranSDS008** [comment]
I made this about screen hastily using Firefox 60 ESR as template as a mock up/suggestion of the about screen based on my about screen suggestion. This should give an idea of the suggestion of the about screen. Hope the dev likes it.

![Mypal Quantum 60 ESR About Screen Final](https://user-images.githubusercontent.com/88842885/180084429-706c7b89-ca87-413e-b76f-39487d548e84.png)

**Comment by NEO-SPECTRUMAN** [comment]
put this quantum to your ass hole
quantum is a synonym of fckn mozilla addon/gui appocalypse/degradation

**Comment by NoNameNeeded2** [comment]
...and it's also the Firefox version the new Mypal is based on, so it's not so far-fetched.

**Comment by SaranSDS008** [comment]
> put this quantum to your ass hole quantum is a synonym of fckn mozilla addon/gui appocalypse/degradation

Isn't New Mypal based off of the same Quantum Engine that you re trashing rn? Im not a fan of mozilla either (Yes, Proton sucks, and Newer Quantum Engine since Version 90 is Bloated), but why trashing the Awesome Photon UI, which Mypal also uses alongside Firefox 60-78 (yes, Photon =/= Proton. 
Proof:
 https://design.firefox.com/photon/
 https://www.techrepublic.com/article/firefox-proton-how-to-experience-the-new-design/
 ), 
the whole Quantum Engine (incl wht Mypal is based off, aka version 68) and Firefox 60-78 versions, which were and are actually gud, less bloated, faster, modern, etc in my opinion? Also, there re ton of browsers out there that still support NPAPI and Firefox Legacy Addons and are based off of either Firefox 4x or Firefox 50x versions. You could use those instead if you dont like newer addons and Firefox Quantum based Browser. Only Mypal is the only browser out there that brings Firefox Quantum to and Modern Addons to Windows Xp.

**Comment by Feodor2** [comment]
Of course i shall make the new repository for another mypal and this mypal will stay where it is.
And it has 68 version clear, put another versions is bad idea i think
