### ISSUE TITLE
How to setup CCleaner to clean Cookies in MyPal68?

### ISSUE THREAD

**Issue by Uzer999999999** [Feodor2/Mypal68#125]
Is there a way to setup the CCleaner ini file to selectively clean the cookies from Mypal68?
I tried the CustomLocation1=FIREFOX|"C:\Documents and Settings\Application Data\Mypal68\Profiles" but no joy.
Is there another way?

**Comment by AstroSkipper** [comment]
Have a look here: https://github.com/Feodor2/Mypal68/issues/99#issuecomment-1163417081
