### ISSUE TITLE
E-Mail Link does not open Thunderbird

### ISSUE THREAD

**Issue by sirrooster** [Feodor2/Mypal68#129]
e.g.: https://saeger-fussbodenstudio.de/teppichboden/
E-Mail Link opens Thunderbird in old MyPal, but in MyPal68 nothing happens.

**Comment by sirrooster** [comment]
From the Menue "Send Link via Email" also doesn't work. Nothing happens.
Copying an Email Link from the Browser also not possible. 
Application Kontextmenue is empfty. Only PDF is listed. 
No "mailto" Kontext available.

**Comment by sirrooster** [comment]
Can not paste picture here.

**Comment by Feodor2** [comment]
So don't, paste pictures only when asked otherwise it is a gibberish that waste the board.
And i could copy the link: **E-Mail: fussbodenstudio-saeger@t-online.de**
But opening links wont work until final stable version release.

**Comment by sirrooster** [comment]
"i could copy the link"
When I right click and choose copy link or email adress my clipboard is empty.
Only the Email text link at the bottom of the the page I can mark and ctrl+C. but copying via right click doesn't work either.
