### ISSUE TITLE
Windows 2000 compatibillity 

### ISSUE THREAD

**Issue by Matiasgroen** [Feodor2/Mypal68#13]
I understand that this might be beyond the current scope of the project but MyPal 68 does not run on Windows 2000 with exkernel 2.9b due to 2 missing exports in NTDLL. Is there any chance this will be looked at in the future?
![depends_2022-04-09_12-11-10](https://user-images.githubusercontent.com/11633814/162568160-af7418c2-dfaa-42ee-9b68-763cf62c4194.png)

**Comment by zzzmod** [comment]
if you change imports in mozglue.dll to existing windows 2000 functions using petools, mypal works (at least for me)

**Comment by Matiasgroen** [comment]
Does it matter which functions to change them to?

**Comment by zzzmod** [comment]
I think it matters but I changed to random functions and mypal started to run.

it’s better to find it out for yourself.

**Comment by Matiasgroen** [comment]
I replaced the missing functions in mozglue.dll and xul.dll with random ones and it's working now, thanks!

**Comment by NEO-SPECTRUMAN** [comment]
> if you change imports in mozglue.dll to existing windows 2000 functions using petools, mypal works (at least for me)

where i can read how to do that?

**Comment by Matiasgroen** [comment]
A friend of mine wrote an easy to follow guide on his blog: http://mrqash.blogspot.com/2022/04/mypal-68-firefox-68121-on-windows-2000.html
