### ISSUE TITLE
Unable to open add-ons

### ISSUE THREAD

**Issue by stanrames** [Feodor2/Mypal68#130]
This is 68.12.1 on XP-32 Media Center Edition,
I can load add-ons, two specific in question are Ghostery and UBlock Origin.
The add-ons are there, the icons are there, but clicking on the icons to open, like to block something or even to disable add-on for a test, gives me blank, white windows.
My other browser open is 28.10.1, and these add-ons CAN be opened there.
Just a heads-up to see if there i a fix. Might be my XP version. Who knows? Not sure where to even look.

**Comment by stanrames** [comment]
Now I feel really stupid. Neither worked. Then the browser crashed, just went away. Not in Task Manager or Process Explorer.
Restarted, posted here, and checked again, and they both open, and that's the first time they've worked since I loaded 68.12.1.
Also, I suddenly had bookmarks toolbar in left margin of screen.
And, opening this to post this message, again "mypal.exe as encountered a problem and will now close". And again, it did NOT close.
So, fairly often I get that message on this version. And sometimes without warning, the browser just closes. Gone. No warning about "you are about to close multiple tabs", just..gone. Restart gives me all the tabs back.

**Comment by stanrames** [comment]
and now they are back to blank windows again. I even tried opening bookmarks sidebar, no change.

**Comment by stanrames** [comment]
More observations:
Since that one time, have not been able to open for use those two add-ons.
Sometimes clicking on them gives a very small blank window, in decadent measurements probably 8 X 6 MM.
Other times, medium sized blank windows probably 20 X 25 MM.
But ALWAYS hovering cursor over UBlock or Ghostery icons gives an attached hourglass, like it's thinking about it.
No idea if this is helpful or not.

**Comment by zanud** [comment]
Can not tell anything about **Ghostery**, but **uBlock Origin** do work in 68.12.3b on my WinXP in both (multi- and single-process) modes.

Also it do work here in  68.12.4b in single-process mode. It is impossible to determine whether it works in multi-process mode, because this version of MyPal has a huge problem in this mode by itself (see my bugreport  #116). 

Try to switch browser to single-process mode.

**Comment by stanrames** [comment]
what exactly meant by switching to single-process mode?
I have always noted Process Explorer shows multiple processes for MP 68, while MP12 never has.
I have never explored single and multiple process settings.

**Comment by Feodor2** [comment]
If you have only sse2 cpu like Pentium 4 478 ublock will fail, but fortunately this will be fixed in the new version.
Why to use two adblocking addons at all, may be you use two antiviruses too? This is stupid
And about Ghostery - it is actually the spyware evil addon  do not use it ever.

**Comment by stanrames** [comment]
Actually, I find specific adblockers do good at specific things.
I've used Ghostery for years. Find it's blocking of trackers better than others.
I used to use AdBlockPlus, with the extension, but most browsers don't allow that.
UBlock allows me to block specific elements.
And no, only one AV.
Things have changed so much since 1972. 
But with WIN95 (used to time it from launch to hack) I developed specific protocols. Unfortunately, browsers got stupid (like FF add-on-mageddon) and the developers either got sidetracked into stupidity or sold out and THEY got stupid.
Like CCleaner sold to Avast. Everybody wants to monetize and track. And no, I don't want them reminding me to UPDATE.
Prime reason MS wants XP dead, and why I keep it running. It's not as easy for Gates and Co to track and monetize XP as it is WIN10.

**Comment by stanrames** [comment]
and I have no idea what processor is in this laptop without looking.
OLD Sony Vaio. 
MP 12, all the add-ons open and work. MP 68, no.

**Comment by zanud** [comment]
> I have never explored single and multiple process settings.

> browser.tabs.remote.autostart was false

It's strange. Default value for `browser.tabs.remote.autostart` is `true`. Was that line in normal or bold typeface?

(Just in case:)
It  is not enough to change this parameter in about:config. Browser must be restarted then. But in my case it was not enough to close it in usual way. A few invisible "mypal.exe" processes remain active after that. Every time I have to kill them by Task Manager (by killing most memory consuming one).

**Comment by Feodor2** [comment]
This is enough i suppose why not to enable adguard? So yes i do not trust them either
![image](https://user-images.githubusercontent.com/19492771/183280254-d4bef006-5643-496c-874f-c93a19bf546d.png)

**Comment by NEO-SPECTRUMAN** [comment]
часто зайдя в дополнения и кликнув по ним
![Копия 2022-08-19_181157](https://user-images.githubusercontent.com/88002487/185650829-03e85e6a-950d-4b09-9a96-309d46938cb9.png)

мы попадаем в никуда
![Копия 2022-08-19_181222](https://user-images.githubusercontent.com/88002487/185650899-29322396-9e06-4150-971b-9a65bc2bb8a9.png)

и назад вернутся тоже не можем
не закрыв полностью настройки
![Копия 2022-08-19_181237](https://user-images.githubusercontent.com/88002487/185650976-e3a3ac48-afeb-48ff-8676-51d411c2e702.png)

**Comment by NEO-SPECTRUMAN** [comment]
в темы, языки, плагины 
потом тоже нельзя попасть``

**Comment by NEO-SPECTRUMAN** [comment]
![2022-08-19_182046](https://user-images.githubusercontent.com/88002487/185651816-3624007f-12a7-4e6b-8f1a-a8ab58867d17.png)

**Comment by NEO-SPECTRUMAN** [comment]
нашел такую же проблему
https://github.com/Feodor2/Mypal68/issues/104#issuecomment-1166515979
