### ISSUE TITLE
cant use proxy

### ISSUE THREAD

**Issue by Ariisthebes** [Feodor2/Mypal68#131]
i cant use proxy in mypal68 
it dosent work

**Comment by zanud** [comment]
How proxy is configured - as **"Use system proxy settings"** or as some other choice?

**"Use system proxy settings"** is broken in Firefox during a number of years.

**"Manual proxy configuration"** and **"Automatic proxy configuration URL"** do work in MyPal68.

**Comment by Feodor2** [comment]
"Use system proxy settings" may not work yes we know #53
