### ISSUE TITLE
68.12.4b XP-32

### ISSUE THREAD

**Issue by stanrames** [Feodor2/Mypal68#132]
Since I cannot get add-ons to open in 68.12.1, decided to load the latest.
On THIS machine, no way.
Unless I am missing something basic.
Got it downloaded, unzipped and launched.
Tried to load Ghostery, just to see.
breakpoint exception, program will now close.
Loaded again. Tried again. Got the Tab has Crashed page.
Try again.
MyPal.exe has encountered a problem and will now close.
I did see a red flash, thought it said DrWatson, but there are no logs to share.

Is there any information I can post that will help?
These are error logs:

Event Type:	Error
Event Source:	Application Error
Event Category:	None
Event ID:	1000
Date:		8/3/2022
Time:		1:46:45 PM
User:		N/A
Computer:	LAPTOP
Description:
Faulting application mypal.exe, version 68.12.0.8195, faulting module mozglue.dll, version 68.12.0.8195, fault address 0x0000c18c.

For more information, see Help and Support Center at http://go.microsoft.com/fwlink/events.asp.
Data:
0000: 41 70 70 6c 69 63 61 74   Applicat
0008: 69 6f 6e 20 46 61 69 6c   ion Fail
0010: 75 72 65 20 20 6d 79 70   ure  myp
0018: 61 6c 2e 65 78 65 20 36   al.exe 6
0020: 38 2e 31 32 2e 30 2e 38   8.12.0.8
0028: 31 39 35 20 69 6e 20 6d   195 in m
0030: 6f 7a 67 6c 75 65 2e 64   ozglue.d
0038: 6c 6c 20 36 38 2e 31 32   ll 68.12
0040: 2e 30 2e 38 31 39 35 20   .0.8195 
0048: 61 74 20 6f 66 66 73 65   at offse
0050: 74 20 30 30 30 30 63 31   t 0000c1
0058: 38 63 0d 0a               8c..    

Event Type:	Error
Event Source:	Application Error
Event Category:	None
Event ID:	1000
Date:		8/2/2022
Time:		9:21:53 PM
User:		N/A
Computer:	LAPTOP
Description:
Faulting application mypal.exe, version 68.12.0.8130, faulting module unknown, version 0.0.0.0, fault address 0x2f65a981.

For more information, see Help and Support Center at http://go.microsoft.com/fwlink/events.asp.
Data:
0000: 41 70 70 6c 69 63 61 74   Applicat
0008: 69 6f 6e 20 46 61 69 6c   ion Fail
0010: 75 72 65 20 20 6d 79 70   ure  myp
0018: 61 6c 2e 65 78 65 20 36   al.exe 6
0020: 38 2e 31 32 2e 30 2e 38   8.12.0.8
0028: 31 33 30 20 69 6e 20 75   130 in u
0030: 6e 6b 6e 6f 77 6e 20 30   nknown 0
0038: 2e 30 2e 30 2e 30 20 61   .0.0.0 a
0040: 74 20 6f 66 66 73 65 74   t offset
0048: 20 32 66 36 35 61 39 38    2f65a98
0050: 31 0d 0a                  1..     

Event Type:	Information
Event Source:	Application Popup
Event Category:	None
Event ID:	26
Date:		8/3/2022
Time:		1:43:21 PM
User:		N/A
Computer:	LAPTOP
Description:
Application popup: mypal.exe - Application Error : The exception Breakpoint
A breakpoint has been reached.
 (0x80000003) occurred in the application at location 0x1000c18c.

Click on OK to terminate the program

For more information, see Help and Support Center at http://go.microsoft.com/fwlink/events.asp.

Event Type:	Error
Event Source:	BROWSER
Event Category:	None
Event ID:	8032
Date:		8/3/2022
Time:		10:19:40 AM
User:		N/A
Computer:	LAPTOP
Description:
The browser service has failed to retrieve the backup list too many times on transport \Device\NetBT_Tcpip_{1C15618F-ABC2-4ACF-BD35-879657D249B4}. The backup browser is stopping.

For more information, see Help and Support Center at http://go.microsoft.com/fwlink/events.asp.
Data:
0000: 88 08 00 00               ...

**Comment by IP-CAM** [comment]
Well, unfortunately, the latest Mypal Browser is far from being ready for modern Websites. By Example, on Github, most new routines, like scriptings, cannot be used anymore, and the Browser frequently crashes on several other Websites as well.

**Comment by Feodor2** [comment]
Github and very bunch of other sites will be fixed in the upcoming next version.
I am cooking much greater update to javascript - will be fixed majority of sites.

@stanrames
I tell you again throw away the ghostery it is spyware - so its even good that it crashes.

**Comment by IP-CAM** [comment]
Great Work, I am now able to continue my work at Github.com 
Thanks a lot for your nice Job!

**Comment by NEO-SPECTRUMAN** [comment]
> Great Work, I am now able to continue my work at Github.com Thanks a lot for your nice Job!

it can't be long
m$ ZOG "fix" compatability with old browsers every week
