### ISSUE TITLE
Загрузка процессора 99%

### ISSUE THREAD

**Issue by zanud** [Feodor2/Mypal68#133]
У Firefox есть древняя очень неприятная проблема: загрузка процессора подскакивает до 99-100% без всякой видимой причины, после чего браузер приходится сносить через Диспетчер задач.

В прошлом году команда, работающая над Seamonkey, нашла, наконец, причину этого безобразия и устранила её. Упоминается об этом, например, [здесь](https://github.com/JustOff/github-wc-polyfill/issues/10) (всю переписку читать нет смысла, только конец, начиная с 24 апреля прошлого года).

Их исправление было портировано в PaleMoon. Может, стоит проделать то же самое применительно к MyPal?

**Comment by greyrat116** [comment]
Вообще желательно отрубить по умолчанию этот network.notify.changed 
Wi-fi роуминг нужен единицам, тем более на ПК.

**Comment by zanud** [comment]
Роуминг может быть и без WiFi. Например, человек ноутбук от кабеля отцепил, ушёл с ним в другое место, и там к тамошнему кабелю подключил.

**Comment by greyrat116** [comment]
Эта штука каждые пять секунд проверяет соединение. Нужна если браузер нельзя закрывать. В комментах видел только одного чела которому эта опция реально была нужна - какой-то преподаватель в универе, который перемещался с ноутбуком в здании по аудиториям. 
Но если не отключать, то да, лучше сделать так

**Comment by zanud** [comment]
> В комментах видел только одного чела которому эта опция реально была нужна - какой-то преподаватель в универе, который перемещался с ноутбуком в здании по аудиториям.

Ну вот я ещё один такой человек - мне не только в пределах здания приходится перемещаться, держа вкладки открытыми, но даже между городами.

> Эта штука каждые пять секунд проверяет соединение.

Я думал, это операционка программе извещение шлёт. Впрочем, не важно: в любом случае _"раз в пять секунд"_ - это настолько ничтожная дополнительная нагрузка, что совершенно непонятно, зачем её отключать.

**Comment by Feodor2** [comment]
Сделал исправление пробуйте

**Comment by zanud** [comment]
Попробовал. Первым делом включил в `about:config` многозадачность и аппаратное ускорение видео, которые пришлось отключить в версии 4b, чтобы она у меня вообще работала (#116). Сейчас всё нормально.

Потом включил uBlock Origin. Так-то он более-менее работал, но всё же слишком часто вызывал падение браузера, причём даже при заходе на достаточно невинные сайты (например, Авито). Полчасика поползал по разным сайтам, пока ни разу не рухнуло.

А чтобы 100% загрузку проверить - это надо в однопроцессном режиме пару-тройку часиков его запущенным продержать. Так что жду.

**Comment by drugoisport** [comment]
Адгуард шикарный адблокер, но не запускается

**Comment by NEO-SPECTRUMAN** [comment]
> Сделал исправление пробуйте

видимо это не единственная причина повисания

серпент с network.notify.changed:false конечно стал зависать на вид реже
а вот последний mypal68 с дополнительно отключенным network.notify.changed
ужо тоже пару раз повис
хотя конечно не по 3 раза в день как было
но mypal я особо и не нагружаю сотнями вкладок...
