### ISSUE TITLE
Mypal игнорирует существующий профиль пользователя и создаёт новый

### ISSUE THREAD

**Issue by zanud** [Feodor2/Mypal68#134]
В принципе, жалоба на нечто похожее здесь уже была, но у меня и ситуация другая, и проявления несколько отличаются, и воспроизводится легко и регулярно.

Основным браузером у меня используется Seamonkey. Недавно я поставил дополнение, которое добавляет в контекстное меню ссылок пункт "Открыть в другом браузере" и вписал туда Mypal. И при первом же запуске через это меню Mypal почему-то проигнорировал существующий профиль пользователя (назовём его **A**) и создал новый (назовём его _X_)!

Дальнейшие исследования показали вот что:

Если Mypal запускать через ярлык или из командной строки, то всегда используется профиль **A**.
Если Mypal запускать из Seamonkey, то всегда используется этот автоматически созданный профиль _X_ (другие новые профили не создаются).

Если запустить Mypal каким-то из этих способов, а потом запускать его этим же способом ещё несколько раз, то в уже открытое окно добавляются новые вкладки.

Если запустить Mypal каким-то из этих способов, а потом запустить другим, то откроется второе окно. И если потом ещё запускать разными способами, то каждый раз новая вкладка будет добавляться именно в соответствующее окно.

Командная строка во всех экспериментах использовалась одна и та же, и браузер получал именно её (отслеживал через Process Monitor).

Предположил, что к этому  безобразию как-то причастно то, что при запуске из Seamonkey текущим каталогом является именно каталог Seamonkey, а не Mypal. Но нет: если запускать Mypal из командной строки, имея текущим каталогом Seamonkey, то всё равно используется профиль **A**.

Последней надеждой было значение переменной окружения PATH. И вот тут я после 30 лет использования Windows обнаружил нечто новое и неожиданное: Windows портит путь.

В настройках системы значение PATH у меня начинается с:
`C:\Program Files\ImageMagick-7.0.1-Q8;C:\WINDOWS\system32;...`

Но в памяти в окружении процесса Seamonkey PATH начинается с:
`C:\Program Files\SeaMonkey;C:\Program Files\ImageMagick-7.0.1-Q8;C:\WINDOWS\system32;...`

А в памяти в окружении процесса Mypal, запущенного через ярлык или командную строку, PATH начинается с:
`C:\Program Files\Mypal;C:\Program Files\ImageMagick-7.0.1-Q8;C:\WINDOWS\system32;...`
независимо от того, какой каталог является текущим.

Но если Mypal запущен из Seamonkey, то в памяти его процесса Mypal PATH начинается с:
`C:\Program Files\Mypal;C:\Program Files\SeaMonkey;C:\Program Files\ImageMagick-7.0.1-Q8;C:\WINDOWS\system32;...`

В итоге я так ничего и не понял. Что при запуске Mypal через командную строку из каталога Seamonkey, что при запуске из самого Seamonkey текущий каталог у процесса получается один и тот же (Mypal), первый каталог в PATH тоже один и тот же (Mypal), но в первом случае Mypal использует правильный профиль **A**, а во втором - "самодельный" профиль _X_.
А больше я, как ни старался, никаких отличий между процессами найти не смог.

Почему же такая разница в поведении одной и той же программы, и как заставить Mypal при запуске из Seamonkey использовать нормальный, уже существующий, профиль?

**Comment by Feodor2** [comment]
Явно указать путь к профилю "-profile"

**Comment by zanud** [comment]
Увы, это невозможно. Тамошняя настройка выглядит так: указывается путь к программе, к которому потом, при выборе пункта меню, код дополнения приписывает URL, который нужно открыть.
Если в задаваемой мной строке я после имени .exe-шника допишу ещё что-то, то всё это вместе взятое будет интерпретироваться как имя файла, который нужно запустить, и, естественно, такого файла на диске не найдётся.

Но сегодня ситуация изменилась. Когда я впервые обнаружил проблему, то сделал резервную копию имеющегося каталога %APPDATA%\Mypal68, немного поэкспериментировал, а потом удалил его и все дальнейшие эксперименты и исследования проводил с новым чистым каталогом, автоматически создаваемым Mypal, который тоже периодически удалял (для чистоты экспериментов).
Вчера, после двух дней разборок с ситуацией, я опять удалил этот каталог и из резервной копии вернул на место сохранённый рабочий.
А сейчас, проверяя возможность дописать "-profile", я опять сделал копию рабочего, в Seamonkey дописал "-profile", убедился, что в таком варианте пункт меню не работает, убрал "-profile" и для проверки правильности отката запустил Mypal.
И вот тут Mypal запустился совсем не так, как вчера-позавчера. Тогда он автоматически создавал новый профиль, а сейчас показал окошко Менеджера профилей, я выбрал тот профиль, которым всё это время пользуюсь, после чего Mypal с ним нормально запустился.
И теперь при всех последующих запусках из Seamonkey Mypal уже стартует молча, использует свой обычный профиль.

То есть, проблема вроде бы "рассосалась". Но ведь это только симптом исчез. А причина, по которой вчера Mypal упорно новый профиль создавал, - она же никуда не делась. Причём он же не каждый раз его создавал, а, раз создав, начинал автоматически использовать при всех последующих запусках из Seamonkey. И одновременно с этим автоматически использовал обычный профиль при запуске с Рабочего стола.

Значит, есть в коде Mypal что-то, заставляющее его в определённой ситуации отвергать тот профиль, который на диске имеется, и который он сам же создал несколько секунд назад при запуске альтернативным способом. И стоило бы это место найти и исправить. Или озвучить причины, чтобы пользователи были в курсе и не удивлялись.

**Comment by zanud** [comment]
---------
Дополнительная информация:

В файле profiles.ini профили записываются в секции с именами вида [Profile0], [Profile1], [Profile2].
Одновременно с ними в этом файле есть и секции с именами вида [Install<hex-код>].
А в файле installs.ini находятся секции с именами вида [<hex-код>], причём эти коды совпадают с кодами из profiles.ini.
Раньше я думал, что эти коды связаны с версией Mypal. Но только что обнаружил, что одна и та же версия Mypal создаёт секции с разными кодами в зависимости от того, какой каталог является текущим в момент запуска браузера.
И соответственно, в зависимости от текущего каталога создаются/используются разные профили!

Зачем это сделано? По-моему, это какой-то абсурд. Но скорее всего, что мои страдания были связаны именно с этим.
