### ISSUE TITLE
Mypal поломалсо

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [Feodor2/Mypal68#135]
второй запуск 68.12.5 закончилсо этим...
![2022-08-10_204139](https://user-images.githubusercontent.com/88002487/183981487-a8c774e0-9e21-48f4-993e-a080e4e84158.png)
![2022-08-10_204227](https://user-images.githubusercontent.com/88002487/183981501-58f8bbdf-5434-483e-9e24-8a61c2df34fa.png)

client area не перерисовывветсо вообще

из -safe-mode стартанул как надо
но отключениё всего чего только может ппридти в голову не помогает...

**Comment by NEO-SPECTRUMAN** [comment]
откатился на 68.12.4
все заработало

**Comment by NEO-SPECTRUMAN** [comment]
дето видел тут подобный скриншот
но щас не нашел

**Comment by Feodor2** [comment]
Не знаю я как накатывал новый так и на старый сверху,  такого не  было
Попробуй чистый профиль.

**Comment by Feodor2** [comment]
Я поймал эту ошибку, думаю дело в руссификаторе, точнее кривой не доделанный языковой код енота.
Чиниться удалением из профиля addonStartup.json.lz4, потом в углу типа просит руссификатор обновить, и ещё перезапуск.
Итого руссификатор использовать пока не желательно, возможно искаженные шрифты тоже из-за этого.
