### ISSUE TITLE
Сайт https://squoosh.app/ не работает ни под версией 68.12.5 ни под версией 68.12.4

### ISSUE THREAD

**Issue by charpote** [Feodor2/Mypal68#137]
под windows  xp

**Comment by NEO-SPECTRUMAN** [comment]
ДА ТЫ ШО!

**Comment by charpote** [comment]
А, шо!, на 360 Extreme Explorer 13.0.2290.0 под тем же windows xp всё
раюотает

чт, 11 авг. 2022 г. в 15:02, NS ***@***.***>:

**Comment by Feodor2** [comment]
Под следующей заработает может
