### ISSUE TITLE
Updating of extensions doesn't work

### ISSUE THREAD

**Issue by AstroSkipper** [Feodor2/Mypal68#138]
Hello Feodor2! I've installed the most recent version **Mypal 68.12.5b**. It's really a great step forwards in development! Unfortunately, updating of my extensions via **Addons Manager** doesn't work at all. I got the message "**No updates**" although updates were available. I had to download and install them manually. Is this issue already known? I couldn't find any topic about that. And, when will it be fixed?

Greetings, AstroSkipper [![ordi1fun.gif](https://i.postimg.cc/k4q8W73j/ordi1fun.gif)](https://postimg.cc/FfC745Kc)

**Comment by Feodor2** [comment]
This was disabled from the very beginning, update only manual.

**Comment by AstroSkipper** [comment]
Thank you, Feodor2, for the clarification! Will this feature be enabled in one of your future releases? [![grattermenton.gif](https://i.postimg.cc/3Nw3kxMh/grattermenton.gif)](https://postimg.cc/gX1C5dkt)

Greetings, AstroSkipper [![0ordi.gif](https://i.postimg.cc/4xHzg8Q1/0ordi.gif)](https://postimg.cc/xXYkG37k)
