### ISSUE TITLE
ZIP File DOWNLOAD Function does not work

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#14]
The DOWNLOAD Function does not work, all Downloads add ZERO BIT Zips, again and again, and in the Browser Admin Section,, Downloads cannot be deleted/removed either. Every time, the Browser starts, those empty ZIP's are downloaded again.

**Comment by NoNameNeeded2** [comment]
https://github.com/Feodor2/Mypal68/issues/2
