### ISSUE TITLE
Discord file uploading broken

### ISSUE THREAD

**Issue by Matiasgroen** [Feodor2/Mypal68#142]
Recently Discord file uploading stopped working. Pasting an image from the clipboard and attempting to send it will result in an "upload failed" every single time. It does not seem to be related to the new 68.12.5b version.

**Comment by NEO-SPECTRUMAN** [comment]
ставим https://addons.mozilla.org/ru/firefox/addon/cors-unblock/
на врямя загрузки жмем кнопкуу

**Comment by aric2746** [comment]
discord does not load anymore. 

![image](https://user-images.githubusercontent.com/67488797/194458087-efdbbfac-5473-4ea2-9517-8f40c0500967.png)

**Comment by NEO-SPECTRUMAN** [comment]
Именно поэтому нужен аддон способный тупо автозаменять любую часть html-ки js-а итд
чтоб можно было тупо выпилить проверки на unsuported browser к хуям
так его, блять, нигде нет

**Comment by aric2746** [comment]
NEO-SPECTRUMAN hopefully the code gets updated. I would like to access discord and ticket #148.
