### ISSUE TITLE
Mypal d3d9window hangs

### ISSUE THREAD

**Issue by TheElf01** [Feodor2/Mypal68#143]
Hi! i get too many d3d9window hangs, any ideas? i already disable acceleration, and any d3d9 stuff in config... still same... thanks!
![Image1](https://user-images.githubusercontent.com/16392474/185931155-a8b9bd91-3c8a-489b-a5ab-f7213148e2e2.gif)

**Comment by Feodor2** [comment]
This is a little data.
Do you say you disabled acceleration but still get the error.
Look readme for take drwatson.log and also name your cpu

**Comment by TheElf01** [comment]
> This is a little data. Do you say you disabled acceleration but still get the error. Look readme for take drwatson.log and also name your cpu

Thanks for reply  my CPU is a i3-550, and here is dr watson log

[drwtsn32.log](https://github.com/Feodor2/Mypal68/files/9466057/drwtsn32.log)

**Comment by TheElf01** [comment]
Hi! someone have same problem?  always happen when i change resolutions or open a fullscreen d3d app

i tested in two computers, one with integrated intel, the other nvidia, same problem

thanks
