### ISSUE TITLE
Googel Drive UI on 68.12.5b

### ISSUE THREAD

**Issue by nreovykti** [Feodor2/Mypal68#144]
Navigation elements / folders won't select onclick in Google Drive user interface.  

If you have direct link to individual document or file, that works.  But clicking around Google Drive folder structure doesn't seem to work.  Nothing selects on click.  

Best regards.

**Comment by hmnogueira** [comment]
Use arrow keys to scrool arround the folders, it works.

**Comment by nreovykti** [comment]
That used to work.  Even on Mypal 29.3.   No longer the case. 

At Google Drive root, the left folder structure nav isn't selectable.  Won't expand.  
And no files in main window are selectable.  Tab or arrows or enter is unresponsive.  Seems there is some kind of scripting layer in between that isn't supported.  

Direct URL to files is fine - editing documents still works.

**Comment by hue4** [comment]
This is a bad problem.  Please fix Google Drive.

**Comment by fenavi** [comment]
The browser no longer displays Google Drive's web page properly.
They don't show the list of folders and files. Instead there's a banner saying "A Place For All Your Files"

**Comment by pbcairo** [comment]
I think it's working in 68.13 with setting the user agent to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36`
