### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal68#15]
At the following page, a horizontal scrollbar appears temporarily.
With multiple reload this is visible and not visible.
With other browsers there is no horizontal scrollbar.
https://www.atb-tuning.de

**Comment by NoNameNeeded2** [comment]
I can confirm this.
However, it's actually not Mypal68 specific but it also happens with Firefox 68.
It's not the first thing that doesn't really work so well, see this thread:
https://github.com/Feodor2/Mypal68/issues/10

But it is at least a more useful browser than the former version of Mypal (which was based on Palemoon, which is based on Firefox from the stone age)
