### ISSUE TITLE
duplicate

### ISSUE THREAD

**Issue by jbclem** [Feodor2/Mypal68#152]
(moved from main Issues section)

A forum that I often visit, growingfruit.org, uses Discourse for it's forum software. It worked fine on Mypal and Mypal68 until a recent forum software update, after the update on Mypal there are no scroll bars, no login buttons, no reply buttons, no avatar, and same thing on Mypal68 except the vertical scroll bar appears and works.  So I can read the messages but there is no way to communicate with the forum.

An Discourse error message at top of page advises: "Please upgrade your browser to view rich content, log in and reply."  I couldn't find any technical information about this on the Discourse website.

I haven't been able to figure out what "rich content" refers to, and if the log in and reply buttons are part of "rich content" or something else.  If this problem can be identified,  could there be a Mypal68 solution?

Another website, the Tor browser forum, https://forum.torproject.net/, with the same problems.

**Comment by jbclem** [comment]
I'm trying to post this in the Not Working Sites section, but that's eluding me.   Apologies for the duplicate(almost)  entry.

**Comment by jbclem** [comment]
This growingfruit.org site is working properly using Feodors' Centaury 0.15.0 .  It would be interesting to know the differences between Mypal68 and Centaury, perhaps Mypal68 could be rigged to work on the upgraded Discourse (forum software) using websites.

**Comment by Gelip** [comment]
@jbclem


> This growingfruit.org site is working properly using Feodors' Centaury 0.15.0

You can share the compiled version of the Centaury 0.15.0
Thx

**Comment by K4sum1** [comment]
Add this to your uBlock Origin filters. (If you don't have uBlock Origin, just get it, you really should use an adblocker)

```
! Block Discourse browser detect script
browser-detect-$script
```

The real solution would be for MyPal68 to satisfy this script, but not sure when that will come. It would need to satisfy the requirements and also fake the user agent to 89 or later

https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/scripts/browser-detect.js
