### ISSUE TITLE
Won't play 20minutos' videos

### ISSUE THREAD

**Issue by andika207** [Feodor2/Mypal68#153]
Mypal68 can't play videos from this news site 
https://www.20minutos.es/videos/internacional/5059531-una-mujer-atraca-un-banco-para-sacar-dinero-de-su-cuenta-y-ayudar-a-su-hermana-con-cancer/

in fact neither of the XP browsers (360EE, Centaury, Firefox...) can play these videos since the website got modernized

I have to send the video link via AnyDesk to a secondary PC with W7 so I can play the videos whether original chrome or firefox

note: the original Basilisk @wolfbeast @mattatobin in W7 (up to date, august 2022) can't play those video clips either... WTF !!!!

**Comment by IP-CAM** [comment]
Videos work well with my MyPal68

**Comment by ab288** [comment]
Hi IP-CAM ....What version of MyPal68 are you using ?

**Comment by IP-CAM** [comment]
last Version 68.12.5b

**Comment by andika207** [comment]
@IP-CAM are you talking about the link I posted above ?
my Mypal68 doesn't show off anything, there's a blank spacing 

<a href='https://postimg.cc/LYYKRs2b' target='_blank'><img src='https://i.postimg.cc/zBpJCLM8/Snap-Crab-No-Name-2022-9-15-21-36-0-No-00.png' border='0' alt='Snap-Crab-No-Name-2022-9-15-21-36-0-No-00'/></a>

**Comment by ab288** [comment]
i have the same version and the videos wont play
    
    
    On 9/15/2022 2:59 PM, Ernie wrote:
    
    
      last Version 68.12.5b
      —
        Reply to this email directly, view
          it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message ID: ***@***.***>
      [
{
***@***.***": <a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": <a class="moz-txt-link-rfc2396E" href="https://github.com/Feodor2/Mypal68/issues/153#issuecomment-1248487092">"https://github.com/Feodor2/Mypal68/issues/153#issuecomment-1248487092"</a>,
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com/Feodor2/Mypal68/issues/153#issuecomment-1248487092">"https://github.com/Feodor2/Mypal68/issues/153#issuecomment-1248487092"</a>,
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com">"https://github.com"</a>
}
}
]
    
    
    -- 
      Remember not to talk bad about farmers with your mouth full!

**Comment by IP-CAM** [comment]
![20minutes](https://user-images.githubusercontent.com/12776547/190848843-e510c664-18dd-414e-b235-9905e3e8b784.png)

**Comment by andika207** [comment]
@IP-CAM @ab288 OK problem solved. 
I noticed advertising in your snapshot so I disabled uBlock and Ghostery now I can watch the video.
