### ISSUE TITLE
Optimal settings 68.12.5b

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal68#154]
Hello,
what are the optimal settings for V68.12.5b so that no BSoD occurs and it runs best.

**Comment by andika207** [comment]
I only have had one BSOD since I first started up this version but the nirsoft tool didn't log the report so I couldn't check it out.
I didn't ticker with settings because occasionally chrome suffer from this problem ever since

**Comment by andika207** [comment]
Firefox was unstable until the 52 realease because it used to crash very often but never caused BSOD unlike chrome.
given there's no official support for Mypal68 it will take one person @Feodor2 ages to discover the bug

**Comment by NS-Clone** [comment]
а не дефолтный content process limit тыкнутый тут сильно влияет на стабильность?

![123](https://private-user-images.githubusercontent.com/19492771/325095820-59c8a004-4ee1-43f2-a89f-92dbbab98b22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyODk1NDQsIm5iZiI6MTcxNzI4OTI0NCwicGF0aCI6Ii8xOTQ5Mjc3MS8zMjUwOTU4MjAtNTljOGEwMDQtNGVlMS00M2YyLWE4OWYtOTJkYmJhYjk4YjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDAwNDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YTc2ZjgwYTY4NzRjOThhMDMzNmY3ZmY2ZGFkZDAwOTE1YTNkYmY5MWU1OTYwMTE4N2E0Y2YyZmVlMDljZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-4BmZmThsZ9CrThf1px_hsT3PhkGR07jeLqjY6Ex6mI)
