### ISSUE TITLE
Sponsorblock doesn't work

### ISSUE THREAD

**Issue by K4sum1** [Feodor2/Mypal68#157]
The addon says it's compatible with Firefox 48+, but there's no options in the settings for the addon, the addon popup is blank and it doesn't do anything on YouTube.
![ScreenShot_20220924095357](https://user-images.githubusercontent.com/77039240/192104783-6f4f1d8e-99f9-4c40-a204-33f8582bffb7.png)
![ScreenShot_20220924095347](https://user-images.githubusercontent.com/77039240/192104784-37c497e1-c9c6-405a-984b-1e39e7d7e3ae.png)

**Comment by andika207** [comment]
why do you need this extension ?
I haven't seen a single ad. on YT for ages with ublock origin.

**Comment by K4sum1** [comment]
> why do you need this extension ? I haven't seen a single ad. on YT for ages with ublock origin.

It's for blocking sponsor reads inside the video. Many bigger creators have sponsor reads, and I find it's just faster and better to use an extension like this to skip past sponsors like terrible fire hazard wireless earbuds, wallet that looks like a pain to use, software meant for businesses that sponsor videos for whatever reason, SSDs that I can't buy inside the US, and more.

**Comment by Ailet1980** [comment]
K4sum1

webextensions.storage.sync.enabled - true

**Comment by K4sum1** [comment]
Was webextensions.storage.sync.enabled set to true in source?
