### ISSUE TITLE
Mypal 68.13 issues thread

### ISSUE THREAD

**Issue by andika207** [Feodor2/Mypal68#160]
it's not out yet so keep calm and stay tuned https://github.com/Feodor2/Mypal68/issues/3#issuecomment-1279302448
feel free to report your early issues over here

**Comment by Trancer03** [comment]
Is 64-bit stable version out, and where I can download it?

**Comment by Feodor2** [comment]
This is such a nightly build
Primary goal has been not reached yet, which the upgrade javascript engine for support regexp (ver 78), but changes are huge already (ver 76).
Also google dns spyware has been replaced #188.

https://mega.nz/file/FfhCVaZJ#7Yt5Ai8lAz-KeGXBiNnfFcS61-5YVdztKxlPYdq7ZZg
sources
https://mega.nz/file/BPBxWRZR#AGG8n69bujNJv2OWsTlDMDB0fDT9IecC6RukCSFWANE

**Comment by AstroSkipper** [comment]
Thank you very much for this nightly build of Mypal. I tested some sites. Unfortunately, **VirusTotal stopped working completely** in **Mypal 68.13.0b**. Neither the main site [https://www.virustotal.com/gui/home/upload](url) nor the reduced site [https://www.virustotal.com/old-browsers/?style=bright](url) works. On the main site, no way to upload a file. All elements in the middle of the website aren't loaded, only the outer frame. On the reduced site, the Google captcha doesn't work (endless loading). 

PS: BTW, I tested GitHub, too. The assets are loading again. Very good!

**Comment by MWF2** [comment]
discord still won't work but hopefully with final released discord work again and title bar button fix for classic theme #190 
![image](https://user-images.githubusercontent.com/74994144/221282679-cb871812-eed2-4369-b090-618eeb89b3ba.png)

**Comment by kiza124** [comment]
Tell me the link from where to download the version of mypal 68.13. Links like https://mega.nz/file/FfhCVaZJ#7Yt5Ai8lAz-KeGXBiNnfFcS61-5YVdztKxlPYdq7ZZg don't open for me because it says I have an old version of the browser and the new version can't be installed because I have Win XP.

**Comment by kiza124** [comment]
Thanks, I didn't know about such a browser. I see there is a link to download the Win32 version and the IA32 Win32 version. What is the difference? For Pentium E2200 processor when using Win XP (32 bit) which one is better to choose?

**Comment by RamonUnch** [comment]
Use the one that has no special flags, because your CPU is recent,
`Win32` : for newer CPU that have SSE2 (your case) Pentium 4+
`Win32 SSE`: For old CPU that only have SSE and no SSE2 (Pentium 3 for instance)
`Win32 IA32` : If you have a really old CPU (without any SSE) Pentium 2 for instance).
`Win64` : For x86_64 bit CPU (all of them) but you need 64 bit windows too...

**Comment by kiza124** [comment]
What is better - Basilisk52 or NM28XP?

**Comment by RamonUnch** [comment]
Both are based on the same UXP engine, so in term of web compatibility they are similar, NM28XP is very much like the old MyPal, and Basilisk52 is very much like the old Centaury (Looks like Firefox 52esr). Their actual names are actually **Serpent** for basilisk and **New Moon** for NM28XP. I think you should give a shot to both and decide which is best for you.This is a bit off-topic though so I do not want to elaborate too much.

**Comment by bushy555** [comment]
If the above mega link doesn't work for MyPal68.13, I've just shoved a copy on to file.io sharing mob.
I tried filebin as well, but they are now chockers and are not accepting any more uploads at the moment.
The zip file is untouched and is the original 60 meg zip file simply taken from mega.

Both of these two sites appear to not have a 30 or 60 day limit, so they should be there for a bit.

Title : mypal-68.13.0.en-US.win32.zip
URL: https://file.io/QJpsTmHmV1on

**Comment by RamonUnch** [comment]
For info the expected Checksums from you will get with Original MEGA link (in case you are unsure):
**File:** mypal-68.13.0.en-US.win32.zip
**Size:** 63 244 482 bytes
**CSR32:** 5BB81C4F
**SHA1:** fb3e2a61ac70f7a9dbd9ef2fa43468bd3dfe81f2
**SHA256:** 8d8493ecceda7c8d5482ff983bc85cd1c504936aa724e77c359c70a9b2d50f21

**Comment by kiza124** [comment]
Thanks, I already downloaded it before - March 10th. And if we give checksums, then MD5 is better, because. to check it, I have the md5summer program.

**Comment by RamonUnch** [comment]
Updated above post with md5

**Comment by kiza124** [comment]
http://www.sberbank.ru/ru/person does not open Mypal 68.13

**Comment by pbcairo** [comment]
Feodor said he would do 68esr, 78esr, 91esr. currently only 68 is being developed but 68 is old now too (time flies too fast yeah) I hope he does 78 at some point after 68 is completed

**Comment by RamonUnch** [comment]
it is indeed based on 68esr but in term of JS engine, which is the limiting factor for web compatibility, Feodor is porting all the new stuff.
As he says the 68.13 build is on par with fx76 and he will release 68.13 non beta when he reaches 78esr level.

**Comment by jasonliul** [comment]
> Feodor said he would do 68esr, 78esr, 91esr. currently only 68 is being developed but 68 is old now too (time flies too fast yeah) I hope he does 78 at some point after 68 is completed

i can't agree more, even an alpha build of 78 esr.

**Comment by blue-dragon-cairo** [comment]
I think he will backport 78's JavaScript engine to 68 I say him saying something similar

**Comment by Feodor2** [comment]
New version
https://mega.nz/file/QaY1zLLY#PhGLpVBfu51To4sjqSgfjaLX6nyebwye82FliTf41yA
sources
https://mega.nz/file/hDRiESYY#7mKpjcPkjczsvlifsoajhaLmggPN3oKe7-HwUeJpBpk
This is prerelease version for testing, javascritpt at 78 level.
**ATTENTION** remove language packs for the original firefox - they will be not anymore compatible.

**Comment by IP-CAM** [comment]
> New version https://mega.nz/file/QaY1zLLY#PhGLpVBfu51To4sjqSgfjaLX6nyebwye82FliTf41yA sources https://mega.nz/file/hDRiESYY#7mKpjcPkjczsvlifsoajhaLmggPN3oKe7-HwUeJpBpk This is prerelease version for testing, javascritpt at 78 level. **ATTENTION** remove language packs for the original firefox - they will be not anymore compatible.

Site refreshes continuously:
https://www.opencart.com/index.php?route=account/login

**Comment by RamonUnch** [comment]
**File:** mypal-68.13.0.en-US.win32.zip
**Size:** 63 937 061 bytes
**CSR32:** 81B6AE20
**SHA1:** 573f325551df96afecd9c1fbad3e44e12c3fb6a0
**SHA256:** d4e0ea2162fb348a026419542269e357bb1f8b32363300db3172efd107a064e3
**MD5:** 00b6ea5c8320d14ad47035ffe5ebf7dc

**Comment by jasonliul** [comment]
@Feodor2 
Thanks, like a dream come true.

**Comment by blue-dragon-cairo** [comment]
the latest version of Discord is working! (tho I use 2019 version) thanks as always

**Comment by blue-dragon-cairo** [comment]
Google meet crashes the browser sometimes in 68.13 (works fine on 68.12.5)

will post DR.WATSON log later

**Comment by NEO-SPECTRUMAN** [comment]
из наблюденй
новый mypal уже не однократно падал
при отпадании интернета
вроде раньшо было с этим постабильней

**Comment by NEO-SPECTRUMAN** [comment]
дропбокс 
https://www.dropbox.com/s/0ofwou52vmbjxwm/Moonsound_pack_last.7z?dl=0
![2023-06-12_160428_](https://github.com/Feodor2/Mypal68/assets/88002487/92b1f511-ad45-4899-af8c-f969bb9feca2)
хотя возможнно это изза нехватки рамы умя

**Comment by NEO-SPECTRUMAN** [comment]
так же в менюшки загрузок
теперь? явно иногда не подсвечиваютссо  неоторые пункты
![2023-06-12_161306](https://github.com/Feodor2/Mypal68/assets/88002487/2316f899-44b9-41ea-a609-a1f1e8ec9933)
![2023-06-12_161312](https://github.com/Feodor2/Mypal68/assets/88002487/60e0df16-f240-4e98-af7b-2e839e322892)
![2023-06-12_161322](https://github.com/Feodor2/Mypal68/assets/88002487/cf0cf4ea-8d9e-40d7-95e8-e4f78f3e12b5)
не помню чтоб такое когда либо было в фаиррфоксе

**Comment by kiza124** [comment]
Prompt link to download the latest version of mypal.

**Comment by Feodor2** [comment]
@NEO-SPECTRUMAN 
Ничего не понятно, напиши нормально текстом в чём дело и с конкртными ссылками.

**Comment by NEO-SPECTRUMAN** [comment]
забыл написать
что нужно клацнуть скачать
тогда падает plugincontainer

**Comment by NEO-SPECTRUMAN** [comment]
щас мне ии клацать не пришлось
оно высккочило при открытии ссылки

**Comment by NEO-SPECTRUMAN** [comment]
> @NEO-SPECTRUMAN Ничего не понятно, напиши нормально текстом в чём дело и с конкртными ссылками.

на тему отсутствие подсветки в меню загрузок
оно появляетсо на рандомно загруженых файлах на вид
врятли зависиит от ссылкки
хотя надо понаблюддать еще

**Comment by stanrames** [comment]
I have been using since 28. This new 68.13 version surprises me. For the first time in years I can use facebook for family stuff (and anything else).
I am certain there are issues..there always are no matter who. Only "bug" seems to be the nagware that says "a new version of MyPal is available. Click here". Takes you to Mozilla, and nothing there for XP.
Thanks for doing this.

**Comment by IP-CAM** [comment]
In the OPTIONS Section, just select:
Never check for updates (not recommended)
to keep that Function off.
