### ISSUE TITLE
XP Whatsapp

### ISSUE THREAD

**Issue by brbr1982** [Feodor2/Mypal68#162]
Since the last two days I cannot use whatsapp web on Mypal 68.
It was working normally yesterday
Thanks a lot

**Comment by TheElf01** [comment]
> Since the last two days I cannot use whatsapp web on Mypal 68. It was working normally yesterday Thanks a lot

works well here,  i use this agent string

Mozilla/5.0 (Windows NT 7.0; rv:68.0) Gecko/20100101 Firefox/68.0
