### ISSUE TITLE
The address wasn’t understood when i try to open austiblox in mypal68

### ISSUE THREAD

**Issue by MWF2** [Feodor2/Mypal68#167]
this is issue when i click play to try play austiblox, and strange that in other browser it did open austiblox after click play while mypal68 is not
![Screenshot_3](https://user-images.githubusercontent.com/74994144/201542758-f1a5bca4-f19d-4064-895e-eb79332c3164.png)

**Comment by MWF2** [comment]
something that in different browser don't happen
![2023-05-05_190504](https://user-images.githubusercontent.com/74994144/236590147-cc4c90fb-cab7-484d-b42c-fbf2b104898b.png)

**Comment by blue-dragon-cairo** [comment]
Opening protocols using other programs doesn't function properly. I tested in Zoom Cloud Meetings too

**Comment by MWF2** [comment]
feodor2 needs to add feature of opening protocols using other programs, including austiblox to his browser

**Comment by Feodor2** [comment]
I try for the upcoming release

**Comment by Feodor2** [comment]
so it is done

**Comment by MWF2** [comment]
alright, thanks, the first austiblox url don't appear, but after select manual, it works
