### ISSUE TITLE
BSOD WHEN CLOSING TABS

### ISSUE THREAD

**Issue by Cixert** [Feodor2/Mypal68#168]
This error occurs in XP SP3 when I quickly close tabs and 2 remain open.
it happens in all versions.
mypal 68.12.1
mypal 68.12.3
Thank you for creating this navigator and keep improving it.
BSOD Image
https://i.imgur.com/NTcHNDh.jpg
CHKDSK part 1
https://i.imgur.com/4M1OqGo.jpg
CHKDSK part 2
https://i.imgur.com/dcgbEEE.jpg

**Comment by MWF2** [comment]
go to #3 about it

**Comment by bushy555** [comment]
Have you tried this in the first instance?  It seems to fix a lot of memory related & tab issues for multi-core computers.
This needs to be a sticky note.

about:config
browser.tabs.remote.autostart      false
and / or
dom.ipc.processCount 0 or 1

**Comment by adxelec** [comment]
Me too (that first solution ie browser.tabs.remote.autostart = false).

BSODs on an i7 were unavoidable, even if applying tweaks to limit the number of processes and memory use. That type of BSOD would not show up in minidumps for some reason, so I couldn't send the BSV reports. So far it is a complete fix.

For various reasons Mypal is important round here, so my thanks to the author for both the original and this one.

**Comment by xrayer** [comment]
I also get this BSOD multiple times (always win32k.sys at the same address) within few minutes of browsing.
The settings of browser.tabs.remote.autostart = false have some effect and I didn't get BSOD yet.
Does it depend on VGA / driver?
I have core i-7 2600K and nVidia GTX 670. A ftriend with ATI VGA didn't get BSOD.

**Comment by Feodor2** [comment]
dup
