### ISSUE TITLE
Google Drive issue

### ISSUE THREAD

**Issue by fenavi** [Feodor2/Mypal68#174]
The browser no longer displays Google Drive's web page properly.
They don't show the list of folders and files. Instead there's a banner saying "A Place For All Your Files"

**Comment by pbcairo** [comment]
I think it's working in 68.13 with setting the user agent to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36`
