### ISSUE TITLE
Can't add another search engine into prefrences

### ISSUE THREAD

**Issue by bolabola6789** [Feodor2/Mypal68#177]
I wanted to use google as my default search engine in the address bar but I there isn't an option for Google and when I click on add another engine it didn't work. I know I can bookmark google and search by clicking on the bookmarks bar but I want the search experience to be as convenient as possible.

**Comment by ahm5jnhi5** [comment]
https://www.reddit.com/r/windowsxp/comments/u6g1n3/adding_google_to_mypal_68_the_complete_tutorial/

**Comment by ahm5jnhi5** [comment]
![H6zwdLB](https://user-images.githubusercontent.com/47126975/210050755-e3f86368-eaae-4fee-b270-d9599e2ad389.png)

**Comment by bolabola6789** [comment]
> https://www.reddit.com/r/windowsxp/comments/u6g1n3/adding_google_to_mypal_68_the_complete_tutorial/

Thanks a lot
