### ISSUE TITLE
cloudflare infinite reload after UI overhaul

### ISSUE THREAD

**Issue by blue-dragon-cairo** [Feodor2/Mypal68#178]
![image](https://user-images.githubusercontent.com/76606635/210406569-82369837-05da-4f5c-8d14-54d52cbfd33e.png)

Note that it happens without any extensions or resetting the browser data. I tried many user agents, including default, Firefox 95, Chrome 108.

**Comment by pbcairo** [comment]
this also happens in Mypal 28.

**Comment by blue-dragon-cairo** [comment]
seems to be fixed in 68.13, and also I need to use the default agent without bumping the browser/OS version
