### ISSUE TITLE
Addons - Searchengines

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal68#18]
In about:support search-engines addons are listed as enabled even though they are not present.
![Screenshot](https://user-images.githubusercontent.com/49531928/162586583-435bb2c1-aebb-4621-986a-ad02c9f2d6e5.jpg)

**Comment by NoNameNeeded2** [comment]
Not all of them are search engines. They are Erweiterungen, hence Addons.
Ublock is not a search engine.

**Comment by Anbima** [comment]
Yes, I installed uBlock.
But the other are searchengines.
How can I remove these?

**Comment by win98se** [comment]
You most probably can't.

> Two questions: Not all search engines are listed as extensions, e.g. IMDB and wiktionary. Maybe these two were not defaults?
When I remove search engines on Options Search page, they still show up as "true" in profile list, even after restarting Firefox. CCleaner still shows them as "disabled" plugins, but they returned as "true" in profiles after a restart , so there is no way to remove them from there now either. So can they actually be removed or would that negatively impact operation? And do these extensions collect data even when not in use?
Thanks.

> ---

> Those two are not bundled with Firefox. Defaults are included in the omni.ja file, so they can't really be removed. And last time I checked it, they couldn't collect any data. This search engine file contains only manifest with an URL to the search engine, list of parameters and translations.

Reference: https://support.mozilla.org/en-US/questions/1266387
