### ISSUE TITLE
Gghh

### ISSUE THREAD

**Issue by Chhhgg** [Feodor2/Mypal68#182]
How to make Ukraind language in mypal please

**Comment by Chhhgg** [comment]
How go make Ukraine language in mypal please

**Comment by Chhhgg** [comment]
How to make Ukraine language in mypal

**Comment by Chhhgg** [comment]
How to make Ukraine language in mypal

**Comment by Chhhgg** [comment]
How to make Ukraine language in mypal

**Comment by blue-dragon-cairo** [comment]
https://addons.mozilla.org/firefox/downloads/file/4101507/ukrainian_language_pack-113.0.20230423.180101.xpi

download it, unzip it and open manifest.json with notepad. Change line <font>#</font>7 to `"strict_min_version": "1.0",` and zip it using the zip format with an xpi extension. install it and select your language in options.
