### ISSUE TITLE
Port to PowerPC OS X (Leopard)

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [Feodor2/Mypal68#184]
Tenfourfox and InterWebPPC both are getting longer in the tooth and eventually more and more of the Web will no longer work on our old Macs.

**Comment by HexagonWin** [comment]
This is something whole different, definitely doesn't fit on the "Issues" of Mypal68.
Though, have you tried out ArcticFox? It has a unofficial port by it's official dev, and it works pretty well.
