### ISSUE TITLE
When will Feodor2 return to work on the project? Man, are you alive? We are worried.

### ISSUE THREAD

**Issue by MP-spec** [Feodor2/Mypal68#186]
Feodor2,
We are worried.
Will you come back to work on MP68?

**Comment by dainiusb** [comment]
Hopefully this isn't the usual case where author loses interest cause he was trying to make something perfect while it was unnecessary.

**Comment by MP-spec** [comment]
Feodor lives in Ukraine,
so he could be lost in this chaos.
You could take shelter in Poland.

**Comment by Feodor2** [comment]
Yes, my life becomes complicated. But sometimes i have good time and conditions to continue browser development, so i do spend the time for that, no other time attend to here answering questions.
So you just hope...

**Comment by Anbima** [comment]
@Feodor2
Good to hear from you and glad to hear you are doing well.

**Comment by mina354** [comment]
@Feodor2 I'm glad to hear you're fine!

**Comment by IP-CAM** [comment]
This is the nightly build new Version from Feodor2, and it so far works well on my PC:
68.13.0b (32-bit)
https://github.com/Feodor2/Mypal68/issues/160

**Comment by Trancer03** [comment]
Feodor2, do you need money? I will be more than happy to donate if you'll set up a secure link!

**Comment by Sen-nin** [comment]
@Feodor2
I too am very glad to hear from you!

**Comment by Trancer03** [comment]
I'm new to GitHub! Can someone explain to me, please, how can I make a contribution to Feodor2?

**Comment by pbcairo** [comment]
select a source file to edit, edit it, and create a pull request
