### ISSUE TITLE
Multi process (e10s) mode is unstable

### ISSUE THREAD

**Issue by spaztron64** [Feodor2/Mypal68#19]
I've noticed that tabs tend to randomly freeze, with YouTube tabs being the worst offender. After switching to single process mode (something I always do anyway), all of these instabilities were fixed.

To switch to single process mode, add a MOZ_FORCE_DISABLE_E10S user environment variable and set it to 1. Don't forget to restart Mypal afterwards.

**Comment by skipster1337** [comment]
For me the single process mode only makes the browser more unstable. Enough for a single tab to crash, it brings down the entire browser. It also appears to make tabs _more_ prone to crashing.

**Comment by NoNameNeeded2** [comment]
> For me the single process mode only makes the browser more unstable. Enough for a single tab to crash, it brings down the entire browser. It also appears to make tabs _more_ prone to crashing.

I can absolutely confirm that.

**Comment by win98se** [comment]
https://github.com/Feodor2/Mypal68/issues/3#issuecomment-1094060298

**Comment by spaztron64** [comment]
Alright, after using Mypal 68 for a while, I too am being hit with random freezes even in single process mode. This applies to 68.12.2b as well.
