### ISSUE TITLE
title bar button glitch while using classic theme

### ISSUE THREAD

**Issue by MWF2** [Feodor2/Mypal68#190]
so it need fix title bar button on xp with classic theme, when if i resize/maximize but on title bar, it will glitch out, this is why aurora xp and 1280px has pull requests for fix title bar at #147

this is example without code:
![glitch of mypal](https://user-images.githubusercontent.com/74994144/221258083-ff535718-63a9-45d5-8e83-619faeda5598.png)
![like this glitch](https://user-images.githubusercontent.com/74994144/221258094-a004faf7-872d-4c9e-a93c-11e712a71e7c.png)
![like this glitch 2](https://user-images.githubusercontent.com/74994144/221258112-d74e49ae-1dc5-4591-955e-147eccd605e9.png)

to this with 1280px's code:
![fix title bar](https://user-images.githubusercontent.com/74994144/221258263-4a182998-507b-481e-a1ad-a210c1db3a04.PNG)

**Comment by 1280px** [comment]
The problem is, as I stated in that PR, that there is no efficient way to detect Windows XP and Windows Vista in Firefox XUL CSS, as corresponding internal filters were removed in Quantum and were not reimplemented.

So, you either have to figure out effective ways to detect needed OS instances first, or implement the filters back somehow.

**Comment by Feodor2** [comment]
I can add windows-xp and windows-vista at the same time to the upcoming release.

**Comment by MWF2** [comment]
alright, so you going to add windows-xp and windows-vista and fix title bar for another upcoming release?

**Comment by 1280px** [comment]
> you going to add windows-xp and windows-vista

He actually did! Now it's only left to do a few minor changes is #147, though I think it'll also make sense to re-visit the files changed in #63 and replace the "windows-glass" workarounds with new Windows version-based queries as well.

**Comment by MWF2** [comment]
ok, so only left that he will do to few minor changes is #147 fix title bar? alright i will wait for another release

**Comment by 1280px** [comment]
You can just make a custom userChrome.css with all the changed rules and it will work the same :) But yeah, I'll look into it when I'll be done with exams

**Comment by MWF2** [comment]
okay

**Comment by MWF2** [comment]
i check it and it's awesome
