### ISSUE TITLE
MyPal68 usage environment and general problems

### ISSUE THREAD

**Issue by kantarousan** [Feodor2/Mypal68#191]
WindowsXP information itself is getting smaller, so I will describe my usage of Mypal68 comprehensively
Sorry for the long post, but I hope it will be of some help in the future.
-----------------------------------------------
Problems with WindowsXP + Mypal68
-----------------------------------------------
Depending on the environment, BSODs may occur frequently in multi-process mode, or they may rarely occur.
Of course, it is desirable to always have multi-process mode available in all systems.
Poor WebGL2.0 performance (Problem with Mypal's web rendering function. Besides this, the graphic card AMD Radeon problem was found)
H264 DXVA hardware acceleration works poorly (VMR9 not utilized)

-----------------------------------------------
[System 1]:

FUJITSU JAPAN FMV-D5380 
CPU Core2 Quad Q8400/MEMORY DDR3-1066/4GB(2GBx2)
GRAPHIC  NIVIDIA Geforce GT635  
WindowsXP ServicePack 3 32bit (Posready Mod)
（other Multi boot OS Windows7 32bit ）

-----------------------------------------------
Mypal version 68.12.5
System 1 always uses single process mode.
BSOD occurs frequently when switching to multiprocess mode.
There is no difference in the frequency of BSOD occurrences due to graphics card changes.

WebGL2.0 performance 
(Unity Browser benchmark 2018 https://linuxreviews.org/static/unity-browser-benchmarks-2018/)
  AMD Radeon HD6450/7570/8570/R7250 score = 24000-26000
  NIVIDIA Geforce GT430 score = 29000-31000
  NIVIDIA Geforce GT635 score = 33000-36000
However, with Windows 7 64bit & Firefox 102.5, the score exceeds 43000 with any graphics card.

MiniDumpFile:
https://drive.google.com/file/d/16thizVHrLEQ15Or7gtd9ADshvG-_1W89/view?usp=sharing

-----------------------------------------------
[System 2]:

FUJITSU JAPAN FMV-D5380 
CPU XEON X3343/MEMORY DDR3-800/8GB(4GBx2)
GRAPHIC CARD AMD Radeon R7 250
WindowsXP ServicePack 3　32bit (Posready Mod)
（other Multi boot OS Windows7&10 64bit ）
-----------------------------------------------
Mypal version 68.12.5
System 2 uses multi-process mode all the time.
BSOD only happens a few times so far.
There is no difference in the frequency of BSOD occurrences due to graphics card changes.
There is no difference in the frequency of BSOD occurrence due to memory replacement (DDR3-800 8GB > DDR3-1066 4GB).

The performance of WebGL2.0 was similar to [System 1].
Regarding the BSOD problem, we are currently investigating the frequency of occurrence due to differences in CPUs.

MiniDumpFile:
https://drive.google.com/file/d/1r5X5Ww5bwHXA0zbU-f-eFBZ2LKiIiOl3/view?usp=sharing
-----------------------------------------------
Supplementary explanation of the system

WindowsXP PAE patcher is not used, if you use it you will not be able to log in to Windows.
Other currently available graphics cards AMD Radeon HD6450,HD6570,HD8570,HD8570-2GB,NIVIDIA Geforce GT430
Currently available CPU Core2Duo E8500
Bios has been modded to add microcode for XEON X3343 and access to hidden settings enabled
By changing a hidden setting item, the graphics card on PciExpress is available at the speed of 5.0GT/S.
About the DDR3-800 memory present in System 2.
There is an unfixed defect in the system BIOS, and in order to use 8GB:4GBX2 memory, it is necessary to modify the ROM (SPD) of the memory module to force it to operate at DDR3-800.
(manufacturer never admitted to system BIOS flaws until the end)

-----------------------------------------------
Graphic card on WindowsXP required in Mypal68
-----------------------------------------------

I think that a cheap graphics card is necessary for drawing recent web pages, but there is a problem that Windows XP is not assumed for the new generation card.
Rumors are true that AMD Radeon cards after 2008 were Direct2D-only and had limited performance on Windows XP (especially Native 2D GDI).
When performing individual benchmarks by PerformanceTest, "AMD Radeon HD6450, HD7570, HD8570, HD8570-2GB, R7 250" became very low performance on WindowsXP.
On the other hand, "NIVIDIA Geforce GT430, GT635" showed performance comparable to "AMD Radeon HD6450 on Windows7".
Old graphics cards such as RadeonX1900 and Geforce7000 are best suited for WindowsXP, but there are problems such as "difficult to obtain, high TDP, incompatible with DXVA and HDCP".
Considering the above circumstances, if the use of the WEB is the primary purpose,
"The existence of drivers for Windows XP", "Good balance of 2D, 3D and DXVA performance", "Even now it is easy to obtain"
Considering them, "low-priced NIVIDIA Geforce 400-700 series" seems to be good.

PerformanceTest V8 BaselineFile:
https://drive.google.com/file/d/1PWUbTKyeZmPhusVqf6f2ggIOgq3jKkhV/view?usp=sharing
-----------------------------------------------
Graphics card UEFI-VBIOS issue
-----------------------------------------------

UEFI is harmful as long as it is used in WindowsXP and Vista.
Graphics cards with "UEFI & Legacy-Hibrid VBIOS" often prevent older systems with only LegacyBios from booting.
This can be avoided by doing "Dump VBIOS > Modification to disable UEFI section > Write" in advance.

All my "AMD Radeon HD7570,HD8570,HD8570-2GB,R7 250,NIVIDIA Geforce GT635" have this modification

-----------------------------------------------
Disable blacklist and force use of WebGL2.0
-----------------------------------------------

As with Firefox, depending on the type of graphics card, [About:Config] should have the following settings (my system 1.2 is all set)
Webgl.disable-angle --> True
layers.acceleration.force-enabled --> True

-----------------------------------------------
About DXVA (FFMpeg acceleration) on Mypal68
-----------------------------------------------

I traced using DXVACHECKECKR during HTML5 video playback, but there is no evidence of Mypal68 accessing DXVA.
But it's still imperfectly accelerated for some types of videos, so it's better than the old Firefox that relied on Adobe Prime.

media.ffmpeg.hwacc_type 0 Incomplete acceleration
media.ffmpeg.hwacc_type 2 Crash (NIVIDIA Geforce GT635) No change from 0 (AMD Radeon R7 250)
media.ffmpeg.hwacc_type 4 Crash (NIVIDIA Geforce GT635) No change from 0 (AMD Radeon R7 250)

Incomplete acceleration is, for example, a video in Youtube Video with the following stats:

a.1920x1080@60 [avc1.64002a (299) / mp4a.40.2 (140)] CPU load 15-27% Probably due to software processing
b.1920x1080@50 [avc1.64002a (299) / mp4a.40.2 (140)] CPU load 15-20% Probably software processing
c.1920x1080@30 [avc1.640028 (137) / mp4a.40.2 (140)] CPU load 8-10% Probably due to hardware processing
d.1920x1080@25 [avc1.640028 (137) / mp4a.40.2 (140)] CPU load 10-13% Probably due to hardware processing

Looking at the changes in the CPU load, there are cases where the CPU load is 8-10% even with a.1920x1080@60 instead of this every time.

When downloading the above video and playing it on MPC-BE

1. Output renderer EVR (DXVA2.0 NetFramework3.5) = CPU load is 20-25%. At first glance, it looks like hardware, but it is software processing.
2. Output renderer VMR9 (DXVA1.0) = CPU load is 0-3% DXVA works perfectly. 　
3. When all internal filters are disabled and [FFDSHOW DXVA VIDEO DECORDER] is registered as an external filter
   DXVA works perfectly regardless of output renderer setting, probably DXVA1.0. CPU load is 0-3%

The CPU load during video playback on Mypal is similar to his EVR (DXVA2.0 NetFramework3.5) in MPC-BE, so it may be software processing.
In case of Firefox + Adobe Prime, the CPU load reaches 37-46%.

-----------------------------------------------
others
-----------------------------------------------

WINDOWSXP defaults to the slow internet connections of the past.
To match today's high speed internet connections.

a. Apply a patch to TCPIP.SYS to remove the limit on the maximum number of connections.
b. Edit the registry and set MTU = 1500, RWIN = 1027840 (optimal values vary depending on the line used)

**Comment by MWF2** [comment]
not only that, when if i using xp x64 bit with hardware acceleation, much tabs it will glitch
![glitch out](https://user-images.githubusercontent.com/74994144/222531555-0b0dbd4d-944d-4837-9ab2-f4529098e5d4.PNG)

**Comment by MWF2** [comment]
![glitch out 2](https://user-images.githubusercontent.com/74994144/222531815-6ace6d98-e50b-4615-ab14-6a513cd975ae.PNG)

**Comment by RamonUnch** [comment]
I would suggest you also give a try to version 68.13.0beta https://github.com/Feodor2/Mypal68/issues/160
I doubt it will fix everything but it is worth trying.

**Comment by kantarousan** [comment]
I found a way to reduce BSOD in multiprocess mode.
As a result of all the experiments, it was "memory installed and consumed" that had a clear effect on reducing BSOD in multi-process mode.
There was no difference due to differences in CPUs and video cards. There was no difference between Mypal Ver68.12 and Ver68.13 Beta.
We have confirmed that BSOD is clearly reduced by installing 8GB of physical memory and applying a modification method (similar to the so-called Chinese patch XP64G.EXE) to the WindowsXP kernel around 2010.

Physical memory capacity

3GB BSOD is very high
4GB　There are many BSODs. If you only use one tab, you won't get many BSODs.
8GB BSOD is very low. About 10 tabs can be started. 　

For example, if you open many tabs of sites such as MSN.COM, it will consume a lot of memory.
At this time, BSOD occurs frequently when 3GB of memory is installed. BSOD rarely occurs with 8GB memory installed.
More than 8GB of memory is not available on my system.

Does Mypal68's multi-process mode have an instruction that uses "memory that does not exist in Windows"? Result of trying to use "nonexistent memory"
The system may crash.

If the BSOD is caused by accessing more than 3GB of memory when the installed memory is less than 3GB, then there must be a way to impose a memory limit on Mypal68 in some way.
maybe.

[Known issue]

As is known, it is necessary to apply a patch to Hal.dll ntkernpa.exe in order to use more than 3GB on WindowsXP 32Bit.
Famous ones include "XP64G", "Fix128" and "PachPAE3".
This is something that fundamentally changes the behavior of the OS, so be careful. You always have to face glitches like "I can't log in to Windows, I get BSOD".
Any combination of OS, video card, drivers, memory, etc. can cause problems.
In general, it is known that the larger the amount of memory that is released in the order of 16GB < 32GB < 64GB < 128GB, the more unstable it is. (If you apply the 128GB Patch here, you will not be able to log in to Windows.)
It is necessary to replace all USB******.SYS with those of Windows Server 2003. (You cannot log in with the WindowsXP SP3 driver.)
All USB devices that have been used once must be completely deleted from the registry and recognized again. (If you leave the past recognition information, it will be BSOD)
All used video cards must be completely deleted from the registry and recognized again. (If you leave the past recognition information, it will be BSOD)

Here are the main changes
"Similar to Chinese patch XP64G.EXE"

[hal.dll]→[hal64g.dll]

C9 53 74 17 80　　　　(Remove 3.5GB memory limit)
↓
C9 53 EB 17 80

6A 10 68 00 00 00 01　　(WindowsXP only missing code)
↓
6A 30 68 FF FF FF FF 

80 40 00 00 00 BE 00 00 01 00 E8　　(WindowsXP only missing code)
↓
80 00 40 00 00 BE 00 00 03 00 E8 

[ntkernpa.exe]→[ntkl64g.exe]

3C 01 75 07 B8　　　(removes 16GB memory limit)
↓
3C 01 74 07 B8　　　

3C 01 75 1B 39　　　(removes 16GB memory limit)
↓
3C 01 74 1B 39

CC 8B FE 55 8B　　　(No need to change if it is already CC 8B FF 55 8B)
↓
CC 8B FF 55 8B

[Boot.ini]

multi(0)disk(0)rdisk(0)partition(1)\WINDOWS="Microsoft Windows XP　Professional Patch64" /kernel=ntkl64g.exe /hal=hal64g.dll /fastdetect /PAE /NOEXECUTE=optin
multi(0)disk(0)rdisk(0)partition(1)\WINDOWS="Microsoft Windows XP　Professional" /fastdetect

[%SystemRoot%\System32\Drivers]
Replace all of these below with version 5.2.3790
usb8023.sys,usb8023x.sys,usbccgp.sys,usbd.sys,usbehci.sys,usbhub.sys,usbintel.sys,usbohci.sys,usbport.sys,usbscan.sys,usbstor.sys,usbuhci.sys,usbvideo.sys

**Comment by MWF2** [comment]
> I would suggest you also give a try to version 68.13.0beta #160 I doubt it will fix everything but it is worth trying.

i use that 68.13 beta, it's not fix issue like glitch ui, and glitch title bar with classic theme

**Comment by MWF2** [comment]
take look, and see #190

**Comment by kantarousan** [comment]
Unfortunately, there was not much difference in the relationship between "Version 68.12.5" and "Version 68.13.0 b" regarding the BSOD issue.

**Comment by Feodor2** [comment]
The first goal is to update javascript - 68.13.0 final release
Second goal to resolve bsod problem - next release
Everything else is not important, but some thing may be done along depending

**Comment by pbcairo** [comment]
Cannot pass through CloudFlare DDoS protection

**Comment by NEO-SPECTRUMAN** [comment]
> Cannot pass through CloudFlare DDoS protection

the same shit
there is any XP browser that can do this?

**Comment by blue-dragon-cairo** [comment]
now cloudflare works for me in 68.13

don't change the useragent-leave it default it worked

**Comment by NEO-SPECTRUMAN** [comment]
for me it works only for "lightweight" cloudflare chalenge
also i tested new fresh unpacked mypal with new profile
and it's doesn't work to....
...also now i have very slow internet connection
maybe it can be reasson too

**Comment by NEO-SPECTRUMAN** [comment]
so you can't pass cloudflare with 10kb/s upload speed

**Comment by NEO-SPECTRUMAN** [comment]
мне кажотсо или в новой версии не так шустро утекает память?
