### ISSUE TITLE
Mypal 68.13.0b - Not saving changes to about:config and added search engines

### ISSUE THREAD

**Issue by danielmcardle** [Feodor2/Mypal68#195]
Hi,

Recently started using Mypal on a Windows XP laptop. For some reason, it's not maintaining changes I make to search engines and about:config settings after I close and open the browser. e.g. I delete the default search engines and add Google Search, and set keyword.enabled in about:config to true. I close the browser, re-open, and they're reset.

Any ideas?

**Comment by Feodor2** [comment]
What about other things, do they save?

**Comment by LuxLOL** [comment]
This problem started in MyPal 68.12.4b

**Comment by pbcairo** [comment]
For me there's no such issue on 68.12.5 and 68.13... do other settings get reset too?

**Comment by LuxLOL** [comment]
> For me there's no such issue on 68.12.5 and 68.13... do other settings get reset too?

Looks like this problem started to happen in MyPal 68.12.4b when using a custom "search.json.mozlz4" where google search (or another search engine) was added.
C:\Documents and Settings\<UserName>\Application Data\Mypal68\Profiles\XXXXXXX.default-default
https://www.mediafire.com/file/bcxn1ygacr3dwzv/search.json.mozlz4/file

**Comment by K4sum1** [comment]
I found that if I move the program it makes a new profile, it could be what happens here. Go to about:profiles and switch to the oldest. Then you can go and delete the others.

**Comment by pbcairo** [comment]
ah yes even updating the browser creates a new profile so I have to switch it

**Comment by Feodor2** [comment]
Straight update is not to creates a new profile, may be you update from newer to older version then delete the **compatibility.ini** file. Anyway i suggest keep backup profile to make sure.
