### ISSUE TITLE
Rust compiler patches?

### ISSUE THREAD

**Issue by pbcairo** [Feodor2/Mypal68#198]
In the build guide:
> Put my rust patch in the rust src dir and apply it

searched in your source code but could not find something related to rust patches. Or is there your Rust compiler in binary?

Just need a Rust compiler to target Windows XP. I tried Rust9X but didn't work and gives me errors in the linker and still building executables for Vista+

**Comment by Feodor2** [comment]
Newer rust versions significaly changed, what was normal on 1.35 will became error, so take Rust9X older version.
My rust patch was in first zips, now i could upload patches to the github - look in the wiki page.
Once i going to try rust version 1.40 or even greater

**Comment by pbcairo** [comment]
ah ok thanks
