### ISSUE TITLE
youtube more tabs with mypal, and youtube website will stuck and not load

### ISSUE THREAD

**Issue by MWF2** [Feodor2/Mypal68#200]
when i was testing like open like 4 or 5 youtube tabs, 1 discord and others tab for other site while i open more youtube tabs, youtube itself won't open, it will stuck like for while, it won't open anything like no search, no videos and nothing, on both real hardware and virtual machine, with browser.tabs.remote.autostart set to false, but with browser.tabs.remote.autostart set to true, nothing happen, but with more youtube tabs, until youtube site won't load, but after close all youtube tabs, and try again with virtual machine, i didn't try it on real hardware tho: This is what it looks like with browser.tabs.remote.autostart set to false.
![image](https://github.com/Feodor2/Mypal68/assets/74994144/af161d23-541b-4cba-a6de-478be4f65267)
this 2 pictures what looks like with browser.tabs.remote.autostart set to true:
![image](https://github.com/Feodor2/Mypal68/assets/74994144/02121f5f-4a6c-4153-89f9-fd3975068aa2)
![image](https://github.com/Feodor2/Mypal68/assets/74994144/d6254c66-bc36-4a46-8416-25aa79df8f2e)

**Comment by blue-dragon-cairo** [comment]
I got a similar thing too if I load too much heavy tabs or run Mypal for too much time the memory will leak or something I have to relaunch the browser

**Comment by MWF2** [comment]
even with set browser.tabs.remote.autostart to false to not get bsod, like this
![image](https://github.com/Feodor2/Mypal68/assets/74994144/e56e8b47-142f-40d8-8190-3797b0043975)

**Comment by Feodor2** [comment]
Opened 9 tabs on youtube and one started playing, such a heavy stream with chat, RAM quickly goes on 2,7 gb, i have 3gb so though this is the max limit of youtube peges, then i saw RAM drops to 2,3, i opened one more tab - 2,5 gb now, after half an hour it remains 2,5. I shall wait several hours and try one more tab.

On loading youtube i see grayed images too, but after ~2sec they painted fine.

**Comment by Feodor2** [comment]
So youtube became even more abomination it is, 10 pages is to much for old machine, while it keeps painting fine the same 2sec, but cpu 95% on switching tabs and playing stutters hard. Beside i opened 10 other sites and then close tubies until playing is restored, which is 4 pages. Direct9 hardware acceleration may helps, but it still unstable.
Conclusion no more than 4 pages.

By the way i forgot about using youtube years ago, i suggest invdius instead - can keep opened of dozen tabs easily.

**Comment by MWF2** [comment]
for people that still use youtube for while like me, yea it cannot switch to invidus
