### ISSUE TITLE
Discord now no longer upload images and videos

### ISSUE THREAD

**Issue by MWF2** [Feodor2/Mypal68#201]
days later after pre relased of mypal with discord working, now issue happen in discord, it no longer upload any images and videos

https://github.com/Feodor2/Mypal68/assets/74994144/fb42e56a-5569-41eb-ab80-d101c70259cc

https://github.com/Feodor2/Mypal68/assets/74994144/fdd3c58b-16d4-4233-a88e-ce375b17d725

**Comment by MWF2** [comment]
https://github.com/Feodor2/Mypal68/assets/74994144/d63d3c8c-2a84-4028-b1fa-c14b16f9cf5c

**Comment by MWF2** [comment]
even i try to upload image from download folder to discord in mypal, and nope still won't work

**Comment by MWF2** [comment]
any got same issues in discord?

**Comment by blue-dragon-cairo** [comment]
doesn't work for me too on the latest Discord version

they keep adding wierd new js to their client

works on 2022 & 2019 version

**Comment by Legendary-Candice-Joe** [comment]
how do you get the 2019 / 2022 client?
Worth mentioning you can use another browser like new moon to upload images and stuff, it's not great but it works for me. But cause new moon has WebRTC removed you can't use it for voice calls.

**Comment by blue-dragon-cairo** [comment]
don't really recommend using old clients unless you really like it or want it

For Mypal68 - #181
For Mypal 27, 28, 29 - Feodor2/Mypal#114

**Comment by Legendary-Candice-Joe** [comment]
Yeah I get the same error tons of people were talking about in the thread. You're right though I should really bother using an older client. I'll just have to wait 'till these issues get fixed.

**Comment by MWF2** [comment]
or if you don't want to use old version, then at least should wait until this issue gets fixed

**Comment by Legendary-Candice-Joe** [comment]
There was a typo in my message woopsie. It's fixed now.

**Comment by MWF2** [comment]
i'm gonna wait as well to discord upload gets fixed in next update of mypal

**Comment by MWF2** [comment]
ok now upload images works again with release today version of mypal 68

**Comment by K4sum1** [comment]
If it's fixed, you should close the issue.
