### ISSUE TITLE
new mypal-68.13.0 does not see 68.12.5 profile and plugins?

### ISSUE THREAD

**Issue by krzysiobal** [Feodor2/Mypal68#202]
I downloaded yesteray this new release and it is not able to see my history, tabs and even plugins from the 68.12.5 version (I installed it to different directory).
Renaming the 68.12.5 directory and moving the 68.13.0 directory to where 68.12.5 previously was does not help.

**Comment by RamonUnch** [comment]
go at `about:profiles` abs you should be able to see all the profiles and select the one you prefer.

**Comment by Feodor2** [comment]
If you install new copy of the browser in the other directory new clean profile is created.
This is so as intended, you may easily copy things from the old profile. Look the tip above about:profiles

**Comment by K4sum1** [comment]
Confusing and bad intended behavior. There's no reason to have this.

**Comment by visionhelp** [comment]
If explaing welcome. 
With a new version the old version is not necessary anymore. 
But when the old version wants to be kept further with, then one has two versions. 
"the tip above about:profiles" appears to me a solution to this. 
If deleting the old versions content respectively not necessary to delete, just copy the content of the extracted (new version) folder to the old folder. 
And (the old) profile is there.
