### ISSUE TITLE
Any chance to make Mypal 68.13b portable?

### ISSUE THREAD

**Issue by jasonliul** [Feodor2/Mypal68#206]
Like old mypal...

**Comment by jasonliul** [comment]
i use tmemutil.dll to make portable anyway.
http://www1.plala.or.jp/tete009/en-US/software.html#TMOZDLL_RELEASE

but weird thing happen, it can't change location, if so, Mypal startup without any profile.

**Comment by blue-dragon-cairo** [comment]
#67
