### ISSUE TITLE
Simplified Chinese language pack for Mypal 68.13.0b

### ISSUE THREAD

**Issue by shawnpxtl** [Feodor2/Mypal68#210]
Because the latest version of Mypal will make the previous language pack unavailable (you can see the specific information [this](https://github.com/Feodor2/Mypal68/issues/203)), so I read the tutorial and made a repair language pack for Simplified Chinese. Users who use Simplified Chinese can go to [Github](https://github.com/shawnpxtl/Mypal68-zh_CN-xpi)
![zh-CN](https://github.com/Feodor2/Mypal68/assets/67815438/934154bc-f265-49c4-98e2-2bcdb9af1b4f)
![zh-CN1](https://github.com/Feodor2/Mypal68/assets/67815438/6a4c3fc0-0128-4969-89f1-0f5ec69db5e4)

**Comment by louies0623** [comment]
如果可以，你能不能也做繁體中文的語言包，因為我在它的教程看不太懂，也希望在Vista 上執行

**Comment by shawnpxtl** [comment]
> 謝謝你在這裡貢獻了簡體中文，但是如果可以，你能不能也做繁體中文的語言包，因為我在它的教程看不太懂，也希望在Vista 上執行

繁體中文啊⋯⋯可以考慮，不過我可能最早也得明晚再看有沒有空做了

**Comment by shawnpxtl** [comment]
> 謝謝你在這裡貢獻了簡體中文，但是如果可以，你能不能也做繁體中文的語言包，因為我在它的教程看不太懂，也希望在Vista 上執行

好了，可以去[这里](https://github.com/shawnpxtl/Mypal68-chinese-xpi/)下载试下了

**Comment by louies0623** [comment]
謝謝你，只是有個錯誤，我用了一下發現到，在設定的首頁中（繁體中文），或是選項的主頁中（簡體中文）它並沒有翻譯到，而在使用Firefox 的69.0b16版翻譯，是正常顯示中文的，我想你可能需要從這版本修改

**Comment by shawnpxtl** [comment]
> 謝謝你的辛勞，只是有個錯誤，我用了一下發現到，在設定的首頁中（繁體中文），或是選項的主頁中（簡體中文）它並沒有翻譯到，而在使用Firefox 的69.0b16版翻譯，是正常顯示中文的，我想你可能需要從這版本修改

你說的是關於界面中的Firefox殘留？如果是這個的話現在應該已經修復了，再看看？我這邊應用之後顯示翻譯是正常的。

**Comment by louies0623** [comment]
![Windows Vista-2023-07-24-23-06-39](https://github.com/Feodor2/Mypal68/assets/44593430/81dc9ac4-20bc-443e-bc89-01a0c0218bf5)
這是安裝後語言包它的樣子

應該像這樣
![Windows Vista-2023-07-24-22-53-25](https://github.com/Feodor2/Mypal68/assets/44593430/bbb3560b-3b93-40e0-89e0-c4249e125c11)

**Comment by shawnpxtl** [comment]
> 並不是Firefox殘留，而是沒有翻譯的部分
> 
> ![Windows Vista-2023-07-24-23-06-39](https://user-images.githubusercontent.com/44593430/255653062-81dc9ac4-20bc-443e-bc89-01a0c0218bf5.png) ![Windows Vista-2023-07-25-00-31-01](https://user-images.githubusercontent.com/44593430/255654874-07f73026-8722-4d33-b4bb-b7383e77af33.png)
> 
> 這是安裝後語言包它的樣子
> 
> 應該像這樣 ![Windows Vista-2023-07-24-22-53-25](https://user-images.githubusercontent.com/44593430/255653607-bbb3560b-3b93-40e0-89e0-c4249e125c11.png) ![Windows Vista-2023-07-24-22-57-43](https://user-images.githubusercontent.com/44593430/255655147-f0513b4a-d154-4c1b-9f9b-a95ea13fbde8.png)

嗯，那我抽空改改吧（

**Comment by louies0623** [comment]
然後在說明的" Mypal 是由 Feodor2 製作的為 Windows XP / Server2003 / Vista 適配的瀏覽器"那一段改為
"Mypal 是由 Feodor2 所開發適用於 Windows XP / Server2003 / Vista 的瀏覽器" 
這樣比較適當

**Comment by shawnpxtl** [comment]
> 然後在說明的" Mypal 是由 Feodor2 製作的為 Windows XP / Server2003 / Vista 適配的瀏覽器"那一段改為 "Mypal 是由 Feodor2 所開發適用於 Windows XP / Server2003 / Vista 的瀏覽器" 這樣比較適當

现在可以去我的仓库再看看了，更新了一版

**Comment by liqideqq** [comment]
> 因为最新版本的Mypal会让之前的语言包不可用（具体信息可以看[这个](https://github.com/Feodor2/Mypal68/issues/203)），所以我看了教程，做了一个简体中文的修复语言包。使用简体中文的用户可以去[Github](https://github.com/shawnpxtl/Mypal68-zh_CN-xpi) ![zh-CN](https://user-images.githubusercontent.com/67815438/244735965-934154bc-f265-49c4-98e2-2bcdb9af1b4f.jpg) ![zh-CN1](https://user-images.githubusercontent.com/67815438/244736412-6a4c3fc0-0128-4969-89f1-0f5ec69db5e4.jpg)

我制作了一个便携版的 Mypal，它在我当地的电脑上运行良好，但在另一台电脑上无法工作。它的接口提示符是“ Window id =”main-Window”^

**Comment by liqideqq** [comment]
不用汉化插件，因为我的本地电脑和另一台电脑都能正常运行。我发现这个插件不能随文件一起携带吗？加了就报错。。。
