### ISSUE TITLE
Support regex unicode identity/character class escapes

### ISSUE THREAD

**Issue by obfuscatedgenerated** [Feodor2/Mypal68#212]
[This function in xterm.js](https://github.com/xtermjs/xterm.js/blob/ac923e55d2f1f99342301d35acb5ae475b07f651/src/browser/AccessibilityManager.ts#L161) tries to compile the regex `/\p{Control}/u`, which uses the Control unicode identity to select control characters.

This seems to be some ES6 feature not supported by mypal (both old mypal and mypal68). It raises the error `SyntaxError: invalid identity escape in regular expression`.

It seems to have been [introduced in Firefox 78](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape#browser_compatibility), but I'm aware this is forked from 68. I understand if this may not be on the roadmap but I'd appreciate if this feature was supported to get my website working in mypal, cheers!

**Comment by RamonUnch** [comment]
Well Feodor started from Firefox 68esr but he is planning to reach a more modern level of web compatibility by back-porting more modern JS engine features to MyPal68.
From what he says the latest 68.13b beta should be on par with Fx 78, it is maybe not perfect yet but you can expect things to improve in the future. hopefully this will come too.

**Comment by obfuscatedgenerated** [comment]
Good to know, cheers 👍 Looking forward to where this project goes!

**Comment by Feodor2** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1367105
I did according this, and applied all except [1519483 Implement the RegExp Match Indices proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1519483) which at 88 version

Next i checked [Matching prices](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape#matching_prices)
Which did not get SyntaxError:

So assume your thing has error

**Comment by obfuscatedgenerated** [comment]
I'll try updating to 68.13b and give it another try

**Comment by obfuscatedgenerated** [comment]
Yep, works in the beta. Thanks
