### ISSUE TITLE
Latest Download is 500+ Megabytes .....!

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#218]
Why has the latest fixed Download such a huge Size ?

**Comment by NEO-SPECTRUMAN** [comment]
WHUT?

**Comment by blue-dragon-cairo** [comment]
i think feodor removed the executable/binaries

i'll reupload them

**Comment by blue-dragon-cairo** [comment]
https://drive.google.com/file/d/1EkfHnFMG_c8goZ8YyxKJNdZhJp_5lGNi/view?usp=sharing

**Comment by Feodor2** [comment]
I doing the next release and have found error that some files did not updated on the git.
Turned out the binary do not match the source  - this is bad, may cause well-wishers around begin an incursion again.
Just in case i also remove the old binary.

**Comment by Feodor2** [comment]
If there is no binary then nothing to dowload
![image](https://github.com/Feodor2/Mypal68/assets/19492771/3297c795-4a5f-48cd-8058-9d6cb677a087)

**Comment by IP-CAM** [comment]
Latest Version can be found here;
https://github.com/Feodor2/Mypal68/releases/tag/68.13.1b

**Comment by vertaa** [comment]
I noticed the Mypal68 does not show the file size when downloading its source code. Is it because the file is to big? when downloading the binary files, it shows the file size.
