### ISSUE TITLE
How do you install 68.13b?

### ISSUE THREAD

**Issue by denizyt9559** [Feodor2/Mypal68#221]
There is only source code, but no installers! Plus I couldn't find any installers in the source code as well!

**Comment by IP-CAM** [comment]
try  this:
https://drive.google.com/file/d/1EkfHnFMG_c8goZ8YyxKJNdZhJp_5lGNi/view?usp=sharing

**Comment by coolio2013** [comment]
Not the installer, but it seems it is newer:
https://archive.org/details/my-pal-68-x-32

**Comment by blue-dragon-cairo** [comment]
that one is 68.12.4 and the one I uploaded is 68.13 based on Firefox 78 JS engine

**Comment by blue-dragon-cairo** [comment]
Feodor didn't make any installers yet, tho there is another created by someone else

**Comment by RamonUnch** [comment]
> New version
> https://mega.nz/file/QaY1zLLY#PhGLpVBfu51To4sjqSgfjaLX6nyebwye82FliTf41yA
> sources
> https://mega.nz/file/hDRiESYY#7mKpjcPkjczsvlifsoajhaLmggPN3oKe7-HwUeJpBpk
> This is prerelease version for testing, javascritpt at 78 level.
> ATTENTION remove language packs for the original firefox - they will be not anymore compatible.

This version is dated 13/05/2023, There is a later release dated 31/05/2023 I have on my disk. I downloaded on the 68.13b release page before it got removed. I will upload it to MEGA and give a link when it is done.

**Comment by RamonUnch** [comment]
Version 68.13b dated 31/05/2023:
https://mega.nz/file/3ToTjIoD#Bz28B3CozM6a_0r_RaT9a3J3cVLiD55uHxzwUujwDAw

VirusTotal scan result (to be sure):
https://www.virustotal.com/gui/file/5b8e660fd13d097cb8c2263ca3cbb4cb26b125dcf9f444db642cc2a07e05f5ca
```
Name: mypal-68.13.0.en-US(31-05-2023).win32.zip
Size: 64815241 bytes (61 MiB)
CRC32: 4687D218
CRC64: 4A453BC3539E4409
MD5: 3abcaa50a73cf97eaf5fe5108eeb71f0
SHA256: 5b8e660fd13d097cb8c2263ca3cbb4cb26b125dcf9f444db642cc2a07e05f5ca
SHA1: ddda2ba8f54d89bf1068b0e8497838e0702d72cc
BLAKE2sp: 06ce5f791b3fb436ff912818d9c521edaa5d8a93aa17b94f2fb5b0806877864c
```
Note that I do not have the exact original file (unfortunately), it seems I renamed the folder to mypal68.13 in 7-zip, I renamed it back to `mypal` as it originally was but the checksum might differ from the original download :(

Anyway I do not have he exact associated source, so I just share it for historical reasons, It is advised to wait for next release, hoping Feodor will not have any source-binary mismatch this time. But this may be useful in the meantime.

**Comment by IP-CAM** [comment]
The latest Mypal68.13.1b Release can be downloaded here:
https://github.com/Feodor2/Mypal68/releases/tag/68.13.1b

**Comment by andika207** [comment]
@IP-CAM I tried it on different computers, (they are not old shit from the early 2000's with 1GB of RAM)
I open a handful of tabs and once I shut it down I get a BSOD.
the code is still buggy because no other browser crashes here

**Comment by RamonUnch** [comment]
@andika207 Follow the instructions on the main page https://github.com/Feodor2/Mypal68#mypal68, scroll a little and you will see how to report a BSOD.

**Comment by Feodor2** [comment]
Also duplicate
