### ISSUE TITLE
Spotify Web Player does not work for MyPal 68

### ISSUE THREAD

**Issue by CRUProductions** [Feodor2/Mypal68#223]
![image](https://github.com/Feodor2/Mypal68/assets/111876654/447202e3-96d5-40be-b66e-fd86a4432680)

It says “Playback of protected content is not enabled”. 

I am also running MyPal 68.13.0b on Windows 2000 (with KernelEx) in a Virtual Machine.

**Comment by IP-CAM** [comment]
Try the latest Mypal68.13.1b Release, it can be downloaded here:
https://github.com/Feodor2/Mypal68/releases/tag/68.13.1b

**Comment by CRUProductions** [comment]
> Try the latest Mypal 68.13.1b Release, it can be downloaded here:
> 
> https://github.com/Feodor2/Mypal68/releases/tag/68.13.1b

Even after updating to 68.13.1, same message. How to enable play DRM/protected content on MyPal 68?

**Comment by Feodor2** [comment]
>DRM/protected content

Never will no matter the update
