### ISSUE TITLE
Google Colab stucks at Loading...

### ISSUE THREAD

**Issue by ghost** [Feodor2/Mypal68#224]
**Issue:** Google Colab gets stuck at loading phase.
**Steps to reproduce:** Open colab.research.google.com, select any notebook or create it yourself (Google account required!).
If you open any notebook, it will stuck at loading, if you create a notebook, it will show blank screen.
**Version:** 68.13.1b
**OS:** Microsoft Windows XP Professional Service Pack 3
![image](https://github.com/Feodor2/Mypal68/assets/118223558/a01740ce-a67e-471d-85c1-b9e244dc4290)

**Comment by blue-dragon-cairo** [comment]
i can confirm that too

**Comment by unattendedplayer** [comment]
As Feodor2 doesn't use Google products, the best fix is to use Kafan Minibrowser (find the modified version from MSFN)

**Comment by bluedragon-cairo** [comment]
I think currently I need to use New Moon to use Colab on XP... https://o.rthost.win/palemoon/palemoon-28.10.7a1.win32-git-20230902-d849524bd-uxp-e27e1cd712-xpmod.7z
