### ISSUE TITLE
closing Mypal 68-13.1 crashes computer

### ISSUE THREAD

**Issue by jbclem** [Feodor2/Mypal68#225]
When I close Mypal-68.13.1 the screen goes black and the computer reboots.  Checkdisk runs and takes a while, showing a lot of error messages, most concerning the mypal profile.  It ends with 55 lost chains .  Eventually, WinXP sp3 starts up and everything seems normal.  Except that I'm leary of using this latest version of Mypal.

Is there a default Mypal-68.13.1 settiing that I need to change, or look for,  that could be causing this problem.

**Comment by RamonUnch** [comment]
@jbclem Follow the instructions on the main page https://github.com/Feodor2/Mypal68#mypal68, scroll a little and you will see how to report a BSOD using BlueScreenViewer. Then just zip the generated `report.html` file and attach it here to a post and hopefully Feodor will be able to fix it.

There are two things that can improve stability for some people:
1) disable hardware acceleration. (in the `about:preferences` page, scroll to Performances and uncheck the `Use hardware acceleration when available`
2) disable multi-process mode. (set `browser.tabs.remote.autostart` to false in `about:config`)

**Comment by Feodor2** [comment]
#3
