### ISSUE TITLE
websites paritally working

### ISSUE THREAD

**Issue by vertaa** [Feodor2/Mypal68#230]
msfn.org the reply forum doesnt loaded.

not sure its working correctyly, but msfn keeps loading and reading data from msfn.org. the website does not seem finish to loading.

![msfn](https://github.com/Feodor2/Mypal68/assets/67488797/e977baa2-05d4-44c4-8550-a50f86cb5143)

stuck at reloading.
https://forums.mydigitallife.net/threads/tool-xp2esd-create-modern-windows-xp-installer-v1-6-2.82935/page-16

**Comment by Feodor2** [comment]
not confirmed

**Comment by vertaa** [comment]
quote is actually working. the lag time and how many times i hit quote was the cause of my display missing or double quoted. 

tried again with mypal68 with a refresh install and it is working,.

https://forums.mydigitallife.net/threads/tool-xp2esd-create-modern-windows-xp-installer-v1-6-2.82935/page-16
