### ISSUE TITLE
Russian language pack for MyPal 68.13.1b is here

### ISSUE THREAD

**Issue by zanud** [Feodor2/Mypal68#231]
[Отсюда](https://disk.yandex.ru/d/Nqt-CQ5nWidkfQ) можно скачать русский языковой пакет для MyPal 68.13.1b, созданный по инструкции, приведённой в #203.

**Comment by Trancer03** [comment]
А где можно скачать русский словарь для проверки орфографии?

**Comment by Trancer03** [comment]
А где можно скачать русский словарь для проверки орфографии?

**Comment by zanud** [comment]
@Trancer03:

https://addons.mozilla.org/ru/firefox/language-tools/

Русских словарей там лежит несколько - под разные вкусы и нужды. При необходимости можно установить сразу несколько и потом на лету переключаться между ними в зависимости от сиюминутных потребностей.
