### ISSUE TITLE
Систематически отпадает скролл по up/down page up\down

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#238]
Собствено сабж
На некоторых страница ВНЕЗАПНО скролл страницы с клавишь отпадает
Тыкание по бегункам и пустотам не возвращает скроление

такое например ловится на том же гитхабе

...да и наверно такая глюка есть и на старом фаирмоксе

**Comment by NS-Clone** [comment]
и отваливаютсо наверно не только они
ctrl + S тоже
при этом на соседних вкладках, с тем же сайтеком
такого не наблюдаетсо

**Comment by Feodor2** [comment]
Нигде не замечал такого
В других вещах ничего не отпадает?

**Comment by NS-Clone** [comment]
> Нигде не замечал такого В других вещах ничего не отпадает?

нет
но уменя как правило 200+ открытых вкладок
и как правило браузер работает 8+ часов
(иногда дня 3)

**Comment by NS-Clone** [comment]
в "старых" фаирфоксах наблюдаетсо другая схожая проблема
ВНЕЗАПНО с кнопок начинают листатсо вкладки
при этом как "осознанно" зайти в этот режим непонятно

**Comment by NS-Clone** [comment]
при этом скролл с колесика мыши остаетсо работать

**Comment by NS-Clone** [comment]
> А после щелчка мышкой по странице фокус перемещается на неё, и всё начинает работать привычным образом.

неп
как раз проблема в том что
"фокус" на страницу никакими щелчками не переводится
можно переключитссо на другую страицу
и скролить на ней
вернутсо назад и скролла так и нет

**Comment by zanud** [comment]
> как раз проблема в том что
> "фокус" на страницу никакими щелчками не переводится

Это, насколько я понял, сейчас так. А я писал про ту ситуацию у "старых фаирфоксов", когда вместо прокрутки страницы вкладки начинали переключаться. Мне в таких случаях щелчок по странице всегда помогал.

**Comment by NS-Clone** [comment]
в старых фаирфоксах
можно вообще иметь фокус на другой странице
и скролить ее колесиком даже не видя ее
а потом возвращаешся а все "уплыло"

**Comment by NS-Clone** [comment]
заметил что заевший скролл отпускает если клацать спойлер
открыть а если не помогло то закрыть


n раз повторил глюку
находясь на
https://github.com/Feodor2/Mypal68
кликаем лкм-ом по любой релизной кнопке

Releases 7
Test ompt 
+6 releases

попадаем на страницу с заевшим скроллом
жмем назад
и повторяем

**Comment by NS-Clone** [comment]
ctrl + s отваливаетсо тоже точно
и по моему даже еще какойто хоткей неработает

мало того при этом НЕ работает ctrl + c на выделенном тексте
и егоо не возвращаает кликание по спойлеру или реакции

так же на "разлоченной" странице
скролл успешно залипаетт обрратно

только перезагрузка страницы избавлляяет от вссех проблем
ну и если открывать в новой вкладке
глюка или нет вообще
и повторяетсо в 2 из 10+ случаев

**Comment by NS-Clone** [comment]
в новом 68.13.3b с чистым профилем повторить не смог
тут же в паралельна открытом основном 68.13.2b повторяемоссть 100%

**Comment by Feodor2** [comment]
И такого тоже никогда не было.

**Comment by NS-Clone** [comment]
> И такого тоже никогда не было.

ну а я опять легко повторил
опять придетсо клонировать фаирфокс
и отключать все что было включенно...

**Comment by NS-Clone** [comment]
а вот я открыл в "приватном" окне
и глюка с ходу нет

**Comment by NS-Clone** [comment]
ну вот я долго юзал другой браузер
и проблемы там не было как таковой

и вот поставил седня ScrollAnywhere
и проблема теперь и тут
на гитхубе снова отваливаетсо скролл с кнопок...
