### ISSUE TITLE
WebRTC - Unable to Choose Line In

### ISSUE THREAD

**Issue by JodyThornton** [Feodor2/Mypal68#24]
When I access my work website (just for trial and error), which utilizes WebRTC to record audio, I cannot select "Line-In".  I can only allow "Default Audio Device", which Line In is selected as.  If I record after that, there is just a constant hum/ring.

**Comment by Matiasgroen** [comment]
Mypal 68 does not yet have WebRTC support. See https://github.com/Feodor2/Mypal/issues/46#issuecomment-1090189853

**Comment by fasduswisdom** [comment]
Darn I wanted to use Discord

**Comment by win98se** [comment]
@fasduswisdom https://github.com/Feodor2/Mypal68/releases/tag/68.12.2b already has WebRTC support, try it.

**Comment by Matiasgroen** [comment]
Won't work, I tried with Discord (required UA spoof) and it received audio fine but couldn't pick up my mic.

**Comment by MWF2** [comment]
as for hangouts call and google meet call, when update 68.12.2b was on, it works, now with 68.12.3b is no longer work hangouts and meet calls anymore in both vista x64 and xp x64 with multiprocess true or false, it gave me a error
![now call hangouts, google meet is not working anymore, even with multiprocess is true and false](https://user-images.githubusercontent.com/74994144/170774125-9c4de09f-1c5b-47a5-9084-072997b71de3.png)

**Comment by Matiasgroen** [comment]
WebRTC is disabled by default in 68.12.3b. See #83
