### ISSUE TITLE
The browser is so laggy

### ISSUE THREAD

**Issue by selvagoat** [Feodor2/Mypal68#244]
literally the title says it this browser should be better than google chrome and turns out google chrome is farly better in performance, mypal crashes or stops working when increasing the video quality in youtube.

**Comment by Legendary-Candice-Joe** [comment]
Also I'd recommend getting the H264ify plugin if you wanna watch YouTube on older computers.

**Comment by MWF2** [comment]
meanwhile at powerful one that i have with intel core i5 2540m, it don't play 1080p with 60 fps so well, but it can play 1080p with 30 fps

**Comment by MWF2** [comment]
> literally the title says it this browser should be better than google chrome and turns out google chrome is farly better in performance, mypal crashes or stops working when increasing the video quality in youtube.

what's specs that you have? whatever cpu, ram gpu from desktop computer or laptop

**Comment by ab288** [comment]
It used to be just as fast as the rest but in the last several
    months  to a year,  I think some browser protocols have been changed
    on the net  and thats been making mypal more laggy. on some sites
    using the latest protocols. 
    just my feeling from what im observing.. the latest version Firefox
    on windows 10 is very snappy. time for another mypal update..  I'd
    be curious to know what is causing the lagginess tho, something has
    changed with the way browsers are interacting with the net now. 
    
    
    The
    On 8/8/2023 2:53 PM, Selva124 wrote:
    
    
      literally the title says it this browser should be
        better than google chrome and turns out google chrome is farly
        better in performance, mypal crashes or stops working when
        increasing the video quality in youtube.
      —
        Reply to this email directly, view it
          on GitHub, or unsubscribe.
        You are receiving this because you are subscribed to this
        thread.Message ID: ***@***.***>
      [
{
***@***.***": <a class="moz-txt-link-rfc2396E" href="http://schema.org">"http://schema.org"</a>,
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": <a class="moz-txt-link-rfc2396E" href="https://github.com/Feodor2/Mypal68/issues/244">"https://github.com/Feodor2/Mypal68/issues/244"</a>,
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com/Feodor2/Mypal68/issues/244">"https://github.com/Feodor2/Mypal68/issues/244"</a>,
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": <a class="moz-txt-link-rfc2396E" href="https://github.com">"https://github.com"</a>
}
}
]
    
    
    -- 
      I am; never doubt; remember, it is I who hold the keys to many
      doors; I will open them one after the other, each one at the right
      time, do you understand this, My child?
      you need not worry, you need not haste; I, the Lord, will bring up
      everything on the right time;

**Comment by Selva124** [comment]
wow i have installed h264ify and it improved the performance alot for youtube
also for discord when they're are too many gifs playing it lags or crashes the browser.

**Comment by Selva124** [comment]
if anyone knows how to fix the gifs issue tell me please

**Comment by Selva124** [comment]
my pc specs are: 1GB Ram, Pentinum(R) Dual-Core CPU E5500 2.80ghz (32 bit system)

**Comment by Selva124** [comment]
today mypal is offently crashing at random moments

**Comment by Selva124** [comment]
> Actually how old your cumpooter? This is to play fine on cor2duo. https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/caminandes-1-llama-drama-av1-opus.webm

the browser is crashing offently now even at 480p quality it struggles alot

**Comment by Legendary-Candice-Joe** [comment]
As unhelpful as it is to say, this might be a problem with your install of Windows.
Even on Windows 2000, and a Socket 478 Pentium 4 I have not had the browser crash randomly. Even the multiprocessing worked.
And although it's slow (because of the Pentium 4) it can still play YouTube videos fine. And load things like Discord fine.

On a 4 Core i3-2120 system running Windows XP the browser is super fast! And I have had barely any problems with it?
So this might be a problem with your browser config or you Windows install itself.

The one issue I've had is just the microphone not working which is unrelated and I have already posted an issue about it.

**Comment by Selva124** [comment]
windows install has no problem bro i used to use chrome always and it's so smooth i modified mypal config a litttle bit for more performance i mean i got more performance but the browser is crashing offently no lag tho

**Comment by Feodor2** [comment]
Yes the browser is too heavy for your coomputar, you have soo small RAM, you to keep no more than one youdupes tab and no more than 10 other tabs.
Or why not to go back for chrome.

**Comment by Selva124** [comment]
i have an issue with my ram and i cannot use any other modern browser, the only most compatiable browser that i found is mypal so i have to stick with it until some months till i upgrade my pc

**Comment by Selva124** [comment]
just if possible please optimize the browser more

**Comment by bushy555** [comment]
Selva124:  1 gig ram?    You are not doing yourself any favours by only running 1 gig of ram. 
XP x32 can handle 3 gig.  XP x64 can handle 128Gig.
Surely you can find / scrounge a 4 gig ram module for your computer. Where I am, they are like $10 on ebay brand new postage included.

**Comment by unattendedplayer** [comment]
What is wrong with these Americans? Why do they think every country's currency equals to the USD? Looks like he's Iranian or Egyptian and afaik $10 is not cheap there or it's even more expensive than $10, leaving you with old parts to use. In those countries those stuff are more expensive than what you get in the USA, because it's a poor country. So think before commenting.

**Comment by bushy555** [comment]
@unattendedplayer  Australia dude. How do I look like Im an egyptian ? 
....And its the equivalent of about us$1.00 in the real world.
And, nah, us aussies don't think. We drink whilst commenting. Chuck another dingo on the barbie mate.
