### ISSUE TITLE
How to change default search engine to Google?

### ISSUE THREAD

**Issue by selvagoat** [Feodor2/Mypal68#245]
There isn't an option to change the search engine to google so how do i do that? i don't like duckduckgo or bing that much i prefer google.

**Comment by NS-Clone** [comment]
кстате до
отсутстввие гугла по дефолту
ну уж очень бесит в новых ХРю браузерах

**Comment by NS-Clone** [comment]
> There isn't an option to change the search engine to google so how do i do that? i don't like duckduckgo or bing that much i prefer google.

try this file 
[google.zip](https://github.com/Feodor2/Mypal68/files/12337889/google.zip)
(maybe it doesn't works in quantum firefox
and you need to find this page in google yourself)

**Comment by NS-Clone** [comment]
maybe this
https://www.google.com/homepage/search/sp-ie10.html

**Comment by bushy555** [comment]
...it is a shame that it isn't just an about:config setting so that the user can simply set it to what they want.

Some of us just want to be able to actually find stuff and don't care about google sharing/sending info.
Duckduckgo has a long way to become a decent search engine. Its actually quite garbage & jun when compared to Googles ~24 years of indexing.

**Comment by NS-Clone** [comment]
> А как в 360 с гугелом, короче хотите гугела берите хромой, вам этот браузер не нужен, тем более когда гугел будет выдовать разришение на доступ в тирнет

все это очень интересно
но голый браузер апсолютно беспомощный пока не поставишь г00голь

и часто это ловит в полевых условиях
распаковал у г00гля нет
и начинаеь трaxатcо с утауткой
искать как добыть г00голь в домашних условиях...

**Comment by Feodor2** [comment]
попробуй mojeek, я утку думаю заменть на него.

**Comment by NS-Clone** [comment]
> попробуй mojeek, я утку думаю заменть на него.

попробовал
![2023-08-22_204018](https://github.com/Feodor2/Mypal68/assets/139008911/88c31f72-b5d5-45dd-89e3-465cf86b481f)

да и англоsuхх-ы прибанят незaлeжану токо так
черер пару лет

**Comment by Feodor2** [comment]
search.brave.com

**Comment by NS-Clone** [comment]
о 
он выдал ожидаемый резльтат
![2023-08-25_022952](https://github.com/Feodor2/Mypal68/assets/139008911/d386bda2-4b53-4ce7-b8c3-33b3793fc2ec)

ни уткаутка ни гугол ни бинг никого ненаашли
(хотя гугол ранньше находил эту статью по названию)
нашел ВНЕЗАПНО яндыкс

**Comment by unattendedplayer** [comment]
mycroftproject.com
Go to Google
Be sure it's G or G (US)
A green button will appear on the search logo
Click on it and select Add G

**Comment by NS-Clone** [comment]
можот можно добавить гугол при помощи манипуляций с файлами?
чтоб самому вытянуть из оригинального фаирфокса

**Comment by Feodor2** [comment]
Писали же тут даже вроде, через другой сайт minecraft вроде выбираеш там гугел клацаеши + поеске появяеться - алюсуеш и есть утебя этот сраный гугел.

**Comment by NS-Clone** [comment]
> Писали же тут даже вроде, через другой сайт minecraft вроде выбираеш там гугел клацаеши + поеске появяеться - алюсуеш и есть утебя этот сраный гугел.

ну тоесть добавлять гугол по дефолту не безопасно для ваших банковских щетов
а посылать на какой то левый сайт значит безопасно

да у меня он где то тоже должен быть
но проблема что там этих гуглов 100500 штук о_О
и хз кого из них надо

**Comment by egrabrych** [comment]
I suggest using this:
[https://addons.thunderbird.net/en-us/firefox/addon/google-default-1/?src=userprofile](url)

**Comment by zanud** [comment]
> можот можно добавить гугол при помощи манипуляций с файлами?
> чтоб самому вытянуть из оригинального фаирфокса

В профиле лежит файл `search.json.mozlz4`. В нём находятся все установленные поисковые плагины.
Можно:
а) Взять этот файл из FF. Удастся такой фокус или нет - не знаю, там в файле хранится версия (точнее, `buildID`) программы, которая этот файл создала.
б) Распаковать файл, отредактировать полученный JSON и упаковать его назад.

> ну тоесть добавлять гугол по дефолту не безопасно для ваших банковских щетов

"Поисковый плагин" это просто текстовый файл, содержащий URL поисковика, на который браузер отправляет введённый пользователем в поисковую строку текст. Единственная переменная часть в этом URL-е - сама эта строка.
Поэтому с помощью поискового плагина в принципе невозможно отправить на внешний сайт ничего, кроме введённого в поисковую строку текста.

И да, вводить пароли от _банковских щетов_ в адресную или поисковую строку не стоит в любом случае ;-)

> а посылать на какой то левый сайт значит безопасно

Способ **б)** я применял очень много раз, чтобы добавить сайты, готовые плагины для которых взять просто негде (и потом уже, после отладки, на Mycroft Project некоторые из них выкладывал).

А потом я с этими распаковками/упаковками задолбался и на своём сайте сделал отдельную страничку специально для установки нужных мне моих самодельных плагинов в любой браузер. Google среди них тоже есть.
Если левизна этого источника не смущает, могу дать URL.

**Comment by NS-Clone** [comment]
> Поэтому с помощью поискового плагина в принципе невозможно отправить на внешний сайт ничего, кроме введённого в поисковую строку текста.

тогда непонятна от куда такое не желание запихнуть гугул в искаропку

**Comment by zanud** [comment]
Вероятно, от общей нелюбви к Гуглу - из-за его тотального шпионажа за действиями пользователей.
Плагин хоть сам по себе ничего плохого и не делает, но ведь результаты поиска всё равно будут показаны на гугловской страничке, а это равносильно тому, что самому зайти на Гугл и запустить поиск оттуда - со всеми вытекающими последствиями.
