### ISSUE TITLE
Discord calls aren't working

### ISSUE THREAD

**Issue by selvagoat** [Feodor2/Mypal68#246]
When i always click the discord call button it never works?

**Comment by bluedragon-cairo** [comment]
in about:config, set:

- media.peerconnection.enabled;true
- general.useragent.override.discord.com;Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20170101 Firefox/112.0

**Comment by Legendary-Candice-Joe** [comment]
Even you get into a call, chances are the mic won't work. Discord complains that it does not have permission but mypal says that it is getting mic input.

**Comment by bluedragon-cairo** [comment]
it's mypal68 issue

try using Centaury 0.15.0 with [this](https://github.com/Feodor2/Mypal/issues/114) patch

**Comment by unattendedplayer** [comment]
Use Kafan minibrowser. It's based on chrome 87

**Comment by bluedragon-cairo** [comment]
that's chinese & there's china's stupid telemetry (forced by their law as far as i know)

**Comment by unattendedplayer** [comment]
NSA vs CCP, I don't care. The OP is on Win7 so I recommend Firefox v78 or Chromium 88 (proven to work on 1 GB of RAM), and should still be functional.
