### ISSUE TITLE
what the hell is this

### ISSUE THREAD

**Issue by selvagoat** [Feodor2/Mypal68#247]
what is this???? 
![image](https://github.com/Feodor2/Mypal68/assets/71284338/782dbc6e-c3c2-4bb2-88cf-3769089c6115)

**Comment by bluedragon-cairo** [comment]
kinda memory leak? happened to me too before when opening too many tabs for a super long time. Restarting Mypal fixed it for me

**Comment by Selva124** [comment]
> kinda memory leak? happened to me too before when opening too many tabs for a super long time. Restarting Mypal fixed it for me

this is so annoying tho it started to happen to me lately these days i don't like restarting mypal everytime this happens.

**Comment by NS-Clone** [comment]
никогда не наблюдал таких глюков ни на одном фаирфоксе

**Comment by NS-Clone** [comment]
лол
ну вот только что получил похожие визуальные глюки в дискорде
из "внешних" факторов 450 вкладок

**Comment by NS-Clone** [comment]
вместе с визуально похожими глюками словил
![Копия 2023-08-26_074951](https://github.com/Feodor2/Mypal68/assets/139008911/eeae453e-33d3-467e-a92b-eb3c5d12944a)

при этом еще элементы от одних табов некоторое время висят в других

но опять же это 500 вкладок и пол дня работы
при том многократно память кончалась

**Comment by Feodor2** [comment]
![image](https://github.com/Feodor2/Mypal68/assets/19492771/4d1d96ac-599d-4459-8dc5-6d82ed939947)
О ты пользуеш этой штукой, а я думал это хлам и собирался удалять.

А ты на х64 системе толи сидиш, бо на обычной хр 100 вкладок и памяти нема.

Потом ещё картинки это неудобство, лучше давай текст доктора воцона или хоятбы событий.

**Comment by NS-Clone** [comment]
> А ты на х64 системе толи сидиш, бо на обычной хр 100 вкладок и памяти нема.
на 32 бит
...ну это не совсем 500 вкладок
500 с предыдущей сессии
и они не прогружены все (хотя тоже жрут дохрена памяти и тормозят браузер)
подгруженных порядка 100 обышно наверно (я столько за один присест легко открываю с 0)

**Comment by NS-Clone** [comment]
> лучше давай текст доктора воцона

он логитсо только если нажать отмена при ошибке?

**Comment by NS-Clone** [comment]
> лучше давай текст доктора воцона

он логитсо только если нажать отмена при ошибке?
