### ISSUE TITLE
Mypal не перезапускает загрузку файлов с последовательным доступом

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#248]
собственно сабж
обрываетсо загрузка какого нибудь master.zip-а на гитх00бе
а retry загрузку с начала не перезапускает
...
хотя нет если 4 раза подряд ткнуть в retry
загрузка начинаетсо
и лол гитх00б стал отдавать один "непродолжаемый" файл вообще с известным размером о_О
![2023-08-18_182937_](https://github.com/Feodor2/Mypal68/assets/139008911/a8dc3b8c-6c23-436d-ab21-2082a42b1ff0)
...
и вот оно оборвало
и этот же файл снова без размера
![2023-08-18_184347_](https://github.com/Feodor2/Mypal68/assets/139008911/ded82eeb-5127-47b5-96ff-a6a290fb578f)
и опять ппришлось 5 раз жать retry

а теперь оборванную загрузку оно приняло за целый файл
и retry вообще нету...

**Comment by NS-Clone** [comment]
хотя может это на стороне гитх00ба?
и я спотыкаюсь об оно только на нем?
щас спенка так же перезапустил загрузку с него в DTA в серпенте
хотя яж им обычно сорцы и качаю
пушо такой проблемы на нем никогда не видел

**Comment by Feodor2** [comment]
Да он такой, ниезвестный размер вроде во всех браузерах

**Comment by NS-Clone** [comment]
> Да он такой, ниезвестный размер вроде во всех браузерах

ну проблема в не неизввесстном размере
а в неперезапускаеммости загрузки

вот проверил серпент молча паузит и молча перезапускает

НО из наблюдений mypal не перезаапускает когда в загрузках остаетсо part файл

НО за удаление part файлов нужно вообще удалять ноги...
а оно по дефолту...

**Comment by Feodor2** [comment]
Чото я не понял чего тебе надо
На жыдохабе не перезапускаются безразмерные загрузки одинаково как на серпе так и майпале

**Comment by NS-Clone** [comment]
на сепре как перезагружаютсо (ну в смысле с 0) проверено пару дней назад
а в майпале же нужно раз 5 нажать retry (чтоб опять начаать качать с 0)

**Comment by Feodor2** [comment]
Так качать можно же без учётки, и просто из комстроки гитом.

**Comment by NS-Clone** [comment]
> Так качать можно же без учётки, и просто из комстроки гитом.

а останутсо непподтвержденые аки спустя 2 месяца вообще?
или уйдут в 404?
