### ISSUE TITLE
whenever i enter facebook mypal crashes immediately

### ISSUE THREAD

**Issue by selvagoat** [Feodor2/Mypal68#249]
why does this happen??? it's so annoying

**Comment by IP-CAM** [comment]
If you're on Win XP, one of the Browsers, shown on the Page linked below, could be a valid alternative for you:
https://github.com/roytam1?tab=repositories

**Comment by Selva124** [comment]
no i'm not on xp

**Comment by MWF2** [comment]
what's your os that you using it?

**Comment by Selva124** [comment]
win7

**Comment by Feodor2** [comment]
give a link to crash

**Comment by Selva124** [comment]
> give a link to crash

it's literally crashing on facebook.com after you log in of course

**Comment by Selva124** [comment]
> Sorry i do not have an account. Let another facebook user check if it crash upon login.

just create an account bro

**Comment by Feodor2** [comment]
Tis is such a big evil so never brow, soorry

**Comment by unattendedplayer** [comment]
If you're using Windows 7 you can use Firefox 78, 82 etc. They should work well. You shouldn't use those browsers (Mypal, New Moon etc.) unless your OS is XP or Vista.

**Comment by Selva124** [comment]
> If you're using Windows 7 you can use Firefox 78, 82 etc. They should work well. You shouldn't use those browsers (Mypal, New Moon etc.) unless your OS is XP or Vista.

well i cannot do that because i have a problem with my ram that shows error 0xc0000005 with every modern app that i use and it's so expensive to buy a ram here so maybe i'll buy it after 2 months or 1 month till now i'll stick with mypal.

**Comment by aberyst** [comment]
I'm using Windows Vista and downloaded the new Mypal 68.13.1 browser. Works great on all websites except Facebook. Crashes instantly on logging in. Tab crash and windows cannot find a solution.

**Comment by jonm58** [comment]
> > If you're using Windows 7 you can use Firefox 78, 82 etc. They should work well. You shouldn't use those browsers (Mypal, New Moon etc.) unless your OS is XP or Vista.
> 
> well i cannot do that because i have a problem with my ram that shows error 0xc0000005 with every modern app that i use and it's so expensive to buy a ram here so maybe i'll buy it after 2 个月之前 or 1 个月之前 till now i'll stick with mypal.

plz buy ram,ram is cheap,i use KINGBANK ram
