### ISSUE TITLE
Mypal68 install version please

### ISSUE THREAD

**Issue by expee4me** [Feodor2/Mypal68#25]
Hello, I'm new here and not technical - please be gentle.
As a long term Mypal user, I've been waiting and hoping for this. Have downloaded Mypal68 and running it portable a few days and it's great. However I am used to installed version, is there an installed version download please? Thank you.

**Comment by win98se** [comment]
Someone else made an installer [here](https://github.com/Feodor2/Mypal68/issues/2#issuecomment-1092871255), not sure if [this fix](https://github.com/Feodor2/Mypal68/issues/2#issuecomment-1091077575) is included, also use it at your own risk.

**Comment by expee4me** [comment]
Thank you. I did find that ISO but couldn't understand how to get it to work for me. I'm used to a simple installer link.

**Comment by gdl-888** [comment]
Isn't the ISO a virus?
Anyways, I think the browser is still unstable and not for everyone's use so there is no installer yet.

**Comment by expee4me** [comment]
Thanks for your reply. The ISO scanned clear but made no sense to me. Stable or not, I'm so impressed by using the current portable version that I'm happy to await an installer. I'm just so grateful that work is carrying on with Mypal.

**Comment by NEO-SPECTRUMAN** [comment]
а я бы на оборот попросил бы не равзодить нуубарские exe-шники
которые сстаавят неизвестно что неизвестно зачемм и неизвестно куда
и которые лишний раз скаанируютсо антивируской :)

**Comment by win98se** [comment]
> I did find that ISO but couldn't understand how to get it to work for me.

It shouldn't be an ISO......
Another link to the same installer [here](https://send.vis.ee/download/a1980953fd6582d7/#ynbvU8V4CBOVf5-qvgNRYw). This link expires after 20 downloads or 7 days, whichever reaches first.

**Comment by ScratchApps** [comment]
> Hello, I'm new here and not technical - please be gentle. As a long term Mypal user, I've been waiting and hoping for this. Have downloaded Mypal68 and running it portable a few days and it's great. However I am used to installed version, is there an installed version download please? Thank you.

There is an installer version with language packs https://github.com/Feodor2/Mypal68/issues/28#issue-1202383563

**Comment by Feodor2** [comment]
I do not plan do installer version until definitive choice the versioned to develop as for langpacks too. I see someone else has made the installer, use it then, but i shall not be responsible of it anyway.

**Comment by expee4me** [comment]
Thank you @Feodor2 I will be patient and like all the silent XP and Mypal users, most grateful for the work on the new Mypal.

**Comment by loris783** [comment]
After you have installed language pack 
enter to about:config in adress bar
create new string intl.locale.requested and set to it,it for italian (example)

**Comment by guilt** [comment]
Hi @Feodor2 what needs to be done for an installer? Adding different versions for different langpacks? Let me know. If there's any scripts from Mozilla/Seamonkey I can investigate how to  build it. Can also help add this to Github CI/CD

**Comment by NS-Clone** [comment]
инсталлеры НЕНУЖНЫ!

**Comment by guilt** [comment]
On this page I noticed someone was making Installers available:

https://github.com/ScratchApps/Mypal68Installer

I definitely think that we should start making it available on the Web site and on GH, it needn't be perfect to begin with. But an installer can take care of making old systems usable quite easily.
