### ISSUE TITLE
Wrong time reported by browser to website

### ISSUE THREAD

**Issue by krzysiobal** [Feodor2/Mypal68#251]
Why this (and few more) websites:
https://webbrowsertools.com/timezone/

shows wrong time? it says

Time on Local Machine	Sun Aug 20 2023 13:55:10 GMT+0100 (GMT+01:00)

while my computer shows 14:55 (I am in UTC+2, during summer time, automatic summer time adjustment is enabled in the windows clock settings).

privacy.resistFingerprinting is set to "false" in about:config

Though for some weird reason, windows XP assings GMT+1 to my city

Above website when viewed on mypal 28.17b says 
Time on Local Machine	Sun Aug 20 2023 14:55:35 GMT+0200

which is correct.

**Comment by Feodor2** [comment]
Did you update to the latest mypal if not then update, but if this on the latest let to look further, what zone exactly you set?

**Comment by krzysiobal** [comment]
This is int 68.13.0b (32-bit)
![winzone](https://github.com/Feodor2/Mypal68/assets/7058666/2fe0da81-5d71-4ec2-a14a-1ccee4882359)

**Comment by Feodor2** [comment]
68.13.0 is not the latest, so update, you may take 68.13.2 here on the github

**Comment by krzysiobal** [comment]
Looks like this has been fixed in 68.13.2, you are genius!

By the way, when I wanted to post this topic today, I mistakenly choose "Sign up" on the github.com, instead of "Sign in" and the animation that is shown here kills the browser - the stars are moving abound 2 frames per second with 100% cpu usage.

![gh](https://github.com/Feodor2/Mypal68/assets/7058666/c5c57f1b-3ba4-4861-b177-84ce98f2aab6)
