### ISSUE TITLE
Downloading MYPAL68 from old browsers

### ISSUE THREAD

**Issue by ghost** [Feodor2/Mypal68#255]
As you know, the files in Releases doesn't appear in old browsers. This will make much harder to download Mypal as you need to have a supported browser such as Kafan Minibrowser or 360Chrome. My suggestion:
Direct link to the files in every release description.
Users should be able to download it easier then.
In Vanilla XP with internet connection you can only visit some HTTP sites and one being Mozilla File repository. There you can download the last working Firefox for XP (52.9.0 ESR), but you cannot download Mypal from GitHub because they use some POS script to make the downloads impossible on older browsers. So you must get a better browser such as something Chromium 87 in order to download this browser.

**Comment by NS-Clone** [comment]
> As you know, the files in Releases doesn't appear in old browsers.

that's why you MUST everytime download "new" browsers for XP

also you can download from github using serpent + **** github polyfill
but you need previously  (2 years ago ) download **** github polyfill from github
or maybe new serpent can download frrom github?

**Comment by Feodor2** [comment]
mypal-browser.org is non https, may download with anything.

**Comment by MWF2** [comment]
as for internet explorer like old version, it no longer works
![image](https://github.com/Feodor2/Mypal68/assets/74994144/dfe74e92-7432-49c1-b02d-cd0e5a685730)

**Comment by MWF2** [comment]
update: so only url works, but not on google when it search
![image](https://github.com/Feodor2/Mypal68/assets/74994144/e4931367-0e75-4f76-ae56-822f9df08a8b)

**Comment by MWF2** [comment]
if you go to that site with google search, it will appear issue, but when if go to url, it will work
![image](https://github.com/Feodor2/Mypal68/assets/74994144/79a7bfb7-4d92-4dc6-8453-b453c6f90900)
