### ISSUE TITLE
discord streams aren't loading at all

### ISSUE THREAD

**Issue by selvagoat** [Feodor2/Mypal68#257]
![image](https://github.com/Feodor2/Mypal68/assets/71284338/64af2c27-8ac2-4608-a523-65ea305bcb3f)

**Comment by bluedragon-cairo** [comment]
for me there was something very interesting happened. If I try to watch the stream on XP, it just loads infinitly, but when I watch the stream on a Windows 7 machine next to my XP machine connected to the same network, the stream shows up in the XP machine. If I stop watching or leave the call in my Windows 7 machine, the stream freezes in the XP machine...

**Comment by Selva124** [comment]
> for me there was something very interesting happened. If I try to watch the stream on XP, it just loads infinitly, but when I watch the stream on a Windows 7 machine (using a different account) next to my XP machine connected to the same network, the stream shows up in the XP machine. If I stop watching or leave the call in my Windows 7 machine, the stream freezes in the XP machine...

is there something i could do to watch streams like maybe modifying something in about:config or idk?

**Comment by bluedragon-cairo** [comment]
not sure
