### ISSUE TITLE
How to update to new version 68.13.2b from 68.13.1b?

### ISSUE THREAD

**Issue by fastnetcom** [Feodor2/Mypal68#258]
The simple copy files does not work and there are differences in folders

**Comment by visionhelp** [comment]
Sorry, deleting the old content deletes settings, bookmarks ? 
But why does overwrite not work. What happens ?

**Comment by bluedragon-cairo** [comment]
just delete previous files & overwrite mypal program files 

if the settings are gone then go to about:profiles and select the old profile and click [set as default] & [launch in new browser]

**Comment by visionhelp** [comment]
Sorry, bluedragon-cairo, my mistake. Was trying to figure out why copy not works for fastnetcom. 

By the way: settings to find still in about:profiles, not saved in the program-folder ´mypal´ ? Thank You.

**Comment by visionhelp** [comment]
The bookmarks should also ? (Sorry. Cannot edit here, does not work for me.)

**Comment by fastnetcom** [comment]
I made new copy of old files directory and overwrite all new mypal files and it does not work for me.
Maybe I need to do it by other way.

**Comment by fastnetcom** [comment]
The copy of the old mypal folder to other place (as backup) does not work after creating new profile. Is it possible at all?

**Comment by visionhelp** [comment]
The copy I do not mean for to use mypal to work. 
Only for backup, if something goes wrong with the new version, in the old folder. 
The extracted mypal folder I understand as portable version. 
Where You start the mypal.exe (in the folder) from, this - I understand - creates new profile TO this folder place.

**Comment by unattendedplayer** [comment]
Go to about:profiles in 68.13.2 and select the other profile as default.

**Comment by visionhelp** [comment]
In Documents and Settings ->Your User´s NAME Account ->Appdata -> Mypal 
Correct ?

**Comment by unattendedplayer** [comment]
In 7, %appdata% leads to Users\Username\AppData\Roaming
In XP, should be Documents and Settings\Username\Application Data\Roaming.

**Comment by visionhelp** [comment]
Ah, You run Mypal for XP on 7 

No, (XP) "Documents and Settings ->Your User´s NAME Account ->Appdata -> Mypal": 
do/did not know in english. What I wrote here ´Appdata´ will be ´Application Data´. Then further there ´Mypal´ -> Profiles.

Ah, wouh, but if You work on 7 ...

**Comment by Zoyandium** [comment]
I don't understand this thread, but I would like advice about how, in general, Mypal68 should be updated.  I downloaded and opened a zip file for version 68.13.2b and copied everything in the Mypal folder to the C:\Program Files\Mypal68 folder of version 68.13b, over-writing it's contents, and everything seems to work OK.
