### ISSUE TITLE
Multipe processes run in the Task Manager: is it really necessary ??

### ISSUE THREAD

**Issue by PLudkovski** [Feodor2/Mypal68#26]
Multipe processes run in the Task Manager: is it really necessary ??

**Comment by pachuco** [comment]
Yes, new firefox is like chrome, multiprocess, but no, that can be changed.
Check **browser.tabs.remote.autostart** and **dom.ipc.processCount** options in about:config.

**Comment by archipelagu** [comment]
Well, if you like stuttering and scrolling freezes when loading heavy pages, you can disable multiprocessing.
