### ISSUE TITLE
"Reduzierte WEB.DE Homepage" = Reduced ... Homepage

### ISSUE THREAD

**Issue by visionhelp** [Feodor2/Mypal68#260]
Reduzierte WEB.DE Homepage. Aufgrund eines alten Browsers oder ungewöhnlicher Browser-Einstellungen sehen Sie eine verkürzte WEB.DE Homepage. Wir empfehlen die Verwendung eines aktuellen Browsers. 

Google translate: "Reduced WEB.DE homepage. Due to an old browser or unusual browser settings, you see a shortened WEB.DE homepage. We recommend using a current browser."  

(web.de is a german big email-provider.) 

(Oh, now, the 68.13.1b, lets me edit here on github again. Great.)

woops, after logging in it works complete. So now still just confusing the first message "due to an old browser".

**Comment by unattendedplayer** [comment]
Go to about:config
add general.useragent.override.web.de (String)
paste some current browser user agent
Click OK and reload the website

**Comment by visionhelp** [comment]
Hm. That´s the only thing that works, so far: 
![image](https://github.com/Feodor2/Mypal68/assets/14303567/0ec1e99c-1b4f-41b1-964f-6f9b06d02377)

Is this saved in ´appdata´, not in ´Programs -> Mypal´, please, for update of Mypal does not change this ? Thanks.

**Comment by unattendedplayer** [comment]
You must add it by right clicking to empty space and select "New > String".

**Comment by visionhelp** [comment]
Thanks a lot. This way ? 
![image](https://github.com/Feodor2/Mypal68/assets/14303567/417f3051-bab2-464b-9dfc-04d34fefc7b2)

**Comment by zanud** [comment]
> Thanks a lot. This way ?

Almost. The value of your string should be not **true** but something that looks like a real useragent string of any modern browser.

**Comment by visionhelp** [comment]
OK. Thank You. 
On XP I only have New Moon, Pale Moon, Mypal. 
A pic from Pale Moon here. Here I am not familiar with, need step by step, please. Thanks. 
![image](https://github.com/Feodor2/Mypal68/assets/14303567/0e608852-9e87-4142-9927-9cf1748e79f3)

**Comment by zanud** [comment]
[There](https://www.useragentstring.com/pages/useragentstring.php) is a collection of useragent strings of everithing (and [different versions of Firefox](https://www.useragentstring.com/pages/Firefox/) in particular).

But take into account that reaction of site may be different for different version of user agent, so sometimes it is better to use some older fake string then the newest one.

**Comment by visionhelp** [comment]
It is only Pale Moon there, not New Moon, not Mypal in this list. 
And Pale Moon only a very old version for Windows NT 5.1 (XP). 
With ´palemoon-28.10.6a1 -xpmod´ I get a reduced functions site. 
This I even prefer instead of the very slow very full blowed 
up´professionell´ Web-Site. 
And this whole trouble just comes from OE6 now is missing the TLS 1.1 or/and TLS 1.2. 
Which as topic is closed now here. 
But so far the discussion is goint to far for here, as is said. OK. 
Thank You.

**Comment by visionhelp** [comment]
THis was once ma question here: what does web_de (a site so) recognize this (an) old browser at all. 
Thank You very much, this is the answer, they do not know its name. 

The now copied string from Pale Moon has at the end (Pale Moon) I did see. My idea already was to change to (Mypal), then after now first test this with (Pale Moon). 
Your explaining does confirm this now to me. Very well. 
Let´s see. I´ll report.

**Comment by visionhelp** [comment]
OK. Doesn´t work this way. 
What is wrong with this string ? 
general.useragent.override.web.de (von Pale Moon);general.useragent.override.web.de;Mozilla/5.0 (%OS_SLICE% rv:68.9) Gecko/20100101 Firefox/68.9 (Mypal)

**Comment by zanud** [comment]
> THis was once my question here: what does web_de (a site so) recognize this (an) old browser at all.

`useragent` string consists of a number of tokens (separated by spaces) that allow to identify the browser (its version, HTML engine, features). There is no strict standard for this string, and it is vendor-specific, but there are some descriptions: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox , https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/ms537503%28v=vs.85%29

How Web server analyzes and interprets string that browser send to it as a part of a HTTP request, depends solely on this Web site programmers.

> What is wrong with this string ?

Can not tell anything about Pale Moon, but `(Mypal)` token looks suspiciously for me because of its format - it should be similar to `Firefox` and `Gecko` format (without parentheses, but with a slash). Also it is not necessary here at all.

On my MyPal I tried `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0`, and WEB.DE showed its front page without warnings about reduced page version and old browser.

**Comment by visionhelp** [comment]
"depends solely on this Web site programmers"; and what is getting as answer, and what is being wanted to be done with it. Thank You. 

Thanks Your string. 
But You use ´my´ ´mypal 68.13.1b en´ version the 64-Bit version, at least. You run on Windows 10. And with a lot more newer Firefox version. I may see from this string. 
Currently I just stop to try this for XP with Firefox 52.0.1 (32-Bit) Mozilla Firefox EME-free - 1.0. Sorry.

**Comment by zanud** [comment]
> But You use ´my´ ´mypal 68.13.1b en´ version the 64-Bit version, at least. You run on Windows 10. And with a lot more newer Firefox version.

No-no-no. I use MyPal 68.13.2b on 32-bit Windows XP. (What it the point to use it on newer Windows versions?)
And I do not have Firefox at all.

Windows 10, 64 bit, Firefox 99 - this is a content of `useragent` string that I "borrowed" from www.useragentstring.com and used for `general.useragent.override.web.de` in the MyPal settings - just to check will WEB.DE be normally working with it or not.

**Comment by visionhelp** [comment]
Ah. OK. Sorry, my misunderstanding. 

Firefox, the last version for XP, I do not use, I do understand it as precondition with for Mypal, may be not understanding correctly. 

"and WEB.DE showed its front page without warnings about reduced page version and old browser": 
OK. Did not realize this statement, sorry. 
Sounds only good. 
Next try, today. Thank You.

**Comment by visionhelp** [comment]
It does not work for me. 
![image](https://github.com/Feodor2/Mypal68/assets/14303567/7f5e4295-f27a-43ae-8eba-6448a90d502f)

**Comment by zanud** [comment]
Unusual case. I decided to show you a screenshot, opened WEB.DE and sow _"Achtung: Ihr Browser ist varaltet!"_
But yesterday everything was OK!
So I decided to start from the very beginning. I deleted all tracks of the WEB.DE by selecting "Forget about this site" in the browser's history. Then I opened WEB.DE:
![native](https://github.com/Feodor2/Mypal68/assets/76625744/94ac8c23-f8c9-4d27-b797-098b88511dd2)
Then I added `"general.useragent.override.web.de;Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"`, cleared history and opened the site:
![FakeAgent](https://github.com/Feodor2/Mypal68/assets/76625744/45b29866-8572-4da5-8a53-d8f33c92fb1a)
And then I disabled **uBlock Origin** for this site, reloaded the page (F5), and voilà:
![FakeAgent-uBO](https://github.com/Feodor2/Mypal68/assets/76625744/1670a1da-f273-43d7-94ad-41406188f8c9)

It is interesting that re-enabling **uBlock Origin** after that  changes the page look - makes it similar to step 2 but without _"Achtung: Ihr Browser ist varaltet!"_ at the top.

**Comment by visionhelp** [comment]
I do not use: uBlock Origin. 
But some weired things are happening at web.de there. 
The first call the site shows this: 
![image](https://github.com/Feodor2/Mypal68/assets/14303567/a9994c4f-e7b3-4fbf-a8e0-8c077afb83e1)
After second call, this (and log-in works): 
![image](https://github.com/Feodor2/Mypal68/assets/14303567/e57d5674-9218-45f4-8b0f-103a01719d73)

As next I want to try to remove the new done key ´general.useragent´ again as try, whether it still works the same.

**Comment by visionhelp** [comment]
OK. The message appears again: 
![image](https://github.com/Feodor2/Mypal68/assets/14303567/90fcd2c6-385a-4291-8250-1676334d3d80)
But: despite the message ´reducedß´ the full functional site happens. 
But the message at all prevent, not to have, the key creat again. This helps it. 
Thank You very much this very helpful contact, this exchange. 
All the best.
