### ISSUE TITLE
infinite site loading with dns over https enabled

### ISSUE THREAD

**Issue by ChuckBartowski91** [Feodor2/Mypal68#261]
Hello. No matter using cloudflare or a custom one, most of the times (maybe sites still not visited) it doesn't load a web page and gets stuck at transfering data from it. Disabling dns over https and reloading the site loads it no problem.

**Comment by Feodor2** [comment]
This feature is ambiguous i may be consider to remove it at all, or remove form the gui at least. What do you all think?

Cauldronfire is a cancer, so link has been removed long ago, but name was left -  the bug indeed.
Now i replace it.

Also please look this
https://www.isc.org/blogs/doh-encrypted-dns/

**Comment by ChuckBartowski91** [comment]
> This feature is ambiguous i may be consider to remove it at all, or remove form the gui at least. What do you all think?
> 
> Cauldronfire is a cancer, so link has been removed long ago, but name was left - the bug indeed. Now i replace it.
> 
> Also please look this https://www.isc.org/blogs/doh-encrypted-dns/

Since I would like to use it with a custom dns my humble opinion is to try to make it work, isn't better for privacy since we are (at least me) on Windows XP, Vista...? but all depends on you and what all the people think about it.

**Comment by jonm58** [comment]
> > 这个功能是不明确的，我可能会考虑完全删除它，或者至少从 GUI 中删除。  大家觉得怎么样？ 
> > Cauldronfire 是一种癌症，所以链接很久以前就被删除了，但名字被留下了——确实是这个错误。  现在我更换它。 
> > 另请查看此 [https://www.isc.org/blogs/doh-encrypted-dns/ ](https://www.isc.org/blogs/doh-encrypted-dns/)
> 
> 因为我想将它与自定义 dns 一起使用，所以我的拙见是尝试使其正常工作，因为我们（至少是我）使用的是 Windows XP、Vista...，这对于隐私来说不是更好吗？ 但这一切都取决于你和所有人的想法。

https://odoh.cloudflare-dns.com/dns-query

**Comment by Feodor2** [comment]
The bug was about cauldron remnants only, the feature itself works good with custom too,  i checked https://doh.opendns.com/dns-query
