### ISSUE TITLE
Spotify website doesn't work

### ISSUE THREAD

**Issue by Midnight-Rambler-72** [Feodor2/Mypal68#262]
Hi, when I'm trying to log in to the spotify website,
![spotify issue](https://github.com/Feodor2/Mypal68/assets/143538293/102fdb58-68ca-426b-b151-0d5f6ac95a6c)
 I get this message:

**Comment by Feodor2** [comment]
Did you learn? if eme then forget about it #43

**Comment by Midnight-Rambler-72** [comment]
Thanks for the info
