### ISSUE TITLE
codeberg.org - mypal CRASH

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#264]
при попытки миграции с гитхаба
на разных этапах валисто с одним и тем же переполнением стека?
![Копия 2023-09-01_023203](https://github.com/Feodor2/Mypal68/assets/139008911/1a70ba21-0fcc-4caa-a13f-26011d2141d5)

свалилсо 4 раза подряд
то на кликание по самому первому migrate
то 2 раза по кликанию по второму migrate (с вводом адреса)
то на ожидании/процессе миграции

копипасто приигодный вариант
Всплывающее окно приложения: Other Filters: mypal.exe - Ошибка приложения : Исключение unknown software exception (0xc00000fd) в приложении по адресу 0x10009e9b.
Всплывающее окно приложения: mypal.exe - Ошибка приложения : Исключение unknown software exception (0xc00000fd) в приложении по адресу 0x10009e9b.
Всплывающее окно приложения: Feodor2/Mypal68: web browser: mypal.exe - Ошибка приложения : Исключение unknown software exception (0xc00000fd) в приложении по адресу 0x10009e9b.

дрвацон ниче не логает при этом
хотя я его даже в исключение антивируски добавил

**Comment by NS-Clone** [comment]
ну вот а сегодня смигратил жменю реп
и ниче не падало...

**Comment by NS-Clone** [comment]
а щас вывалилсо с той же ошибкой
при переходе с вкладки профиля
https://codeberg.org/NEO_SPECTRUMAN
на другую уже открытую вкладку

**Comment by NS-Clone** [comment]
быстренько проверил на "чистом" браузере
повторить не получилось
на "не чистом" падает каждые 10 кликов
на всякий сверил целостность бинарников winmerge-м
все соответствует 68.13.2 релизу

**Comment by Feodor2** [comment]
И уменя нет ошибки, но 560 вклдок никогда я не открывал.

**Comment by NS-Clone** [comment]
> И уменя нет ошибки, но 560 вклдок никогда я не открывал.

может это только для авторизированных?
ато я пробовал чистый браузер но без авторизации

**Comment by NS-Clone** [comment]
mypal.exe -safe-mode тут тоже не помогает

**Comment by NS-Clone** [comment]
> но 560 вклдок никогда я не открывал.

кстате от антинаучное иследование
щас 760 вкладок

старт браузера

![Копия 2023-09-24_050436_](https://github.com/Feodor2/Mypal68/assets/139008911/f1e3fe95-4a7b-4f26-858b-10255bb61bb7)
1-я "пирамида" это без мультипроцесса
2-я с мультипроцессом
на время не обращаем внимание
это я видимо наклацал скорость обновлления в процессе...

казалось бы чего там тупо загрузить список вкладок из пред сессии
но нет
```
рама без мультипроцессса
2130
3330 - 1200 метров майпал (пиковое)
2640 - 510 метров майпал (потом спадает)
```
```
рама с мультипроцессом
2130
3240 -1110 метров майпал (пиковое)
2760 - 630 метров майпал (потом спадает)
```

тобешь куда то в пустоту при старте улетел гиг
а потом от куда то освободилось 600 метров

и это же ХРю а не графике
она непоказывает выгрузку в своп 
как делает это вин15 чтобы лучше продаватсо

**Comment by NS-Clone** [comment]
еще в скриншотах нашел то же исключение
но по другому адресу
![2023-09-06_040706_](https://github.com/Feodor2/Mypal68/assets/139008911/80cef73d-b5d4-4baa-b066-7b238a628bd1)

**Comment by NS-Clone** [comment]
С browser.tabs.remote.autostart;TRUE
ни то не другое уже неделю не попадаетсо
хотя щас я туда особо и не захожу
