### ISSUE TITLE
Youtube does not fully load

### ISSUE THREAD

**Issue by Zoyandium** [Feodor2/Mypal68#266]
Using version 68.13.2b I found that Youtube does not fully load a few days ago.  The homepage stops loading with grey placeholders for thumbnails and text.

**Comment by MWF2** [comment]
if you running with ublock, what version that you using to cause issue?

**Comment by MWF2** [comment]
if you running 1.50.0, then just upgrade to 1.51.0 that fix issue for me
https://github.com/gorhill/uBlock/releases/tag/1.51.0

**Comment by Zoyandium** [comment]
Upgrading uBlock Origin to version 1.51.0 fixed the problem.  Thanks.  I would like to draw your attention to the "Check for Updates" tool in the Add-ons manager not working.  Also, if I click the highlighted "Check for Updates" in the Allow Automatic Updates section of the uBlock settings nothing happens.

**Comment by Feodor2** [comment]
Sure, this is mozilla stuff. I shall remove that "Check for Updates" tool for to not confuse.
Later when it will be stable version, i shall set autoupdates for browser, but never for other stuff.
