### ISSUE TITLE
Google Drive downloads not working at all

### ISSUE THREAD

**Issue by selvagoat** [Feodor2/Mypal68#272]
I cannot literally download anything from google drive it always does this to me:
![image](https://github.com/Feodor2/Mypal68/assets/71284338/81e06ee5-d8c7-4723-8738-43b71b7fc4a4)

**Comment by bluedragon-cairo** [comment]
It works fine for me (v68.13.2)

try changing the useragent:

general.useragent.override.drive.google.com;Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

ignore the old browser warning at the bottom

**Comment by Selva124** [comment]
where do i change the user agent?

**Comment by Feodor2** [comment]
You never give links to actual things, so nothing to do.
But about agent you open the **about:config** and make the new agent entry
![image](https://github.com/Feodor2/Mypal68/assets/19492771/6d12b54d-6e85-4ec9-99cb-b44c5a737f12)

**Comment by Selva124** [comment]
that still doesnt seem to work :/
