### ISSUE TITLE
Image saving issues

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#273]
раньше я писал 
что если нажать save image as
на некоторых сайтиках/конккретных элементах страницы 
у нас появляется "вечная" не отменяемая не удаляемая загрузка
которую "отпустит" только после перезагрузки браузера

![Ы](https://user-images.githubusercontent.com/88002487/248460604-9b3027ba-5c7c-4e80-88e6-f2de606ba9b4.png)

и что можно по людские сохранить только через
view image -> save image as

> Не воспроизводиться, я посохранял много рисунков тут с жидохаба.
Попробуй чистую утсановку.

так вот на чистом браузере оно не воспроизводитсо и у меня...
а менять профиль сильно радикально

**Comment by zanud** [comment]
> так вот на чистом браузере оно не воспроизводитсо и у меня...
> а менять профиль сильно радикально

В качестве менее радикальной меры иногда помогает открыть страничку в приватном окне.

**Comment by NS-Clone** [comment]
потыкал консоль
при сохранении ничего вроде никуда не логитсо

**Comment by zanud** [comment]
В данном случае приватное окно - не ради безопасности, а для исключения влияние cookies. Я буквально позавчера на одном сайте так нашёл причину одной внезапно возникшей просто фантастической проблемы.

**Comment by NS-Clone** [comment]
лол
надо провериить

**Comment by NS-Clone** [comment]
это надо будет скопировать браузер
и постепенно возвращать в дефолтное состояние

**Comment by NS-Clone** [comment]
mypal.exe -safe-mode тоже не помогает
так же как и всего 8 открытых вкладок

**Comment by NS-Clone** [comment]
а вощем занулить конфиг задачка не простая
массового выделения нет
автосортировка уносит нас хрен знает куда
посстранична считая количество ресетнутых от начала/конца
тоже нормально не сделатть
из 15 зануленных после пперезапуска 10 снова на своих местах как modified

**Comment by NS-Clone** [comment]
ВО снес все browser.***
и стало сохранятсо

**Comment by NS-Clone** [comment]
корень зла 
browser.tabs.remote.autostart;false
@Feodor2 проверяй теперь сохранение у себя

**Comment by zanud** [comment]
> а вощем занулить конфиг задачка не простая

Очень простая. Настройки хранятся в текстовом файле `prefs.js` в профиле. И творить с ними там можно что угодно и чем угодно. Главное - делать это при незапущенном браузере, потому что браузер читает этот файл только один раз, при старте, а при выходе перезаписывает.

**Comment by Feodor2** [comment]
Да в однопроцессе зависает.

**Comment by NS-Clone** [comment]
клацнул дефолтное
![2023-11-24_131843_](https://github.com/Feodor2/Mypal68/assets/139008911/dca6cd2b-bc2f-47db-a8ed-126e686158cd)
с памятью стало немного полегче
