### ISSUE TITLE
Посоветуйте действующий javascript PAUSE addon

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#275]
собственно сабж
иногда/часто/всягда нужно остановить всю лабуду на гофносайтах (на 1-й вкладке)
а потом включить ее обратно без перезагрузки страницы
а сделать этого как всегда нечем...

какойто адон пробовал
но он ничего не останавливал

**Comment by Feodor2** [comment]
F12 отладчик, справа пауза

**Comment by NS-Clone** [comment]
> F12 отладчик, справа пауза

ф12 разворачиваетсо секунд 5
вкладка отладчика прогружаетссо секунды за 3
потом надо выцеливатьь кнопочку паузы
это сильно долго чтобы практически использвовать

вот бы эту кнопочку на отдельную кнопку

**Comment by NS-Clone** [comment]
да и от этой паузы даже скроллбар справа неработает...
жесть

**Comment by zanud** [comment]
Надеюсь, что из всякого разного, вываливаемого по ссылке https://addons.mozilla.org/ru/firefox/search/?q=noscript удастся подобрать что-то подходящее.
