### ISSUE TITLE
unknown software exception (0x80000003) в приложении по адресу 0x024a97bd

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#278]
новое приключение

на днях наконец поставил adblock + noscipt

ну и теперь имеем систематические падения раз по 10 в день
в рандомных местах как правило при кликании

![2023-09-21_054621_](https://github.com/Feodor2/Mypal68/assets/139008911/7f840795-038f-43aa-8af7-31ad868ac3df)
`
unknown software exception (0x80000003) в приложении по адресу 0x024a97bd
`
исключение и адрес всегда одни и те же

количество вкладок не влияет
падает и на 700+ и на 8

это все при browser.tabs.remote.autostart;false

щас будем наблюдать чего буит с browser.tabs.remote.autostart;true

**Comment by Feodor2** [comment]
А какая версия майпала?

**Comment by NS-Clone** [comment]
> А какая версия майпала?

68.13.2b

**Comment by NS-Clone** [comment]
с browser.tabs.remote.autostart;true уже полтора дня работает без падений
 (ну не щитая падений от usb audio)

**Comment by NS-Clone** [comment]
до с browser.tabs.remote.autostart;true
браузер намного стабильней
но все равно иногда падает
но опять же при этом теперь не нужно перезапускать браузер

**Comment by NS-Clone** [comment]
скриншот со времен browser.tabs.remote.autostart;FALSE
ВНЕЗАПНОЕ падение на ровном месте
![2023-09-06_031400_](https://github.com/Feodor2/Mypal68/assets/139008911/25125cbf-68ef-4be6-af04-59b36e770cc0)

```
Всплывающее окно приложения: mypal.exe - Ошибка приложения : Исключение unknown software exception (0x80000003) в приложении по адресу 0x052ee7f1.
```

**Comment by Feodor2** [comment]
800000003 почининино #284

**Comment by NS-Clone** [comment]
похоже что неп
![2023-11-04_020855](https://github.com/Feodor2/Mypal68/assets/139008911/da6bd2fc-f7f4-4753-93d9-08b0d7bed105)
