### ISSUE TITLE
Браузер Mypal 68.13.2b по-прежнему несовместим с Windows XP SP2

### ISSUE THREAD

**Issue by EgorKuzevanov** [Feodor2/Mypal68#279]
Браузер Mypal 68.13.2b по-прежнему несовместим с Windows XP SP2 (2004 года выпуска). При запуске **mypal.exe** на Windows XP SP2 выскакивают две следующих ошибки:
![IMG_0785](https://github.com/Feodor2/Mypal68/assets/78859951/c18f1e11-88d3-419a-b742-c48335032516)
![IMG_0786](https://github.com/Feodor2/Mypal68/assets/78859951/d08762c8-0b35-4d38-98cd-bdfddcf39035)
**Feodor2**, пожалуйста, исправьте данный неприятный баг.

**Comment by zanud** [comment]
Как можно считать это ошибкой, если в описании браузера с самого начала говорится, что с SP2 он не дружит?

И я уверен, что даже если удастся найти способ избежать того первого сообщения, то дальше обнаружится, что есть ещё много чего такого, что необходимо браузеру для работы, но отсутствует в Windows XP SP2.

**Comment by Feodor2** [comment]
Да по прежнему, и я не собирался это испровалять, ты это знаеш, но тебе хочеться поспамить - нет.

**Comment by NS-Clone** [comment]
смысла особого и нет
машина которую проблематишно поставить sp3
не особо то и будет переваривать и текущие интернеты...
