### ISSUE TITLE
Exception Access Violation [UNSORT LIST]

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#280]
mypal 68.13.2b
browser.tabs.remote.autostart;FALSE
БЕЗ adblock и noscript
0x0313acc4
![2023-08-26_223201_](https://github.com/Feodor2/Mypal68/assets/139008911/7274d223-d48a-41be-8d88-ddda6b10aacf)
  
</br>  
</br> 
</br>
  
mypal 68.13.2b
browser.tabs.remote.autostart;FALSE
С adblock и noscript
0x0430de44
![2023-09-24_231111_](https://github.com/Feodor2/Mypal68/assets/139008911/b3fee31e-aa39-4bb5-92a5-5742b37ff66f)
при этом, по моему, при нажатии Ок браузер не закрывается и работает дальше
  
</br>
</br>
</br>

mypal 68.13.2b
browser.tabs.remote.autostart;TRUE
С adblock и noscript
0x03c865c6
![2023-09-25_061707_](https://github.com/Feodor2/Mypal68/assets/139008911/c86b8104-eb72-4ca2-8105-62460753b8dc)

**Comment by Feodor2** [comment]
Без стэка это неочём, нужны докторы вацоны или минидампы

**Comment by NS-Clone** [comment]
> Без стэка это неочём, нужны докторы вацоны или минидампы

ну по идеи ты хотя бы можешь определить в каких функциях оно читает не от туда
конечно если утя все положитсо по тем же адресам...

а дрвоцона умя сильно не любит антивируска
даже добавленный в вайтлист...

**Comment by Feodor2** [comment]
Не определяется

**Comment by NS-Clone** [comment]
> Не определяется

а я думол ты както мож загрузить список меток в олидбг

**Comment by Feodor2** [comment]
И это ночём - адреса куда попало, нужно узнать что посылвет по этим адресам.

**Comment by Feodor2** [comment]
Картинки больше не надо
