### ISSUE TITLE
Actualy NOT fully Portable?

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#283]
68.13.2 переименовал папку c portable версией (с pmprt.mod)
и успешно конфиг стал дефолтным
пришлось откатилсо назад (достал из бекапа)

при переходе с предыдущей версии
я тоже менял название папки
но конфиг вроде бы не отваливалсо

**Comment by Feodor2** [comment]
Профиль не слетает, а расширение да, надо выкл\вкл,
Ещё в 13.3 я применил  https://bugzilla.mozilla.org/show_bug.cgi?id=1429838

**Comment by NS-Clone** [comment]
> Профиль не слетает, а расширение да, надо выкл\вкл,

не ну сам профиль весь не слетел
а вот все modified в about:config стали дефолтными
в том числе вернулось закрытие вкладок с переходом вправо

**Comment by NS-Clone** [comment]
cтранно а щас вроде бы как запустил тот же браузер (на котором отвалилссо конфиг)
и модифицированные настройки в абаутконфиге есть

**Comment by Feodor2** [comment]
По всякому переименовывал и переносил на другой комп - слетают только расширения, нужно любое расширение выключить, 2 раза перегрузить брацзер и потом можно включить.
И как-то так получилось что я не применил [1429838](https://bugzilla.mozilla.org/show_bug.cgi?id=1429838) Так что в 13.3 будет так же само как в 13.2

 я могу пересобрать и выложить omni.ja


>Its interface prompt is“Window id =” main-window”^

What is this? How to reproduce?

**Comment by liqideqq** [comment]
> По всякому переименовывал и переносил на другой комп - слетают только расширения, нужно любое расширение включит, 2 раза перегрузить брацзер 和 потом можно включить。 И как-то так получилось что я не применил [1429838](https://bugzilla.mozilla.org/show_bug.cgi?id=1429838) Так что в 13.3 будет так же само как в 13.2
> 
> я могу пересобрать 和 выложитьomni.ja
> 
> > 其界面提示为“Window id =”main-window”^
> 
> 这是什么？如何重现？

I used the Simplified Chinese language pack to prompt this question.
https://github.com/shawnpxtl/Mypal68-chinese-xpi

**Comment by Feodor2** [comment]
duplicate #67
