### ISSUE TITLE
Blank pages when repeatedly clicking extensions in the Add-ons Manager of Mypal 68.13.3b

### ISSUE THREAD

**Issue by AstroSkipper** [Feodor2/Mypal68#286]
Hello Feodor2! 

I have documented this new issue in detail and with pictures in my thread "**Mypal 68 in Windows XP - Custom Buttons and Extensions**" on **MSFN**. Here is the link: 
[https://msfn.org/board/topic/183657-mypal-68-in-windows-xp-custom-buttons-and-extensions/?do=findComment&comment=1253710](https://msfn.org/board/topic/183657-mypal-68-in-windows-xp-custom-buttons-and-extensions/?do=findComment&comment=1253710) 

Cheers, AstroSkipper [![matrix.gif](https://i.postimg.cc/9XNRQdMg/matrix.gif)](https://postimg.cc/RqKVPnww)

**Comment by Feodor2** [comment]
The new view is set by **extensions.htmlaboutaddons.enabled**
There was an error, which is fixed now, and have pushed the commit
You may take the [fixed omni ja](https://github.com/Feodor2/Mypal68/files/12849208/omni.zip)

**Comment by AstroSkipper** [comment]
> The new view is set by **extensions.htmlaboutaddons.enabled** There was an error, which is fixed now, and have pushed the commit You may take the [fixed omni ja](https://github.com/Feodor2/Mypal68/files/12849208/omni.zip)

Thank you very much for your quick teply!
I will copy the **fixed omni.ja** into my test installation as soon as I am at my desktop computer again.

Greetings, AstroSkipper [![ecrire-ordi.gif](https://i.postimg.cc/g0mccjP2/ecrire-ordi.gif)](https://postimg.cc/1871J9tk)

**Comment by AstroSkipper** [comment]
Helli Feodor2! I replaced the old **omni.ja** file by your fixed one. The pref **extensions.htmlaboutaddons.enabled** is set to false by default and seems to have the correct value. Now, clicking onto extensions works as usual. Many thanks for that! 

Kindest regards, AstroSkipper
