### ISSUE TITLE
Missing and not working entries for updating extensions in Mypal 68.13.3b/68.13.4b

### ISSUE THREAD

**Issue by AstroSkipper** [Feodor2/Mypal68#287]
Everything related to this issue, I have documented in detail and with pictures in my thread "**Mypal 68 in Windows XP - Custom Buttons and Extensions**" on **MSFN**. Here is the link:
[https://msfn.org/board/topic/183657-mypal-68-in-windows-xp-custom-buttons-and-extensions/?do=findComment&comment=1253714](https://msfn.org/board/topic/183657-mypal-68-in-windows-xp-custom-buttons-and-extensions/?do=findComment&comment=1253714) 

Cheers, AstroSkipper [![matrix.gif](https://i.postimg.cc/9XNRQdMg/matrix.gif)](https://postimg.cc/RqKVPnww)

**Comment by Feodor2** [comment]
Once i had decided remove extensions update, so i reconsidered. The thing is altogether with #286 also set **extensions.update.enabled** and **extensions.update.url**

**Comment by AstroSkipper** [comment]
> Once i had decided remove extensions update, so i reconsidered. The thing is altogether with #286 also set **extensions.update.enabled** and **extensions.update.url**

Again, many thanks for your quick reply and explanations! I am very glad that you reconsidered your decision. As already mentioned in the issue #286, I will follow your advices to check everything related to the features and prefs for updating extensions when I am at my desktop computer again.

Kindest regards, AstroSkipper [![ssuper5sur5.gif](https://i.postimg.cc/DZLCnf3b/ssuper5sur5.gif)](https://postimg.cc/qhBcGTRk)

**Comment by AstroSkipper** [comment]
Hello Feodor2! As I **already** wrote in #286, I replaced the old **omni.ja** file by your fixed one. Next, I set the pref **extensions.update.enabled** to the value **true**. Now, I am dealing with the pref **extensions.update.url**. I deleted its default value and set this new value: **https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=%APP_LOCALE%&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%**
Is this the correct value?

Greetings, AstroSkipper

**Comment by AstroSkipper** [comment]
Additionally, I set the pref **extensions.update.background.url** to the value **https://versioncheck-bg.addons.mozilla.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=%APP_LOCALE%&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%**
Is that correct, too? [![smilie-denk-49.gif](https://i.postimg.cc/DyM2Jb4M/smilie-denk-49.gif)](https://postimg.cc/568cDy3B)

**Comment by AstroSkipper** [comment]
With these settings, I had the first success in updating the extension [Clear Cache](https://addons.mozilla.org/de/firefox/addon/clearcache/versions/) from version 3.1 to 3.2. 
[![superouais.gif](https://i.postimg.cc/zvMcYTjr/superouais.gif)](https://postimg.cc/64r0d2gj)
Unfortunately, updating [uBlock](https://addons.mozilla.org/de/firefox/addon/ublock-origin/versions/) doesn't work. At the moment, I don't know why. [![smilie-denk-50.gif](https://i.postimg.cc/R0c9Dssk/smilie-denk-50.gif)](https://postimg.cc/McKhcD85)

**Comment by Feodor2** [comment]
>I assume there is another variable or value which is checked before offering updates

app_version in the link for sure, but i shall not put the link, and i would not recommend to set autoupdate for all extensions to 78.

>TypeError: XPIDatabase.mustSign

This was fixed

**Comment by AstroSkipper** [comment]
> > I assume there is another variable or value which is checked before offering updates
> 
> app_version in the link for sure, but i shall not put the link, and i would not recommend to set autoupdate for all extensions to 78.
> 
> > TypeError: XPIDatabase.mustSign
> 
> This was fixed

Thanks for this information and fixing the **uBlock** related error! So, are the links correct I set as values for updating? 
[![smilie-denk-49.gif](https://i.postimg.cc/DyM2Jb4M/smilie-denk-49.gif)](https://postimg.cc/568cDy3B)

**Comment by Feodor2** [comment]
>mean by "but i shall not put the link"?

to extensions.update.url

**Comment by AstroSkipper** [comment]
And what kind of link would you add there?

**Comment by Feodor2** [comment]
> So what's wrong with the

This was deleted at the first and will stay empty, but you can put any link by yourself, is this not enough or better to remove the thing at all as i planned.

**Comment by AstroSkipper** [comment]
> > So what's wrong with the
> 
> This was deleted at the first and will stay empty, but you can put any link by yourself, is this not enough or better to remove the thing at all as i planned.

I will use this link and leave the update function activated even if this feature is still faulty and needs fixes. Without this link I posted above, the user will not be informed when extension updates are available which would not be particularly desirable.

**Comment by AstroSkipper** [comment]
@Feodor2 

Mypal 68 is based on Firefox, in which there has always been an update function for extensions that has done its job perfectly. Since you have changed your mind again and are no longer interested in it, even though this function is still not working properly, I hereby close this issue again before chess-sensical rubbish is posted here again by the spammer @andika207, as it happened in issue #296. My time is too precious to be annoyed by such filth. There are more important things to do. 

Kind regards, AstroSkipper
