### ISSUE TITLE
ЛГБТ формат времени в history

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#288]
без коментариев (выуживать нужные страницы из истории одно удовольствие)
![2023-10-12_012121](https://github.com/Feodor2/Mypal68/assets/139008911/35ea4adf-2a51-4660-ae16-a2cd920ea120)

**Comment by NS-Clone** [comment]
в интернетах вообще пишут что оно должно подстраиваетсо под системный формат времении...
можот при адаптации поломалось?
кто нить гляньте у себя

**Comment by Feodor2** [comment]
Чего то я не понял, этот формат даты у них уже давно, ну накати русск язык, новый пак 68.13+  уже сделали, правда я не проверял, я даже привык к англ формату, он не только в браузерах а много ещё где нет русск.

**Comment by NS-Clone** [comment]
мало того в этой амрмурне еще и время на час мимо
вот прям заходишь на страницу
а в списке всплывает на час меньше

**Comment by Feodor2** [comment]
> время на час мимо

Это должно быть исправлено в 13.2

**Comment by Feodor2** [comment]
Дело в летних или зимнем времени и кодеровке даты в число, а почемуто оно не учитывает это. 
Вот уже правильно показывает когда перевекли часы, пока до следущего перевода будем если живы.

**Comment by NS-Clone** [comment]
> Дело в летних или зимнем времени и кодеровке даты в число, а почемуто оно не учитывает это. Вот уже правильно показывает когда перевекли часы, пока до следущего перевода будем если живы.

ну тут у самой венды глюки с отображением времени файла
так венда то показыывает неправильно файлы не из текущего времени
а тут прямо в текущем
