### ISSUE TITLE
Use GitHub Releases instead of MEGA/AnonFiles

### ISSUE THREAD

**Issue by 1280px** [Feodor2/Mypal68#29]
This is way more secure than downloading it from sketchy websites like AnonFiles. GH also allows to upload up to 2GB per release (which is more than enough) and download files from legacy browsers (unlike MEGA), so why it's not being used?

**Comment by ScratchApps** [comment]
> This is way more secure than downloading it from sketchy websites like AnonFiles. GH also allows to upload up to 2GB per release (which is more than enough) and download files from legacy browsers (unlike MEGA), so why it's not being used?

https://github.com/Feodor2/Mypal68/issues/7#issuecomment-1091216545

**Comment by IP-CAM** [comment]
It's on Github now !
https://github.com/Feodor2/Mypal68
