### ISSUE TITLE
Fuzzy text under Xp

### ISSUE THREAD

**Issue by enigma131** [Feodor2/Mypal68#290]
Hi,
Thanks for the release, all my favorites are working fine.
I have a problem with text rendering under my Xp partition, under Win 7 it's oK.
Text is fuzzy, see attached picture (use save image on ccomputer), at left serpent 52 browser.
Does it exist a way to solve this ?

![mypal](https://github.com/Feodor2/Mypal68/assets/31815445/48d71f0a-3271-4b69-bf72-a838dbc3cdf2)

**Comment by Feodor2** [comment]
On xp some fonts will be sure bad, because of no direct2d, but regular about:config fonts looks good. Did you change things?
Checkt the safe mode or clean profile.

**Comment by enigma131** [comment]
I have change Nothing at the moment. I've compare with Serpent, but there are so many lines in config...
Wich lines should I look to change ?

**Comment by RamonUnch** [comment]
Font smoothing in Mypal follows the system setting. I disable font smoothing at system-wide level.

in your screenshot Serpent displays font without anti-aliasing and MyPal uses anti aliasing.
To see the font related settings search for `gfx.font` and you will see only 15 settings.

**Comment by rocknard** [comment]
I deleted "Skia" and others, but "Skia" surely i deleted this.

**Comment by win98se** [comment]
I see someone is a ClearType hater. 😂

And actually, the line you would want to find is `gfx.text.disable-aa`. Turn it on, restart Mypal68, and voila - ClearType is gone for you.

**Comment by enigma131** [comment]
Wow win98se, this works, well-done. I can continue test without breaking my eyes :)

**Comment by enigma131** [comment]
I've close ticket, but I think It must be sticked somewhere.
