### ISSUE TITLE
Find more search engines  locked ?

### ISSUE THREAD

**Issue by enigma131** [Feodor2/Mypal68#292]
I'm looking for adding DuckDuckGo / and - or Bing (same engine ?)  to MyPal 68.
How to done it ?

**Comment by AstroSkipper** [comment]
Use the website [Mycroft Project](https://mycroftproject.com/search-engines.html)  to find and to add your favourite search engines!

**Comment by enigma131** [comment]
It's working via Mycroft, thanks
