### ISSUE TITLE
What did you do with the search engine in 13.3b and 13.4b?

### ISSUE THREAD

**Issue by Sen-nin** [Feodor2/Mypal68#295]
Hello. I was surprised to find DuckDuckGo had disapeared from the search engine list when I installed 13.3b. I had to find a way to get it back. In 13.4b, you added more unfamiliar search engines in addition to Quant. Quant only works in only limited areas. It does not work in Japan, for example. We cannot access it or get a warning message. Considering there are many beginners, I think you had better be a little more conservative about search engines. They even do not know the word _search engine_.

**Comment by Feodor2** [comment]
The search i put for default - the startpage would be enough for 99% including japan beginners.
You tell what it failed to search about japan
Meanwhile qwant is not default so beginners are past.

Before i used the duck search myself, but it become worse and worse and also censored, that's why i replaced it.
wiki also goes politics and censored, not trustworthy too.

By the way It is very easy to set duck default back for you, no need any thirdparty things like mycraft whatever.

**Comment by zanud** [comment]
Hello, @Feodor2.

I am here with almost exactly same question: "What have happened? Why all well-known engines disappeared from the list?"
I examined `omni.ja` and discovered that **all** existed in the past engines are removed.

After your explanation here, I want to ask: _"Wouldn't it be better to preserve old engines, and just put your new ones to the start of list?"_ (so everyone will be able to choose what he/shi prefers).

**Comment by AstroSkipper** [comment]
> By the way It is very easy to set duck default back for you, no need any thirdparty things like mycraft whatever.

Hello @Feodor2,

May I kindly ask which way exactly you mean?  [![smilie-denk-49.gif](https://i.postimg.cc/DyM2Jb4M/smilie-denk-49.gif)](https://postimg.cc/568cDy3B)

**Comment by NS-Clone** [comment]
конешно поступать в стиле М$-ZОG не очень хорошая идея
обновлениё
выпелено то, то, то

**Comment by andika207** [comment]
Google is and will remain the best search engine for years until M$ finds a way to improve their crap Bing
I am glad to see DuckDuckShit go. 
it's totally obsolete and I have never liked it. thanks @Feodor2

**Comment by K4sum1** [comment]
What is with all the weird changes like removing search engines and no searching in address bar?

**Comment by NS-Clone** [comment]
поиск в адрес баре ненужон!

**Comment by zanud** [comment]
Some people (including me) prefer to have a separate search bar, some people can not live without searching in address bar.

So there **is** a corresponding setting in the MyPal settings.

**Comment by andika207** [comment]
> Some people (including me) prefer to have a separate search bar

I agree 100% 
this allows you to keep up the text on the search bar just in case you want to search the same thing on multiple tabs at a time or just change some words without the need to re-write it from scratch

**Comment by K4sum1** [comment]
You can just have a separate search bar without disabling searching in the address bar. Disabling that feature by default will be confusing for new users.

**Comment by Feodor2** [comment]
To tell again  replced search providers with another because their search has been became bad and censored.
You may prove me otherwise.
Also you may set back former search by few clicks

**Comment by zanud** [comment]
> To tell again replced search providers with another because their search has been became bad and censored.

This can be an adjustment for adding new providers and setting one of them as a default, but not for removing all old providers completely.

> Also you may set back former search by few clicks

Where?

**Comment by Feodor2** [comment]
open desired search site
![image](https://github.com/Feodor2/Mypal68/assets/19492771/d4172ec6-6255-4d87-9e01-52beecd1fd87)
next
![image](https://github.com/Feodor2/Mypal68/assets/19492771/8df662cb-8060-468c-99cb-ae1fdd3bebab)

**Comment by zanud** [comment]
> next

Not all sites support this. For example, try to reproduce this on google.com or mail.ru

**Comment by andika207** [comment]
> For example, try to reproduce this on google.com or mail.ru

@zanud  where are you from?

**Comment by zanud** [comment]
@andika207
It's about my origins or about my current location?  8-)

**Comment by andika207** [comment]
> @andika207 Is it about my origins or about my current location? 8-)

either of them. cheers

**Comment by zanud** [comment]
USSR -> Ukraine -> Russia via some intermediate countries.

**Comment by andika207** [comment]
> USSR -> Ukraine -> Russia via some intermediate countries.

I couldn't find any discussion thread in the [www.forum.ru-board.com/forum.cgi ](https://forum.ru-board.com/forum.cgi?forum=5)
isn't there any general public interest over there about Mypal68 ?

**Comment by zanud** [comment]
At least: [Мой новый браузер - Mypal ](http://forum.ru-board.com/topic.cgi?forum=2&topic=5894) and [MyPal 68](https://msfn.org/board/topic/183495-mypal-68/)

**Comment by AstroSkipper** [comment]
> open desired search site ![image](https://user-images.githubusercontent.com/19492771/276990802-d4172ec6-6255-4d87-9e01-52beecd1fd87.png) next ![image](https://user-images.githubusercontent.com/19492771/276991324-8df662cb-8060-468c-99cb-ae1fdd3bebab.png)

This way is not offered here, unfortunately. Here is a screenshot:
[![Mypal-68-13-4-duckduckgo-com.png](https://i.postimg.cc/1RJ5QQPk/Mypal-68-13-4-duckduckgo-com.png)](https://postimg.cc/9zwjdsDb)

**Comment by Sen-nin** [comment]
@Feodor2  Thank you. Your information regarding your decision on the search engine change is quite valuable.

The quality of search results may vary depending on the language, so I think it is best to be conservative for that reason too. As Japanese is an isolated language, totally different from any other language including Chinese or Korean, not to mention English, Google has been struggling for years to understand web pages written in Japanese. They may have had some success, but I am not so sure about other search engines. Recently bing and Duck have started producing good search results in Japanese.

Also, less popular search engines may show poorly designed web pages in Japanese as they may not have many Japanese web designers. In this regard as well, bing and Duck have improved a lot recently. Right now, Google, bing, and Duck have come to produce equally easy-to-read web pages. Startpage web page design is yet to be optimal.

Clicking on a plus sign or even using Mycroft Project search engine plugins would be too difficult for beginners. I think the best way is to add major search engines to the search engine list from the start.

I have several XP computers here and there. When I installed 13.3b on one of them and searched the Web, I was brought to Qwant, somehow not Startpage, and got a strange warning message in English like "we cannot show good search results from your area" or something like that.

As Japanese is an isolated language, almost no one understands foreign languages. We study English for at least six years in high school, but even then, less than 0.1% of Japanese can make somewhat meaningful utterances in English. Those less than 0.1% of us, who claim to be able to speak English, actually  just utter a string of English words that do not make any sense at all. As such is the situation, a warning message in English must baffle Japanese users. Qwant shows the following message now: 

> Qwant The search engine that respects your privacy
> Thanks for your visit
> Unfortunately we are not yet available in your country.

If this were written in Japanese, experienced users would find a way out. I think we need to avoid a situation like this. It would be like Americans or Russians run into a Chinese warning message.

**Comment by zanud** [comment]
> The search i put for default - the startpage would be enough for 99% including japan beginners.

Очень многие провайдеры выдают своим клиентам серые IP-адреса. А Startpage таких посетителей отшивает:
_"We're sorry for the inconvenience! Our system has detected the type of high-volume traffic coming from your internet connection that is normally associated with bots and scrapers."_

Те, кто выходят в Интернет через популярные прокси, точно в таком же пролёте.

**Comment by andika207** [comment]
> @Feodor2 is active on both.

I did mean, are there other Mypal68 devs aside from @Feodor2 ???

**Comment by zanud** [comment]
(Looking at pull requests list) I doubt.

**Comment by andika207** [comment]
> (Looking at pull requests list) I doubt.

 I can't believe nobody else all over the Russia land is not interested in this project.

this is a very sad news because with more active developers would could spot and fix bugs way faster

**Comment by Feodor2** [comment]
Give the example that duck-bing better search for japan.
If its really confirmed i shall restore it

Also i don't know why no green thing for add new search engines, investigation is needed, finally use mycraft thing then.

And yes i only the developer.

**Comment by zanud** [comment]
> Give the example that duck-bing better search for japan.
> If its really confirmed i shall restore it

What to do with fact that among Qwant, Startpage, Mojeek, and Brave only Brave works for me?
All three others rejects all requests either with "We do not support your language/country" or with "You are sending too many requests".

It looks like 70-80% should go to ~~сад~~ Mycroft.com

**Comment by jonm58** [comment]
@Feodor2 Can you add Searxng search engines?

**Comment by K4sum1** [comment]
You keep making changes that most people don't like. Instead of digging through here to find the one link that works to add x engine, they're probably just going to use New Moon or insert Chinese Chrome fork here. There exists no universe where a significant amount of people want Google, but are instantly defeated and use the default instead of digging here or replacing browser. Removing or changing x thing that is popular won't make people want to have it like that, it will make them use something else.

I myself even switched to Qwant for a significant amount of time. I switched back to DuckDuckGo because Qwant loaded slower, and didn't have built in conversion/translation functionality, or at least that was how it was at the time. Maybe it's better now, but if I want to throw MyPal on x device just to look up y thing, I don't want to fumble with search engines and fumble in about:config to not end up on a malware site on the computer and browser that would be vulnerable to it the most because .com was appended onto want I wanted to search.

Also I know whatever search engine is censored. In Firefox and with the address bar, if I don't get the results I want I just click the logo for a different search engine and it searches with it. If I want to search something that Google or DDG doesn't like, it's just one extra click for Qwant or whatever.

Conclusion (and TL;DR):
You can have Qwant or whatever be the default, just add back the other search engines so if someone wants to use them they don't have to dig here for one site to add them for each computer.

Also make the address bar work for searching. You already use the search bar to search, it does not effect you if searching there works or not because you're not using it to search.

**Comment by andika207** [comment]
> Also make the address bar work for searching. 

I don't like to use the URL bar as the search engine because sometimes you are tipping something and the browser understands your are tipping a true URL and as such the page gets broken and causes more stress.

**Comment by andika207** [comment]
> You keep making changes that most people don't like. 

TALK FOR YOURSELF !
you like to attribute **''most people''** to a handful of random swallowers. https://github.com/Feodor2/Mypal68/issues/101#issuecomment-1772076068

**Comment by jonm58** [comment]
> > 你不断做出大多数人不喜欢的改变。
> 
> 为自己说话！ 你喜欢将 **“大多数人” **归因于少数随机吞食者。 [ 第101章（评论） ](https://github.com/Feodor2/Mypal68/issues/101#issuecomment-1772076068)

@Feodor2 Open a discussion in Github,See how many search engines we can get? And the custom search engine thing.

**Comment by Feodor2** [comment]
Нда starpage зобанил меня за русск язык - удаляю нахрен,

**Comment by andika207** [comment]
@zanud  https://www.youtube.com/watch?v=CGU9rg6kEVc

**Comment by NS-Clone** [comment]
> Нда starpage зобанил меня за русск язык - удаляю нахрен,

отрыл
сразу получил посыл что я злостный спамботюзателеьвпн
хотя я его впервые вижу
и зашол традиционным способом...

**Comment by NS-Clone** [comment]
> Нда starpage зобанил меня за русск язык - удаляю нахрен,

тыж удоляй его у себя
а не у всех как лгбтэпол

можот у кого то он и будет работать
а кушать он не просит...
...мне например некогда выгугливать альтернативы гуг00лу

**Comment by Feodor2** [comment]
@NS-Clone 
Так нифига себе я захотел проверить как он ищет на русском, а он меня послал, и теперь уже всегда посылает.
Это ещё хуже уткабинга, нахер такой поисковик.

So let we to choose new default search engine, alse maybe restore duck-obing, but wont do it default for sure.

**Comment by NS-Clone** [comment]
> @NS-Clone Так нифига себе я захотел проверить как он ищет на русском, а он меня послал, и теперь уже всегда посылает. Это ещё хуже уткабинга, нахер такой поисковик.

воще зашибезный ресурс
судя по сгенерированному линку https://www.startpage.com/sp/captcha-block****

он вообще прекрасно определил что я сижу с мобильного оператора (и какого)
и ко мне еще предъявы про подозрительную активность?

**Comment by Sen-nin** [comment]
@Feodor2 

> Give the example that duck-bing better search for japan.

I think I never said duck or bing is better than any other search engine. What I said is that they are doing a fairly good job in Japan recently.

Search engine algorithms are revised several times a day. They are drastically revised a few times a year. I cannot guarantee what will happen to them tomorrow or next week.

In any case, I will come up with some examples later on.

**Comment by andika207** [comment]
> I think I never said duck or bing is better than any other search engine. 
What I said is that they are doing a fairly good job in Japan recently.

wasn't Yahoo the leading search engine in Japan ?

**Comment by Sen-nin** [comment]
Yahoo! Japan used to nearly monopolize the search engine market in Japan. At that time Yahoo! used to have their own search engine. Then Yahoo.com (USA) gave up. They started to use bing instead. Yahoo! Japan (yahoo.co.jp), a separate company, decided not to use bing but instead they started to use Google. Here is the latest stats:

Google  75.98%
Yahoo!  16.24%
bing     7.13%
Duck     0.31%

Google's share is 92% in Japan if Google and Yahoo! are put together.

I used to exclusively use Google myself, but now I use duck most of the time. I do still use Google to find my own websites.

Why duck? Because it does not show Japanese if my browser language is set to English. That is an absolutely necessary feature if you teach English. In addition, I mostly use duck image search.

Suppose I am to teach the word _dog_, I need photos or illustrations labelled "dog," not "犬 (inu)" which means _dog_. Why? Because I use photos and illustrations in order to avoid using or showing the Japanese language.

These days duck is as good as Google most of the time, so I do not need to switch to Google in the case of normal search activities unless I am to find my own websites.

But that's my very personal preference, everybody else probably just wants the old search engines back.

I almost forgot. I do use Google to find how many instances of a certain phrase or word exist in search results. For example, I may need to find how often "Merry New Year" is used and whether that expression is correct or not. In that case, I use Google because bing or duck cannot be used for that purpose. There are probably many teachers who do the same. It is not actually the accurate way to find these things, but it is the fastest way. The accurate way is to search a language corpus.

Other than these two, there is no need to go to Google these days. Of course, that does not mean Google is any worse than duck.

**Comment by andika207** [comment]
> Why duck? Because it does not show Japanese if my browser language is set to English. That is an absolutely necessary feature if you teach English. 

so if you look up ''dog images'' with google it will show japanese websites ?

**Comment by Feodor2** [comment]
бинг на русск ищет номально

I very very do not like when search sites mess the links.
So what do you think about brave and to set it default?

**Comment by NS-Clone** [comment]
> I very very do not like when search sites mess the links.

ну так жо? гугол собирает статистику переходов
полезность результатов выдачи
(хотя глядя на результаты поиска последнее время...)

раньше вроде был плагин для разгугливания ссылок
интересно для нового квантума такой есть? (никак не доходят руки поискать)

**Comment by zanud** [comment]
> раньше вроде был плагин для разгугливания ссылок
> интересно для нового квантума такой есть? (никак не доходят руки поискать)

Google сначала показывает нормальную ссылку, а на шпионскую она подменяется в момент щёлкания по ней.
Для борьбы с этим плагин не нужен, можно обойтись с помощью userscript. А скрипт - один и тот же - работает в браузере любого вида. Я в прошлом себе такие писал - и для Google, и для Яндекса.
Да и NoScript справиться должен.

**Comment by NS-Clone** [comment]
> Да и NoScript справиться должен.

г00гл ужо некоторое время без жабоскрипта
выдает бланкпейдж

**Comment by zanud** [comment]
Тогда userscript - отменять навешанный на ссылки обработчик события `click`.
Вот те склады: [OpenUserJS](https://openuserjs.org/), [Greasy Fork](https://greasyfork.org/), [Tampermonkey](https://www.tampermonkey.net/scripts.php).
Поройся, может там уже готовые решения есть.

**Comment by Feodor2** [comment]
I knew the addon for clean links which has been deleted from the mozilla, may look in the archive. Anyway goolag is no no no. What else will you suggest?

**Comment by Feodor2** [comment]
Okey i set brave the default, delete startpage and restore the duck.
