### ISSUE TITLE
Errors and problems when installing and updating extensions in Mypal 68

### ISSUE THREAD

**Issue by AstroSkipper** [Feodor2/Mypal68#296]
Hello @Feodor2 ! I examined the installing and updating of extensions more deeply. I found several problems and errors. All my observations and investigations will be posted in this issue to provide data for easier and more targeted fixing. But first of all, the good news. After I restored the manual and automatic update for extensions as I already described [here](https://msfn.org/board/topic/183657-mypal-68-in-windows-xp-custom-buttons-and-extensions/?do=findComment&comment=1253829), many of them could be installed and updated without any serious problems. I was permanently checking the process of installing and updating via the **Browser Console**. Thus, I could identify errors, warnings or problems when occurring.

**1. Fresh install of uBlock Origin 1.52.2 in single-process mode**

Fresh profile in **Mypal 68.13.4b**, **single-process mode**, no other extensions installed. I called up the website https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ and installed **uBlock Origin 1.52.2** (latest version) directly from there. The installation seemed to perform properly but looking at the **Browser Console** tells us there are problems and errors. Here is a **screenshot** of the **Browser Console** with all entries related to the installation process without a browser restart: 
[![Mypal-68-13-4-u-Block-Origins-after-first-install.png](https://i.postimg.cc/GpxS597x/Mypal-68-13-4-u-Block-Origins-after-first-install.png)](https://postimg.cc/v1Dz18d4)
Here we can see, for example, that a restart seems to be needed but a request to restart is not sent to the user for doing so. BTW, why is a restart needed at all? This is not the case otherwise. Furthermore, there is an error: **TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.** in **ExtensionContent.jsm:552:25**. And the temporary xpi file **tmp-fuh.xpi** couldn't be deleted which seems to be related to a problem in the file **XPIInstall.jsm**. 
And this is how it looks when you switch directly to the **Add-ons Manager** during installation:
[![Mypal-68-13-4-u-Block-Origins-after-first-install-2.png](https://i.postimg.cc/j5jkZSt1/Mypal-68-13-4-u-Block-Origins-after-first-install-2.png)](https://postimg.cc/5HZ3t1H5)
Unfortunately, this remains until a page refresh or a browser restart is carried out. What do you think? Can all this be fixed? [![interroge.gif](https://i.postimg.cc/qMdjJCR3/interroge.gif)](https://postimg.cc/grNv4j3z)

**PS:** Interestingly, when manually installing **uBlock Origin 1.52.2** via the downloaded xpi file, there is only one entry related to this kind of install: **TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.** in **ExtensionContent.jsm:552:25** which is the same error as posted above. And nothing about a needed restart. Here is a small screenshot of it:
[![Mypal-68-13-4-u-Block-Origins-after-first-install-3.png](https://i.postimg.cc/k4tFTcnR/Mypal-68-13-4-u-Block-Origins-after-first-install-3.png)](https://postimg.cc/zb8gBTHq)

**Comment by andika207** [comment]
uBlock Origin works perfect here. No errors.

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/QdqXGXW5/screenshot-2.png' border='0' alt='screenshot-2'/></a>

**Comment by AstroSkipper** [comment]
> uBlock Origin works perfect here. No errors.

This issue is **not** about whether **uBlock Origin** works or not. And of course, it works. It is about problems and errors when installing and updating extensions. Check the browser console when installing or updating extensions! Then, you will see what I mean.

**Comment by andika207** [comment]
> Check the browser console when installing or updating extensions! 

what extensions and how do you check the browser console ?

**Comment by Feodor2** [comment]
ublock works no matter errors.
Notice that with singleprocess you get more errors

**Comment by AstroSkipper** [comment]
> ublock works no matter errors.

I never said **uBlock origin** wouldn't work in **Mypal 68**. And of course, it does. But the process of installing **uBlock Origin**, especially via the **[addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)** website, causes errors in **Mypal 68** when using **single-process mode**. That's what I documented above.

> Notice that with singleprocess you get more errors

Interesting! I created a new profile using **Mypal 68** in **multiprocess mode**. And you are right. In this mode, there are less errors, but not free of errors either. I will document that later.

**Comment by AstroSkipper** [comment]
**2. Fresh install of uBlock Origin 1.52.2 in multiprocess mode**

Fresh profile in **Mypal 68.13.4b**, **multiprocess mode**, no other extensions installed. I called up the website https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ and installed **uBlock Origin 1.52.2** (latest version) directly from there. The installation seemed to perform properly but looking at the **Browser Console** tells us there is an error. Here is a **screenshot** of the **Browser Console** with all entries related to the installation process without a browser restart:
[![Mypal-68-13-4-u-Block-Origins-after-first-install-in-MP-mode-2.png](https://i.postimg.cc/vTTnHKfv/Mypal-68-13-4-u-Block-Origins-after-first-install-in-MP-mode-2.png)](https://postimg.cc/hQFv2pCJ)
the temporary xpi file **tmp-i7r.xpi** couldn't be deleted which seems to be related to a problem in the file **XPIInstall.jsm**.
And this is how it looks when you switch to the **Add-ons Manager**:
[![Mypal-68-13-4-u-Block-Origins-after-first-install-in-MP-mode.png](https://i.postimg.cc/6qPv7hhx/Mypal-68-13-4-u-Block-Origins-after-first-install-in-MP-mode.png)](https://postimg.cc/dZ81prX5)
Unfortunately, this remains until a page refresh or a browser restart is carried out. What do you think? Can all this be fixed? [![interroge.gif](https://i.postimg.cc/qMdjJCR3/interroge.gif)](https://postimg.cc/grNv4j3z)

**Comment by AstroSkipper** [comment]
@Feodor2 Why are there more errors when using **Mypal 68** in **single-process** than in **multiprocess mode**? And will you fix some of the important ones?

**Comment by andika207** [comment]
> And this problem occurs when you switch to the **Add-ons Manager**:

I can't replicate your crap here, it was you who ever claimed that ublock was not supported on anything under Firefox 78
maybe this browser requires SSE3 instructions and your **Pentium 4** is unsupported

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/QdqXGXW5/screenshot-2.png' border='0' alt='screenshot-2'/></a>

**Comment by AstroSkipper** [comment]
> I can't replicate your crap here, it was you who ever claimed that ublock was not supported on anything under Firefox 78 maybe this browser requires SSE3 instructions and your **Pentium 4** is unsupported
>
@andika207 
Stop commenting here in this issue! You are not @Feodor2 , and you obviously don't understand anything. Everything, you wrote above is crap and void. No artificial intelligence will help you as a substitute. @Feodor2  has already asked you not to derail the issues here. So, be obedient and spare us your rubbish! Maybe then you can learn something, which I somehow doubt, though.

**Comment by andika207** [comment]
> Maybe then, you can learn something, which I somehow doubt, though.

this is what we have learnt from the Pentium 4 lover

**_''You can't have installed uBlock Origin 1.47 in Mypal 68. It is not compatible. It needs FF 78+''_**

**Comment by AstroSkipper** [comment]
@Feodor2 

Can you please delete the comments of the stalker @andika207 ? This person only spreads untruths here, has nothing constructive to contribute and pollutes the issues here. I don't know what this rubbish is about.

**Comment by andika207** [comment]
> Can you please delete the comments of the stalker @andika207 ? 

chatGPT was not wrong, the FASCIST wants to try to silence everybody who doesn't agree with him

**Comment by andika207** [comment]
> This person only spreads untruths here

maybe you suffer from Alzheimer at your age but I have a screenshot in case you can't remember your own claims

**Comment by andika207** [comment]
note, Feodor is not your big brother so do not bother him and don't call him out for assistance, you are old enough to defend yourself  with your weapons 

Feodor has a lot of work upfront with regards to the BSOD issues https://github.com/Feodor2/Mypal68/issues/3#issuecomment-1773147699 
I don't think this kind of issues reported by one single-process fanboy in 2023 are a priority for him

**Comment by Feodor2** [comment]
Yes i dont have time to fuss over. I ask your both just stop here, go look other places for your squabbles

Also recent ublock actually is for 78 version, there is no stright way to install it on 68 original fox, so there is a hack in the mypal to install ublock and unknown will newer versions work.

**Comment by AstroSkipper** [comment]
@Feodor2 

FYI, from my side, there are **no squabbles** here. [![nimportequoi.gif](https://i.postimg.cc/L8TCnV91/nimportequoi.gif)](https://postimg.cc/MnnbLVj6) The plural you have chosen in your statement is therefore **not** correct in terms of content. [![snegatif.gif](https://i.postimg.cc/xC9KLrrZ/snegatif.gif)](https://postimg.cc/hJ3zq5t8) If you skim the previous, rubbish posts, you'll notice that you have a **spammer** and **stalker** named @andika207 in your issues who is constantly insulting others, posting offtopic, trying to inject pseudo politicisation and derailing your issues. That's unfortunately a fact. And of course, you really don't deserve something like that. To tell the truth, there is definitely a lack of moderation here. But, I know such a moderation would be time-consuming and arduous. And you obviously have more important things to do than hang out with brainless idiots. In my forum **MSFN**, this **spambot** would have been blocked or banned long ago.  In any case, I have neither the time nor the inclination to deal with such trash generated by people with a **single-digit IQ** or by a **mis-configured AI**. [![snegatif.gif](https://i.postimg.cc/xC9KLrrZ/snegatif.gif)](https://postimg.cc/hJ3zq5t8) But one thing is clear: your issues, your problem, and not mine. You will know what to do. Anyway! No squabbles initiated by me. [![nimportequoi.gif](https://i.postimg.cc/L8TCnV91/nimportequoi.gif)](https://postimg.cc/MnnbLVj6)

**Comment by andika207** [comment]
@AstroSkipper bla bla bla.... typical granny hidden in a room behind a computer who suffered from a sad childhood period thus posting countless emogis in each reply like a little kid.

chatGPT was not wrong, the aim of this **hitlerian** is to silence everyone who don't lick his balls and I know for a fact he's been fighting against multiple other users and as such many of those don't visit the MSFN forum anymore let alone his annoying and useless discussions threads 

Again, Feodor and all other users are adults, if they feel the need to voice something out they will just call me out on their own they have zero need to listen to your pointless advices

Message **edited 14 times** so far LOL.... you must be bored
feel free to deposit your anger here  **\\______________/** then get a life an move on stupid old fart!

**Comment by Feodor2** [comment]
Hey, i asked to stop this, even if i am not native english at all and select wrong word.
I see something veery noot good between you, okey that's happens, but i insist you to go make relationship elsewhere
