### ISSUE TITLE
AV doesn't like Mypal68 [False Positives]

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#297]
в 68.13.4 антивируска хочет удолять mozglue.dll
с криком `Win32/Heur.Generic.Hx4Csw0A`

**Comment by NS-Clone** [comment]
хотя вот натравил вирус тотал
и он показывает 0/76
https://www.virustotal.com/old-browsers/file/56eae5c907fdac19ca5ffb71727ac9293be57ce968068f9941066c98ffe7904d

**Comment by AstroSkipper** [comment]
Forget about your antivirus programme and find a new one!

**Comment by andika207** [comment]
> IMHO, forget about your antivirus programme and find a new one!

will you recommend him your crap PANDA DOME  that you use with a Pentium4 ?

**Comment by andika207** [comment]
> хотя вот натравил вирус тотал и он показывает 0/76 

https://www.virustotal.com/gui/file/56eae5c907fdac19ca5ffb71727ac9293be57ce968068f9941066c98ffe7904d

**Comment by AstroSkipper** [comment]
> will you recommend him your crap PANDA DOME that you use with a Pentium4 ?

I guess reading isn't your strong point. I haven't used Panda for a long time, although it's ok. My statement is and was what I wrote, without your unqualified comment. I didn't recommend anything.

**Comment by andika207** [comment]
> I didn't recommend anything.

**_''forget about your antivirus programme and find a new one!''_**

**Comment by andika207** [comment]
>The issues here are about supporting the development of Mypal 68

You are not being any helpful if you show up to recommend your Panda Dome crap. 
**#facts**

**Comment by AstroSkipper** [comment]
> The granny of your country is causing much more trouble in europe by keeping the doors open to blacks and muslims. this is a true insult to me

@andika207 
**Mypal's issues** are **not** about **politics**. [![snegatif.gif](https://i.postimg.cc/xC9KLrrZ/snegatif.gif)](https://postimg.cc/hJ3zq5t8) Such comments are simply nonsense, totally superfluous and **off-topic**. [![suisjebete.gif](https://i.postimg.cc/fWrpqtyr/suisjebete.gif)](https://postimg.cc/3W2tdwgX) Furthermore, there is **no** "granny of my country" for a longer time which proves you do not know anything about European politics. 
Next, stop spreading falsehoods as for example your babbling about Panda, and above all, stop talking to me! [![sstop.gif](https://i.postimg.cc/LX1n530f/sstop.gif)](https://postimg.cc/TLTRHgxY) 
You are wasting my time. This is my last reply to you. Savy? [![klarsoweit.gif](https://i.postimg.cc/XvbjrdP3/klarsoweit.gif)](https://postimg.cc/dh5PXkvS)

**Comment by Feodor2** [comment]
Я проверил на virusscan.jotti.org - всё зёленая, косперски в том числе.

> will you recommend him your crap PANDA DOME that you use with a Pentium4 ?

Didnt know that, anyway dont go to derails the issues.

**Comment by andika207** [comment]
>  Furthermore, there is no "granny of my country" for a longer time 

Her first name is URSULA. I am sure you know her and why she's flooding europe of ilegal migrants

**Comment by andika207** [comment]
> stop talking to me!  You are wasting my time. This is my last reply to you. 

I asked chatGPT for the definition of NARCISIST, FASCIST and SUPREMACIST. 
guess what the AI bot told me about you.

**Comment by andika207** [comment]
> Didnt know that, anyway dont go to derails the issues.

I'm sorry for the off-topic. @Feodor2 
just ignore and move on. 
cheers

**Comment by AstroSkipper** [comment]
> guess what the AI bot told me about you

I'm afraid not even artificial intelligence can help someone like you. [![suisjebete.gif](https://i.postimg.cc/fWrpqtyr/suisjebete.gif)](https://postimg.cc/3W2tdwgX)

**Comment by andika207** [comment]
★_**Dear chatGPT. what's the best working anti-virus for WinXP ? Panda Dome or something else ?**_  ★
