### ISSUE TITLE
Mypal cannot longer fork Github Repositories

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#30]
Mypal 29_3 cannot longer fork NEW Github Repositories. Existing Forks can still be updated, but new Repositories cannot be forked anymore. It did work before, but now, the FORK Button (second button from top right) has no function anymore. Possibly, Github changed some Code again.
![maypal_forking_problem](https://user-images.githubusercontent.com/12776547/163341704-64fc945d-99d4-47a9-a319-b6be93bacb92.png)

![maypal_forking_problem2](https://user-images.githubusercontent.com/12776547/163356205-6d330f93-f093-414b-8b34-76f6500e7435.png)

**Comment by Feodor2** [comment]
Has forked normally, so this is something on your end.

**Comment by IP-CAM** [comment]
Github obviously fixed the Problem, it now works again as planned.
Thank you.

![github_fork](https://user-images.githubusercontent.com/12776547/163668342-a9c39ddd-840d-42c5-a4b8-ba857340497b.png)
