### ISSUE TITLE
Import old MyPal browser data

### ISSUE THREAD

**Issue by DavoGer** [Feodor2/Mypal68#300]
Import from old MyPal browser data like cookies, history, logins&passwords, formfils, preferences, permissions,.... is essential need. Now, only bookmarks import works. 
Can you do something about it?

**Comment by Feodor2** [comment]
Nothing was changed about the matter. Please specify detail what did you do and where was the error?

**Comment by DavoGer** [comment]
When click on "Import" option in Saved logins, or just option "Import from Another Browser" in File menu, get only choice for import data from Microsoft Internet Explorer (pic in attachment). No other options, no other browsers. On my system have installled (and used) Mypal 29... and Firefox 52... but none of them show as choice for import data. 
Thank you for help.
![Import](https://github.com/Feodor2/Mypal68/assets/148593513/6619338a-b61e-47e0-9aab-983284b4974c)

**Comment by Feodor2** [comment]
Sure this will not work with mypal, cannot tell about firefox52, no matter,  you to copy data manually, there are several files, also this was discussed in thouthands places.
