### ISSUE TITLE
Какята байда №1

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#301]
а наxрена в майпале вообще нужна М$-ZОG проверка каких то совместимостей?
которая сделлана явно для повышения продаж вин15
тем более когда на ХРю нам и так нужно постоянно боротсо с отменами ХРю, win32, нормального гуя...

**Comment by Feodor2** [comment]
What's happened dude?
Какая ещё провырка совметимсости?

**Comment by NS-Clone** [comment]
это которая скипает установку
если текущая версия браузера официально не поддерживаетсо М$-ZОG

**Comment by Feodor2** [comment]
Так чо случилось, какие плгины?

**Comment by jonm58** [comment]
xpinstall.signatures.required to false?

**Comment by Feodor2** [comment]
Ладно проехали, хватит делать левые темы со спамными названиями

**Comment by NS-Clone** [comment]
потом еще об шонить спотыкнусь
тему подыму

а так где искать install.rdf в новых адонах не есно...

**Comment by jonm58** [comment]
> потом еще об шонить спотыкнусь тему подыму
> 
> а так где искать install.rdf в новых адонах не есно...

lmao
xul addons?

**Comment by NS-Clone** [comment]
> Так чо случилось, какие плгины?

вот тте рас https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-basic/
вот тте два https://addons.mozilla.org/en-US/firefox/addon/browsec/

доколе? g00lag будет решать за нас
какие адоны нам ставить а какие нет
![2023-10-26_234648_](https://github.com/Feodor2/Mypal68/assets/139008911/1bcc2a23-772c-4b9a-bdf6-a79c6816a051)
![2023-10-26_234544_](https://github.com/Feodor2/Mypal68/assets/139008911/1bc306ab-74d8-4845-9664-b1758f883089)
