### ISSUE TITLE
Settings and language change

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal68#302]
Hello,

do any settings need to be changed in 68.13.4b so that it can be used crash-free on Windows XP 32-bit?

Can someone please send me the link to the description for changing the language pack. Or has it already been translated into German?

**Comment by Feodor2** [comment]
No any special settings, you may help the crash will be fixed by telling how to reproduce the crash, but if i don't reproduce it myself then you are to submit drwatson log, and only drwatson. Pictures and others things are useless shit.

About languages there is a separate thread please look there.

**Comment by NS-Clone** [comment]
> and only drwatson

а там сильно много конфиденциальной информации
которую злоумышленик может использовать чтобы похитеть ВСЕ ИМЕННО ТВОИ пароли от банковских щетов :)

**Comment by Feodor2** [comment]
Та ви шо, тогда не оптгавляйте доктора, но картинки всё гвано не надо
