### ISSUE TITLE
Podziękowanie za Mypal !!! Thanks for MyPal !!!

### ISSUE THREAD

**Issue by ziemowit1973** [Feodor2/Mypal68#303]
Witam :) 
Bardzo Ci dziękuję za przeglądarkę Mypal :) 
Używam jej z powodzeniem na Wim XP SP.3 
Wszystko działa dobrze :) 
Pozdrawiam mocno i dziękuję za pracę - obyś cały czas ją uaktualniał :)

--------------------------

Hello :)
Thank you very much for my MyPal browser :)
I use it successfully on WIM XP sp.3
Everything works well :)
Best regards and thank you for your work - May you update her all the time :)

**Comment by Feodor2** [comment]
grateful
