### ISSUE TITLE
MyPal 68.13.4 does not launch on Longhorn 4074

### ISSUE THREAD

**Issue by FlorianisonGitHub** [Feodor2/Mypal68#305]
I tried to get MyPal68 to work on Longhorn 4074, but it opens and closes for less than a second.

**Comment by jonm58** [comment]
Windows Longhorn 4074? Well, although the version number is high, the API support is around 2K3 Beta.

**Comment by FlorianisonGitHub** [comment]
Is there a workaround to get it to start and work on Longhorn 4074?

**Comment by jonm58** [comment]
> Is there a workaround to get it to start and work on Longhorn 4074?

I'm don't know

**Comment by FlorianisonGitHub** [comment]
Actually, it works now! If you patch it with Xompie, it will work!

**Comment by p1glynlol** [comment]
> I found a workaround: If you patch it with Xompie, it will work on Longhorn 4074! Result: ![Longhorn 4074-2023-10-28-17-26-41](https://user-images.githubusercontent.com/111876654/278842912-add5e359-986b-4cb2-8b05-6c5998a57045.png) Do we think this is necessary?

That's good, does it work on Firefox 52/53?

**Comment by FlorianisonGitHub** [comment]
Firefox 47+ and Chrome 26+ doesn't work on Longhorn 4074 even if I patched it with XomPie Patcher, despite getting MyPal 68 to work.

**Comment by FlorianisonGitHub** [comment]
Alternatively, you can use the Application Compatibility Launcher from Windows 2000 UURollup package to get MyPal to work on Longhorn 4074.

**Comment by FlorianisonGitHub** [comment]
I got good news! Firefox versions up to 49 can run on Longhorn 4074 (if you use the Application Compatibility Launcher).

**Comment by unattendedplayer** [comment]
It never promised compatibility for beta versions of Windows, so there's no point to create an issue for that.

**Comment by youself64github** [comment]
How to do Application Compatibility Launcher on Longhorn 4074 for Mypal68?

**Comment by FlorianisonGitHub** [comment]
> How to do Application Compatibility Launcher on Longhorn 4074 for Mypal68?

Application Compatibility Launcher is from "Windows2000-UURollup-v11-d20141130-x86-ENU". You can get it the following files:
"reg.exe" and "AppComp.cmd". All you need is 2 files in a folder to get it to work. Once done, it is functional.

Drag and Drop "mypal.exe" from MyPal 68, and then hit enter, and it will open. After that, type y and hit enter to save settings, and then you're done!
