### ISSUE TITLE
Make Mypal portable?

### ISSUE THREAD

**Issue by Mypalgithub** [Feodor2/Mypal68#308]
I would like to make Mypal portable.
i.e all the files, history, logins, passwords should be in a folder on an usb drive, not in the windows user folder.
How can we do this?

**Comment by Feodor2** [comment]
https://github.com/Feodor2/Mypal68/wiki/Portable#advanced-stuff

**Comment by Mypalgithub** [comment]
Thank you for that.
We are still missing some steps in the process.
We have set up a new profile and deleted the others referring to C: drive.
However when we restart Mypal it has reproduced the old C: drive files and lost the new usb profile.
We have to go through and set up the new profile each time.
What do we need to do to stop the old c: drive profiles returning?

**Comment by Feodor2** [comment]
With portable mode the profile is inside the browser folder always.  Did you read the link above and actually put the empty file to enable portable?

**Comment by Mypalgithub** [comment]
Yes. We copied the profile files from c: to the usb drive.
We found a messy way to stop the c: files loading and to force the usb drive files to be used: We made the c: files all read only.
It is not 100% because we still have to a "click restore session" tabs message each time.
There must be some way to stop Mypal reading and trying to write to C: drive?

**Comment by Feodor2** [comment]
So you are want to go some hard way, okey then do whatever you want, but do not confuse others.
portable works good.

**Comment by Mypalgithub** [comment]
Definately don't want to go "some hard way". We tried to find a way to make it work. 
Simply want to use Mypal as portable.
As noted, we have done exactly as described in your references, but it still opens the c: drive files, not the usb files. There appear to be missing some steps in the process described in https://github.com/Feodor2/Mypal68/wiki/Portable#advanced-stuff.
Simply want to use Mypal as portable.
How do we make Mypal portable?

**Comment by Feodor2** [comment]
**Inside the browser folder is another folder named browser look there files _pmprt.mod_ or _pmundprt.mod_ they are empty, no matter what inside, only names.**
Did you put there a file?

**Comment by Mypalgithub** [comment]
We do not have files pmprt.mod or pmundprt.mod anywhere in browser folder.
We have profile files in h:\Portable\Mypal\browser\AppData\Local\Mypal68\Profiles\umcfnrbj.default\
We have a default profile in about:profiles Root Directory	H:\Portable\Mypal3\browser\AppData\Local\Mypal68\Profiles\umcfnrbj.default
However the program will always start using files in the c:\Users\w10\AppData\Roaming\Mypal68\Profiles\bej6f6q6.default-default\ folder unless we make them read only, which is not a satisfactory solution.
How do we make Mypal portable?

**Comment by Feodor2** [comment]
>We do not have files pmprt.mod or pmundprt.mod

Of course, did you think it will be self-generated, or may be you don't know how to create the file?

**Comment by Mypalgithub** [comment]
Apparently we do not know how to create them.
We put a empty file called pmundprt.mod in the Mypal\browser folder but 
it did not make any difference.
We put 2 empty files called pmprt.mod and pmundprt.mod just in case, but 
that did not help either.
How do we create the required files?

P.S. Have you heard of people being hit by the "Tray Status" downgrade? 
microsoft call it an upgrade but it has shut lots of systems down, 
including one of our computers.

**Comment by Feodor2** [comment]
Then nothing to do of me, while you may yourself learn about computers
Or bring someone who knows how tor fix your computers and make portable.
