### ISSUE TITLE
Flight Radar

### ISSUE THREAD

**Issue by ibmaxx82** [Feodor2/Mypal68#309]
Flight Tracker no work https://www.flightradar24.com/-36.79,-185.42/7

![Clipboard04](https://github.com/Feodor2/Mypal68/assets/116393960/580e1dbf-aad5-4ce0-a4ae-1f6f380cc122)

**Comment by IP-CAM** [comment]
Works well with Mypal 68.13.5b
![flight](https://github.com/Feodor2/Mypal68/assets/12776547/e71cd648-2026-46b3-9b29-e4c808057d6d)

**Comment by unattendedplayer** [comment]
Open about:support and look at WebGL1.

**Comment by ibmaxx82** [comment]
Using 68.13.5b and about:support shows this - 

![Clipboard02](https://github.com/Feodor2/Mypal68/assets/116393960/f0af9ee2-8ce7-4071-9c13-24b70417c741)

**Comment by Feodor2** [comment]
This is poor videocard or bad driver, so what videocard is?

**Comment by Pikse** [comment]
For me WebGL1 fails in latest Mypal but not in FF52. Maybe Mypal (FF68) has unnecessarily restrictive hardware blacklist?

**Comment by ibmaxx82** [comment]
Adapter detail as here - 

![Clipboard02](https://github.com/Feodor2/Mypal68/assets/116393960/d9753ee6-da6e-49e0-a818-531eb35332f7)

**Comment by Feodor2** [comment]
I think its poor, nothing to do.
You may check it on fox43 for webgl, once i am going to take that old version into mypal68

**Comment by RamonUnch** [comment]
for me WebGL1 works slow but fine with my very poor graphic card: Mobile Intel(R) 965 Express Chipset Familly
however it is indeed newer than the Radeon x300.

**Comment by zanud** [comment]
@RamonUnch:
> for me WebGL1 works slow but fine with my very poor graphic card: Mobile Intel(R) 965 Express Chipset Familly

On my notebook with the same graphic card WebGKL is not available:
![WebGL](https://github.com/Feodor2/Mypal68/assets/76625744/f50a9413-6b68-4a83-a288-405ba61b735b)

**Comment by zanud** [comment]
@RamonUnch 
> for me WebGL1 works slow but fine with my very poor graphic card: Mobile Intel(R) 965 Express Chipset Familly

On my notebook with the same graphic card WebGL1 works too:
![WebGL](https://github.com/Feodor2/Mypal68/assets/76625744/a8f8374a-061e-4541-8051-b44ec925dc72)

_"Initializing WebGL backbuffer failed"_ looks like an explanation why it is slow. And definitely this is a graphic card driver failing.

**Comment by ibmaxx82** [comment]
Works OK on secondary computer running Intel(R) HD Graphics Family
Reinstalling new driver for Radeon X300 did nothing so poor card for sure.

**Comment by JeanPaulLucien** [comment]
> Adapter detail as here -

Radeon X300 is OpenGL 2.0 graphic card.
EGL 3+ is inside Mypal 68.

**Comment by JeanPaulLucien** [comment]
> for me WebGL1 works slow but fine with my very poor graphic card: Mobile Intel(R) 965 Express Chipset Familly

Hmm...

> Indeed, the 965GM graphics controller supports OpenGL 1.5

**Comment by JeanPaulLucien** [comment]
Guys, see and complete settings as in #376 described, then check `about:support`. Then fill new issue with.
