### ISSUE TITLE
html5test

### ISSUE THREAD

**Issue by vertaa** [Feodor2/Mypal68#310]
HTML 5 test does not complete. it is stuck on the checking screen.

https://html5test.com/

**Comment by Stepman123** [comment]
https://html5test.opensuse.org/

**Comment by niutech** [comment]
I've [updated HTML5Test](https://github.com/niutech/html5test), check out https://html5test.co.

**Comment by JimMP68User** [comment]
> I've [updated HTML5Test](https://github.com/niutech/html5test), check out https://html5test.co.

Did you misspell the link address? Is it ".co" or ".com"?

**Comment by niutech** [comment]
html5test.com is the original one, not updated for 5 years. [html5test.co](https://html5test.co) is my updated version (max 594 points).
