### ISSUE TITLE
Google as possible search engine and search on URL bar not working

### ISSUE THREAD

**Issue by Edw590** [Feodor2/Mypal68#311]
Hi. First of all thank you so much for this browser. I'm using it on an old Windows 7 computers (low RAM, slower CPU, no hardware acceleration) and it's *perfect*. So thank you so much!!!

- But could you please add Google as a possible search engine? I've tried to add it and it doesn't give me the option.
- And also could you please fix the URL bar to accept search engine searches? I input something into it and it thinks it's a URL and never a search.

Thank you again!

**Comment by RamonUnch** [comment]
> And also could you please fix the URL bar to accept search engine searches? I input something into it and it thinks it's a URL and never a search.

Look at the pinned Issue #101

**Comment by egrabrych** [comment]
>     * But could you please add Google as a possible search engine? I've tried to add it and it doesn't give me the option.
  
Try the add-on **Google (Default) 20150907** by mo0kid :  [https://addons.thunderbird.net/en-us/firefox/addon/google-default-1/?src=userprofile](url)

**Comment by Edw590** [comment]
Thank you! Then I think I have no more issues about this. I'll close the Issue. Thank you again to both!
