### ISSUE TITLE
Google Maps 3D not supported

### ISSUE THREAD

**Issue by LuckyTil** [Feodor2/Mypal68#312]
MyPal 68.13.5b

[Google Maps Globe Mode](https://support.google.com/maps/answer/3031966) not available.

"Globe mode" checkbox is gray.

[WebGL test](https://get.webgl.org/webgl2/) passed successfully.

Hardware Acceleration enabled.
WebGL2 enabled.

**Comment by IP-CAM** [comment]
MyPal 68.13.6b

[Google Maps Globe Mode](https://support.google.com/maps/answer/3031966) is available.

![google-maps](https://github.com/Feodor2/Mypal68/assets/12776547/ee8ccc17-729d-476a-9138-234d8c13cb56)

**Comment by LuckyTil** [comment]
> MyPal 68.13.6b
> 
> [Google Maps Globe Mode](https://support.google.com/maps/answer/3031966) is available.

Where can I download the Windows version 68.13.6b?

**Comment by LuckyTil** [comment]
FYI, Globe mode is not Satellite mode
![image](https://github.com/Feodor2/Mypal68/assets/50541759/03930a12-371b-40ae-ba22-c73ca32e50c2)

**Comment by LuckyTil** [comment]
> The official Download Links are NOT correct, they include 650+MB of space, better download it here:
> http://www.bigmax.ch/mypal-68.13.6.zip

Forbidden.

**Comment by IP-CAM** [comment]
Sorry, the download link just mentioned a minute ago does not work either, it's also a 655 MegaByte download. So, I removed my last post again. Get in touch with Feodor2, to get a working download link.

**Comment by unattendedplayer** [comment]
Try changing the useragent of maps.google.com to something newer.
Visit: about:config
Right click, select New value and String
Name: `general.useragent.override.maps.google.com`
Value: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.15) Gecko/20100101 Firefox/102.15`

**Comment by LuckyTil** [comment]
@unattendedplayer ,

> Try changing the useragent of maps.google.com to something newer. Visit: about:config Right click, select New value and String Name: `general.useragent.override.maps.google.com` Value: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.15) Gecko/20100101 Firefox/102.15`

I use

general.useragent.override = `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.15) Gecko/20100101 Firefox/102.15`

User-Agent header sets fine.

But Globe Mode still not available. :(

**Comment by LuckyTil** [comment]
I try FireFox Portable 119.0, 32 bit

Under this browser, Globe Mode is available.

**Comment by LuckyTil** [comment]
Not fixed on 68.13.7b 32bit :(

Quick check link:
https://www.google.com/maps?force=webgl
