### ISSUE TITLE
Facebook crash; Issue Tab crash 

### ISSUE THREAD

**Issue by aberyst** [Feodor2/Mypal68#313]
I'm using Windows Vista and downloaded the new Mypal 68.13.1 browser. Works great on all websites except Facebook. Crashes instantly on logging in. Tab crash and windows cannot find a solution.

**Comment by RamonUnch** [comment]
I suggest you use the latest build : MyPal68.13.5b, the old 68.13.1 is indeed unstable.

https://github.com/Feodor2/Mypal68/releases/tag/68.13.5b

You could also wait a couple of days and there will probably be again a new bug-fix version of MyPal68.

**Comment by Feodor2** [comment]
And not to do duplicate reports
