### ISSUE TITLE
Testing versions 68.13.7b 64 bits : "Couldn't load XPCOM"

### ISSUE THREAD

**Issue by enigma131** [Feodor2/Mypal68#314]
Under Virtualbox 6.1.22:
Version 32 bits with Xp Pro 32 bits : OK
Version 64 bits with Xp 64 Bits (Pro) : don't lunch, get message : "Couldn't load XPCOM"
Version 32 bits with Xp Mediacenter : crash at lunch (in kernel32.exe), no special message in file 7291_appcompat.txt
All 3 Xps are registered, and with original dlls.

**Comment by bluedragon-cairo** [comment]
For me it works in XP Media Center 2005.

Will have to check if it works in Media Center 2004 in my another computer

**Comment by rafm5** [comment]
Version x32 | 2k3: OK
Version x64 |2k3: Couldn't load XPCOM

**Comment by enigma131** [comment]
X32 problem solved by adding standard Srvice pack 3 over MediaCenter edition.
X64 Edition problem remains

**Comment by rafm5** [comment]
Same issue appears with mypal-68.13.8.en-us.win64

**Comment by Gravarty** [comment]
> Same issue appears with mypal-68.13.8.en-us.win64

Yep, latest version of MyPal still crashes with this error mesage, so i don't quite understand why this thread was closed.. Maybe this bug reappeared in a newer version of MyPal?
