### ISSUE TITLE
Warning: Unresponsive script.

### ISSUE THREAD

**Issue by vertaa** [Feodor2/Mypal68#317]
When I hover the mouse over a picture to view it, I keep getting the following popups.

![image](https://github.com/Feodor2/Mypal68/assets/67488797/bfebebf6-9048-4bfd-a065-604896f656ec)

**Comment by NS-Clone** [comment]
до в новой версии появилась систематически (ну или можот сайтики дообновлялись)
а еще 68.13.7 явно на порядок чаще сыпет access violation-ами

**Comment by NS-Clone** [comment]
ну а седня вернулась 100% загрузка проца (и лечиттссо только перезапском)
на mypal-е в этом году такого не было ни разу

**Comment by rafm5** [comment]
Yes, very common on Amazon. Ticking the 'do not ask again' box does not solve the popup.

**Comment by NS-Clone** [comment]
так
еще один виснущий гофносайтек оказалсо виснущим и на предыдущей версии


из новых возможно глюков субъективно браузер стал падать не так как раньше
раньше предлагал востановить вкладки без перезапуска
щас востановление вкладок после ошибки я не вижу вообще (просто валитсо после Ок)
но само "ваши вкладки напипнулись" пару раз выскакивало вообще без каких либо сообщений
чего в прошлых версиях я не видел
