### ISSUE TITLE
Random crash with MyPal68.13.7b when loading a reddit page

### ISSUE THREAD

**Issue by RamonUnch** [Feodor2/Mypal68#318]
I got a random crash when trying to load a reddit page:
The link was this one: https://www.reddit.com/r/uBlockOrigin/comments/17tm9rp/comment/k9i62zu/?utm_source=reddit&utm_medium=usertext&utm_name=youtube&utm_content=t1_ka0g6rz
Only the tab crashed and it did not affect my session so it is not a big deal. 
I was not able to reproduce the bug occurred only once to me for now.

I thought I would still give the drwtsn32.log file. Feel free to close if you think it is pointless.

OS: Windows Server2003 Windows NT 5.2.3790
[mypal68.13.7b-drwtsn32.log.zip](https://github.com/Feodor2/Mypal68/files/13427101/mypal68.13.7b-drwtsn32.log.zip)

**Comment by unattendedplayer** [comment]
Workaround: use old.reddit.com since Mypal is unstable with the new version.

**Comment by JimMP68User** [comment]
> I got a random crash when trying to load a reddit page:

Hmmmm. That reddit link loaded okay for me. Using 13.7b here, 32 bit Xp Pro SP3.
