### ISSUE TITLE
1080p youtube movie in one process mode with software decoding

### ISSUE THREAD

**Issue by mserafym** [Feodor2/Mypal68#319]
Mypal 68.13.7b
uBlock Origin + h264ify extensions

Hardware:
P:         Pentium Dual-Core E5800 3.2GHz
MB:      ASRock 775i65G R2.0 with last bios + microcodes updates 2015 year (0E) for 45nm 1067A processors
RAM:    2X1Gb DDR400 Samsung (3-3-3-8)
V:         Gigabyte ATI Radeon 9600 Pro 128Mb DDR, AGP
LAN:     3Com 905C-TX-M
S:          Creative Audigy 1 SB0160
SSD:     Industrial pSLC 128Gb SATA1 via SATA to IDE adapter
MON:  1280x1024x32

Original Windows XP SP3 Professional + simplix updates to 2019 year + last DirectX 9.0C + core certs updates

In one process mode youtube 1080p30fps H264 movie load CPU  to 100% (2 cores) and play with many dropped frames (window mode and full screen mode)!
In multiply process mode the same movie play nice without any dropped frames with cpu load to 40-80%

The same test for 720p30fps H264 movie doesn't has any problems with play in two modes and play nice without any dropped frames! (CPU load 20-40%)

**Comment by unattendedplayer** [comment]
It's a known problem with the browsers. Try playing them in local media player. You can use [YTSource](https://www.free-codecs.com/3dyd-youtube-source_download.htm).

**Comment by mserafym** [comment]
@unattendedplayer thanx, i know about this solution, but... there is a bug. My hardware old, but play movies in 1080p normaly.
@Feodor2 , будь-ласка, зробіть з цим що-небудь! Дуже дякую Вам!

**Comment by Feodor2** [comment]
Thas not a bug, try enable direct9 by **layers.allow-d3d9-fallback**, direct9 became more stable but another errors  still possible.
Also you may compare how other browsers play 1080 without direct9
