### ISSUE TITLE
Issue When if i try to go to youtube and watch video after change media.ffmpeg.hwacc_type to 4 and even it crash when i try something in google hangouts screenshare in mypal quantum browser of winxp x64 with media.ffmpeg.hwacc_type 0

### ISSUE THREAD

**Issue by MWF2** [Feodor2/Mypal68#32]
when after i put media.ffmpeg.hwacc_type to 4 in mypal quantum running windows xp x64, when i go to youtube, and try to watch video for test, it crash like it closed itself

https://user-images.githubusercontent.com/74994144/163685576-d5701ee7-7ce1-41f9-ad6e-53d22a91f354.mp4

**Comment by MWF2** [comment]
![glitch when if i screenshare on mypal quantum window but not entire screen](https://user-images.githubusercontent.com/74994144/163685916-64465bfc-49dc-41ab-a38b-c5b75becea31.PNG)
glitch when if i use screenshare 1 window in mypal quantum but not entire screen in google hangouts, and slow when if i use entire screen in meet and hangouts when i already use graphics driver for xp x64

**Comment by NoNameNeeded2** [comment]
The only setting I could find is this one:
media.ffmpeg.low-latency.enabled

The setting you describe doesn't seem to exist.

**Comment by Anbima** [comment]
Youtube-Video with XP32
media.ffmpeg.hwacc_type:0 = no crash
media.ffmpeg.hwacc_type:2 = no crash
media.ffmpeg.hwacc_type:4 = crash

**Comment by Anbima** [comment]
@NoNameNeeded2
Install new update 68.12.2b:
https://github.com/Feodor2/Mypal68/releases/tag/68.12.2b

**Comment by NoNameNeeded2** [comment]
> 

Oh, there is an update...

**Comment by Feodor2** [comment]
2 - cuda - means for nvida videocards
4 - likely for all direct9 cards
AND it will used only for play VP8-9 H264 an AV1 videos, but for av1 there separate decoder so VP8-9 and H264 only
So what videocard there you get crash?

**Comment by Anbima** [comment]
Crash with media.ffmpeg.hwacc_type:4 on nvidia GeForce 7300 GT

**Comment by MWF2** [comment]
mine it crash with media.ffmpeg.hwacc_type: 4 on intel hd graphics 6.14.10.5394 x64

**Comment by pachuco** [comment]
I get instacrash on yt with media.ffmpeg.hwacc_type of either 2 or 4.
Specs:
- winxp SP3 x86
- GPU: NVIDIA Quadro 600

Also, multiprocessing disabled.

**Comment by MWF2** [comment]
![now call hangouts, google meet is not working anymore, even with multiprocess is true and false](https://user-images.githubusercontent.com/74994144/170773805-09efab9d-2dea-4e90-a809-f86531a5974d.png)
now hangouts call, google meet call is no longer works anymore, even with multiprocess set to true and false in both, vista x64 and xp x64

**Comment by foxtrot-99** [comment]
for hangouts, feodor told me to set **media.peerconnection.enabled;true** in about:config
