### ISSUE TITLE
Mypal downgrade подключение более нового профиля

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#320]
чагочаго????
![2023-11-24_141042](https://github.com/Feodor2/Mypal68/assets/139008911/8193a94e-6379-439f-962e-0e94c88551f7)

ладно я понимаю предупредили
так оно тупо не запускаетсо
во какая безопасность ваших банковских щетов

неее так не пойдет
не надо и тут разводить плейстейшны

(это при переезде с 68.13.7 на 68.13.5)

**Comment by JimMP68User** [comment]
??

Will see that message if old Mypal version tries to access a profile newer version of Mypal now points to.

Can go to "about:profiles" (put in browser address bar) and re-select an old or or new profile folder?

**Comment by Feodor2** [comment]
Не делай идиотские названия темы - вроди просил.
Новый профиль не пускает файл compatibility.ini просто удали

**Comment by Feodor2** [comment]
There is a file inside you profile **compatibility.ini** - you are to delete it, than you can
