### ISSUE TITLE
Font glitch

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#321]
Старое issue по моему сдохло

вот опять
по моему все тоже но с другим? шрифтом

![2023-11-24_143024](https://github.com/Feodor2/Mypal68/assets/139008911/f2fe2201-7b91-48ce-b3db-3025cebd43b9)
![2023-11-24_143236](https://github.com/Feodor2/Mypal68/assets/139008911/fb199118-05b5-45cd-b341-dfee352b76af)

Lucidag.ttf
CRC32: 9ff174f5
MD5: c1c8bda7336c62e03c3e485f717781e2
SHA-1: 20f3d74a29ac79bc7d3f4bdb0347483413a4cb6a
SHA-256: 78d58e0050593266e258415389c30587cedebcdb5e6d782e95e99ac3c3ff2417

**Comment by NS-Clone** [comment]
кстате в папке браузера есть fonts
от туда случаем не будут братсо шрифты с большим приоритетом?
можот туда можно сразу положить гарантированно рабочие на mypal-е?

**Comment by Feodor2** [comment]
https://github.com/Feodor2/Mypal/issues/14#issuecomment-719821537
