### ISSUE TITLE
Mypal Korean support?

### ISSUE THREAD

**Issue by TK50P** [Feodor2/Mypal68#322]
Hello I am using mypal well
but I wish if you can add korean support (and other language), can you add MUIs on next release?

**Comment by RamonUnch** [comment]
I suggest you have a look at #203.

**Comment by unattendedplayer** [comment]
Isn't it kinda weird even custom Chromium forks have multilingual support out of the box? (Except some heavily modified trash like 360Chrome)

**Comment by bluedragon-cairo** [comment]
Mypal 68.12 supported Firefox language packs... Maybe because 68.13 has some Firefox 78 stuff making it incompatible
