### ISSUE TITLE
[Question] Creating a toolbar using addon

### ISSUE THREAD

**Issue by bluedragon-cairo** [Feodor2/Mypal68#323]
Is it possible to create a toolbar like in Mypal 28? In Mypal 28 it was possible to create a toolbar in Customise Toolbars screen.

I'm trying to make an extension that restores a proper status bar with progress meter and JavaScript `window.status = '...';` work...

**Comment by Feodor2** [comment]
Not ever possible as it was in Mypal 28, though may be possible by other ways like extensions.
