### ISSUE TITLE
Some sites do not load properly on XP SP3

### ISSUE THREAD

**Issue by LuckyTil** [Feodor2/Mypal68#324]
68.13.7b 32bit

Site ​https://www.livelib.ru/ not loaded properly on Windows XP SP3 (x86).

Console output:

```
Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_quickRestart” browser.xul
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul
```

But loads OK on Windows 11 (x64).

See
![image](https://github.com/Feodor2/Mypal68/assets/50541759/2554d9f9-1e32-4f00-9255-ea9269ad3d69)

**Comment by RamonUnch** [comment]
It seems that https://www.livelib.ru/ loads a lot of unencripted data from an encrypted page (mixed content)
By default MyPal68 does not like that.

You can click on the padlock before the https:// then you will see:
![Image2](https://github.com/Feodor2/Mypal68/assets/74856804/8ffad87a-5b2f-4d40-bfee-32a8259a2ed3)

Just click on Disable Protection for now and you will see the page displays properly.

**Comment by jonm58** [comment]
If there is https only mode this would be no problem.

**Comment by LuckyTil** [comment]
Thanx!
