### ISSUE TITLE
[Suggestion] Change Name/Icon?

### ISSUE THREAD

**Issue by IPeluchito** [Feodor2/Mypal68#325]
Now that Firefox is used as a base, is it possible that the browser name can be changed to Myfox or something similar?
Personally, I use Basilisk with the Firefox 2019 icon (the one that doesn't have the image of the fox and the central sphere) and it looks great!!!

Thank you for your effort on such a great project!!!!

**Comment by Feodor2** [comment]
However no change here, the name and icon was settled long ago.

**Comment by bluedragon-cairo** [comment]
If you want it only in your computer then you can modify omni.ja (to modify it, unzip and change the files and re-zip it using 7-Zip and setting compression level to Store(0) )
