### ISSUE TITLE
"Failed to serialize referrerInfo"

### ISSUE THREAD

**Issue by LuckyTil** [Feodor2/Mypal68#329]
Page ​http://yun.complife.info/1ar.htm not load properly on Windows XP SP3 (x86).

Console output:
E10SUtils: Failed to serialize referrerInfo 'BBoSnxDOS9qmDeAnom1e0AAAAAAAAAAAwAAAAAAAAEYBAAAAIWh0dHBzOi8veXVuLmNvbXBsaWZlLmluZm8vMWFyLmh0bQAAAAABAQAAACFodHRwczovL3l1bi5jb21wbGlmZS5pbmZvLzFhci5odG0BAQ==' [Exception... "Could not convert JavaScript argument arg 0 [nsISerializationHelper.serializeToString]" nsresult: "0x80570009 (NS_ERROR_XPC_BAD_CONVERT_JS)" location: "JS frame :: resource://gre/modules/E10SUtils.jsm :: serializeReferrerInfo :: line 706" data: no]

Page https://yun.complife.info/1ar.htm not load properly either.

But loads OK on Windows 11 (x64).

**Comment by LuckyTil** [comment]
And loads OK on XP SP3 under FireFox 52.9 and Mypal 29.3.0 (Pale Moon).

**Comment by JeanPaulLucien** [comment]
Was not reproduced in Mypal 68.13.4b

**Comment by LuckyTil** [comment]
I tried in 68.13.7b
