### ISSUE TITLE
broken page...

### ISSUE THREAD

**Issue by leksnet** [Feodor2/Mypal68#330]
.
https://www.austinregionalclinic.com/

.

**Comment by JeanPaulLucien** [comment]
Screenshot?

**Comment by leksnet** [comment]
Attached, and here is another...

https://www.timeanddate.com/worldclock/timezone/zulu

<https://1drv.ms/i/s!Ai9OW6t_HadrabTXtkszKAi9O1o>
[https://x3wwqw.dm.files.1drv.com/y4miRPusUflwgyVGBIraqsxqNTt8gNF_MAJjnO0kFklBXxI2xNurW93VpCY-knPLAWKn0jdON8zd8NBiJpZYnKvfCyuw4MEcZz0mgynLZ1Yd67RZhOSk_dGIRv4O0yBEyqzwpB3002LkvPF03eAOSPUD33QWqZ_XyOLoQGQvxuWIifYmO4u26mpz5Yz80ADg2Fv3FU7dyWgyOr3RMks82762g?width=200&height=150&cropmode=center]
[https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]sshot2.jpg

[https://www.timeanddate.com/scripts/cityog.php?title=Current%20Local%20Time%20in&city=%E2%80%9CZulu%E2%80%9D%20Military%20Time&country=Time%20Zone&image=generic]<https://www.timeanddate.com/worldclock/timezone/zulu>
Current “Zulu” Military Time<https://www.timeanddate.com/worldclock/timezone/zulu>
Current local time in “Zulu” Military Time. See a clock with the accurate time and find out where it is observed.
www.timeanddate.com

________________________________
