### ISSUE TITLE
Feature request: Auto-update

### ISSUE THREAD

**Issue by palikacska** [Feodor2/Mypal68#334]
Could you implement an auto update feature and create an installer?

Like it was for the original (now discontinued) Mypal.

It would be very useful.

**Comment by NS-Clone** [comment]
get the win15 out with auto update

**Comment by palikacska** [comment]
@NS-Clone What do you mean by win15? I was talking about that it would be a great feature if the browser updated itself. Itself, nothing else. This is unrelated to Windows updates.

**Comment by JimMP68User** [comment]
> Could you implement an auto update feature and create an installer?
> 
> Like it was for the original (now discontinued) Mypal.
> 
> It would be very useful.

Too much to do: 1) copy 2) unzip 3) re-point to old bookmarg, password etc dir
Too simple??

**Comment by NS-Clone** [comment]
> Too much to do: 1) copy 2) unzip

2) unzip with replace
thats all
