### ISSUE TITLE
changing profile location

### ISSUE THREAD

**Issue by jbclem** [Feodor2/Mypal68#336]
Is there a way to change the Mypal68 profile location.  I'd like to try different profiles on different versions and I don't see how to keep the profiles straight in the regular Documents and Settings location.  Can I put the Profile folder in the same folder where I've installed a certain Mypal68 version...and have it read when I start up that version of Mypal68?

**Comment by JimMP68User** [comment]
> Mypal68 profile location.

First, have you read this?

"_Profiles - Where Firefox stores your bookmarks, passwords and other user data_"

https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data

**Comment by Feodor2** [comment]
There are several ways, easy one is to drop an empty file inside (you are to make it by yourself).
look https://github.com/Feodor2/Mypal68/wiki/Portable#advanced-stuff
