### ISSUE TITLE
Странная утечка памяти?

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#341]
Последние n дней ВНЕЗАПНО систематически утекает память
на 2-х браузерах 68.13.7 и 68.13.5
(на  68.13.5 практически свежий профиль)

ниче не обновлял не ставил адонов
![141637668](https://github.com/Feodor2/Mypal68/assets/139008911/667489d1-2b8c-4ea9-9637-9c4062f42e89)

из включенных адонов только browsec и новый DTA 

в том числе утекание наблюдаетсо и на 1-й открытой вкладке манагера DTA
без открывания вкладок о_О

съев гига 3 браузер крашитсо

68.13.5  - 1 легкая вкладка и загрузка 100М файла а потом закрытие браузера
![2023-12-23_233346](https://github.com/Feodor2/Mypal68/assets/139008911/75b4285d-cde8-4249-8912-10323f93084b)

бидабида
шоподелать?
всё жо месяцами работало
это у меня одного?

**Comment by NS-Clone** [comment]
68.13.7 - востановил сессию на 500 вкладок
открыл вкладку с гитхабом
и написал пост выше
![2023-12-23_235112](https://github.com/Feodor2/Mypal68/assets/139008911/24c5df08-e5e1-4107-9572-5e415c522aad)

**Comment by Feodor2** [comment]
Чо с бруском всегда было нормально?
А как же безопаснсть банкового счота?
Насколько знаю это его анальные зонды такое делают - попробуй замени брусек на другое, например veepen 2.0.7 там хотябы нет анального зонда от гугела.

**Comment by NS-Clone** [comment]
>Чо с бруском всегда было нормально?

со времен мозиловского геко фаирфокса

щас как раз его отключил на предудыщей версии майпала
и целый день не улетал
(а так до он последнее время зачастил кидать рекламу "купикупикупи про со скидкай)

> Насколько знаю это его анальные зонды такое делают - попробуй замени брусек на другое, 
> например veepen 2.0.7 там хотябы нет анального зонда от гугела.
ну в свое время это осталсо "последний" рабочий на "старом" фаирфоксе

**Comment by NS-Clone** [comment]
до "новый" mypal тоже вроде попустило без бровсеков
