### ISSUE TITLE
"View - Text Encoding" menu item not available

### ISSUE THREAD

**Issue by LuckyTil** [Feodor2/Mypal68#342]
mypal 68.13.7

Menu item "View - Text Encoding" not available on most sites, as outlook.com, wikipedia.org, etc.
But menu item available in FireFox 52.9 on same sites.

**Comment by Feodor2** [comment]
This come from the beginning of poor fixing language things for winxp.
And this is almost unneeded thing at all, i am not going to look at this in foreseeable future.

**Comment by NS-Clone** [comment]
> And this is almost unneeded thing at all

ващета нет
иногда автоопределение таки косячит
и выдает кракозябры
...правда это в основном на старых или кривых сайтах
