### ISSUE TITLE
website not rendering properly

### ISSUE THREAD

**Issue by jbclem** [Feodor2/Mypal68#344]
This website: https://feeds.feedburner.com/pri/theworld
renders correctly when I use Firefox 52.9 ESR, and also Serpent 52.  When I open it using Mypal 68.13.7b it shows  a jumble of text with no formatting.

I'll try to add to attachments(screenshots) showing exactly what the problem is...but I don't see how to do this so I'm trying the "paste, drop, or click to add files."  If that doesn't work, just go to the link I listed above and it's easy to see what happens.  Using Mypal 68.12b gives an error message about XML, using Mypal 68.13.7b just shows the page without formatting. 

![RSS page rendered properly on Firefox 52 ESR](https://github.com/Feodor2/Mypal68/assets/7868249/b49809a8-5f81-490d-afb3-b6708985c0ec)
![RSS page not rendered properly on Mypal 68 13 7b](https://github.com/Feodor2/Mypal68/assets/7868249/6485c781-b9b1-41f1-813f-d8c415981ab5)

**Comment by jonm58** [comment]
> 该网站： [ feeds.feedburner.com/pri/theworld ](https://feeds.feedburner.com/pri/theworld) 当我使用 Firefox 52.9 ESR 和 Serpent 52 时，它可以正确呈现。当我使用 Mypal 68.13.7b 打开它时，它会显示一堆没有格式的文本。
> 
> 我将尝试添加到附件（屏幕截图）以准确显示问题所在......但我不知道如何执行此操作，因此我尝试“粘贴、删除或单击添加文件”。 如果这不起作用，只需转到我上面列出的链接，就可以很容易地看到会发生什么。 使用 Mypal 68.12b 会给出有关 XML 的错误消息，使用 Mypal 68.13.7b 仅显示未格式化的页面。
> 
> ![RSS 页面在 Firefox 52 ESR 上正确呈现](https://private-user-images.githubusercontent.com/7868249/292967833-b49809a8-5f81-490d-afb3-b6708985c0ec.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzA2NDEsIm5iZiI6MTcwMzY3MDM0MSwicGF0aCI6Ii83ODY4MjQ5LzI5Mjk2NzgzMy1iNDk4MDlhOC01ZjgxLTQ5MGQtYWZiMy1iNjcwODk4NWMwZWMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMDk0NTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg4N2ZmODJiNWFhZTg5YjM4YTJmZmQwNmZkNGIwYmE5NzY5YzZhNzYyODFlNzRlZWU5ZmE5MmQzZTFmMmJiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t7YxPfOkiGI_hZOqsIOqR3z2WmLbjfSvGto8z5V17mM) ![RSS 页面未在 Mypal 68 13 7b 上正确呈现](https://private-user-images.githubusercontent.com/7868249/292967836-6485c781-b9b1-41f1-813f-d8c415981ab5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzA2NDEsIm5iZiI6MTcwMzY3MDM0MSwicGF0aCI6Ii83ODY4MjQ5LzI5Mjk2NzgzNi02NDg1Yzc4MS1iOWIxLTQxZjEtODEzZi1kOGM0MTU5ODFhYjUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMDk0NTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWZkMzFiMGJjNTZmN2Y2YWFjMjJmOWUyODhkMDQ2YmNiZDAyNTBjZDE3MWVlNmMyZDkyZmQwZGQ5M2UxNmIyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LuUauU9Pj0KedjJqstrDtQ0cr2LaS1Gw8HX3PyeqZqQ)

this is rss,dude
Firefox 57+ kill rss

**Comment by IP-CAM** [comment]
Well, Mypal does not work as planned on several other regular Websites, I already made a posting on such a while ago. I had to move on to Serpent, to have those problems fixed.

**Comment by jonm58** [comment]
use Feed Reader addons

**Comment by NS-Clone** [comment]
> This website: https://feeds.feedburner.com/pri/theworld renders correctly when I use Firefox 52.9 ESR, and also Serpent 52. When I open it using Mypal 68.13.7b it shows a jumble of text with no formatting.
> 
> I'll try to add to attachments(screenshots) showing exactly what the problem is...but I don't see how to do this so I'm trying the "paste, drop, or click to add files." If that doesn't work, just go to the link I listed above and it's easy to see what happens. Using Mypal 68.12b gives an error message about XML, using Mypal 68.13.7b just shows the page without formatting.
> 
> ![RSS page rendered properly on Firefox 52 ESR](https://private-user-images.githubusercontent.com/7868249/292967833-b49809a8-5f81-490d-afb3-b6708985c0ec.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzU2NTgsIm5iZiI6MTcwNzgzNTM1OCwicGF0aCI6Ii83ODY4MjQ5LzI5Mjk2NzgzMy1iNDk4MDlhOC01ZjgxLTQ5MGQtYWZiMy1iNjcwODk4NWMwZWMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMTQ0MjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGY2ZGYzMzEwNTRmNWQzNzRmMDAzODQ5NGUyNjlmODc0YjhhYzBlMzVmNzgxZDU3MDQ4OTJhNDkwZjBjNDcyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.abYagZV0w4DTUhHonbDtuxuiJxkisLiIb21SustfC10) ![RSS page not rendered properly on Mypal 68 13 7b](https://private-user-images.githubusercontent.com/7868249/292967836-6485c781-b9b1-41f1-813f-d8c415981ab5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzU2NTgsIm5iZiI6MTcwNzgzNTM1OCwicGF0aCI6Ii83ODY4MjQ5LzI5Mjk2NzgzNi02NDg1Yzc4MS1iOWIxLTQxZjEtODEzZi1kOGM0MTU5ODFhYjUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMTQ0MjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDc4OTUwNzY1OTMzY2EzNGMyMDMyNWJkZjMyYThiZWIzMTVkNDAzYjgxNmUxMzc1MjY1ZjQ1NWQxNDU0MTBlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IxiyTB0yofJP_ct8eIqVMmEO_wT3scYeyjC07pfaUBA)

how to get this row tab mode?
