### ISSUE TITLE
Using developments from the future Superfox browser (based on Firefox) from the Win32ss developer

### ISSUE THREAD

**Issue by Aspire89** [Feodor2/Mypal68#345]
Здраствуйте. Будет ли браузер Mypal 68 использовать наработки из другого будущего браузера Superfox (на основе Firefox, который выйдет в 2024 году), когда тот будет поддерживать Windows 2000/2003/XP/Vista/7/8/8.1 от разработчика Win32ss? Спасибо
https://github.com/win32ss/supermium/issues/95
https://github.com/win32ss/supermium/issues/136
https://github.com/win32ss/supermium/issues/131

**Comment by Feodor2** [comment]
На всякий случай я тебя забаню.
Возможно ты и не перерегистрированый Егор, так пишешь такой же бред, не хочу тут видеть таких.

**Comment by mediaexplorer74** [comment]
> На всякий случай я тебя забаню.

Прива, с наступающим. О, в гитхабе банить можно? Сто лет тут, а о такой фиче не знал ) Пасиб, вдруг потребуется тоже

**Comment by asdf2345** [comment]
I really prefer the idea of building up upon 68, and don't think every XP browser should be the same. At the same time though why ban him for a valid suggestion?

**Comment by jonm58** [comment]
> I really prefer the idea of building up upon 68, and don't think every XP browser should be the same. At the same time though why ban him for a valid suggestion?

too noisy

**Comment by spacedrone404** [comment]
I've never understood people who can't answer an important and moreover relevant question. People who threaten with bans and intimidatingly threatening answers.
