### ISSUE TITLE
openai chatgpt not working at login

### ISSUE THREAD

**Issue by ahm5jnhi5** [Feodor2/Mypal68#346]
ChatGPT is not working here:
https://chat.openai.com/auth/login
when clicking on the blue Log in button nothing happens
and there does not seem to be a way to by pass this page to be able to actually login and use the website.
using mypal-68.13.7b

**Comment by bushy555** [comment]
Confirmed. Also with v13.7b

**Comment by dapgo** [comment]
What was the solution?
 it seems failing on 68.14 curious it works on FF155 loading the same profile.
User agents?
