### ISSUE TITLE
Can't open https://github.com

### ISSUE THREAD

**Issue by diakin** [Feodor2/Mypal68#348]
https://github.com 
Secure Connection Failed
An error occurred during a connection to github.com. PR_CONNECT_RESET_ERROR
    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.

Внизу слева пишет -Performing a TLS handshake to github.com...
 
Потом закрывал-открывал браузер, перезагружал страницу -  https://github.com открылся.

**Comment by NS-Clone** [comment]
открываетсо норм
можот утя время на компе ушло а потоо синхронизировалось?
на ХРю как раз времена уходят :rofl:

**Comment by Al6bus** [comment]
юзай впн или тормоши своего провайдера

**Comment by diakin** [comment]
Я тестил на Win7. Яндекс браузер открывает без проблем, Edge тоже. 
Висит на этом - Performing a TLS handshake to github.com...
Потом открывается... или не открывается.

Вообще хотел этот браузер использовать в ReactOS. Так-то в  Win7 все прекрасно работает,  современные сайты открывает. Банковские тоже.

**Comment by dartraiden** [comment]
Проблема не в браузере, см в конце [поста](https://forum.ru-board.com/topic.cgi?forum=5&topic=51176&start=0&limit=1&m=4#1)

**Comment by diakin** [comment]
Понижайте уровень TLS через about:config    security.tls.version.max
1 = TLS 1.0    2 = TLS 1.1  3 = TLS 1.2   4 = TLS 1.3

Переключил на 1.2 - все работает.
А во что это выливается с точки зрения безопасности?  Я так понимаю, что ничего страшного? В 1.3 запрещены старые протоколы. Или лучше оставить 1.3, а гитхаб как-нибудь через antizapret?

**Comment by dartraiden** [comment]
TLS 1.3, емнип, работает быстрее за счёт того, что там рукопожатие более короткое. Конечно, речь идёт про считанные миллисекунды. В общем, там много отличий.

**Comment by NS-Clone** [comment]
вангую что сразу сбеситсо клоунфларе
и перестанет пускать на все сайты

**Comment by diakin** [comment]
Не получилось установить расширение антизапрет.
[runet-censorship-bypass-0.0.1.56-full-rc0.zip] пишет, что несовместима
0.0.1.49 - устанавливается, но пишет Ошибка расширения - chrome.proxy.settings.onChange is undefined.

**Comment by sergeevabc** [comment]
Ребят, погодите, рано ссылаемся на РКН. Берём хромообразный браузер 100+, в [тесте](https://clienttest.ssllabs.com:8443/ssltest/viewMyClient.html) он показывает поддержку TLS 1.3, как и Pale Moon 32. как и MyPal 68, Из них только последний не открывает Github. Никаких прокси и изменений трафика не используется.

**Comment by dartraiden** [comment]
У хромиума может быть некий механизм определения проблем и отката на более
раннюю версию TLS

Да и кого ещё винить в том, что у _части_ россиян в Gecko-based браузерах
проблемы с соединением? Общий знаменатель тут только РКН.

ср, 10 янв. 2024 г., 04:30 Aleksandr Sergeev ***@***.***>:

**Comment by sergeevabc** [comment]
Анализ уровня «нюхом чую» принять не могу.

* Беру несколько портативных версий [Firefox ESR](https://portableapps.com/apps/internet/firefox_portable/legacy): 78, 91, 102
* Github.**com** не открывается в 78 и 91
* Github.**com** открывается в 102:
  * Соединение установлено по TLS 1.3
  * Шифр AES 128 GCM SHA256
  * Сертификат Digicert
* Иду в консоль разработчика MyPal и копирую параметры запроса к Github.**com**, после чего скармливаю их в Curl 8.5
<details>
<summary>Лог успешного соединения по TLS 1.3</summary>
``` console
$ curl.exe -vI "https://github.com/" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:78.0) Gecko/20100101 Firefox/78.0 Mypal/68.13.7" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "Connection: keep-alive" -H "Upgrade-Insecure-Requests: 1" -H "Pragma: no-cache" -H "Cache-Control: no-cache"
* Host github.com:443 was resolved.
* IPv6: (none)
* IPv4: 140.82.121.3
*   Trying 140.82.121.3:443...
* Connected to github.com (140.82.121.3) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: C:\01 Входящие\Браузеры\curl\curl-ca-bundle.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_CHACHA20_POLY1305_SHA256 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
*  start date: Feb 14 00:00:00 2023 GMT
*  expire date: Mar 14 23:59:59 2024 GMT
*  subjectAltName: host "github.com" matched cert's "github.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type ? (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 1: Public key type ? (384/192 Bits/secBits), signed using sha384WithRSAEncryption
*   Certificate level 2: Public key type ? (2048/112 Bits/secBits), signed using sha1WithRSAEncryption
* old SSL session ID is stale, removing
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://github.com/
* [HTTP/2] [1] [:method: HEAD]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: github.com]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [accept-encoding: deflate, gzip, br, zstd]
* [HTTP/2] [1] [user-agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:78.0) Gecko/20100101 Firefox/78.0 Mypal/68.13.7]
* [HTTP/2] [1] [accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8]
* [HTTP/2] [1] [accept-language: en-US,en;q=0.5]
* [HTTP/2] [1] [upgrade-insecure-requests: 1]
* [HTTP/2] [1] [pragma: no-cache]
* [HTTP/2] [1] [cache-control: no-cache]
> HEAD / HTTP/2
> Host: github.com
> Accept-Encoding: deflate, gzip, br, zstd
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:78.0) Gecko/20100101 Firefox/78.0 Mypal/68.13.7
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
> Accept-Language: en-US,en;q=0.5
> Connection: keep-alive
> Upgrade-Insecure-Requests: 1
> Pragma: no-cache
> Cache-Control: no-cache
>
< HTTP/2 200
...
```
</details>

* Возвращаюсь в MyPal и убеждаюсь, что TLS 1.3 вообще работает.
Для этого открываю, например, Github.**ink**:
  * Соединение установлено по TLS 1.3
  * Шифр AES 256 GCM SHA384
  * Сертификат ZeroSSL
---
Не вижу блокировок со стороны РКН.
Вижу, что в старых версиях Firefox есть проблема с сертификатами DigiCert.

**Comment by dartraiden** [comment]
> Видно, что проблема касается старых версий Firefox

Проблема и на актуальных версиях возникает.

**Comment by diakin** [comment]
Я предлагал сделать некий список сайтов-исключений  на которых автоматом переходит на TLS1.2
Настройки же можно менять на лету.

**Comment by sergeevabc** [comment]
@dartraiden, решением тем ближе, чем больше вещественного в обсуждении. Например, логов соединений, особенно снятых программой Wireshark, которые любит анализировать @valdikss, автор Antizapret и GoodbyeDPI.

Я привёл хоть какие-то логи, подтверждающие, что соединение устанавливается без всяких трюков (например, через Curl, имитирующий Firefox). Что же это за уникальная технология на рынке, которая блокирует только одну из двух программ, отправляющих аналогичный запрос?  Вот есть конкретный лог и конкретный вопрос, на который нужно ответить. Ответ «в России сообщают о похожие проблемах, значит, это РНК» это отписка, лишь бы самим ничего не делать — у кого-то в России гаснет свет в подъезде, только у одних лампочку выкручивают хулиганы, а у других проводка коротит.

Блокировку должно быть видно в обмене трафиком, это не квантовая физика.

**Comment by sergeevabc** [comment]
Новая информация.

* MyPal, FF ESR 78 и FF ESR 91 не могут открыть адрес https://github.com/
* Но если ввести https://www.github.com:443/ то перебрасывает на ^ и всё работает

**Comment by zanud** [comment]
> * MyPal, FF ESR 78 и FF ESR 91 не могут открыть адрес https://github.com/

Только что MyPal 68.13.7b эту ссылку открыл без каких-либо проблем.

**Comment by zanud** [comment]
У меня за несколько дней до Нового Года начались точно такие же проблемы с заходом на разные сайты, куда я до того чуть ли не ежедневно заходил без каких-либо проблем (DuckDuckGo, Google, YouTube). То PR_CONNECT_RESET_ERROR, то "Сайт не отвечает", то "Сайт не найден", то ещё что-то.

**Но:** Если я на эти же сайты захожу не с росссийского IP-адреса. Как только я включаю использование заграничного прокси, всё тут же начинает открываться с полпин[к/г]а. Выключаю использование прокси - немедленно те же проблемы.

Как вы понимаете, на уровень TLS прокси никак влдиять не может.

**Comment by ValdikSS** [comment]
> Что это за уникальная технология на рынке, которая блокирует только одну из нескольких программ, отправляющих аналогичный запрос? Вот есть конкретный лог и вопрос, на который нужно ответить.

Блокировка по TLS Fingerprint. Это блокировка со стороны России.
[github.com-mypal68-rublock.zip](https://github.com/Feodor2/Mypal68/files/13888219/github.com-mypal68-rublock.zip)

**Comment by zanud** [comment]
> Блокировка по TLS Fingerprint. Это блокировка со стороны России.

Тогда почему она распространяется только на очень избранные программы? И почему не действует, когда я работаю через прокси? Прокси ведь никак на зашифрованные данные не влияет.

**Comment by dartraiden** [comment]
Потому что оно не по программам блокирует, а по паттернам в трафике.

**Comment by ValdikSS** [comment]
> И почему не действует, когда я работаю через прокси? Прокси ведь никак на зашифрованные данные не влияет.

У вас прокси, с большой вероятностью, работает не на порту 443, а для этого типа блокировки анализируют только его.

**Comment by sergeevabc** [comment]
@ValdikSS, вы говорите, что у разных программ разный отпечаток при отправке запросов по защищённому соединению. А я замечал, что уже Firefox ESR [102](https://portableapps.com/apps/internet/firefox-portable-legacy-102) открывает Github без дополнительных уловок (по крайней мере у меня, глядишь, ещё кто скачает и проверит). 

Следует ли из этого, что можно взять отпечаток 102, имплантировать его в MyPal, подобно тому, как @Feodor2 ранее перенёс в 68 версию Javascript-движок 78 и useragent, тем самым решить вопрос с доступом к этому сайту?

**Comment by zanud** [comment]
Кстати, насчёт доступа к Github. Я сначала удивился, почему здесь все пишут, что к нему доступ пропал, а у меня этой проблемы нет. Потом просмотрел повнимательнее свой proxy.pac - в нём github.com прописан.
Но раз я об этом не помнил, то значит, что прописан он там давно, года два уже как, и явно не из-за РКН, а из-за его собственной политики.

Как же вы все на него месяц назад попадали? Они свою блокировку отменили?

**Comment by zanud** [comment]
> Блокировка по TLS Fingerprint. Это блокировка со стороны России.

Но ведь анализатор видит, с каким сайтом обмен идёт. Ему же не только IP-адреса доступны (которые в любом случае видны), в HTTPS и имя сайта открытым текстом передаётся.

Вот сейчас у меня проблемы с DuckDuckGo, Google, YouTube, но ни одного сайта из этой троицы в списках РКН нет.

**Comment by sergeevabc** [comment]
> Как же вы все на него месяц назад попадали?

Я заходил (и захожу) на github.com без проблем с помощью браузеров
* Waterfox и Pale Moon (на базе Gecko 102),
* LibreWolf (Gecko 109),
* IceCat (Gecko 115),
* Cent (Chromium 102)
* Supermium (Chromium 119),
* Opera 95 

@zanud, мы тут о доступе только к github.com и только через MyPal, а не вообще о блокировках, а то тема быстро замылится и воз останется на месте, а нужно найти решение. На данный момент автору темы нужно проверить [одно](https://github.com/Feodor2/Mypal68/issues/348#issuecomment-1884829322) и [второе](https://github.com/Feodor2/Mypal68/issues/348#issuecomment-1884886318). Ждём его ответов.

**Comment by zanud** [comment]
А я убрал github.com из своего proxy.pac, после чего без проблем зашёл на него с помощью MyPal 68.13.7b (как на данную страницу, так и на главную сайта в целом).

**Comment by zanud** [comment]
Заодно проверил те три сайта, с которых у меня всё началось, а  там уже всё в порядке, соединяется моментально.

Похоже, окно в мир починили.

**Comment by diakin** [comment]
Когда ввожу https://www.github.com:443/ оно в строке меняется на https://www.github.com/ и соответственно висит.
Но.. бывает повисит-повисит и зайдет на сайт. 

Только что открыл MyPal и зашел на гитхаб. Через 5 минут снова пытаюсь зайти - висит ждет TLS.

**Comment by diakin** [comment]
скачал Mozilla Firefox, Portable Edition Legacy 102
зашел мгновенно.

**Comment by sergeevabc** [comment]
@Feodor2, можете изменить TLS отпечаток MyPal на используемый в FF 102?

**Comment by diakin** [comment]
Скачал VPN попробовал, ~~пшерги~~ github открывается мгновенно.

**Comment by diakin** [comment]
> Чтобы такое повторить в другой программе, может понадобиться переписать в ней изрядный объём кода
А может там просто длл-ку можно позаимствовать...

**Comment by diakin** [comment]
В любом случае костыль со сбросом настроек до TLS1.2 решает проблему.

**Comment by zanud** [comment]
@diakin 
> А может там просто длл-ку можно позаимствовать...

Если такое можно сделать, то и в исходниках перенести будет легко.

@sergeevabc 
Где в моих словах можно было увидеть навязывание мнения, тем более автору? Я просто объясняю здесь присутствующим, что _"взять кусок кода из одного open source проекта и адаптировать к другому open source проекту"_ может быть о-о-чень сложно, с тало быть - долго. Чтобы вы не ждали чудес на Старый Новый год.
Тем более, что автору, для того, чтобы у себя эту проблему воспроизвести, нужно (строго по классике) сменить страну проживания.

**Comment by ValdikSS** [comment]
Блокируют сочетание:
```
Cipher Suites (18 suites)
    Cipher Suite: TLS_AES_128_GCM_SHA256 (0x1301)
    Cipher Suite: TLS_CHACHA20_POLY1305_SHA256 (0x1303)
    Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)
```

```
security.ssl3.ecdhe_ecdsa_chacha20_poly1305_sha256=false
security.ssl3.ecdhe_rsa_chacha20_poly1305_sha256=false
```
Как вариант.

**Comment by diakin** [comment]
Вот, "по совету друзей" добавил в настройки строчку security.tls13.chacha20_poly1305_sha256 -> false
все работает вроде и гитхаб тоже.

**Comment by dartraiden** [comment]
Можно и другой шифр отключать, например security.tls13.aes_256_gcm_sha384 = false

**Comment by JeanPaulLucien** [comment]
> An error occurred during a connection to github.com. PR_CONNECT_RESET_ERROR
This is not Mypal issue.

**Comment by JeanPaulLucien** [comment]
> Блокировку должно быть видно, это не квантовая физика.

I do not know when internet provider said: "Yeah, we block access to resource". People in Russia are sure that they can't visit some website because angry website owner forbids that. Internet providers say: "Contact with website support." People were much surprised when we told them that RKN does that.

**Comment by JeanPaulLucien** [comment]
> TLS Fingerprint
https://bugzilla.mozilla.org/show_bug.cgi?id=1850504

**Comment by sergeevabc** [comment]
@JeanPaulLucien, folks who reported problems with Github in this thread used FF forks < 102, MyPal included. There is no such problem with FF 102+. It means we can take part of the upstream code and adapt it here to solve the issue. Whether the developer will do this is unknown. While he is thinking, a couple of workarounds related to changing about:config preferences have been proposed. That is why new messages are no longer published in this topic, we are waiting. Thanks for stopping by, move on.

**Comment by dartraiden** [comment]
> I do not know when internet provider said: "Yeah, we block access to resource". 

ТСПУ управляются не провайдером, и никаких "заглушек" пользователю не отдают.

**Comment by zanud** [comment]
> ТСПУ управляются не провайдером (для провайдеров это "чёрные ящики")

Позавчера мне выпала возможность попеременно подключаться к двум разным провайдерам.
Пытаюсь зайти на GitHub и прочие серверы, "забуксовавшие" перед Новым годом, - "буксуют", как и раньше.
Переключаюсь на альтернативного провайдера - всё работает без каких-либо проблем.
Тут же возвращаюсь на своего обычного провайдера - опять "буксовка".

Несколько раз в течение дня проверял, и каждый раз картина была как описано выше. А ведь, по идее, ТСПУ из одного центра управляются.

> А что, собственно, может сделать разработчик, кроме как отключить по умолчанию одну из указанных настроек, чтобы изменился набор шифров, на который триггерится аппаратный цензор.

Хуже всего здесь то, что блокировка срабатывает не на сами шифры, а на некие косвенные их признаки. И набор этих признаков (по которым происходит опознание) блокирующая сторона в любой момент может изменить, после чего все затраченные создателем браузера усилия окажутся напрасными.

**Comment by JeanPaulLucien** [comment]
Seems I know what they blocks - protests in Bashkortostan.

**Comment by zanud** [comment]
@JeanPaulLucien
Let look when this issue was created.
And for me this problem started even earlier - in the second half of December.
Definitely, RKN hired some great forecasters.

**Comment by sergeevabc** [comment]
> Хуже всего здесь то, что … блокирующая сторона в любой момент может изменить, после чего все затраченные создателем браузера усилия окажутся напрасными.

Хорош драматизировать. Давайте не делать вообще ничего, т.к. Солнце не вечное, пригодных для переселения планет не видать, а если и видать, то долететь невозможно, а если возможно, то столкновение галактики Млечного Пути с Андромедой это обнулит, если до того не собьёт метеоритным дождём. Суть MyPal — показывать сайты под Windows XP. Для этого в код постоянно добавляют технологии из старших версий, например, обновляют движок Javascript, иначе сайты перестанут отображаться корректно. Ровно так нужно обновить и «код работы с сетью», ведь очевидно, что Github работает в FF 102+ не потому, что в последнем отключены шифры. Не размышлять об этой возможности можно только по одной причине — при несовместимости кода с XP, чего доказано не было, т.к. никто в код ещё не лазил.

**Comment by zanud** [comment]
@sergeevabc 
Если пройти по одной из даденных чуть выше ссылок, то можно узнать, что полгода назад проблема, аналогичная нашей, вылезла с текущей на тот момент версией FF в Туркменистане. И тогда, как и сейчас, пользователей Хрома она не затронула.
Что сказали разработчики FF? "Мы, конечно, можем сделать наш обмен с серверами похожим на Хромовский, но смысла в этом не видим."

**Comment by sergeevabc** [comment]
@zanud, Туркменистан — страна маленькая (7 млн) и экзотическая, у них и блокировки экзотические. Это как восхититься самоуправлением кантонов в Швейцарии и потом вздыхать, ну почему в России не так, забывая, что в первой стране живёт 9 млн с протяжённостью с запад на восток 350 км с альпийскими коровами, а во второй — 145 млн и 10 000 км с таблицей Менделеева. У нас блокируют по [домену и айпи](https://github.com/Feodor2/Mypal68/issues/348#issuecomment-1884625892). Разве этих двух методов уже не хватает, чтобы ограничить доступ? Хватает, но их даже и не применяют в отношении Github. Как писал @dartraiden, эта блокировка по отпечатку всплыла как побочный эффект охоты на что-то другое, но попутно досталось пользователям Firefox <102.

**Comment by zanud** [comment]
> Туркменистан — страна маленькая (7 млн) и экзотическая, у них и блокировки экзотические.

Ничего экзотического - тупо запретили любую связь по HTTPS с заграницей.

> забывая, что в первой стране живёт 9 млн с протяжённостью с запад на восток 350 км с альпийскими коровами, а во второй — 145 млн и 10 000 км с таблицей Менделеева.

В той 9-миллионной стране, скорее всего, больше пользователей FF, чем в 145-миллионной MyPal.

> эта блокировка по отпечатку всплыла скорее как побочный эффект охоты на что-то другое

И это тоже загадочно. Блокируют TLS3 по косвенным признакам, не обращая внимание на доменное имя и IP-адрес, но при этом следят за 443 портом, однако игнорируют общеупотребимые порты прокси-серверов.
Вот с чем можно так бороться? Да ещё и, как оказалось, в сети Tele2 ничего не блокируется.

Но я ещё раз обращаю внимание:
1. Никто из посторонних не знает, по каким именно признакам срабатывает блокировка.
2. Набор признаков, по которым блокировка срабатывает, в любой момент может быть изменён на другой, и всё старания @Feodor2 по переносу кода из FF117 (или какой там сейчас текущий) пойдут лесом.

**Comment by sergeevabc** [comment]
> Набор признаков, по которым блокировка срабатывает, в любой момент может быть изменён на другой.

Если у нас «набор признаков» изменят так, что он перестанет быть аномалией, затрагивающей отношения Github и пользователей Firefox <102, перекинувшись. например, на невозможность под любым Firefox зайти без видимых причин на популярный ресурс вроде Youtube, но при этом на него можно будет зайти под Хромом, это в течение дня вызовет вопрос о профессионализме госорганов. А чтобы не падать лицом в грязь, отработана процедура:  такой-то госорган доказывает опасность такого-то ресурса, после чего выбирается блокировка по домену или айпи, а не какая-то экзотика, дискриминирующая пользоавтелей.

**Comment by zanud** [comment]
"Не льсти себе - подойди ближе". Вот статистика: http://alexvaleev.ru/browserstat/2023/12/, доля Firefox (всех версий) в России - меньше полутора процентов. Кто их бухтение заметит?

**Comment by sergeevabc** [comment]
«Бухтение» на уровне государства измеряется не статистикой Яндекс.Радара и Ливинтернета, которые искажены блокировщиками рекламы, без которых уже сложно представить пользователей Firefox, а работой с системными аналитиками вроде [Натальи Касперской](https://www.youtube.com/watch?v=Jm05c5Q3kjg) и Игоря Ашманова, агентства которых имеют решения для сбора и анализ происходящего в [соцсетях](https://lenta.ru/news/2023/12/28/goluyu-vecherinku-ivleevoy-vysmeyali-v-memah/).

**Comment by JeanPaulLucien** [comment]
> @JeanPaulLucien Let look when this issue was created. And for me this problem started even earlier - in the second half of December. Definitely, RKN hired some great forecasters.

Forecaster is not needed. If you read laws, you know a procedures. duration and deadlines. You have known when court has finished. This is final.

**Comment by Feodor2** [comment]
Если шо я открыл ещё сайт https://codeberg.org/Theodor2/Mypal68

>старания @Feodor2 по переносу кода из FF117 (или какой там сейчас текущий) пойдут лесом.

91 и чего это лесом, большая куча сайтов заработает снова

**Comment by zanud** [comment]
@Feodor2 
> и чего это лесом, большая куча сайтов заработает снова
Имелось в виду: "Ничто не вечно под луной". В смысле: через какое-то время набор признаков, по которым рубят соединение, изменят, и если от этого те версии FF, которые умудряются работать сейчас, работать тоже перестанут, то вместе с ними "приляжет отдохнуть" и MyPal.

@sergeevabc 
Исходя из таких рассуждений, стоит не дожидаться перитонита, а уже сейчас повоздейстовать на это самое государство.
Есть на сайте РКН такая интересная страничка: [Общественная электронная приемная](https://rkn.gov.ru/treatments/ask-question/), на которой можно жаловаться на всякое разное.
Можно сейчас согласовать примерный текст обращения, решить, какой раздел выбирать в блоке "Тематика обращения" и побомбить его своими "Фе".

**Comment by sergeevabc** [comment]
> @Feodor2
> 91 и чего это лесом, большая куча сайтов заработает снова

Кстати, да. Успешно открыл Github в [Seamonkey](https://www.seamonkey-project.org/releases/) 2.53 на базе Gecko 91.0.

**Comment by zanud** [comment]
А я Github только что в древнючем Firefox 52.9 открыл.

**Comment by Al6bus** [comment]
Судя по успеху симанки, я чекнул инфу, она на 60й еср лисе базируется с юзер агентом от 91й. Мош у кого не открывается, попробовать мимикрировать под ua самой симанки.

**Comment by dartraiden** [comment]
> побомбить его своими "Фе".

Спортлото ещё можно побомбить, без обид...

**Comment by zanud** [comment]
@Al6bus 
> похожечто у более "оффициальной" "вынужденной" (ff 60esr+) морской обезьянки шансов на открытие больше чем у остальных, даже более передовых "ноунеймов", втч палемуна. К сожалению...

**Seamonkey 2.49.5**
Нормально заходит на GitHub.
UA: "Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0 SeaMonkey/2.49.5"
С таким UA у MyPal сюда не заходит.
Но эта версия поддерживает только TLS2, а при таком ограничении и MyPal сюда заходит.

Более новые Seamonkey проверить не могу (у меня XP), но **Iceape-UXP 52.9**, который поддерживает TLS3, и у которого UA "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0 SeaMonkey/2.49.4", тоже на GitHub заходит, а MyPal с его UA - нет.

Так что вряд ли игры с UA помогут.

@dartraiden
> Спортлото ещё можно побомбить, без обид...

Так я и отвечал на предложение дожидаться радостного момента, когда государство само соизволит поинтересоваться у Спортлото результатами очередного розыгрыша (населения).

**Comment by zanud** [comment]
Кстати, тут выше просили добавить возможность ограничивать версию TLS выборочно для конкретных сайтов. Так вот, формально такая возможность имеется уже сейчас: ставим `security.tls.version.fallback-limit = 3`, а в `security.tls.version.fallback-limit` прописываем через запятую список доменных имён. После этого на указанные в списке сайты должно заходить с уровнем, заданным в `security.tls.version.fallback-limit`, а на все остальные с уровнем, заданным в `security.tls.version.max`.

И это работает - я именно так сейчас сюда и зашёл. Только вот после успешного захода посещённый сайт из списка удаляется. А это странно, так как данная ошибка у Mozilla значится исправленной ещё 8 лет назад: https://bugzilla.mozilla.org/show_bug.cgi?id=1223131

Создать здесь отдельную жалобу, или и так сойдёт?

**Comment by Feodor2** [comment]
Проверить как рабоатет на 52, ройтамах и оригинале 68, а потом по результату решай кому жаловаться. Мозила думаю не будет спешить, вот мунчик если ему больше нечего делать может починит быстро.
Если это проблема только моя, то в долгий ящик наверное в конец списка перед автообновлением и установщиком.

**Comment by JeanPaulLucien** [comment]
Strange talk is here. You have the right to send a mail to government structure, but are telling not do that.
Write to yours ISP.

> проблема только моя

I suppose this problem is users in Russia only.
