### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by sirrooster** [Feodor2/Mypal68#349]
https://kfz.check24.de/auto/rechner/web/rechner?appSettings=41024ac0-ed12-49dc-9d94-2bb7f85aefa7

It's a calculator for car-Insurance and pther things. It's not opening.

**Comment by IP-CAM** [comment]
504 Gateway Time-out
The server didn't respond in time.
It's most likely not a Browser Problem, it's not working with other Browsers either.
