### ISSUE TITLE
x64 version - Couldn't load XPCOM

### ISSUE THREAD

**Issue by Typical0** [Feodor2/Mypal68#35]

**Comment by Feodor2** [comment]
After will be the finally selected version what to stay an further develop (68-78-91)
Not in the visible future.

**Comment by JodyThornton** [comment]
I'm also interested in this.  Thanks foi myPal v68 :)

**Comment by Gabrielx36** [comment]
Will there be a 64bit version of this. That would be great. I just got a geniue cd of windows xp x64 edition. And I would love to see this browser work on it.

**Comment by Matiasgroen** [comment]
The browser already works on XP64, but a native x86_64 build would be nice. I understand if that is currently outside the main scope of the project though.

**Comment by Gabrielx36** [comment]
It actually doesn't work. You might be referring to the ios of it. Those are actually different from the real version. i have a genuine disc of Windows xp x64. And I tried the browser on it inside a vm and got an error. So it would be great if one day we get a native 64 bit version of this browser. I plan to windows xp x64 edition and the browser for something special. 
![2022-06-02](https://user-images.githubusercontent.com/106503020/171685594-602e0b8b-ab09-46fa-bdcb-a346b744d8aa.png)

**Comment by Matiasgroen** [comment]
It works fine on my end. Are you using SP2? And judging by the files on your desktop, do you have WineD3D or some other ugly hack installed? That probably breaks it.
![image](https://user-images.githubusercontent.com/11633814/171690763-b2a37d4b-c38f-403f-8483-556fbb6b2133.png)

**Comment by Gabrielx36** [comment]
Yes I'm using sp2. I have AVG installed. I don't know what the heck wine 3d is. But I got the files from the mypal website. Do you think my anti-virus is interfering or something else. Either way I really think we could use a native 65bit version

**Comment by NEO-SPECTRUMAN** [comment]
mypal website?

**Comment by Gabrielx36** [comment]
Hold it I think I found the problem. It might have been virtual box guest additions drivers. I tried it on actual hardware with xp x64 edition and it works. Only downside is that it would never surpass 4gb since that is all 32bit can support. But I hope that when they get to it. We one day get a 6rbit version even if it is currently outside of the project for now.

**Comment by NEO-SPECTRUMAN** [comment]
> Only downside is that it would never surpass 4gb since that is all 32bit can support

try load 4GB+ with multiprocess mode on

**Comment by Gabrielx36** [comment]
Wait the computer I ran it on only had 4gb. Ill tell you this though
 Someday I'm going to build the ultimate windows xp machine. And I'm going to use windows xp x64 edition. The pc will have more than 4gb. But I don't have anything currently that has more than 4gn of ram and supports windows xp x64. But still. Hopefully one day we get a 64bit version of it even if it takes more than years to complete.

**Comment by Gabrielx36** [comment]
But at least it works. Hopefully it gets more stable has time goes on.

**Comment by JodyThornton** [comment]
I'm still VERY hopeful an x64 version comes to pass.  My objectives for using MyPal 68 are completely diffferent.  I'm using it with Windows 8.

I want to use it so that I can have version f Quantum that is backported with security updates.  I would love to have a version of Firefox ESR, with the Quantum Photon shelll that can be updated to current security standards.  In fact, I hope that Feodor2 never moves to v91, because that would be Proton, which I'm now using.

**Comment by Feodor2** [comment]
On win7 and never you may use original firefox with all updates. On win8 i myself use fox91.
And whats wrong with the Proton?

**Comment by JodyThornton** [comment]
No I understand that Feodor2, but what I'm looking for is a Quantum browser fork, like Firefox ESR 68 or 78, with updates ported back to it.  This is basically what you're doing with MyPal 68, except it can also run under XP.

As for what's wrong with Proton?  Really?  Well, I hate the rounded floating tabs.  I like the square, boxier look of Quantum.  What you have with MyPal 68 is the old Photon appearance, which I prefer.  Basically, I'm looking for the closest thing I can get to bring back Quantum 68 or 78, in an x64 build, with current security updates.

This is not on you.  I'm just hopeful that 78 is where MyPal will end up, and iin x64.  That's all.

I will keep you and your country in my thoughts.  Stay safe.

**Comment by NEO-SPECTRUMAN** [comment]
панаразводилась фанатеков ежесекундных security updates.

**Comment by win98se** [comment]
> I hate the rounded floating tabs. I like the square, boxier look of Quantum. What you have with MyPal 68 is the old Photon appearance, which I prefer.

If you don't know, you can actually use `userChrome.css` and `userContent.css` to modify the appearance. These works for current version of Firefox, including Firefox 91 ESR. For example, [some people make a set of styles to revert to the Photon appearance](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style).

Considering newer standards and various things that newer versions of Firefox supports, there is no reason not to move to 91 if there is any possibility to.

**Comment by JodyThornton** [comment]
I'm well aware of that, but thank  you.  I use  Firefox  ESR 91 as it stands, but support ends in late August.  I use CSS mods to create a Photon/Quantum appearance.  But more workarounds will be needed for ESR 102.

I was hoping for an security-updated Quantum/Photon build that can stiil browse most sites.  ESR 78 would likely be the best bet, but ESR 68 dies work for me.  I figured if I could get a year or two out of it, that would be terrific.  After all, it's no different than what the Pale Moon or Waterfox Classic crowds get (except they want XUL compatibility)

**Comment by IntelMiner** [comment]
+1 for a Windows XP 64-bit version. There's very little XP-64 software that was ever released and a decent browser would be nice

**Comment by Feodor2** [comment]
Still i did not try build x64s, there are things more important - even fixing a microphone.
For if you really want  try build it yourself

**Comment by Feodor2** [comment]
I have done x64 veersion, but it fails to run on xp64 because of this
https://github.com/llvm/llvm-project/blame/6a075b6de4cafebec9ca1ff9eec7229a617c93f6/llvm/lib/Target/X86/X86ISelLowering.cpp#L15027C28-L15027C28

I get 0 there on my xp64. So i publish x64 and you will check either i will have to patch llvm and rebuild or my xp64 needs patch as it vanilla sp2.

**Comment by JodyThornton** [comment]
Excellent news Fedor2.  I would be running such a version on Windows 8, so perhaps it will not affect me.
Can't wait to download it.  Cheers!

**Comment by Feodor2** [comment]
Seems on xp64 fails regardless updates, have to patch llvm, and consider this is not important, means i don't plan to fix this in near future.

**Comment by newbie-461** [comment]
http://www.nynaeve.net/?p=187
pre-Vista Windows does not initialize the Thread Local Storage in a dynamically loaded DLL.

![Image](https://github.com/user-attachments/assets/3be53621-016e-41f4-a796-4c46b22fad0c)
so I manually add xul.dll to mypal.exe import table (use PE-bear_0.7.1), make dll static linked
[mypal.zip](https://github.com/user-attachments/files/20069561/mypal.zip)
mypal-64bit seems to work with XP64 after that. 
![Image](https://github.com/user-attachments/assets/99707f47-e4ea-4c98-952e-3f6ab4231697)

**Comment by NS-Clone** [comment]
А чего будет когда софта попробует сделать LoadLibrary когда она уже загружена?

**Comment by newbie-461** [comment]
> won't there be 2 identical dll files in the frame?

https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya
"The system maintains a per-process reference count on all loaded modules. Calling LoadLibrary increments the reference count. Calling the FreeLibrary or FreeLibraryAndExitThread function decrements the reference count. The system unloads a module when its reference count reaches zero or when the process terminates (regardless of the reference count)."

> and what does it get so you can try to fix randomly falling spotlights?

Use debugger to check the crash point, if there is fs:[2C] or gs:[58] asm code before it, that tricky fix might work

**Comment by Gelip** [comment]
@newbie-461 
Wow - this works :-)
Please add xul.dll to 64-bit version 68.14.4b because 68.14.8b wrong display elektroda.pl
![Image](https://github.com/user-attachments/assets/ee609d5c-a89f-4ec3-9066-5f5d0ca7bdd1)
68.14.4b 32-bit display OK:
![Image](https://github.com/user-attachments/assets/6e02a313-013f-4737-9647-9845eb588260)

**Comment by Gelip** [comment]
OK, I already know how :-)
![Image](https://github.com/user-attachments/assets/53d0ec8d-0dda-4f64-8d9b-452240d84e18)
![Image](https://github.com/user-attachments/assets/371aefc9-0859-470e-904a-d623a91abf88)
![Image](https://github.com/user-attachments/assets/0fd3c127-7cd9-46fb-bc7a-74c6e2864313)
