### ISSUE TITLE
SSE4 процы

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#350]
раз у тебя часто редкие релизы
может ты мож периодически собирать версии заточенные под разные процы?

ХРю жо работает на машинах 2014 года почти из коробки
но чета когда речь заходит про ХРю
всех переклинивает и они начинают жужжать про SSE1 которые 2000-х годов и с которых не поинтернетитть ужо тк там гиг рамы обычно предел...

я собирал под march/mtune i386 и под корудуба
и разница в скорости была 2-х кратная

**Comment by Feodor2** [comment]
SSE4 и ещё 2 с 3 тоже, уже есть в декодерах рисунков и видео
Вот сегодя будет для SSE1 где я вырезал все выше. А ты типа хочеш чтобы я повырезал всё ниже sse4, - сэкономит 1 ну 2 максимум именно мб, то есть перевыпускать отдельную версию ради эконеомии 2 мб? Думаю нет смысла. 
Мой корч и то не тянет SSE4, а у него 3гб.

**Comment by NS-Clone** [comment]
> А ты типа хочеш чтобы я повырезал всё ниже sse4, - сэкономит 1 ну 2 максимум именно мб,

я не про конкретные вставки sse4 кода
а про сборку с автоматической оптимизацией под новые процы
можот в этих ваших рустах тоже такое есть

ато браузер у нас и так ползает
а мы улучшаем совместимость с первым пнем?

**Comment by Feodor2** [comment]
Да в рустах можно выбирать какое sse включать, нон там нет ни видео ни рисунков наскольок знаю, даже веберендерер ничего такого не используюет.
Если нечем заняться и такой хороший мощный комп утебя, и знаеш как собирать - давай под sse4 соберёш сам.
Я подскажу если шо что где включать

**Comment by NS-Clone** [comment]
> Если нечем заняться и такой хороший мощный комп утебя, и знаеш как собирать - давай под sse4 соберёш сам.
> Я подскажу если шо что где включать

если roytam не собрал то я тем более не соберу :)

**Comment by NS-Clone** [comment]
> , нон там нет ни видео ни рисунков наскольок знаю, даже веберендерер ничего такого не используюет.

а к чему тут видео и рисунки?
то 2х я вообще наблюдаю на эмуляторе

хотя такой выиграшь возможно на агрессивном -OFast
там вообще оптимизации что дают х2 на -O0
дают х0.5 в сравнении с неоптимизированной версией

(я как раз вот в гуляюсь ибо надо чтоб щитало хотябы дни а не месяца Ж )

> Мой корч и то не тянет SSE4,
и все бы небыло бы так грустно
если бы мой корадуба не был бы 2008 года...


> давай под sse4 соберёш сам.
я бы не отказалсс от оффлайн версии всего чаго надо скачать для сборки про запас :)
а так ты говорил про сборку на 8.1
а на 7-ке оно всё работаит?

**Comment by Feodor2** [comment]
Да 7х64 хватит и ещё минимум 8гб озу.
Собрать просто можно под вин7, не нужно мудохаться с рустом - это думаю 90% проблемы. - автовыкачивание и т.д.

**Comment by Feodor2** [comment]
https://www.chaynikam.info/cpu_tech.html
Только sse42 может быть нужно для чегото кроме графики.
мой фен2 все таки тянет 4a, но толку мало имхо от этого

**Comment by JeanPaulLucien** [comment]
> собирать версии заточенные под разные процы
Нет смысла. Другое дело, что можно разбить так, что готовый к работе браузер делать легким для модификации конечным пользователем. @Feodor2, как считаешь?
