### ISSUE TITLE
Discord Crash 68.13.8b, x64 version MyPal68 does not load.

### ISSUE THREAD

**Issue by vertaa** [Feodor2/Mypal68#351]
Windows XP Stock. Any way to fix?

![image](https://github.com/Feodor2/Mypal68/assets/67488797/46f1e8d5-bb3c-4660-9e76-42c2123af622)
![image](https://github.com/Feodor2/Mypal68/assets/67488797/4b2b0fc5-866a-4d4e-a97f-eeb5daa43de1)

Extensions.
![image](https://github.com/Feodor2/Mypal68/assets/67488797/f17a0bc4-6eaa-445d-ac7c-dc8bd98628ba)
I cannot find task manager extension for firefox version68 to use with this version of mypla68.

**Comment by Feodor2** [comment]
Shuld not take 32 bit 68.13.8 except you machine is older pentiuym4 (SSE)

**Comment by vertaa** [comment]
No my machine is not older then a Pentium4 (SSE). 

So the crash cannot be fixed on  on the 32bit version of MYPAL68?

![image](https://github.com/Feodor2/Mypal68/assets/67488797/63fcbdff-e010-47d8-b9e8-e28d177c9048)

**Comment by vertaa** [comment]
![image](https://github.com/Feodor2/Mypal68/assets/67488797/ced95e90-a07a-4806-9853-33e59293bfc0)

**Comment by Feodor2** [comment]
First please stop to pile pictures (does anyone ever read readme).
Next you are to remember that any x64 software wont run on x86 system, which winxp is.
Next you please read readme things about the matter before report something.
Next drop 68.13.8 and take 68.13.7 version
Finally look here already exists issue about discord, use search.
