### ISSUE TITLE
Discord crash after updating mypal to 68.13.8b

### ISSUE THREAD

**Issue by pachuco** [Feodor2/Mypal68#353]
This crash happens to me upon switching to a loaded discord tab.

[drwtsn32_disco.zip](https://github.com/Feodor2/Mypal68/files/13878926/drwtsn32_disco.zip)

**Comment by pachuco** [comment]
Come to think of it, not being able to use discord is a feature, not a bug.

**Comment by NS-Clone** [comment]
не тестировал новую
но в 68.13.7 еще работает

**Comment by NS-Clone** [comment]
не знаю кудо написать
2 часа плясок с бубном


ВНЕЗАПНО дискорд стал валить браузер при востановлении сессии в 68.13.7 и при открытии вкладки с ним в 100% случаев
(мультипроцесс включен и 900 вклдок)
с exception 0x80000003
![2024-01-26_190620](https://github.com/Feodor2/Mypal68/assets/139008911/de7ce140-3f9a-4f42-9741-53a7910f84ec)

обновил до 68.13.8
все тоже самое

взял удолил 400 метровый cache2 из профиля

И О ЧУДО
востановвление сессии стало жрать на 1 гиг меньше оперативы (я ужо репортил)
до
![2024-01-26_190917](https://github.com/Feodor2/Mypal68/assets/139008911/dd8e3442-89d2-4000-8b9c-281512c3cdf8)

после
![2024-01-26_190938](https://github.com/Feodor2/Mypal68/assets/139008911/f17ee15b-3d89-4851-a795-a11750d40fe9)

но дискорд все равно валитсо с exception 0x80000003

но после попытки захода на страницу дискорда
в cache2 у нас образзовалось 15 мегабайт кешов
и на следующий запуск
опять востановление сесси жрет на 1 гиг больше рамы


отключил кеширование
browser.cache.offline.enable;false
browser.cache.disk_cache_ssl;false
browser.cache.disk.enable;false
browser.cache.memory.enable;false

востановление сессии перестало жрать дополнительный гиг
![2024-01-26_190938](https://github.com/Feodor2/Mypal68/assets/139008911/3f099c42-b968-484e-a021-80fc72dd6126)

но дискорд все равно валитсо с exception 0x80000003 в 100% случаев

откатилсо обратно на 68.13.7

и О ЧУДО дискорд заработал
в cache2 целых 0 байт
проифиль и настррйки те же
но востановлениие сессие опять жрет дополнительный гиг

![2024-01-26_191754](https://github.com/Feodor2/Mypal68/assets/139008911/bf7e9f90-e9d1-4338-a5d1-d26c2353679f)

**Comment by NS-Clone** [comment]
а так неп это совпадениё

оно опять не востанавливает
откатилсо на 68.13.5
тоже самое
вернулсо 68.13.8
с 5-й попытки востановило
хотя работопособность дискордов еще не проверял

**Comment by NS-Clone** [comment]
почистил количество вкладок до 700
и откатилсо обратно на 68.13.7
браузер не упал
и дискорд снова заработал

бубен наше все

**Comment by NS-Clone** [comment]
ну дискорд вроде еще работает
еще вспомнил что у меня было content process limit 2
до этого в options
а потом я вернул на 3 (default)
может при мультипроцессе с меньшим числом процессов
тоже свои глюки
