### ISSUE TITLE
68.13.8b Translation plugin issue

### ISSUE THREAD

**Issue by liqideqq** [Feodor2/Mypal68#357]
After installing the translation plugin, a crash error dialog box appears when clicking on translation. I hope it can be fixed.
https://addons.mozilla.org/zh-CN/firefox/addon/%E8%85%BE%E8%AE%AF%E7%BF%BB%E8%AF%91/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
![微信图片_20240114113021](https://github.com/Feodor2/Mypal68/assets/58159901/0c0164dc-540f-465e-9390-eb8ca109488c)

**Comment by RamonUnch** [comment]
Look at #203

**Comment by Feodor2** [comment]
Alse please check the cpu if its level newer than pentium3 or atlonXP do not take this version - take previous 68.13.7
