### ISSUE TITLE
Javascript and private fields

### ISSUE THREAD

**Issue by JeanPaulLucien** [Feodor2/Mypal68#359]
Which Mypal version supports this? I've found a website with crazy developers which have broken a website just adding a one private field.

**Comment by Feodor2** [comment]
I am going to add the feature along with other stuff from 91 firefox.
Next version
I already began to make it, so far estimate at least 3 months.

**Comment by JeanPaulLucien** [comment]
Could you add only private fields at near time I want to check some websites and tell about result.

**Comment by Feodor2** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1562054
This is v90 stuff, to go through all things
The task same great as was for regex thing 68.13
estimate time is the best guess.

**Comment by JeanPaulLucien** [comment]
I know you have planned to add a various features from 90 version. I mean add only private fields and their dependencies if it will be faster than adding all features from 90. Why I ask? I know websites where the one private field (one string `#var`) per all website.

**Comment by Feodor2** [comment]
How do you know that it will be faster, for me this is not faster but otherwise.
Until look for things, like gresemonkey scripts, to fix the site you want
