### ISSUE TITLE
WhatsApp Web

### ISSUE THREAD

**Issue by Gettobox** [Feodor2/Mypal68#36]
So on this new mypal68 we cant use WhatsApp Web?
or any solution for this?

**Comment by grof017** [comment]
In about:config add new string
general.useragent.override.web.whatsapp.com
Mozilla/5.0 (Windows NT 5.1; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by Gettobox** [comment]
yeay thank you now i can use again

**Comment by brbr1982** [comment]
thanks a lot

**Comment by mof22** [comment]
Since the last two days I cannot use whatsapp web on Mypal 68.
It was working normally with the solution mentioned above until the day before yesterday.

**Comment by szabota** [comment]
Заработало так:

Заходите в:
C:\Documents and Settings\USERNAME\Application Data\Mypal68\Profiles\XXXXYYYY.default-default
В файл "prefs.js" добавляете такую строку:
user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0");
Вуаля, WhatsApp Web теперь работает в mypal !
