### ISSUE TITLE
Something went wrong when I tries to edit Readme in GH repo

### ISSUE THREAD

**Issue by JeanPaulLucien** [Feodor2/Mypal68#362]
Steps to reproduce:
1. Open repo.
2. Click icon to edit readme file.

Result: something went wrong message.

**Comment by Feodor2** [comment]
They keep push the new shit, to cut off us.
May be it is the good time to drop github.

Find the first version where it works - begin with 91.
Good if 91 works, say i shall complete the move to 91 on march.
Of course they will push newer shit by the end of the year and i shall have to move to 102...

**Comment by JeanPaulLucien** [comment]
> time to drop github

I'm in.
