### ISSUE TITLE
Cannot install add-ons

### ISSUE THREAD

**Issue by TheAmpPlayer** [Feodor2/Mypal68#366]
I cannot install any add-ons on mypal v68.13.7b[
I tried installing this plugin: [ modify_http_response ](https://github.com/JustOff/modify-http-response/releases/tag/1.3.8)
But failed getting the following error:
"The add-on downloaded from this site could not be installed because it appears to be corrupt."
![image](https://github.com/Feodor2/Mypal/assets/90857134/26249083-615d-4bc3-90c3-0c16c3851f15)

I'm running windows XP SP3 32-bit.

**Comment by NS-Clone** [comment]
maybe it's "old firefox" add-on

**Comment by NS-Clone** [comment]
"for Firefox, Pale Moon and SeaMonkey"

**Comment by Feodor2** [comment]
It may be not obvious but old addons do not work
there stuff helps to enable some old addons
https://github.com/xiaoxiaoflood/firefox-scripts/tree/3079cc5089368bd10083896c37fa80153265fab5
