### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by RoozerXC** [Feodor2/Mypal68#367]
I am using Windows XP Service Pack 3, and the latest version of Mypal (68.13.8b). I am not running on a virtual machine as I'm using this on real hardware (Dell Inspiron 1501)

After scanning the QR code in the discord login page, the browser simply crashes

To reproduce:
1. Visit https://discord.com/app on Mypal
2. Go to your phone, and in the Discord app click on "Scan QR Code"
3. Scan the QR code. **DO NOT LOG IN.**
4. Mypal will crash

![Crash](https://github.com/Feodor2/Mypal68/assets/45127566/a06e2624-4abe-4aac-829b-81e0bec6c6cc)

**Comment by JeanPaulLucien** [comment]
Check https://github.com/Feodor2/Mypal68/issues/358 also.

**Comment by Feodor2** [comment]
not related and duplicate
