### ISSUE TITLE
Firefox 57+ legacy does not allow to work WebGL 2

### ISSUE THREAD

**Issue by JeanPaulLucien** [Feodor2/Mypal68#371]
```
WebGL warning: <SetDimensions>: Failed to create WebGL context: WebGL creation failed: 
* tryANGLE
* Exhausted GL driver options.
TypeError: GLctx is undefined
```
I still did not collect information to understand a reason.

**Comment by jonm58** [comment]
> ```
> WebGL warning: <SetDimensions>: Failed to create WebGL context: WebGL creation failed: 
> * tryANGLE
> * Exhausted GL driver options.
> TypeError: GLctx is undefined
> ```
> 
> I still did not collect information to understand a reason.

OpenGL driver lol

**Comment by JeanPaulLucien** [comment]
> OpenGL driver lol

Do you mean a reason outside Mypal?

**Comment by jonm58** [comment]
> > OpenGL driver lol
> 
> Do you mean a reason outside Mypal?

Yes,Windows XP don't Have OpenGL ES 2.0

**Comment by JeanPaulLucien** [comment]
This is strange. Other people say it requires hardware, my hardware is okay.
https://superuser.com/questions/969935/opengl-2-1-or-higher-for-windows-xp

**Comment by jonm58** [comment]
> This is strange. Other people say it requires hardware, my hardware is okay. https://superuser.com/questions/969935/opengl-2-1-or-higher-for-windows-xp

Windows XP only support OpenGL 1.1

**Comment by JeanPaulLucien** [comment]
```
OpenGL version string: 3.3.0
OpenGL (software) version string: 1.1.0
```

**Comment by jonm58** [comment]
> ```
> OpenGL version string: 3.3.0
> OpenGL (software) version string: 1.1.0
> ```

layers.prefer-opengl set true

**Comment by ibmaxx82** [comment]
Have a look at issue #309 on the WebGL problem

**Comment by JeanPaulLucien** [comment]
Seems this is Firefox 53+ legacy:
```
OPENGL_COMPOSITING	
disabled by default: Disabled by default
available by user: Enabled via layers.prefer-opengl
DIRECT2D	
unavailable by default: Direct2D is not available on Windows XP
GPU_PROCESS	
unavailable by env: Windows XP, Vista, and 7 Pre-SP1 cannot use the GPU process
WEBRENDER	
opt-in by default: WebRender is an opt-in feature
WEBRENDER_QUALIFIED	
blacklisted by env: No qualified hardware
```

**Comment by JeanPaulLucien** [comment]
Another low skill code websitel:
```
<canvas id="canvas" tabindex="0">
		HTML5 canvas appears to be unsupported in the current browser.<br>
		Please try updating or use a different browser.
	</canvas>
```
I found that in HTML. This text is not visible.
