### ISSUE TITLE
mypal safe mode

### ISSUE THREAD

**Issue by Sirbu4** [Feodor2/Mypal68#372]
mypal 68 safe mode how to switch on and off?

**Comment by RamonUnch** [comment]
use the `-safe-mode` command line argument. You can create a shortcut to `mypal.exe` that you would name *Mypal 68 Safe mode* and edit the command line as follow:
![image](https://github.com/Feodor2/Mypal68/assets/74856804/84c56b1e-a6a0-486b-a625-3ce1e6f91a75)

**Comment by Sirbu4** [comment]
Hi

Thanks for the prompt reply.  Does that command disable safe mode?  If so what
is the command to open mypal in safe mode?

Regards

Simon

**Comment by RamonUnch** [comment]
The `-safe-mode` command does starts mypal in safe mode, if you omit it it will start normally. Same for Firefox.

**Comment by Sirbu4** [comment]
Thanks, that's very helpful.

 

  _____
