### ISSUE TITLE
Turn off Angle from Google by default to improve Mypal

### ISSUE THREAD

**Issue by JeanPaulLucien** [Feodor2/Mypal68#376]
I opened `about:config` and made `webgl.disable-angle;true`. You need make `webgl.force-enabled;true` to make it workable. As result I got native hardware render for WebGL 1:
```
WebGL 1 Driver Renderer	NVIDIA Corporation
WebGL 1 Driver Version	3.3.0
```

I recommend to accept my settings as default for Mypal, because:

- user will see an information about hardware. 
- reports about issues with WebGL is easier to understand. does not work the reason will be clear it's hardware. 
- should be without issues, WebGL 1 exists until FF 4;
- finally the reason why WebGL 2 does not work is clear too.
- works (I even say preferable) for Windows XP-7. 
- save your PC resources.

**Comment by Feodor2** [comment]
With these settings did not get crash upon closing the browser while webgl stuff has loaded? (about:support for example)
Anyway i am going to fix this today

**Comment by Feodor2** [comment]
yet not fixed either

**Comment by RamonUnch** [comment]
It would be still nice to have angle as an automatic fallback if the hardware does not allows webgl without it.
On my Integrated Intel 965 Chipset, the only way to have webgl is to use angle.

**Comment by NS-Clone** [comment]
умя на 68.13.7 если сделоть webgl.disable-angle;true
webgl1 тоже отпадает
а webgl2 как не было так и нет

**Comment by Feodor2** [comment]
one webgl.disable-angle;true is not enough

you check on 965 roytam's browsers

**Comment by NS-Clone** [comment]
> one webgl.disable-angle;true is not enough

а webgl2 на ХРю завезен?
или это только у меня его нет?

**Comment by NS-Clone** [comment]
> первого хватает для браузера вполне.

да хз можот надо для новомодных гофносайтеков

**Comment by NS-Clone** [comment]
> когданибудь может смогу сделать первое вэбгл для гма

ну треугольнички в тестах и так рисуютсо
или это включаетсо софтваре рендорор?

**Comment by jonm58** [comment]
Webgl1 is best
![Windows XP Professional-2024-02-20-01-08-07](https://github.com/Feodor2/Mypal68/assets/73036321/2eff47d9-9509-448b-89e4-30ff0fca5fe7)

**Comment by Feodor2** [comment]
Рыбки если плавают то остальное всё будет тоже работать
http://webglsamples.org/aquarium/aquarium.html

**Comment by NS-Clone** [comment]
клацнул на серпенте52
webgl.force-enabled;true 
и заплавали
![2024-02-19_210307](https://github.com/Feodor2/Mypal68/assets/139008911/858cb1bb-486e-4be2-b405-7fb036030e66)

**Comment by Feodor2** [comment]
да без тех **именно двоих** настроек они не будут плавать

**Comment by NS-Clone** [comment]
> да без тех **именно двоих** настроек они не будут плавать

на мупаале они включены
и другие тесты что то рисуют
и показывают что что то рабоотает
(а если отключить то не рисуют и не показывают)
на серпенте я тушел вебгл

щас тыкаю разные настройки в мупале
но рыбки не появляютсо

**Comment by NS-Clone** [comment]
рыбок нет
а вот blob с того же сайтека рработаает
![2024-02-19_211306](https://github.com/Feodor2/Mypal68/assets/139008911/d06f1022-02fb-40e9-aa36-4a8d494887a3)

**Comment by Feodor2** [comment]
Та успокаойся, трогать нужно только 2 вышеуказанные настройки и ничего больше.
Если не поплыли, то ещё попробовать то что показал @jonm58 и всё, и не забудь все настройки вернуть назад.

**Comment by NS-Clone** [comment]
> Если не поплыли, то ещё попробовать то что показал @jonm58 и всё, и не

он предложил софтваре рендорор?

**Comment by NS-Clone** [comment]
нет испоганеть не получилось
хотя в некоторых случае в начале именно такая картинка как на мупале
на несколько секунд

layers.low-precision-buffer;true на мупале так же вощвращал на место
но это ничего не дало

**Comment by NS-Clone** [comment]
вот сравнение результатов этого теста
https://browserleaks.com/webgl

![2024-02-19_215355](https://github.com/Feodor2/Mypal68/assets/139008911/3536e78b-dbf7-458c-966d-9915a3d0b5f6)
![2024-02-19_215413](https://github.com/Feodor2/Mypal68/assets/139008911/e9beb98f-ae69-40c1-85ec-cc932f563675)

**Comment by NS-Clone** [comment]
или этот angle тоже софтварный рендорор?

**Comment by NS-Clone** [comment]
> Mesa3D's libEGL.dll and libGLESv2.dll are used

where is this mesa3d?
usually there is only opengl32.dll dxtn.dll

**Comment by jonm58** [comment]
1.I'm use One core API
2.mesa3d is software renderer,like google angle

![browserleaks-webgl-2024_02_20_09_46_01](https://github.com/Feodor2/Mypal68/assets/73036321/a9c3d011-3034-4aa4-ad69-ecd575bd740b)


> > Mesa3D's libEGL.dll and libGLESv2.dll are used
> 
> where is this mesa3d? usually there is only opengl32.dll dxtn.dll

https://github.com/pal1000/mesa-dist-win

**Comment by NS-Clone** [comment]
> 2.mesa3d is software renderer,like google angle

i know
and in all mesa3d "packages" that i have
there is no any libEGL.dll, libGLESv2.dll

also last for XP from that link 17.1.8.401-1
is without libEGL.dll, libGLESv2.dll too :rofl:

**Comment by NS-Clone** [comment]
> https://github.com/pal1000/mesa-dist-win

also in releases they are mention ARM64
is there any ARM64 binaries there?

**Comment by jonm58** [comment]
> > 2.mesa3d is software renderer,like google angle
> 
> i know and in all mesa3d "packages" that i have there is no any libEGL.dll, libGLESv2.dll
> 
> also last mesa3d for XP from your link 17.1.8.401-1 is without libEGL.dll, libGLESv2.dll too 🤣

> 1.I'm use One core API

what do you mean?
![图片](https://github.com/Feodor2/Mypal68/assets/73036321/69d2ee82-1ba7-4280-88db-094f0b3fadd4)
![图片](https://github.com/Feodor2/Mypal68/assets/73036321/84f702a1-efe9-4cbc-8049-cc4330ace1e7)

also you can set
webgl.enable-draft-extensions;true
webgl.enable-surface-texture;true
webgl.enable-privileged-extensions;true

**Comment by NS-Clone** [comment]
> what do you mean?
without ocapi there is
![2024-02-20_060829](https://github.com/Feodor2/Mypal68/assets/139008911/87fa3748-9192-405d-90ef-de6012ec6bd3)
![2024-02-20_060917](https://github.com/Feodor2/Mypal68/assets/139008911/c7bef574-c481-4f94-957d-90c56eb7fae5)

**Comment by jonm58** [comment]
sorry
"Mesa3D EGL library used by OpenGL ES drivers. This debuted in 21.3.0"
https://github.com/pal1000/mesa-dist-win?tab=readme-ov-file#opengl-es-drivers-and-egl-library

**Comment by Feodor2** [comment]
So no way then
[NS-Clone](https://github.com/NS-Clone) tell please the model of your videocard
