### ISSUE TITLE
Some websites do not work properly

### ISSUE THREAD

**Issue by Gelip** [Feodor2/Mypal68#380]
Why the some websites does not work correctly:
[https://winraid.level1techs.com/](url)
[https://discourse.coreelec.org/](url)
`Unfortunately, [your browser is unsupported](https://www.discourse.org/faq/#browser). Please [switch to a supported browser](https://browsehappy.com/) to view rich content, log in and reply.`

**Comment by K4sum1** [comment]
Add this to your uBlock Origin filters. (If you don't have uBlock Origin, just get it, you really should use an adblocker)

```
! Block Discourse browser detect script
browser-detect-$script
```

The real solution would be for MyPal68 to satisfy this script, but not sure when that will come. It would need to satisfy the requirements and also fake the user agent to 89 or later

https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/scripts/browser-detect.js

**Comment by K4sum1** [comment]
@Feodor2 I still get the Discourse error with 68.14.3

![ScreenShot_20240721131746](https://github.com/user-attachments/assets/9b05ed02-a156-4b0e-8e4f-0f60f2119d27)
