### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by TiredOfWindows** [Feodor2/Mypal68#382]

**Comment by TiredOfWindows** [comment]
Hi, I downloaded and used MyPal 68.13.8 on two of my Win XP computers and it seems you are on the right track, Keep up the good work!

**Comment by JimMP68User** [comment]
> Hi, I downloaded and used MyPal 68.13.8 on two of my Win XP computers and it seems you are on the right track, Keep up the good work!

Q: Why you no use 68.13.7b as recommended? Are you using early 386 design CPU?  Thanks in advance for answer.

**Comment by TiredOfWindows** [comment]
Both computers have PIII processors and Mypal 68.13.7 would not start on either one. 68.13.8 runs Ok but slowly with many warnings about slow or long running scripts. Sent from my iPhoneOn Feb 14, 2024, at 11:55 AM, JimMP68User ***@***.***> wrote:﻿

Hi, I downloaded and used MyPal 68.13.8 on two of my Win XP computers and it seems you are on the right track, Keep up the good work!

Q: Why you no use 68.13.7b as recommended? Are you using early 386 design CPU?  Thanks in advance for answer.

**Comment by Feodor2** [comment]
cheers
