### ISSUE TITLE
Mypal68 Release v.68.13.9b has been released !

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#383]
Check this Site to download the latest Mypal v.68.13.9b:
https://codeberg.org/Theodor2/Mypal68/releases/tag/68.13.9b

**Comment by JimMP68User** [comment]
But, "Theodor2"?

**Comment by NS-Clone** [comment]
> But, "Theodor2"?

ancient TH == F
ancient PH == F

**Comment by NS-Clone** [comment]
так Discord на вид работает

**Comment by NS-Clone** [comment]
дискорда глючит при скролле
![2024-02-17_193526_](https://github.com/Feodor2/Mypal68/assets/139008911/3e150b18-7f23-46db-8ef7-6c4178f68efc)

хотя чисто субъективно
браузер отзывваетсо быстрее чем 68.13.7

**Comment by NS-Clone** [comment]
вообще со скроллом и перерисовкой экрана серъезные глюки
![2024-02-17_193815_](https://github.com/Feodor2/Mypal68/assets/139008911/e5b72c22-bd81-468d-a4cd-ae5588ff67a5)

**Comment by NS-Clone** [comment]
и если в 68.13.7
при скролле участки не дорисовывались на пару кадров
то щас активно дублируетсо одна строка
и так и остаетсо навсегда
и помогает только F5

**Comment by NS-Clone** [comment]
сессию на 900 вкладок оно тоже не может востановить
![2024-02-17_195145](https://github.com/Feodor2/Mypal68/assets/139008911/838a57b4-5e09-40e3-9daf-cb4e67726c0b)
и при этом браузер так же зависает на всегда как и 68.13.7
68.13.8 выдавал ругательства что ваши вкладки наипнулись и браузер не нужно было перезапускать
но там неработает дискдор

**Comment by NS-Clone** [comment]
а с этой размазывалкой браузер неюзабельный

**Comment by NS-Clone** [comment]
layers.force-active;true заставило перерисовыватсо

**Comment by NS-Clone** [comment]
еще помогло layers.low-precision-buffer;true

**Comment by NS-Clone** [comment]
а пробовал layers.allow-d3d9-fallback
ниче не дало

**Comment by NS-Clone** [comment]
от безысходносте запустил новомодный спермиум...
...о божо это нечто

оно из коробки создало 13 (тринадцать КАРЛ! процессов)
сожрала 2,5 гига рамы (при 0 вкладок! и лазении в настройках)
оно в принципе не может работать с HDD ибо им дико дрочет
только запуск браузера минуты 3
я нисмог открыть ни одной вкладки
только с SSD оно стало юзабельным
1 вкладка жрет гиг рамы
переодически рама отжыраетсо в количестве 1 гига
а потом в таком же количестве освобождаетсо
проц на половину нагружен на 1-й вкладке

ах ну и до
по дефолту оно еще оставляяет 8 процессов висеть в раме
после закрытия браузера


конешно нужный сайтек оно запустило...

вощем хром это для кипячения воды на рюзонах
всегда знал что юзоры хрома больные люди
ждем обновления фаирфокса
ибо я привык иметь 3-х значное число вкладок в браузере
а не единичное

**Comment by RamonUnch** [comment]
> дискорда глючит при скролле ![2024-02-17_193526_](https://private-user-images.githubusercontent.com/139008911/305661252-3e150b18-7f23-46db-8ef7-6c4178f68efc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDE0MzYsIm5iZiI6MTcwODI0MTEzNiwicGF0aCI6Ii8xMzkwMDg5MTEvMzA1NjYxMjUyLTNlMTUwYjE4LTdmMjMtNDZkYi04ZWY3LTZjNDE3OGY2OGVmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQwNzI1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDFmOGE2YmQ2NjNlODEwNDMyNzU4ZGRmNjBhNTE4ZjJhOTQ0ZmRjMTUwNGZkNmZjZTg1NmUyZmExZTc0ZWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qhRJUJcKd7Hyad-MV8hrtcrcn-0e4Gu26KqOd5lFyZE)
> 
> хотя чисто субъективно браузер отзывваетсо быстрее чем 68.13.7

I have the same issue, it can be fixed by disabling d3d9
just set `layers.allow-d3d9-fallback;false`

**Comment by JimMP68User** [comment]
> layers.force-active;true заставило перерисовыватсо хотя местами глюки остались (ноо они хотябы исчезают) ну и нагрузка явно стало на порядок большей это видимо чиссто отладошный режим

Where find the " layers.force-active;true  " script

to modify it?

**Comment by NS-Clone** [comment]
> > layers.force-active;true заставило перерисовыватсо хотя местами глюки остались (ноо они хотябы исчезают) ну и нагрузка явно стало на порядок большей это видимо чиссто отладошный режим
> 
> Where find the " layers.force-active;true " script
> 
> to modify it?

in about:config
but it's slow down browser
try layers.low-precision-buffer;true
it still glitching but less

**Comment by JimMP68User** [comment]
re: " in about:config "

Got it.

**Comment by mserafym** [comment]
> от безысходносте запустил новомодный спермиум... ...о божо это нечто
> 
> оно из коробки создало 13 (тринадцать КАРЛ! процессов) сожрала 2,5 гига рамы (при 0 вкладок! и лазении в настройках) оно в принципе не может работать с HDD ибо им дико дрочет только запуск браузера минуты 3 я нисмог открыть ни одной вкладки только с SSD оно стало юзабельным 1 вкладка жрет гиг рамы переодически рама отжыраетсо в количестве 1 гига а потом в таком же количестве освобождаетсо проц на половину нагружен на 1-й вкладке
> 
> ах ну и до по дефолту оно еще оставляяет 8 процессов висеть в раме после закрытия браузера
> 
> идо это гуафно не умеет нормально сохранять html-ки !!!!!! о_О
> 
> конешно нужный сайтек оно запустило...
> 
> вощем хром это для кипячения воды на рюзонах всегда знал что юзоры хрома больные люди ждем обновления фаирфокса ибо я привык иметь 3-х значное число вкладок в браузере а не единичное
> 
> уж лучше бы вин32сс фаирфокс100500 портировал :)


Поставил ради тестирования...
Не знаю, что там у вас "сожрало" у меня работает нормально, потребление RAM в норме, не вылезает за рамки стандартного потребления для хромиум-портов в Windows XP.
Работает быстро, но с мультимедиа, как обычно, траблы в WinXP - как и у других хромиум-клонов. Много гюков
Но! скорость серфинга впечатляет! Сказывается очень быстрый JS движок.

28 открытых вкладок, потребление:
![RAM](https://github.com/Feodor2/Mypal68/assets/28388059/a632da2f-ce62-4741-95f8-708a449a3f54)

**Comment by Feodor2** [comment]
Hey the bug with scrolling was discovered for a long time.
Seems you still get it because you mess with settings, do not do this
Do you really know about that layers..... stuff, i think not
Anyway with default settings i do not reproduce this, so you take vanilla profile and check again

**Comment by JimMP68User** [comment]
> Поставил ради тестирования... Не знаю, что там у вас "сожрало" у меня работает нормально, потребление RAM в норме, не вылезает за рамки стандартного потребления для хромиум-портов в Windows XP. Работает быстро, но с мультимедиа, как обычно, траблы в WinXP - как и у других хромиум-клонов. Много гюков Но! скорость серфинга впечатляет! Сказывается очень быстрый JS движок.
> 
> 28 открытых вкладок, потребление:

Have 835 tabs open here, not every tab has been clicked on to make "active" on screen since last reload of Mypal68, but have maybe 15 to 25 active tabs this morning (810 then not active refresh), and was playing two videos (Rumble and Youtube) at the same time using Mypal68 version 13.9b

PC is year 2008 Dell Optiplex 755 with Core2 Duo 8400 CPU at 3 GHz and 4 GB or ram, and have video accelerator card too.

Only site I  have issue with is www.wordpress.com after login my screen goes white with WP logo in center of screen but there is HTML that was loaded (View Page Source) but nothing displayed except WP logo.

**Comment by NS-Clone** [comment]
> 28 открытых вкладок, потребление:

это фотошоп! :)

> стандартного потребления для хромиум

так я и говорю
хромые ненужны

**Comment by NS-Clone** [comment]
> Do you really know about that layers..... stuff, i think not
> Anyway with default settings i do not reproduce this, so you take vanilla profile and check again

ну на этом браузере я полез менять слои
когда скролл уже отвалилсо...
да и менял только что то связанное с вебгл....

потом проверю чистый браузер


большая прооблема что браузер гарантированно крашитсо
в 3 из 4 востановлений предыдущей сессии

**Comment by mserafym** [comment]
> > 28 открытых вкладок, потребление:
> 
> это фотошоп! :)
> 
> > стандартного потребления для хромиум
> 
> так я и говорю хромые ненужны

Нет, это не фотошоп, это просто кому-то лень почитать issues и добавить пару файликов, которые предложил автор после обнаружения "конфликта" с VS Redistributable 2015-2019.

**Comment by NS-Clone** [comment]
> > > 28 открытых вкладок, потребление:
> > 
> > 
> > это фотошоп! :)
> > > стандартного потребления для хромиум
> > 
> > 
> > так я и говорю хромые ненужны
> 
> Нет, это не фотошоп, это просто кому-то лень почитать issues и добавить пару файликов, которые предложил автор после обнаружения "конфликта" с VS Redistributable 2015-2019.

ну пральна
все ж вокруг телепаты и знают что среди 100500 issues-ов аффтар дето положил файлик
без которого нехрена ниработаит

**Comment by Feodor2** [comment]
У меня сейчас 137 вкладок 800 - 1Гб,  браузер крутиться с выхола 13.9,
думаю ещё 20 я споконйо могу пользовать а дальше больше не надо.
Я думаю только 64 версия будет более менее номально с тысячами вкладок работать.

**Comment by NS-Clone** [comment]
> У меня сейчас 137 вкладок 800 - 1Гб

про хромой или про мупал?

**Comment by NS-Clone** [comment]
а кстате наадо попрообывать уменшить раазмер окна до миннимума
и глянуть что будет

**Comment by NS-Clone** [comment]
@Feodor2 а мож объяснить по русске
чаго смещение кода с базового адреса
у них вызывает 10 ккратное потреблене рамы?
 https://github.com/win32ss/supermium/issues/251

**Comment by Feodor2** [comment]
> чаго смещение кода с базового адреса

Это старая проблема хромых с этими файликами, если они установлены в системе. Нужно их удалить из системы (msvs redist 2015),  когда-то я пользовался 360хромым, а майпал был ещё совсем сырым. Этот новый хром я не хочу пробовать потому что он совсем не для хр изготовляется,  думаю работа под хр там побочная вещь типа маленький бонус, если там не будут конкретно вычищатся все вещи для win10+ он и дальше бдутет больше жрать, а махинации с апи-мс файликами мало помогут

**Comment by NS-Clone** [comment]
> Нужно их удалить из системы

я так понимаю у меня chroome.dll вообще смещает prio.dll
который я удолять не собираюсь (проще удолитть хромого Ж)

**Comment by NS-Clone** [comment]
чистый 68.13.9
![2024-02-19_232237](https://github.com/Feodor2/Mypal68/assets/139008911/9faa70f5-c542-4d75-aa40-9677fa497c30)
1024 about:blank востанавливает без проблем
памяти жрет мало и размер окна не влияет
![2024-02-19_232135](https://github.com/Feodor2/Mypal68/assets/139008911/0de3cfaf-b281-4c07-93b2-aa0a04ac3940)

НО рабоочий браузер с маленьким окном я уже 2 раза подряд востановил с маленьким окном
буду скриншотитть график памяти на время запуска с разным размером окна
и потом выложуу ррезультат

**Comment by NS-Clone** [comment]
на щет дудбирования оддной строки
чистый 68.13.9
чистый профиль
глюка на месте
![2024-02-19_231453_](https://github.com/Feodor2/Mypal68/assets/139008911/74a60f43-a7f8-4b22-bdac-df4ee8a4a6a3)

**Comment by NS-Clone** [comment]
угу в отличие от других параметрров
для layers.allow-d3d9-fallback;false нужен перезапуск
