### ISSUE TITLE
Set myPal68 as the default browser in the Windows XP

### ISSUE THREAD

**Issue by LuckyTil** [Feodor2/Mypal68#384]
1. Now, the option "Set as default browser" does not work in the XP SP3 x86.
Can You fix this?

2. How does mypal check if it is the default browser? That check does not work. What registry key(s) should be modified?

**Comment by Feodor2** [comment]
Did it ever worked before? If so you then have already set the default browser
I never bothered to fix this because think its useless, i may fix later along with the installer they related, when browser be ready for the installer.
If you want to set the default browser everyday, then may create installer yourself.
Take any mozilla browser and make it default, search registry, get keys, replace mozilllas with mypals, put this all to cmd or make nsis installer whatever.

**Comment by etsenberg** [comment]
> Did it ever worked before? If so you then have already set the default browser I never bothered to fix this because think its useless, i may fix later along with the installer they related, when browser be ready for the installer. If you want to set the default browser everyday, then may create installer yourself. Take any mozilla browser and make it default, search registry, get keys, replace mozilllas with mypals, put this all to cmd or make nsis installer whatever.

No, it never worked, and it's annoying. I corrected the following keys:

[HKEY_CLASSES_ROOT\.htm]
@="mypalHTML"
"Content Type"="text/html"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\.html]
@="mypalHTML"
"Content Type"="text/html"
"PerceivedType"="text"

[HKEY_CLASSES_ROOT\MypalHTML\shell\open\command]
@="\"C:\\Program Files\\mypal-68.13.7.en-US.win32\\mypal\\mypal.exe\" -osint -url \"%1\""

[HKEY_CLASSES_ROOT\http\shell\open\command]
@="\"C:\\Program Files\\mypal-68.13.7.en-US.win32\\mypal\\mypal.exe\" -osint -url \"%1\""

But every time I start mypal, it asks me if I want to make it the default browser! I uncheck the box "check if it is default", but it doesn't help. The next time - the same question, and the box is checked again! How to disable this check if it does not work correctly?

**Comment by Feodor2** [comment]
Reset browser.shell... settings

**Comment by Feodor2** [comment]
The easiest way is to take the old mypal 29 install and set default then replace with the new mypal.
So if I am not going fix the thing soon, then try yourself, and the option has been hidden on intent, when will fix may restore it easy.

**Comment by K4sum1** [comment]
Made a registry thing to set as default. Kinda broken, control panel set as default doesn't work but if you open a thing and pick Mypal, it gets set as default.

[mypaltest.zip](https://github.com/Feodor2/Mypal68/files/15269600/mypaltest.zip)

**Comment by K4sum1** [comment]
Does set as default browser work now?

**Comment by K4sum1** [comment]
@Feodor2 This is not fixed in 68.14.3. I still do not have the option to set as default.

**Comment by Robbbert** [comment]
I had noticed this yesterday, MyPal doesn't show in the list of browsers to choose one for default.

I will try the patch from K4sum1.
