### ISSUE TITLE
multiword search tries to resolve site instead of searching

### ISSUE THREAD

**Issue by wesinator** [Feodor2/Mypal68#385]
68.13.8b

a normal multiword search only tries to resolve the search string as a site instead of sending it to the search engine.
![mypal68_search_text_trying_to_visit_site](https://github.com/Feodor2/Mypal68/assets/5124946/c3adf466-0e87-4374-ae7c-a18dbc4c0bbf)
you have to manually arrow down to a search engine which is an extra step and not the expected address bar behaviour.

**Comment by RamonUnch** [comment]
#101
