### ISSUE TITLE
dup

### ISSUE THREAD

**Issue by abcxyz0123** [Feodor2/Mypal68#388]
I have tried running the 64-bit version (68.13.8b) of MyPal68 on Windows XP x64 and get a "Couldn't load XPCOM" error.  I am able to run the 32-bit version of MyPal68 (68.13.8b) without any issue.

![untitled](https://github.com/Feodor2/Mypal68/assets/107862236/b645a433-da9a-4746-ba21-5d6abc71b818)

**Comment by RamonUnch** [comment]
See Issue #35
