### ISSUE TITLE
PDF View/Download error V68.12.2b

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal68#39]
I change the PDF of preview in MyPal and save.
Here it happens that the PDF is not displayed in MyPal.
Many tabs are opened, which want to display the PDF, but the PDF are listed in the TEMP folder with 0 bytes as * .part.
I have to close PayPal, otherwise further tabs will be opened.

**Comment by IP-CAM** [comment]
works perfect!
![show_download_pdf_file](https://user-images.githubusercontent.com/12776547/163852927-4eb753d0-6bf6-4e12-a5ae-b87753b01800.png)

**Comment by Anbima** [comment]
Goto about:preferences
Change PDF in applications to "inquire every time"
Open a PDF and choose in "open with" "MyPal"

**Comment by Feodor2** [comment]
What is the actual error? 
I did like you - opened pdf - selected open with mypal - it asks again - certainly because of the set "ask every time"

**Comment by Anbima** [comment]
Goto about:preferences
Change PDF in applications to "inquire every time"
Open a PDF and choose in "open with" "MyPal"

The PDF is not displayed in PayPal, but again the page is displayed with the selection as it should be opened.

**Comment by Feodor2** [comment]
So what is the actual error? You turn this setting and get what it is does - "inquire every time".

**Comment by Anbima** [comment]
The PDF is not displayed.
It always comes the message for the selection again and again.

**Comment by Feodor2** [comment]
> It always comes the message for the selection again and again.

"inquire every time" means this right, what do you expect then?

**Comment by Anbima** [comment]
It opens a new tab each time and the PDF is not displayed.
![Screenshot](https://user-images.githubusercontent.com/49531928/164914825-985c1c68-2061-4572-8421-d6ed88a7db27.jpg)

**Comment by Feodor2** [comment]
SURE you set to not display but "inquire every time" so it does eXACTLY as you set.

**Comment by Anbima** [comment]
When the window above appears, I click "Durchsuchen..." and select "Mypal".
Then I click 2x "OK".
Now the PDF should be displayed in Mypal.
But it doesn't. It always comes back to the selection as in the picture.
You will see that multiple tabs with the same name are open.

**Comment by Feodor2** [comment]
You get what you set by yourself and i completely do not understand what else do you want sorry.

**Comment by Anbima** [comment]
I choose that the PDF should be displayed with Mypal. But the PDF is not displayed, but it is repeatedly opened the window with the selection.

I explain it again with pictures.

Setting in MyPal:
![1](https://user-images.githubusercontent.com/49531928/164935917-2584389f-7900-435b-bf82-0c135e214ab2.jpg)

Open URL of PDF.

Click on "Durchsuchen":
![2](https://user-images.githubusercontent.com/49531928/164936479-b46f4759-5d07-4a08-9fcd-294fa0836db6.jpg)

Choose "Mypal":
![3](https://user-images.githubusercontent.com/49531928/164936526-18640286-fea1-4ff9-8ef8-375e8392f6bc.jpg)

Klick "OK":
![4](https://user-images.githubusercontent.com/49531928/164936556-26a28d98-e18b-4006-94e2-82a9bfe49651.jpg)

Now the PDF should be displayed in MyPal.
But this is not displayed. It comes again the selection.

Can you reproduce it?

**Comment by Feodor2** [comment]
> Now the PDF should be displayed in MyPal.

This is wrong, if you set "inquire every time" it will do it every time. May be you want new setting like "inquire one time"?

**Comment by Anbima** [comment]
If I selected "Open with MyPal" and then click OK, the PDF must be displayed in MyPal.
Anything else would be wrong.

**Comment by Feodor2** [comment]
Not understanding. 
"inquire every time" what means.
Someone else explain please.
