### ISSUE TITLE
v68.13.9b is losing all the top menu bars when maximizing videos into full-screen mode and after exiting full-screen mode by ESC button

### ISSUE THREAD

**Issue by PLudkovski** [Feodor2/Mypal68#390]
v68.13.9b is losing all the top menu bars when maximizing videos into full-screen mode and after exiting full-screen mode by ESC button
Only the side-scroll bar (on the right side) seems to be retained after hitting the ESC button.
This happens on Youtube, Pornhub and various other video sites.

Am i the only one experiencing this ??
What could possibly went wrong?

**Comment by Feodor2** [comment]
This is a new bug, to be fixed by the next version.

**Comment by PLudkovski** [comment]
Thank You, Sir
