### ISSUE TITLE
v68.13.9b causes EXTREMELY HEAVY CPU-Load (approximating 100% of ONE Core)  results in responsiveness deficit / freezing

### ISSUE THREAD

**Issue by PLudkovski** [Feodor2/Mypal68#395]
v68.13.9b causes EXTREMELY HEAVY CPU-Load (approximating 100% of ONE Core) and results in responsiveness deficit / freezing
This can clearly be observed in the Windows Task Manager.

So far i have observed this alarming behaviour only when opening this website:

https://poloniex.com/trade/LTC_BTC/?type=spot

I have intentionally posted this here, and not in the non-working websites section, because:
**A)** it seems to be a very serious bug, probably worth investigating the root cause
**B)** technically the website is loading & rendering and can be used (albeit with dramatically reduced responsivity)

And my suspicion is, that at least some other websites using similar code, will potentially cause the same issue.

Or am i the only one experiencing it?

Best Greetings from Poland !

**Comment by jonm58** [comment]
Do you have a graphics card?

**Comment by Feodor2** [comment]
I think this is not a bug, this is such a site not suitable for weak computers.
If you find another such site please tell.
Also may try it on another browser, chromish one seems has better performance, may be the site optimised for chrome special.

**Comment by PLudkovski** [comment]
> Do you have a graphics card?

Yes, the screen is connected to a graphics card over DVI.
My graphics card is an old nVidia GeForce GTX 460.

My CPU is also relatively old, but its not a weak one:
Intel Xeon E5-1660 @3.3 GHz (it has 6 Physical Cores + supports Hyperthreading = 12 Logical Cores)
&  64 GByte of ECC memory

So its old, but definitely not a weak machine.
I am surprised if nobody else experiences the same 100% CPU-Load (on **ONE** of the Cores) causing (nearly) freezing,
whenever opening the above-mentioned URL. Something seems to be fishy, causing continual EXTREME CPU-Load.

**Comment by jonm58** [comment]
try

> > Do you have a graphics card?
> 
> Yes, the screen is connected to a graphics card over DVI. My graphics card is an old nVidia GeForce GTX 460.
> 
> My CPU is also relatively old, but its not a weak one: Intel Xeon E5-1660 @3.3 GHz (it has 6 Physical Cores + supports Hyperthreading = 12 Logical Cores) & 64 GByte of ECC memory
> 
> So its old, but definitely not a weak machine. I am surprised if nobody else experiences the same 100% CPU-Load (on **ONE** of the Cores) causing (nearly) freezing, whenever opening the above-mentioned URL. Something seems to be fishy, causing continual EXTREME CPU-Load.

idk,try Turn on "multiprocess mode"???
or seem multiprocess mode has some bug?

**Comment by PLudkovski** [comment]
> try
> 
> > > Do you have a graphics card?
> > 
> > 
> > Yes, the screen is connected to a graphics card over DVI. My graphics card is an old nVidia GeForce GTX 460.
> > My CPU is also relatively old, but its not a weak one: Intel Xeon E5-1660 @3.3 GHz (it has 6 Physical Cores + supports Hyperthreading = 12 Logical Cores) & 64 GByte of ECC memory
> > So its old, but definitely not a weak machine. I am surprised if nobody else experiences the same 100% CPU-Load (on **ONE** of the Cores) causing (nearly) freezing, whenever opening the above-mentioned URL. Something seems to be fishy, causing continual EXTREME CPU-Load.
> 
> idk,try Turn on "multiprocess mode"??? or seem multiprocess mode has some bug?

Yes, but this bug can best be spotted with the setting:

**browser.tabs.remote.autostart = false**

because on a single process running in the Task Manager, one can clearly see how **ONE** of the Cores will be constantly burdened with 100% CPU-Load.

Don´t you experience this on your machine, with dramatically reduced responsivity?

**Comment by Feodor2** [comment]
The site loads the core of the modern cpu too and on the recent firedox.
Obviously when to switch for single process the whole browser will glitch.

**Comment by NoNameNeeded5** [comment]
I can only confirm what Feodor says:
The CPU load is also quite high on a modern computer with Win11 and a recent version of Firefox.
On chrome based browsers the CPU load is a little bit lower, however, every 4 seconds or so it will rise considerably. I could actually hear the CPU fan to speed up every 4 seconds. It definitely shouldn't be that way.
So this website is a big mess, their developer should really fix it, maybe you should try to reach him if this website is important to you?

**Comment by PLudkovski** [comment]
> I can only confirm what Feodor says: The CPU load is also quite high on a modern computer with Win11 and a recent version of Firefox. On chrome based browsers the CPU load is a little bit lower, however, every 4 seconds or so it will rise considerably. I could actually hear the CPU fan speeding up every 4 seconds. It definitely shouldn't be that way. So this website is a big mess, their developer should really fix it, maybe you should try to reach him if this website is important to you?

Thanks for posting your observation.
I added a second non-working website to the concerning section over here:
**NOT WORKING SITES LIST [POST HERE ONLY!] #228**

Thanks,
Pavel
