### ISSUE TITLE
URL кодирование

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#397]
браузер любит портить ссылки при копипасте для мало понятных в 21-м веке целей (и по моему это еще и не везде отключаемо)
и при этом сам же не в состоянии их декодировать (в адресной строке)
если всякие ``:`` и ``\`` закоддированы тоже
например
``https%3A%2F%2Fgithub.com%2FFeodor2%2FMypal68%2Fissues``

**Comment by jonm58** [comment]
is UTF-8? lol
