### ISSUE TITLE
Better dark mode

### ISSUE THREAD

**Issue by K4sum1** [Feodor2/Mypal68#399]
Enabling dark mode should also enable the code that displays a dark mode version of the page. An example of this is it should recognize the CSS @media (prefers-color-scheme: dark) if the dark theme is enabled and use it. There are also some websites that do this in JS instead, but I have no idea what all that entails. This CSS code was added to Firefox 67, so it is there. Just this early on it reflected the system settings and not the browser theme. Considering 10 1709 and 8.1 and earlier don't have a proper dark mode, this always defaults to light mode.

Also making the settings page dark like in current Firefox would be cool too.
![ScreenShot_20240316035512](https://github.com/Feodor2/Mypal68/assets/77039240/acb935ba-6fa1-4987-a803-eb6524579eb6)

**Comment by K4sum1** [comment]
So this should be able to be fixed by a GUI option to set browser.in-content.dark-mode to true, and ui.systemUsesDarkTheme to 1. Although I needed to restart browser for it to take effect

MyPal even already has dark mode settings with these both set.
![ScreenShot_20240317062415](https://github.com/Feodor2/Mypal68/assets/77039240/dcf7efcc-6025-48fc-930d-113336940294)

**Comment by Feodor2** [comment]
I shall look to set them default
