### ISSUE TITLE
Google.com search results options do not appear

### ISSUE THREAD

**Issue by Logicomedian** [Feodor2/Mypal68#404]
When you scroll down the fetched results after a google search, there are the 3 dots right to the translate this page. 
This function does not operate (no scroll down menu).

**Comment by RamonUnch** [comment]
related:
* #245
* #295
* #311

**Comment by RamonUnch** [comment]
Sorry for misreading your issue.
For me, using the latest 68.13.9b I have no issue, when I click the three dots I see the side panel pop up properly.
