### ISSUE TITLE
Save as type blank when saving files

### ISSUE THREAD

**Issue by K4sum1** [Feodor2/Mypal68#406]
When saving downloaded files, save as type is just blank, and I can't set it to anything. It seems to be just a visual bug though as if I remove the extension it still gets saved with the proper one.

![ScreenShot_20240318095529](https://github.com/Feodor2/Mypal68/assets/77039240/038fc992-368b-4b89-9705-14c903b3894d)

**Comment by NS-Clone** [comment]
опять же и тут косяк
не всегда нужен этот original extension
я его специально меняю (потому что так нада Ж)
а оно мне его востанавливает...

**Comment by Feodor2** [comment]
No time for look into this, may be after the next version.

**Comment by NS-Clone** [comment]
печально что roytam не пилит свой mypal68

**Comment by Feodor2** [comment]
ага бизон, ройтам сосредоточен на пельменных.
I do not confirm the bug by the way
![image](https://github.com/Feodor2/Mypal68/assets/19492771/631a681b-4e1a-4ef6-810e-497f263edd43)
