### ISSUE TITLE
Having issues with extensions (Ublock Origin)

### ISSUE THREAD

**Issue by Stuffonthe8s** [Feodor2/Mypal68#41]
So I just got the new MyPal, which I have to say when it is working, performance has been great for me, so I am excited to see where the new development goes. Along with the BSOD issues upon closing I have seen well noted already, I am personally having a lot of issues getting my Ublock Origin to work. I am seeing others here report success with it, so I can't seem to figure out why mine isn't working. First, I tried installing from the main Firefox extension page, which would install the extension, but it would not work in any noticeable way and wouldn't show at the top either, only showing on my list of extensions. Upon trying to uninstall it, I was brought to realize that it would not fully remove itself. It would uninstall and then glitching anytime I tried to install it again. I also tried using XPI files only to be given an error. I even tried deleting my profile and trying again to no avail. I am not sure what is going on. Is there anything specific that I need to be doing here, or is this a common issue?

**Comment by win98se** [comment]
Try to restart Mypal68 just after installing uBlock Origin. This worked for me, also a bug since 68.12.2b.

**Comment by Feodor2** [comment]
For ublock look #9
What others extensions issues do you have

**Comment by grof017** [comment]
Not a big issue but I notice next. No matter which extension try to disable it doesn't appear (disabled}, this will appear always after third attempt. Now if I try to enable any extension it never be enabled and appeared in tools menu until restart of MyPal. Ublock always crash.

**Comment by Feodor2** [comment]
> No matter which extension try to disable it doesn't appear (disabled}

I am examining this error already so before it fixed disable and do restart.

**Comment by tymsh01** [comment]
> > No matter which extension try to disable it doesn't appear (disabled}
> 
> I am examining this error already so before it fixed disable and do restart.

Feodor2, first of all thanks for your all effort. 
Any update on this error? This started to be a big trouble for me. I can't delete any extension which i've installed before. 
It always seems "have been removed" and "undo" buttons after even i restart + exit and start + restart pc etc.

Tried eveything as can as i do. I delete extension xpi files, folders...Still same. I also delete some *sqlite files. Still same.

So now, for example i can't install another version of "same" extension or for example i can't install "ublock legacy"

My motivation is, "ublock" was perfect OK and i want to use it so much but actually "ublock origin" is so problematic add-on for my XP SP3. 

After i start with safe mode, i can use Google Drive without any problem. But once ublock origin active, it always ends with crashes.

Btw for all of others attention, 

* I disabled browser.tabs.remote.autostart;false
* Process count "0"
* Even i added MOZ_FORCE_DISABLE_E10S with value "1"
* And my laptop sse2 supported Win XP SP3 (No PAE) with 4 GB RAM 

Also, in even SAFE MODE, 
*protonmail still crashes and can't open (old version and new -- tried both)

And this extension disable-remove problem is continuing as my biggest problem.

Hope you can update soon. Thanks again for your all efforts.

**Comment by Stuffonthe8s** [comment]
I'm sorry for the late response. I can confirm that on the newer builds that restarting MyPal after installing Ublock Origin seems to have fixed that issue. Thank you
