### ISSUE TITLE
URL bar often mistakes searches for domains

### ISSUE THREAD

**Issue by K4sum1** [Feodor2/Mypal68#410]
For example if I want to search the name of a Minecraft mod, I click rename, copy the selected name, and paste it in my browser. For this example, I will use UniversalTweaks-1.12.2-1.10.0. If I copy and paste this into Mypal, instead of searching it, it treats it like a website, and it immediately fails to connect because it's not a proper domain. Modern versions of Firefox don't have this issue.

**Comment by K4sum1** [comment]
I like to just throw my cursor to one bar. I don't want to have to use two bars.

**Comment by Feodor2** [comment]
#101

**Comment by K4sum1** [comment]
> #101

@Feodor2 take another look at this issue, it's not related to 101. It's an upstream issue.

**Comment by Feodor2** [comment]
So you have set keyword thing and still get the error, is it?

**Comment by K4sum1** [comment]
Yeah, I even got the information in the comment above (https://github.com/Feodor2/Mypal68/issues/410#issuecomment-2010757872) testing stock Firefox alpha releases. It's an old Firefox issue.

**Comment by K4sum1** [comment]
@Feodor2 Can you reopen please. I might try fixing this stuff once I start trying to build Mypal.
