### ISSUE TITLE
Reverse the NN1–Fx61 Bookmark Description Field UI removal

### ISSUE THREAD

**Issue by walmar** [Feodor2/Mypal68#416]
To restore the native ability to manage bookmarks with a description.

References:
* [View Bookmarks - Menu Items - Netscape Handbook (1994) - mcom.com](http://home.mcom.com/home/manual_docs/menus.html#RTFToC7)
* [Creating a Bookmark Folder - ou.edu](https://www.ou.edu/class/webstudy/n4/old/N_Creating_a_Bookmark_Folder.htm)
* ~~[1402890 - Stop supporting and remove the description annotation - Bugzilla - Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1402890)~~
* [1463738 - Remove the Bookmark description UI - Bugzilla - Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1463738)
* [mozilla-central - changeset 420406:e9a9f3abd88935b5d4106a53d15d956ab2870ac4 - mozilla.org](https://hg.mozilla.org/mozilla-central/rev/e9a9f3abd889)
* [#diff-6d7440c2b1819b5f4b32bfcf6a71599c - Bug 1463738 - Remove the Bookmark description UI. r=dao - mozilla/gecko-dev@9f30e28 - GitHub](https://github.com/mozilla/gecko-dev/commit/9f30e2893402b316367f5e0b21b2d72fbe5a7afb#diff-6d7440c2b1819b5f4b32bfcf6a71599c)
* [Changed - Firefox 62.0, See All New Features, Updates and Fixes - Mozilla](https://www.mozilla.org/en-US/firefox/62.0/releasenotes/)

Below is a quote from [Properties window - Firefox Help - Firefox Bookmarks Tutorial (The Mozilla Help Site) - Gunnars](https://mozilla.gunnars.net/firefox_bookmarks_tutorial.html#Bookmarking_a_page) for a quick overview that does not require opening the links listed above.
> Description: You can enter a description for your site here. This can be useful when you have many bookmarks or the site's address or name don't indicate what the site is about.

<details><summary>Illustration of the transition for the bookmark properties dialog window</summary>

I found the image on a Mozilla server.

![Image](https://assets-prod.sumo.prod.webservices.mozgcp.net/media/uploads/images/2018-09-08-10-51-44-944b02.png)

</details>

**Comment by Feodor2** [comment]
So you did not tell why to do it.

**Comment by walmar** [comment]
I thought the purpose of the missing field was somewhat self-explanatory and is explained further in the references.

I also think it's more the other way around, that the official Firefox release notes don't specify why this general functionality should be removed.

However, I have added more information to the issue. Let me know if there's anything else you'd like to know.

**Comment by Feodor2** [comment]
Ah, i never used this feature, and did not notice that it has been removed. 
I ask everybody else is it worth to be restored, and i would not to lose time for this before complete the next version.

**Comment by Feodor2** [comment]
So no anybody else cares.
