### ISSUE TITLE
Loading of "Legacy" XUL extensions with overlays

### ISSUE THREAD

**Issue by walmar** [Feodor2/Mypal68#417]
Is there a way to load – modified – overlay extensions?

Waterfox Current 2020.10, another Firefox 68 based browser, has an integrated loader from the Thunderbird project for this purpose.

References:
* [Waterfox/browser/components/extensions/common/src/Overlays.jsm at 2020.10-current · WaterfoxCo/Waterfox · GitHub](https://github.com/WaterfoxCo/Waterfox/blob/2020.10-current/browser/components/extensions/common/src/Overlays.jsm)
* [Engage the new overlay loader · MrAlex94/Waterfox Wiki · GitHub - Internet Archive](https://web.archive.org/web/20200214034114/https://github.com/MrAlex94/Waterfox/wiki/Engage-the-new-overlay-loader)
* [Convert Overlay Extension to Legacy WebExtension | Thunderbird](https://developer.thunderbird.net/add-ons/updating/tb68/overlays)
* ["Legacy" XUL extensions with overlays - Thunderbird/Add-ons Guide 63 - MozillaWiki](https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63#.22Legacy.22_XUL_extensions_with_overlays)

**Comment by K4sum1** [comment]
Not sure how well that would work. Mypal68 isn't really 68 anymore. It's more like 78 with 68 GUI, and soon 91 with 68 GUI. Not sure if the old XUL code between versions is kept around or not. Why I suggest something integrated in https://github.com/Feodor2/Mypal68/issues/400 instead of this.

**Comment by Feodor2** [comment]
dup
Answered on #27

**Comment by Ariel-Schnee** [comment]
I really wish this thing could use legacy extensions.



---

Signature - SFW - https://www.fanficparadise.com/arielschnee/sig3.htm
Signature - NSFW - https://www.fanficparadise.com/arielschnee/sig3_NSFW.htm

**Comment by walmar** [comment]
@K4sum1

The combination of Firefox 68 with updated web features is one of the main reasons I'm considering using this browser on a daily basis.

I only brought up the overlay loader integration because I couldn't find any other documented approach (including userChromeJS) for loading this particular type of overlay extensions.

But as you can see, the owner does not really care about the topic anyway - when deciding to treat the collected information about a overlay loader as developed by the Thunderbird team like as part of a more generally conversation about XUL stuff. And now this issue turns into another distracted conversation about all kinds of Firefox extensions.

So loading - modified - overlay extensions will not happen unless there is a fork with this loader or someone explains how to load the same extension files via userChromeJS or a similar approach.
