### ISSUE TITLE
Separator in bookmarks toolbar

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#418]
собственно разделитель не отображаетсо на панели закладокк если его создать 
(не знаю работало ли оно когда либо в квантууме ибо только щас попыталсо привести в поррядок панельку чтоб было как в старом фаирфоксе)
хотя оно работает в выпадающих менюшках

**Comment by Feodor2** [comment]
У меня отображаеться.
Anybody else please check this.

**Comment by NS-Clone** [comment]
ага в старой версии и у меня работает
нужно опять копать

еще может дело в "отключить визуальное оформление" в совместимости?

**Comment by NS-Clone** [comment]
а собственно так и есть
![2024-04-17_172034](https://github.com/Feodor2/Mypal68/assets/139008911/b103996c-93b6-4399-b732-210beeab4de8)
![2024-04-17_172059](https://github.com/Feodor2/Mypal68/assets/139008911/8dc3acfd-889c-451f-94b2-d73916bbc27f)


![2024-04-17_172047](https://github.com/Feodor2/Mypal68/assets/139008911/54466e39-250c-4f81-aad3-de825d0b62d3)
