### ISSUE TITLE
Port Mypal to macOS

### ISSUE THREAD

**Issue by brunochanrio** [Feodor2/Mypal68#419]
Anyone can port Mypal to the Apple macOS operating system? And is possible to make it compatible with Apple Silicon?

**Comment by Feodor2** [comment]
And tips is the same as for the ubuntu
#418

**Comment by Feodor2** [comment]
And tips is the same as for the ubuntu
#361

**Comment by FlorianisonGitHub** [comment]
And port it to iBook G3/G4/G5 PowerPCs, because TenFourFox is completely outdated.
