### ISSUE TITLE
Can't Access Fanfiction.net Stories Anymore

### ISSUE THREAD

**Issue by Ariel-Schnee** [Feodor2/Mypal68#421]
I keep getting the runaround when it asks me to verify I'm human.

I click that I am.

Then it loops back to asking the same thing once again.

**Comment by IP-CAM** [comment]
Try this latest MyPal Version 68.13.9b (32-bit) it should then work as planned:
https://codeberg.org/Theodor2

**Comment by Ariel-Schnee** [comment]
> Try this latest MyPal Version 68.13.9b (32-bit) it should then work as planned: https://codeberg.org/Theodor2

Is that an official release? I thought they only released here (https://github.com/Feodor2/Mypal68/releases). Hmmm...

**Comment by Feodor2** [comment]
Yes, I did not it here because gitgub was broken for me of the missing features.
The next release soon will be here.

**Comment by Ariel-Schnee** [comment]
> Try this latest MyPal Version 68.13.9b (32-bit) it should then work as planned: https://codeberg.org/Theodor2

It didn't work. I'm still stuck in the damn loop.:)

Oh flibberjisting nuts.

**Comment by RamonUnch** [comment]
Would it be possible to tell about the other repo on https://codeberg.org/Theodor2 on the readme.md file, or maybe a pinned issue? So that people that are not following the issues threads closely can still easily find the new repo.

**Comment by Feodor2** [comment]
Sure i can now edit github README
