### ISSUE TITLE
What was done to get video decoding working on XP? Also probably enable it for all platforms too

### ISSUE THREAD

**Issue by K4sum1** [Feodor2/Mypal68#423]
I would like to add this functionality to my browser to replace decoding using the media foundation on my browser r3dfox. However I'm not sure what commit added it, and the nondescript names on the early commits make it hard to figure out. Could you tell me what you did for video decoding on XP?

Why I would want to do this is to fix this issue where some videos play and some don't. https://github.com/Eclipse-Community/r3dfox/issues/9#issuecomment-2028442108 Supermium fixed it and Mypal fixed it but only on XP. I want to use the XP code globally to fix it globally.

**Comment by Feodor2** [comment]
\media\ffvpx
\dom\media\platforms\ffmpeg
Look roytam's too, he took my old stuff from mypal27 at first place, where it used system ffmpeg.

**Comment by K4sum1** [comment]
I don't think I can figure out how to apply a lot of unlisted changes like this. It's not that big of a concern for me. 

Keeping it open since the second part of having it enabled for more than XP might be worth doing.

**Comment by Feodor2** [comment]
For figure take original ffmeg source then look media\ffvpx\config_win32.h such a config.
Notice that I have removed cude nvenc as proved to be useless, so to delete leftovers

**Comment by K4sum1** [comment]
I've noticed videos on Twitter/X and Reddit do not play for me and idk if it's related to something done here.
I didn't think anything of it when it first happened thinking something was being funny with the network, so I'm not entirely sure when it began.
