### ISSUE TITLE
Add option for disabling/enabling e10s in about:preferences

### ISSUE THREAD

**Issue by K4sum1** [Feodor2/Mypal68#424]
I think it would be a good idea to have a GUI option for enabling/disabling e10s in preferences. I think put it under the performance options under the hardware acceleration tickbox.

**Comment by Feodor2** [comment]
Why, I think this is unnecessary.
I shall continue update javascript css servo and yes low-memory-unload-tab too, then audioworklet, direct9 webgl and webtrc. But not going to look at all for minor and unnecessary things

**Comment by K4sum1** [comment]
I could probably make it and send it as a pr sometime when I have some free time away from r3dfox.

**Comment by Feodor2** [comment]
But why a waste? I know you have your own browser, if your already have complete all tasks on it and don't know what to do,.you may do necessary things here instead.

**Comment by K4sum1** [comment]
Yeah, that's the plan. I eventually want to work on a Mypal68 fork. No idea when this will be though.
