### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by pleasefixbug** [Feodor2/Mypal68#425]
so ... this issue is VERY VAD!
i included a video explaining the issue.
basically it is a bug with changing the language.
it is VERY BAD!
video is bigger that 10MB, so i uploaded it to youtube
https://youtu.be/tPWfe5SIbHc
if it says the video is doing something like idk if it does not play just come back in like a hour or so 
Thank You :D

**Comment by Feodor2** [comment]
Certainly. If you could search before post.
