### ISSUE TITLE
Implement JPEG XL

### ISSUE THREAD

**Issue by K4sum1** [Feodor2/Mypal68#429]
Would be cool to have

Relevant Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1707590

**Comment by Feodor2** [comment]
Again why, is this really necessary? And where does it used?

**Comment by win98se** [comment]
Probably too early to ask for this feature, as of now only Apple Safari 17 is supporting it. https://caniuse.com/jpegxl

**Comment by jonm58** [comment]
> Probably too early to ask for this feature, as of now only Apple Safari 17 is supporting it. https://caniuse.com/jpegxl

No, there's also Firefox Nightly, Thorium, Pale Moon, and Waterfox that support jpegxl.
