### ISSUE TITLE
Twitter crashes with mypal 68.14.0 [This stupid and good example how not to make the issue]

### ISSUE THREAD

**Issue by tolengo** [Feodor2/Mypal68#431]
Hello pal, twitter is crashing all the time with this new version 68.14.0.
**Thanks for your work!**
![gah](https://github.com/Feodor2/Mypal68/assets/65049831/374233a3-e39a-4773-b9a7-097bbfcad5f7)

**Comment by Feodor2** [comment]
Please make the issue proper way, until this nothing to do

**Comment by JimMP68User** [comment]
> twitter is crashing all the time

Cannot find where it crashes. Have been in and out of Twitter all morning and no crashes.

**Comment by tolengo** [comment]
Why are you so rude? personal issues"?
My comment was respectful and grateful.

**Comment by tolengo** [comment]
Happy now?
![error](https://github.com/Feodor2/Mypal68/assets/65049831/fafe1e24-566f-4ec7-9ff1-c72eecaf591c)

**Comment by Feodor2** [comment]
Where was rude? You should have look there and further before post a new issue, but you did not.
![image](https://github.com/Feodor2/Mypal68/assets/19492771/f3f70f9a-c3c2-47e5-8f5f-418fb8d58af9)

**Comment by tolengo** [comment]
**Ok thanks. I posted my sistem before. I forgot this time.**
![sistema](https://github.com/Feodor2/Mypal68/assets/65049831/7f1750c1-1263-40bb-b58e-2762c3d9fbdc)

**Comment by NS-Clone** [comment]
ну за большие и очень известные сайты можно было бы и репортить отдельно
(и там можно решать как их заставить работать)
а вот конешно когда начинаетсо поток из неработает ocherednoihrenoten.to
да и ты принимаешь все сильно близко
хомяков полно
вон в issues-ах спepмиума творитсо не меньшее...

**Comment by Feodor2** [comment]
I do not reproduce, please give the drwatson.

**Comment by tolengo** [comment]
I deactivated "Hardware Acceleration" but the problem continues. It didn't happen to me with any previous version of MyPal.
The problem occurs very often on Twitter because it is a site that I use very frequently, but it will also happen in other sites.

**Comment by Feodor2** [comment]
Try new version

**Comment by tolengo** [comment]
> Try new version

I already did.
The same problem.
I previously deleted all references in the windows registry.
Thanks
![EEEEEEEE](https://github.com/Feodor2/Mypal68/assets/65049831/1ec5ffc1-f1d0-4fe6-a042-495984fd38a3)

**Comment by tolengo** [comment]
Gmail's own print menu where you have, for example, the option to save as PDF does not exist.

In its place the Windows XP print menu appears.
**Thanks**

**Comment by Feodor2** [comment]
please try this  https://github.com/Feodor2/Mypal68/releases/tag/testcrash%23427

**Comment by NS-Clone** [comment]
> Try new version

чисто субъективно
новая неврсия валитсо с этим исключением чаще чем предыдущая...
(но это конешно пальцем в небо ниче не значит)

**Comment by Feodor2** [comment]
для чего testcrash специльно выложил, и у него вроде номально уже

**Comment by tolengo** [comment]
> please try this https://github.com/Feodor2/Mypal68/releases/tag/testcrash%23427

Thanks but I really don't know what to do with that.

**Comment by Feodor2** [comment]
Sorry that expired the link here right
https://github.com/Feodor2/Mypal68/releases/tag/testcrash%234272

**Comment by tolengo** [comment]
> Sorry that expired the link here right https://github.com/Feodor2/Mypal68/releases/tag/testcrash%234272

Yes I have already downloaded that.
I don't know what it's for. I am a common user, not a programmer.
Thanks for your time.

**Comment by tolengo** [comment]
Too many random crashes.
Returning to version 68.13.7
