### ISSUE TITLE
Dup

### ISSUE THREAD

**Issue by TiredOfWindows** [Feodor2/Mypal68#432]
I am writing this from Mypal 68.13.8b. I downloaded the latest version Mypal 68.14.0 and it will not start in Windows XP SP3 I get the following message.

![image](https://github.com/Feodor2/Mypal68/assets/42479819/5c149416-ed64-42ff-a64e-2078db8bc11f)

**Comment by FlorianisonGitHub** [comment]
the sse/non-sse and win2000/xp rtm/xp sp1 ver is not complete yet...
