### ISSUE TITLE
Mypal 68.14.0 - Неверная кодировка некоторых строк в about:addons

### ISSUE THREAD

**Issue by zanud** [Feodor2/Mypal68#433]
Mypal 68.14.0
Windows XP (RU)

Сделал вчера модуль русификации для Mypal 68.14.0, установил его и обнаружил, что кое-что в about:addons выводится крокозябрами:
![rus](https://github.com/Feodor2/Mypal68/assets/76625744/13082dab-6e16-4e24-9c04-c85a939aaed7)

Для проверки "не я ли накосячил?" установил вместо своего русификатора тот, который скачал некогда с ru-board. Ошибка сохранилась и с ним.

Далее обнаружил, что то же самое наблюдается даже и без русификаторов. На свежесозданном чистом профиле имеем:
![eng](https://github.com/Feodor2/Mypal68/assets/76625744/68c0583c-84e9-4777-8897-fb85127fe5fc)

То есть, значение имеют языковые настройки не браузера, а операционной системы.
Ну, и суть ошибки традиционна: строку, находящуюся в какой-то национальной кодировке, интерпретируют как находящуюся в ANSI-1252.
Способов учудить подобное известно много, поэтому строить предположения, какой именно имеет место в данном случае, не буду, просто указываю на факт.

(В линейке 68.13 данная ошибка не наблюдается, так как там эта дата выводится на английском языке.)

**Comment by Feodor2** [comment]
Да есть такое, в следующей версии наверняка будет исправлено.

**Comment by zanud** [comment]
Кстати: сделанный .xpi выложить куда-то или оставить себе для сугубо личного употребления?

(Делал его так: распаковал из 68.14 подлежащие переводу файлы, сравнил их с аналогичными файлами из 68.13, после чего удалил из своего предыдущего перевода строки, ставшие ненужными, а те, которые появились новые, добавил, взяв из официального перевода Firefox 83.)

**Comment by Feodor2** [comment]
Как хочешь

**Comment by zanud** [comment]
Дело же не в "выкладывать или нет", а в том, как других пользователей известить о выложенном файле. По поводу локализаций 68.13 здесь хотя бы отдельная тема была.

В общем, залил его вот [сюда](https://disk.yandex.ru/d/tVS6MMjpG0CFmQ) и написал об этом в теме на ru-board.

**Comment by Feodor2** [comment]
> По поводу локализаций 68.13 здесь хотя бы отдельная тема была.

Она спрятана в глубине, ипользуй поиск

**Comment by zanud** [comment]
> Она спрятана в глубине, ипользуй поиск

А зачем мне её искать? Я о ней и так знаю, и даже свой перевод для 68.13 туда выкладывал. Но её называние же специфично (оно именно о 68.13), а сейчас уже 68.14.

> Я думаю сделать дату всегда англ независимо от языка

М-м-м. А в чём там вообще проблема? Я вчера увидел на ru-board упоминание о причастности ICU. Но я имел дело с ICU и, вроде, у меня тогда всё нормально было.

**Comment by Feodor2** [comment]
>Но её название же специфично (оно именно о 68.13)
да нет  Language Packs for mypal #203 

>М-м-м. А в чём там вообще проблема?
Слив русск языка

**Comment by zanud** [comment]
> да нет Language Packs for mypal #203

А, да. Я помнил, что она была посвящена конкретно 68.13.0, но чего-то мне казалось, что это и в название вынесено было.

> > М-м-м. А в чём там вообще проблема?
> 
> Слив русск языка

Я видел на ru-board упоминание, что ICU что-то там в дата портит. Но у меня в нескольких проектах ICU используется, и я такого в них не наблюдал.

Ткни, пожалуйста, пальцем в файл исходников MyPal, где этот "нехороший" вызов содержится, попробую посмотреть, что там происходит.
