### ISSUE TITLE
Superfox Theme for Mypal68?

### ISSUE THREAD

**Issue by FlorianisonGitHub** [Feodor2/Mypal68#434]
![mypal68](https://github.com/Feodor2/Mypal68/assets/111876654/f6ebec25-a8b4-4859-9b31-d8d24a99ccdb)

I installed Superfox theme for Mypal68, but I noticed glitches.

**Comment by Feodor2** [comment]
Likely it is not suitable, it must be notice about where state what browser and version it supports.
