### ISSUE TITLE
Mypal 68.14.0 - Косметические проблемы с поисковыми плагинами (1)

### ISSUE THREAD

**Issue by zanud** [Feodor2/Mypal68#435]
После перехода на версию 68.14 обнаружил, что при старте браузера в его консоли появляется пачка однотипных сообщений об ошибках вида:
> Error while loading 'jar:file:///C:/Program%20Files/Mypal68/browser/omni.ja!/chrome/browser/search-extensions/bing/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:517
> addons.xpi	WARN	Exception running bootstrap method startup on bing@search.mozilla.org: Error: Error while loading 'jar:file:///C:/Program%20Files/Mypal68/browser/omni.ja!/chrome/browser/search-extensions/bing/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:517:20) JS Stack trace: readJSON/</<@Extension.jsm:517:20
> onStopRequest@NetUtil.jsm:126:18

Да, у меня установлено много поисковых плагинов, в том числе и для сайтов, плагины к которым раньше были в Mypal штатно.

Начал разбираться. Обратил внимание, что ругается не на все мои плагины, а только на часть из них.  Начал разбираться с этим, проанализировал список тех, на которые ругается, и обнаружил, что он содержит исключительно те, которые раньше были в Mypal штатно. Причём в нынешней ругани присутствуют даже те из них, которые у меня сейчас вообще отсутствуют!

Покопавшись в разных файлах профиля, обнаружил, где эта собака закопана - в файле `addonStartup.json.lz4`. Профиль у меня живёт давно, я только браузеры обновляю, и записи с теми плагинами явно остались со времён, когда эти плагины были штатными.

Но как-то это нехорошо. 68.13.7 и предыдущие же не ругались. Так что лучше так и продолжать. Или удалять из `addonStartup` записи о компонентах, которых "живьём" уже нет.

**Comment by Feodor2** [comment]
Да можно безболезнено удалить, потом два раза перезагрузить или любое дополнение выкл\вкл

**Comment by zanud** [comment]
Нет, удаление файла не совсем безболезненно. Русификатор и словари проверки правописания после него подхватываются частично: в списке установленных дополнений они видны, причём показаны как активные, но по факту не работают, и в настройках браузера в менюшках выбора языка интерфейса и языка проверки правописания присутствует только английский. Так что эти компоненты, в отличие от обычных дополнений, после удаления `addonStartup.json.lz4` приходится по-новой устанавливать.

Но главное - о при частности`addonStartup.json.lz4` к данной проблеме пользователь же каким-то образом узнать должен. А откуда?

**Comment by Feodor2** [comment]
А два раза перегружал?

**Comment by Feodor2** [comment]
У меня профиль очень старый тоже, но языка не ставил только словарь еn-ru

**Comment by zanud** [comment]
Ну так у тебя и проблемы со значками поисковиков не было.

**Comment by Feodor2** [comment]
Я думаю уже немало пользуются языками, тут заявляли о французком и китайском, и никто пока на значки не жаловался.

**Comment by zanud** [comment]
А пропадание значков с наличием пакета локализации никак не связано. Локализация всплыла у нас уже по ходу переписки как пример того, что (у меня) не подхватилось автоматически после удаления обновления до 68.14. И я даже не знаю, был ли в этом виноват файл `addonStartup.json.lz4`, так как установил языковой пакет заново ещё до того, как начала ковыряться в `addonStartup`.
