### ISSUE TITLE
Mypal 68.14.0 - Косметические проблемы с поисковыми плагинами (2)

### ISSUE THREAD

**Issue by zanud** [Feodor2/Mypal68#436]
После обновления Mypal с 68.13.7 на 68.14.0 у поисковых плагинов DuckDuckGo и Brave пропали значки. Пропали везде - и в поисковой строке, и в разделе "Поиск" настроек браузера.

А у Quant и Mojeek значки остались. В чём разница между этими парами, непонятно.

Пробовал восстановить значки по-всякому - ни один способ не сработал.

Даже когда удаляю файл `search.json.mozlz4`, новый файл с четырьмя штатными поисковиками создаётся, но DuckDuckGo и Brave - без значков.

А в новом профиле значки есть у всех четырёх.

Почему так получается? Что мешает браузеру найти значки, которые внутрь него самого вшиты?

**Comment by Feodor2** [comment]
Понятное дело это в профиле, но у меня все значки на месте.

**Comment by zanud** [comment]
Всё, победил я значки. Но это маразм похлеще привязки имени каталога профиля к каталогу, из которого браузер запущен.

В исчезновении значков виновными оказались сразу два файла: `addonStartup.json.lz4` и `search.json.mozlz4`.

В `addonStartup.json.lz4` для каждого встроенного поискового плагина прописано `lastModifiedTime`, которое неизвестно откуда берётся (в omni.ja даты всех файлов всегда 01.01.2010 00:00:00) и непонятно что означает.

А в `search.json.mozlz4` для каждого встроенного поискового плагина прописан GUID-образный ID, который неизвестно откуда берётся (в omni.ja их ID email-образные) и непонятно от чего зависит (от одной и той же версии MyPal и одного и того же профиля я в процессе моих экспериментов получал в `addonStartup.json.lz4` разные ID).

И при любом отклонении любого из этих значений от того, что в данный момент желает увидеть браузер, приводит к исчезновению значка. А желания версии 68.14, как оказалось, не совпадают с желаниями 68.13. А файлы `addonStartup.json.lz4` и `search.json.mozlz4` от версии 68.13 тупо наследуются, и никакие изменения в них автоматически не вносятся ("см. пункт (1)").
Но при этом

**Comment by Feodor2** [comment]
Да эти файлы лучше зря  не трогать.
