### ISSUE TITLE
Better portable mode?

### ISSUE THREAD

**Issue by K4sum1** [Feodor2/Mypal68#438]
If using the pmprt.mod portable mode, it creates a Profile folder in the Mypal68 directory. What if Mypal68 instead detected the presence of a Profile folder in the application directory and just used that as an indicator for potable mode? Regular Mypal68 would not have this Profile folder, and it would make it not rely on a otherwise useless file.

**Comment by Feodor2** [comment]
You know there are two portable modes.
https://github.com/Feodor2/Mypal68/wiki/Portable#there-are-two-modes

And of course this is minor thing at all, instead you can do something really useful.
For example investigate these #427 #431 #437

**Comment by K4sum1** [comment]
I think the wiki suggests pmprt.mod can let multiple different profiles of the browser run, however all I get is a Close Mypal message saying it's not responding and to close it.

![image](https://github.com/Feodor2/Mypal68/assets/77039240/28908150-10b7-465d-b0a6-c78725a6a7b4)

If I click close, it just closes and opens right back up in my current profile. pmundprt.mod doesn't have this issue and just opens a new window.

It took multiple reads to even pick up on this difference so maybe it should be made more clear. I was using pmprt.mod for the longest time when it's pmundprt.mod that I would want. I still can't set browser as default though so idk if that's a difference either.

I cloned the Mypal68 style portable mode for my browser a bit back, and that included both files. There seems to be no difference at all here, not even a close message. I assume I missed something, but idk. This issue was created because I was suggested to make a portable mode that just checked for a Profile folder in the directory, and I tried taking a look and couldn't figure it out, so I tried asking here.

https://github.com/Eclipse-Community/r3dfox/commit/25c2fcba4b4c16e487adb486554ae0f633df1913

For those issues, to even begin to help I would first need to replicate the problem. I could probably do that in a VM and I do have a few Intel HD 4000 machines, however I'm currently busy, and the computers I use have no issues.

**Comment by Feodor2** [comment]
>I think the wiki suggests pmprt.mod can let multiple different profiles

That is 'multiple instances', each with its own profile, thought this is clear.

https://github.com/Feodor2/Mypal68/wiki/Portable#advanced-stuff
learn about --no-remote switch this is it
