### ISSUE TITLE
Script abort

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal68#439]
The following page is not built completely and the following error message appears:
https://www.amazon.de/AVM-VDSL-Supervectoring-DECT-Basis-deutschsprachige-Version/dp/B09RLYH43B

![Screenshot](https://github.com/Feodor2/Mypal68/assets/49531928/5c47f899-ab98-408c-8744-a0211647a840)

**Comment by Feodor2** [comment]
Do not abort, choose left button.

**Comment by Anbima** [comment]
Then it takes a long time again and the message appears again.
Until I have confirmed it three times.
And it has also happened that the browser has crashed.
What is the reason for this?

**Comment by Feodor2** [comment]
To be found the reason, what about other browsers regarding this?

**Comment by Anbima** [comment]
With 360Chrome 13.5 the page is displayed within 1-2 seconds (very fast) and there is no error.
With Mypal 29.3.0, the page takes a while to load, but there is no error.

**Comment by Feodor2** [comment]
> 360Chrome 13.5

And do all things work the same?

I recall on the old mypal I disabled this thing at all, yes this is annoying stupid shit, and "don't ask again" never works. The weaker machine you have and more monstrous site like the amazon as well then you get it always.
By the way on decent machine it works on mypal 68 and on chrome 109 the same
set **dom.use_watchdog;false**, while I consider set it default next version

**Comment by Feodor2** [comment]
For the amazon may be, on the AMD 8730 X8 it is not script abuse.
The chrome may not have this feature at all, so suggest disable it.

**Comment by NS-Clone** [comment]
> dom.use_watchdog;false

эта та шняга которая сообщает про зависшие жабоскрипты?
конешно она порядошно достает
но иногда то она помогает вернуть к жизни полностью зависший браузер
можот там есть какой нить threshold?
который можно подкрутить

**Comment by Feodor2** [comment]
Later I shall take newer fox to weak machine but with win7х64 and 8gb RAM.

@NS-Clone 
If on single process then yes this feature may be helpful, play with these
dom.max_script_run_time
dom.max_chrome_script_run_time
dom.max_ext_content_script_run_time

**Comment by Anbima** [comment]
But with 360Chrome 13.5, the Amazon page loads in a very short time.
And the processor is the same.

**Comment by NS-Clone** [comment]
> If on single process then yes this feature may be helpful

да квантум в отличаи от геков виснет с 100% загрузкой по всем ядрам
да и я давно на мультипроцессе
ибо на синглпроцессе глючит сохранение файлов

**Comment by Feodor2** [comment]
@Anbima
And I asked does the site works the same on 360, nothing broken and such.

**Comment by Anbima** [comment]
With 360Chrome, the page is displayed completely without error or abort.

**Comment by Feodor2** [comment]
Well I checked it on the similar machine Phenom II X3 3.5 and with both mypal and 360chrome.
It loads normally same without an one script abuse, so I don't know.
And later as I told shall check on weak machine with win7.

**Comment by NS-Clone** [comment]
> Well I checked it on the similar machine Phenom II X3 3.5 and with both mypal and 360chrome. It loads normally same without an one script abuse, so I don't know. And later as I told shall check on weak machine with win7.

да мало ли
может у него там локальная жабореклама вылазит
ты и не проверишь

умя подозрение что браузер вешаетсо на страницах где есть webp/webm видео в больших количествах

**Comment by Anbima** [comment]
I have noticed that the CPU load is only 25% when building the page.
Please find attached a screenshot.
Is this the same for you?

It takes 40 seconds for the page to load completely.
With 360Chrome it is 5 seconds.
![CPU](https://github.com/Feodor2/Mypal68/assets/49531928/0fb2b252-cc64-4556-93bf-b8017a60b1a6)

**Comment by Anbima** [comment]
I have run a network analysis via the console.
It works very quickly up to favicon.ico.
Then it takes a while for new entries to appear.
Further down there is another longer pause.

With Javascript deactivated, the favicon.ico is the last entry in the network analysis.
Mypal 68 cannot process the Javascript correctly.

Are there any settings here that I could test?

![Screenshot](https://github.com/Feodor2/Mypal68/assets/49531928/ffb73fa8-3956-4773-9e29-01e2f129c100)

**Comment by Feodor2** [comment]
Pentium dualcore 2.93  - 2gb RAM

**Mypal**
373 requests
112.62 MB / 86.96 MB transferred
Finish: 1.52 min
DOMContentLoaded: 9.26 s
load: 13.68 s

**360**
505 requests
27.3 MB transferred
54.1 MB resources
Finish: 2.4 min
DOMContentLoaded: 18.15 s

**Comment by Anbima** [comment]
**360Chrome 13.5**
506 requests
26.1 MB transferred
42.6 MB resources
Finish: 30.24 s
DOMContentLoaded: 7.38 s
Load: 9.62 s

In my test with Mypal68 DOMContentLoaded: 29.21 s.
That's much longer than yours. What could be the cause?

I have deactivated uBlock, that's not the reason.
I have also deactivated hardware acceleration as a test. No change.

**Comment by NS-Clone** [comment]
@Feodor2 вот кстате большая проблема этих не отвечающих скриптов
то что оно нахренато переводит фокус на вкладку с этим не отвечающим скриптом
и когда ты его не останавливаешь
тебе каждые 5 секунд возвращает на эту вкладку
и вообще проц в 100% при этом может грузить совершенно другой процесс
а браузер дергосмыкает при этом
