### ISSUE TITLE
RE: layers.acceleration.force-enabled

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#440]
> From 68.14.1 Intel for Direct9 are blacklisted, but you can enable it by 
> **layers.acceleration.force-enabled**
 Hello and thanks a lot for the new Release.
Question:
where do I have to add this Code ?
layers.acceleration.force-enabled

Best regards,
Ernie

**Comment by RamonUnch** [comment]
type `about:config` in the url bar, click Yes to the warning.
search for the `layers.acceleration.force-enabled` option, double click it to change its value.

In general when someone talks about advanced settings, thy are in the `about:config` page

**Comment by IP-CAM** [comment]
thank you very much!
