### ISSUE TITLE
68.14.1b does not recognize the copied user profile

### ISSUE THREAD

**Issue by erjot111** [Feodor2/Mypal68#441]
I copied the Profiles folder from 68.12.5b but 68.14.1b does not recognize it. After starting the browser, there is no changes.

**Comment by RamonUnch** [comment]
Have a look in `about:profiles` (type it in the url bar) you might have the old profile listed here and if it is the case you will be able to enable it from there.

Anyway there are a lot of difference between 68.12.5b and 68.14.1b so maybe a clean profile is a good idea to avoid configuration  problems.

**Comment by erjot111** [comment]
Thank you. I copied the Profiles folder from 68.12.5b to 68.14.1b and then created a new profile in it. At the moment, everything seems to work properly.
