### ISSUE TITLE
Read #355

### ISSUE THREAD

**Issue by FlorianisonGitHub** [Feodor2/Mypal68#444]
I am always wanting to test Mypal68 on Windows 98/ME with KernelEx/KernelEx Core, Windows 2000 without Extended Kernel, Windows XP SP0, SP1, and SP2, and processors for non-SSE and SSE only processors. Is there work in progress for these versions?

**Comment by Feodor2** [comment]
You know no one else cares, but this is not an excuse to make the duplicate issue.
