### ISSUE TITLE
MyPal stops responding when opening google or gmail

### ISSUE THREAD

**Issue by vkshaw0807** [Feodor2/Mypal68#448]
![screenshot](https://github.com/Feodor2/Mypal68/assets/104304803/e63b47cc-62cc-4e32-a233-caf31bc3aba1)

MyPal stops responding when opening Google or Gmail even on latest version of MyPal 68.14.1b.

the dialogue box shows is attached above.
after closing the dialogue box the page freeze until refreshing the page.

how to deal with this??

**Comment by Feodor2** [comment]
This is firefox specific thing, it indicates that you system is weak or bloated, you may disable this thing by dom.use_watchdog;false
There is the same issue #439, go there for further discussion.
