### ISSUE TITLE
[Docs] Build Enviroment?

### ISSUE THREAD

**Issue by roytam1** [Feodor2/Mypal68#45]
@Feodor2 please tell us how to compile mypal68, i.e. using which MSVC compiler (or EWDK), which version of `rustc` and `mozilla-build`.

**Comment by Feodor2** [comment]
I shall put it into the wiki.
Shortly - all stuff from the old instruction, but 8gb ram; some new utils for rebuilding rust; actual rust build; clang-cl

**Comment by roytam1** [comment]
don't know how many parts in old official build instruction can be applied: https://web.archive.org/web/20200630221246/https://firefox-source-docs.mozilla.org/setup/windows_build.html

**Comment by andika207** [comment]
@roytam1 do you want to compile something different or just help @Feodor2 improve his Mypal 68 ?

**Comment by roytam1** [comment]
> @roytam1 do you want to compile something different or just help @Feodor2 improve his Mypal 68 ?

both 😊

**Comment by andika207** [comment]
that sound cool.... 
the S52 is apparently based on FF68 but it simply doesn't support many addons that require FF57+ https://github.com/jannispinter/indicatetls/issues/47

**Comment by andika207** [comment]
that sounds cool.... 
the S52 is apparently based on FF68 but it simply doesn't support many addons that require FF57+ https://github.com/jannispinter/indicatetls/issues/47

**Comment by Feodor2** [comment]
I put the essential part https://github.com/Feodor2/Mypal68/wiki/Building-from-the-source
And my [rust patchs](https://github.com/Feodor2/Mypal68/files/8597633/rust.zip)

**Comment by roytam1** [comment]
> I put the essential part https://github.com/Feodor2/Mypal68/wiki/Building-from-the-source

can you explain more about building rustc and do I have to move rust compiler files manually?

**Comment by Feodor2** [comment]
@roytam1 
>can you explain more about building rustc and do I have to move rust compiler files manually

What part more you want to explain - if i did not write about move files so why do want to move? Have you built own rust?

**Comment by roytam1** [comment]
> What part more you want to explain - if i did not write about move files so why do want to move? Have you built own rust?

so the rust compiler lives in mypal68 tree? or I should download rust source tarball and extract it out of mypal tree and build it?

**Comment by Feodor2** [comment]
Ah the rust compiler is rustc.exe with few other files and it is not related to the mypal tree at all, and of course it is to be built before mypal building. I took rust source from github then set to the 1.35 version, all by git commands.

**Comment by roytam1** [comment]
when I really want to try building rust-1.35 on win7, there are some prerequisites:

- you need .NET framework 4.0 and PowerShell 2.0 installed
- you need to create `powershell.exe.config` to use .NET framework v4: https://stackoverflow.com/a/5069146
- you need to tell .NET v4 to use newer TLS: https://stackoverflow.com/a/63960229

then download rustc from https://static.rust-lang.org/dist/rustc-1.35.0-src.tar.gz

it tried to compile bootstrap:

```
$ python x.py
info: Downloading and building bootstrap before processing --help
      command. See src/bootstrap/README.md for help with common
      commands.
downloading https://static.rust-lang.org/dist/2019-05-14/rust-std-1.34.2-i686-pc-windows-msvc.tar.gz
extracting c:\mozilla-build-3.2\rustc-1.35.0-src\build\cache\2019-05-14\rust-std-1.34.2-i686-pc-windows-msvc.tar.gz
downloading https://static.rust-lang.org/dist/2019-05-14/rustc-1.34.2-i686-pc-windows-msvc.tar.gz
extracting c:\mozilla-build-3.2\rustc-1.35.0-src\build\cache\2019-05-14\rustc-1.34.2-i686-pc-windows-msvc.tar.gz
downloading https://static.rust-lang.org/dist/2019-05-14/cargo-0.35.0-i686-pc-windows-msvc.tar.gz
extracting c:\mozilla-build-3.2\rustc-1.35.0-src\build\cache\2019-05-14\cargo-0.35.0-i686-pc-windows-msvc.tar.gz
    Updating crates.io index
  Downloaded libc v0.2.51
  Downloaded cmake v0.1.33
  Downloaded cc v1.0.28
  Downloaded toml v0.4.10
  Downloaded lazy_static v0.2.11
  Downloaded petgraph v0.4.13
  Downloaded serde_json v1.0.33
  Downloaded serde v1.0.82
  Downloaded filetime v0.2.4
  Downloaded getopts v0.2.17
  Downloaded serde_derive v1.0.81
  Downloaded ryu v0.2.7
  Downloaded itoa v0.4.3
  Downloaded ordermap v0.3.5
  Downloaded cfg-if v0.1.6
  Downloaded fixedbitset v0.1.9
  Downloaded num_cpus v1.8.0
  Downloaded time v0.1.40
  Downloaded proc-macro2 v0.4.24
  Downloaded quote v0.6.10
  Downloaded syn v0.15.22
  Downloaded unicode-xid v0.1.0
  Downloaded winapi v0.3.6
   Compiling proc-macro2 v0.4.24
   Compiling unicode-xid v0.1.0
   Compiling ryu v0.2.7
   Compiling libc v0.2.51
   Compiling winapi v0.3.6
   Compiling serde v1.0.82
   Compiling itoa v0.4.3
   Compiling fixedbitset v0.1.9
   Compiling cc v1.0.28
   Compiling cfg-if v0.1.6
   Compiling ordermap v0.3.5
   Compiling getopts v0.2.17
   Compiling build_helper v0.1.0 (C:\mozilla-build-3.2\rustc-1.35.0-src\src\build_helper)
   Compiling lazy_static v0.2.11
   Compiling filetime v0.2.4
   Compiling petgraph v0.4.13
   Compiling num_cpus v1.8.0
   Compiling cmake v0.1.33
   Compiling quote v0.6.10
   Compiling syn v0.15.22
   Compiling time v0.1.40
   Compiling serde_derive v1.0.81
   Compiling toml v0.4.10
   Compiling serde_json v1.0.33
   Compiling bootstrap v0.0.0 (C:\mozilla-build-3.2\rustc-1.35.0-src\src\bootstrap)
    Finished dev [unoptimized] target(s) in 1m 29s
Usage: x.py <subcommand> [options] [<paths>...]

Subcommands:
    build       Compile either the compiler or libraries
    check       Compile either the compiler or libraries, using cargo check
    test        Build and run some test suites
    bench       Build and run some benchmarks
    doc         Build documentation
    clean       Clean out build directories
    dist        Build distribution artifacts
    install     Install distribution artifacts

To learn more about a subcommand, run `./x.py <subcommand> -h`
```

but when I really try to build, it fails:
```
$ cat config.toml
[llvm]
targets = "X86"
experimental-targets = ""
[build]
build = "i686-pc-windows-msvc"
host = "i686-pc-windows-msvc"
target = "i686-pc-windows-msvc"
docs = false

$ python x.py build
    Finished dev [unoptimized] target(s) in 0.42s
failed to parse TOML configuration 'config.toml': invalid type: string "i686-pc-windows-msvc", expected a sequence for key `build.host`
failed to run: c:\mozilla-build-3.2\rustc-1.35.0-src\build\bootstrap\debug\bootstrap build
Build completed unsuccessfully in 0:00:00
```

**Comment by Feodor2** [comment]
For config.toml brackets mean - host and target is to bracket.
The EWDK i use the same way and no VC 2015, though i have VC 2013 express installed including net4.

I remember errors with msbuild was fail to look include path
Look for files kile "Microsoft.Cpp.targets" where the word "useenv" is, delete all related that useenv

**Comment by roytam1** [comment]
@Feodor2 maybe it is easier if you may provide your copy of compiled rustc and/or clang-cl
 instead of people trying to figure out how to build them by themselves.

**Comment by Feodor2** [comment]
Not because i don't get license stuff which rust has different. This is not the obstacle too difficult, after you will set all things you begin malign whatever you want or try the oldest rust for win9x may be it will make.

**Comment by Feodor2** [comment]
Hell yes cmake unnecessary rely on msbiuld or unnecessary itself - modern fashion.
Examine config file where is possible to abandon LLVM building and set its regular setup.

**Comment by roytam1** [comment]
> So build both x86 and x64 rusts.

@Feodor2 and x64 rust's libstd can't link:
```
  = note:    Creating library C:\mozilla-build-3.2\rustc-1.35.0-src\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\std-d69cc7093c8783d5.dll.lib and object C:\mozilla-build-3.2\rustc-1.35.0-src\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\std-d69cc7093c8783d5.dll.exp
          std-d69cc7093c8783d5.std.5n8l6vgk-cgu.2.rcgu.o : error LNK2019: unresolved external symbol InterlockedIncrement referenced in function _ZN3std3sys7windows7condvar7Condvar12wait_timeout17hf3f32d74653dffedE
          std-d69cc7093c8783d5.std.5n8l6vgk-cgu.2.rcgu.o : error LNK2019: unresolved external symbol InterlockedExchangeAdd referenced in function _ZN3std3sys7windows7condvar7Condvar12wait_timeout17hf3f32d74653dffedE
          C:\mozilla-build-3.2\rustc-1.35.0-src\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\std-d69cc7093c8783d5.dll : fatal error LNK1120: 2 unresolved externals
```

**Comment by Feodor2** [comment]
Hmm.... did not get this. Do you use the same ewdk and llvm as i?
x86_64 lib not needed for x86 mypal so check if you have ready x64 rustc.exe (build\x86_64-pc-windows-msvc\stage2\bin) you may take it without lib

**Comment by roytam1** [comment]
> Hmm.... did not get this. Do you use the same ewdk and llvm as i?
> x86_64 lib not needed for x86 mypal so check if you have ready x64 rustc.exe (build\x86_64-pc-windows-msvc\stage2\bin) you may take it without lib

it didn't even get pass stage1, and I can build x86-32 rustc.exe only

**Comment by Feodor2** [comment]
This all mess about the rust lib so if you will not resolve the error preserve x86 lib then comment that code or cancel patch at all.

**Comment by NS-Clone** [comment]
а сколько сорцы весят вместе со всем git хламом?
