### ISSUE TITLE
v68.14.1b (32-bit) is badly CRASHING after opening: https://www.verifyemailaddress.org/

### ISSUE THREAD

**Issue by PLudkovski** [Feodor2/Mypal68#450]
Whenever trying to open the following URL:

https://www.verifyemailaddress.org/

Mypal v68.14.1b is crashing really bad, the process becomes unresponsive/stuck
and the dumprep.exe process is immediately started inside the Task Manager.
(at least this is what happens when running in the single-process mode, with
the flag: browser.tabs.remote.autostart = false )
Honestly, haven´t tested it in multi-process mode.
Am running it on Win2003 R2 Server 64-bit Enterprise Edition. (NT 5.2)

I have intentionally posted this here, and not in the non-working Sites section,
because the Crash is really bad and i believe deserves careful investigation,
because a similar Webpage source-code on other Sites could potentially cause
the same Crash there as well.

Can anyone else confirm this behaviour ??

**Comment by RamonUnch** [comment]
I can confirm the tab crash using Server 2003 32bit running on using a Core2Duo T7500 and hardware acceleration disabled.

However when suing uBlock Origin I get no crash, I was only able to reproduce the crash after disabling it.

I am using the testcrash release that fixed random youtube crashes soit is a dirrerent crash.
Here is the drwatson log file attached.

[drwtsn32log_Server2003x86.zip](https://github.com/Feodor2/Mypal68/files/15316518/drwtsn32log_Server2003x86.zip)

**Comment by Feodor2** [comment]
I do not get it no matter ublock, I shall make new patch according to your drwatson.

**Comment by Feodor2** [comment]
try new testcrash

**Comment by RamonUnch** [comment]
[drwtsn32log_Server2003x86_testcrash2.zip](https://github.com/Feodor2/Mypal68/files/15368103/drwtsn32log_Server2003x86_testcrash2.zip)

I still get a crash but location is different.

**Comment by Feodor2** [comment]
New version is out please check

**Comment by RamonUnch** [comment]
No more crash for me on this page, even with uBlock disabled! Hopefuly it also works for PLudkovski.
