### ISSUE TITLE
These sites are clearly not displayed correctly by the mypal 68.14.1b browser.

### ISSUE THREAD

**Issue by kiza124** [Feodor2/Mypal68#451]
These sites are clearly not displayed correctly by the mypal 68.14.1b browser.
https://supermarine.ru/catalog/honda/honda_cbf125t/?utm_source=yandex&utm_medium=cpc&utm_campaign=mot_hnd_tk|106843206&utm_content=5395797716|15791322695|213|desktop|www.ixbt.com&utm_term=---autotargeting|||cid-106843206|gbid-5395797716|adid-15791322695|pid-50260887116&yclid=12504357389843824639
https://supermarine.ru/catalog/honda/honda_cb350rs/?utm_source=yandex&utm_medium=cpc&utm_campaign=mot_hnd_tk|106843206&utm_content=5395797716|15791322695|213|desktop|forum.ixbt.com&utm_term=-- -autotargeting|||cid-106843206| gbid-5395797716|adid-15791322695|pid-50260887116&yclid=15723831772516712447
https://aliexpress.ru/item/1005004579436362/reviews.html?spm=a2g2w.detail.0.0.1f9435c7pfb5Te&filters=ONE_STAR&sku_id=12000029700087935 - The page is displayed distortedly and incorrectly, part of the page is not shown - reviews of those who bought the product (appears for a second and disappears)
https://roscontrol.com/product/sir-plavleniy-valio-viola-slivochniy/ 
https://i2hard.ru/publications/30396/ -sometimes it opens correctly, but cannot save to the hard drive correctly - when opening the saved file, a distorted image of the page is displayed.

**Comment by zanud** [comment]
Из любопытства попробовал сходить по ссылкам.
Первые две выглядят коряво.
Странички на Aliexpress нет (ошибка 404).
А последние две ссылки показываются совершенно нормально.

**Comment by Feodor2** [comment]
![image](https://github.com/Feodor2/Mypal68/assets/19492771/244a2b1b-fe77-4dcb-ac6e-8e87bdcc82cb)
Что тут непонятного, кидайте свои сайтитки туда, у меня нет времени проверять каждый.
@zanud 
Если нечего делать можешь определить чего им не хвататет.

**Comment by zanud** [comment]
Самый последний сайт из списка смотреть уж не стал, поскольку предполагал, что у него причина та же, что и у предпоследнего. А у этого предпоследнего увидел именно то, что и ожидал: старая известная проблема - браузеры сохраняют на диск не все файлы, которые нужны странице. Например, не сохраняются файлы, относительные ссылки на которые прописаны не в HTML, а в CSS. Потом файл открываем с диска, браузер не находит несохранённые перед этим файлы (стили, шрифты), вид страницы портится, иногда существенно.

Что там было у Aliexpress, посмотреть уже нельзя. А вот с первыми двумя ссылками (ведут на один и тот же сайт) - загадка.
Начнём с того, что Iceape (который XUL-based) показывает эти странички совершенно нормально. А в консоли (где отображение всего включено по максимуму) при этом пишет от двух ошибках:
1. `ReferenceError: $ is not defined`
2. `SyntaxError: missing ] after element list`

Mypal же эти странички показывает с совершенно убитой вёрсткой, и в его консоли (с ровно теми же настройками отображения) пишутся те же самые две ошибки. Однако, в отличие от Iceape, в Mypal-овской консоли ещё пишется и огромное число предупреждений. В основном они касаются CSS:
- `Неизвестное свойство «-moz-columns».  Потерянное объявление.`
- `Неизвестное свойство «color-scheme».  Потерянное объявление.`
- `Неизвестный псевдокласс или псевдоэлемент «has».  Набор правил проигнорирован из-за плохого селектора.`

и т.п., и, скорее всего, ломает странички что-то из этого.

Но также среди консольной ругани (почти в самом начале) есть вот такие три строки:
```
Загрузка <script> по адресу «https://bitrix.info/ba.js» не удалась.
Загрузка <script> по адресу «https://mod.calltouch.ru/init.js?id=s09z750c» не удалась.
Загрузка <script> по адресу «https://mc.yandex.ru/metrika/tag.js» не удалась.
```
и с чем эта ругань связана, непонятно, т.к. все три файла по этим ссылкам в отдельных вкладках прекрасно открываются. А на политики безопасности CORS в консоли жалоб нет, так что на это не спишешь.

--------
Да, и раз уж о безопасности заговорил, то вот что хочу спросить:
В консоли браузера очень часто встречаются сообщения вида:
`Попытка нарушения системы безопасности: содержимое «https://supermarine.ru/catalog/honda/honda_cb350rs/» не имеет права загружать moz-extension://e41d956a-6192-4935-a677-e4b63c10894c/overlay.html или ссылаться на него.`

Но расширения с ID e41d956a-6192-4935-a677-e4b63c10894c у меня нет, это явно что-то внутрибраузерное. Интересно, что именно.

**Comment by zanud** [comment]
Ага, после отключения `uBlock Origin` два скрипта из тех трёх стали загружаться (неподдающимся остался только `https://mc.yandex.ru/metrika/tag.js`), но вид странички это не исправило.

**Comment by zanud** [comment]
Поковырялся я подробнее с сайтом `https://supermarine.ru`. Ситуация такая: в HTML-коде указанных страничек имеются вот такие строчки:
```
<link rel="stylesheet" href="[/local/templates/supermarine/libs/slick.css](view-source:https://supermarine.ru/local/templates/supermarine/libs/slick.css)">
<link rel="preload" href="[/local/templates/supermarine/libs/jquery.fancybox.min.css](view-source:https://supermarine.ru/local/templates/supermarine/libs/jquery.fancybox.min.css)" as="style" onload="this.onload=null;this.rel='stylesheet'">
<link rel="preload" href="[/local/templates/supermarine/libs/jquery.formstyler.css](view-source:https://supermarine.ru/local/templates/supermarine/libs/jquery.formstyler.css)" as="style" onload="this.onload=null;this.rel='stylesheet'">
<link rel="preload" href="[/local/templates/supermarine/css/base.css?v=2.2](view-source:https://supermarine.ru/local/templates/supermarine/css/base.css?v=2.2)" as="style" onload="this.onload=null;this.rel='stylesheet'">
```
(нет, не в заголовке, а ближе к концу файла).

Из этих четырёх файлов стилей Mypal загружает только первый, остальные три игнорирует, а для правильного отображения страничек последний из них является критически важным.

Насколько я понял из своих экспериментов, Mypal такой вариант тега `<link>` вообще не поддерживает (в Firefox он с 85-й версии появился).

Дальше странности:
1.  При открытии простейшего файла:
```
<!DOCTYPE HTML>
<html>
<head>
</head>
<body>
<div>
  <p>P</p>
</div>
</body>
</html>
```
в веб-консоли Mypal появляется ругательство: `Неизвестное свойство «color-scheme».  Потерянное объявление.` - причём два раза на каждое открытие файла. Какая `color-scheme`, откуда?

2. С загадочным дополнением, упомянутым мной в прошлый раз, я разобрался - это установленное у меня **Link Status Redux** (настоящий ID которого вообще-то "linkstatus@jha.iki.fi"). Но какого чёрта веб-странички пытаются к нему обратиться? И как они вообще узнают о его существовании? По-моему, тут дело не в страничках, а сам Mypal чудит.

И ещё найденная в процессе разборок проблема:
В веб-консоли в сообщениях об ошибках справа показывается имя файла, где эта ошибка произошла. И во всех браузерах при щелчке по этому имени происходит переход к месту проблемы. А в Mypal 68.14.1 щелчок по имени ничего не делает (хотя всплывающая на имени файла подсказка именно этот переход и обещает).
А раньше такой щелчок работал.
