### ISSUE TITLE
browser.sessionstore.interval и не сохранение сессий

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#458]
браузер щас крашитсо постоянно
а вот сессии востанавливаютсо явно не сильно свежие

хотя в конфиге дефолтный browser.sessionstore.interval;15000
на 15 сек
щас же складываетсо впечатление
что сессия сохраняетсо только при закрытии браузера
и то не всегда

а еще есть какой то
browser.sessionstore.interval.idle;3600000
который непонятно чего значит

и вообще посоветуйте нормальный session manager для квантума
какой был/есть на геко
который может хранить сессии в разных! файлах
и при этом востанавливать сессию без 1К активных грузящихся вкладок
(на которых браузер гарантированно паадет)

**Comment by Feodor2** [comment]
У меня последнее время отрубает свет часто, но сесси всегда нормально восстанавливает, то есть мне встроенного функционала хватает, правда у меня то ссесии не по 1000 вкладок.

**Comment by NS-Clone** [comment]
> мне встроенного функционала хватает

ну на встроенном функционале
открыл вкладку и упал
и sessionstore-backups ужо пустое Ж)

**Comment by Feodor2** [comment]
Какую вкладку, ты видел другие репорты, если я это сам могу воспроизвести я чиню, если не могу то чиню по логу вацона, а так без конкретной ссылки или лога это ниочём - пшик, даже если проблема действительно есть.

**Comment by NS-Clone** [comment]
> Какую вкладку, ты видел другие репорты, если я это сам могу воспроизвести я чиню, если не могу то чиню по логу вацона, а так без конкретной ссылки или лога это ниочём - пшик, даже если проблема действительно есть.

это было всегда в фаирфоксе
вопрос про
работает ли официально сейчас это ежели 15 секундное сохранение
или уже нет

**Comment by NS-Clone** [comment]
а собственно сессии часто не сохраняютсо и без падений

**Comment by NS-Clone** [comment]
previous.jsonlz4


вощем смотрим
закрываю браузер
sessionstore-backups\recovery.jsonlz4
sessionstore-backups\recovery.baklz4
сразу удоляютсо

создаетсо
sessionstore.jsonlz4
уровнем вышо

sessionstore-backups\previous.jsonlz4
остаетсо лежать старый

запускаю блраузер
sessionstore-backups\previous.jsonlz4 сразу! заменяетсо новым?
и сразу создаетсо sessionstore-backups\recovery.jsonlz4


востанавливая сессию
тут замечаю что sessionstore.jsonlz4 уже нету


вощем кто то явно намудрил с бекапами...
нахрена бекапить каждые 3 секунды
если эти бекапы первым же делом чуть шо сносятсо?

**Comment by NS-Clone** [comment]
ну и еще одна извечная проблема

упали при востановлении сессии

sessionstore.jsonlz4 уже удолилсо

sessionstore-backups\previous.jsonlz4
sessionstore-backups\recovery.jsonlz4
лежат (при том recovery нормального размера)

запускаешь браузер опять
само востановить не предлагает
restore previous session засерено\недоступно

**Comment by NS-Clone** [comment]
> Какую вкладку, ты видел другие репорты, если я это сам могу воспроизвести я чиню, если не могу то чиню по логу вацона, а так без конкретной ссылки или лога это ниочём - пшик, даже если проблема действительно есть.

@Feodor2 вот конкретней
браузер еще работает

а ни recovery.jsonlz4 ни recovery.baklz4 тупа нету!
тобешь они либо не создались вообще 
либо удалились

но есть sessionstore.jsonlz4 уровнем выше
и можно предположить что тупо не создались
или оно перемещает sessionstore.jsonlz4 в sessionstore-backups
и переименовывает в recovery.jsonlz4
а перемещение не удаетсо

потом еще подкину туда recovery.jsonlz4 ручками
и посмотрю начнет ли он заменятсо
когда опять поймаю такое

**Comment by NS-Clone** [comment]
Наблюдение №2
случайно прибил браузер (кнопка закрыть оказалась браузерная а браузер не отвечал (поэтому он молча улетел))
нормально предложило востановить сессию
НО
recovery.baklz4
recovery.jsonlz4
лежат и дата у них не меняетсо...

**Comment by NS-Clone** [comment]
ну после этого
браузер успешно отказывалсо сохранять текущую сессию

и потом начал
![2024-06-14_140122](https://github.com/Feodor2/Mypal68/assets/139008911/afe6351e-84de-4e62-908b-07a3b451a2e4)

при этом при запуске браузера (с 0 вкладок) до востановления сессии
он сгенерировало новый recovery.jsonlz4 (ну тоесть затерев предыдущий recovery.baklz4)
при этом никаого sessionstore.jsonlz4 и небыло

**Comment by NS-Clone** [comment]
угу оно cpeт и в консоль
```
Could not write session state file  Error: TypeError: cannot use 'in' operator to search for "toMsg" in "out of memory"
    postMessage resource://gre/modules/PromiseWorker.jsm:349
 postMessage@resource://gre/modules/PromiseWorker.jsm:349:17
 ```

вот кстате тожо
 https://support.mozilla.org/uk/questions/1403535

**Comment by NS-Clone** [comment]
EnoughForAanybody[8388608]?

**Comment by NS-Clone** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1691498
(не могу щас редактировать псто)

**Comment by NS-Clone** [comment]
https://gist.github.com/jscher2000/d7c77f90bde6f37f526faa56c6a2b19e
тут они упоминают 125 случай не про оно?

**Comment by NS-Clone** [comment]
проредил about:config примерно как в 
https://support.mozilla.org/uk/questions/1403535
но размер файла сессии не уменьшилсо
