### ISSUE TITLE
toLocaleDateString() broken in 68.14

### ISSUE THREAD

**Issue by Pikse** [Feodor2/Mypal68#460]
```
 const day = new Date(2022, 3, 11);
 console.log(day.toLocaleDateString('en-US', { weekday: "short" }));
```
Starting MyPal 68.14.1 this returns `Mon Apr 11 2022 (GMT+0000)`.

In MyPal 68.13.9 it returned `Mon` which is the expected result.

These longer dates make text on my go-to weather site overlap and unreadable.

**Comment by Feodor2** [comment]
Please try the new version

**Comment by Pikse** [comment]
Fixed! Thanks.
