### ISSUE TITLE
Mypal 68.14.2 not working good but early version worked just fine

### ISSUE THREAD

**Issue by tolengo** [Feodor2/Mypal68#461]
Dear Mr. Feodor, I was using approximately for two weeks "Mypal 68.14.2".
I don't know if you uploaded it by mistake, or if it was an early version (then you deleted the link). But it worked quite well during all this time, without the crashes that had made me return to version 68.13

This new version 68.14.2 you uploadsed a couple of days ago is not going well. The browser itself is very slow and freezes at times. 
It has problem selecting objects in the screen for example I click an image and it opens the image above.
It feels like I have 16MB of RAM and my Internet connection is a 1995 telephone modem.

**Please reupload this early version I mentioned until the next update. 
Thank you very much for your time!**
![OP](https://github.com/Feodor2/Mypal68/assets/65049831/32e569bf-2e14-480a-b07e-d075a570fc30)

**Comment by Feodor2** [comment]
There is no difference, only one small bug fixed  (some lines removed inside browser.js file)
