### ISSUE TITLE
v68.14.2b (32-bit) causing multiple BSOD daily, error within nVidia library nv4_disp.dll anyone else ??

### ISSUE THREAD

**Issue by PLudkovski** [Feodor2/Mypal68#467]
v68.14.2b (32-bit) causing multiple BSOD daily, error within nVidia library nv4_disp.dll anyone else ??
My graphics card is an old EVGA GeForce GTX460 and OS is Windows Server 2003 R2 64-bit SP2 VL Enterprise Edition.

How exactly to troubleshoot what is causing it?

**Comment by PLudkovski** [comment]
Strange thing was, it did NOT happen with previous version v68.14.1b and i am heavily using it on daily basis.

**Comment by Feodor2** [comment]
Ensure this is not the the graphics card.
Try a 3d game or the furmark or finally go back to the previous mypal.

I think this the card is dying, did you watch the heat?
