### ISSUE TITLE
v68.14.2b_en_US_win32 - No option to update add-ons, no option to set default browser

### ISSUE THREAD

**Issue by migf1** [Feodor2/Mypal68#469]
Hello,
please bare with me, this is my very first time with the browser. Win XP Home SP3 32bit, on an ancient TOSHIBA Satellite M40 notebook: https://imgur.com/gb3YyJa

First of all I'd like to thank you guys very much for all you are doing! 

I'd like to ask where is the option to set mypal as my default browser (very very useful when other programs try to open links on the web, like avast or panda av for example), and also where is the option to update my installed extensions. I cannot find either of them.

As a side note, I noticed that not all firefox add-ons get installed (for example Bitwarden) but I guess that's normal, right?

Thanks in advance for any help you may provide!

PS. I also had some weird graphics glitches, with pictures and text producing very long vertical lines below them, but I fixed it by disabling hardware acceleration (although it hurts performance in my case).

**Comment by Feodor2** [comment]
This is was discussed already - use search
