### ISSUE TITLE
Do NOT try to install NOSCRIPT

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#47]
...or it will screw up your MyPal Installation. It cannot even be removed in full again. Just as warning !!!

**Comment by grof017** [comment]
![untitled](https://user-images.githubusercontent.com/81296923/164501174-caac72cf-d983-492c-b06e-4f39fd544dc9.JPG)
Work for me. Mine isn't install version.

**Comment by rocky7717** [comment]
@ip-cam

What version of No Script did you install to My Pal 68???

**Comment by Feodor2** [comment]
I have checked version from moziila, it seems normally. What other addons do you have?

**Comment by IP-CAM** [comment]
Sorry for the Delay, I don't recall, what Noscript Version Number I installed, but after hiding most all scriptings from Github, I unsuccessfully tried to remove NoScript again, to make my Github Repositories fully show all details again. NoScript now still exists in my (old) Installation, it's just disabled, but cannot be removed anymore.
I now installed another clean new MyPal in another Subdirectory, and I would like to know, what File does contain all my User Access Infos and Passwords. Could you please tell me, what File(s) I have to move into the new MyPal Installation, to have my Passwords available again available in the new Installation. Thank you !
