### ISSUE TITLE
FYI: MyPal cannot open Dropbox.com and Chase.com

### ISSUE THREAD

**Issue by DrestinBlack** [Feodor2/Mypal68#470]
I love using MyPal, it works great!

However, two sites I have great need to use I cannot open with MyPal: Dropbox and Chase (online banking).

Just wanted to bring it to the developers attention in case it hasn't been mentioned before.

Thanks in advance.

**Comment by hhihhio** [comment]
it may work on newer chromium browser

**Comment by Feodor2** [comment]
to the not working sites
