### ISSUE TITLE
not working site

### ISSUE THREAD

**Issue by sirrooster** [Feodor2/Mypal68#472]
https://t.co/B36JWmYIUK

https://www.sciencedirect.com/unsupported_browser

**Comment by hhihhio** [comment]
It require newer Chromium version browser. Just use Supermium instead if you have 4GB ram, I have to use Mypal because my PC only have 2GB RAM

**Comment by Feodor2** [comment]
Came to wrong place, look elsewhere for the chrome.

**Comment by sirrooster** [comment]
Superium is for Windows Vista.
I have XP32bit
