### ISSUE TITLE
Возможность добавления своих поисковых движков в браузер.

### ISSUE THREAD

**Issue by by-tndy** [Feodor2/Mypal68#473]
Возможно ли добавление собственных поисковых движков в браузер? ибо из предоставленных ниодин не подходит, и возможность добавления своих тоже не увидел

**Comment by Feodor2** [comment]
Всё точно также как в обычной лисе.
Вот только гугел такой пархатый что не предостовляет возможности добавить себя, по простому можно добавить через mycroftproject.com, но говорят что он сломался, короче если хочешь гугела то удаляй сразу этот браузер и переходи на хромой.

**Comment by by-tndy** [comment]
> Всё точно также как в обычной лисе. Вот только гугел такой пархатый что не предостовляет возможности добавить себя, по простому можно добавить через mycroftproject.com, но говорят что он сломался, короче если хочешь гугела то удаляй сразу этот браузер и переходи на хромой.

Ничего, и без гугла проживу. К счастью Яндекс добавился, но из строки к сожалению так же не работает, приходиться либо на начальном экране вводить запрос. Либо через отдельную строку, что неудобно и по уродски выглядит..
