### ISSUE TITLE
Cannot remove Extensions from my Github Site

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#474]
It must be some Javascrript-related Problem, because the Entry Field to remove Github Extensions does not show up on my latest version MyPal Browser.

**Comment by Feodor2** [comment]
Latest only? Some github things still broken, but will be fixed, I am working on it now.

**Comment by IP-CAM** [comment]
> Latest only? Some github things still broken, but will be fixed, I am working on it now.

Yes, older Version worked well on this.

**Comment by Feodor2** [comment]
Please try the new version

**Comment by IP-CAM** [comment]
Problem solved, thank you very much for the new Version!
