### ISSUE TITLE
Cross-Origin Request Blocked: when trying to log in to leonardo.ai (Mypal 68.14.1b)

### ISSUE THREAD

**Issue by etsenberg** [Feodor2/Mypal68#476]
Currently I see the problem when trying to log in with my google or microsoft account only at leonardo.ai website, several other sites which use the similar procedure of signing in work OK. Maybe it's a leonardo's bug (while it works OK in Firefox 115). But I checked the web console at leonardo page and found this error: 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o4504767521292288.ingest.sentry.io/api/4504767547179008/envelope/?sentry_key=a851bd902378477eae99cf74c62e142a&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F8.7.0. (Reason: CORS request did not succeed).
I checked the info about this error and found the following:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default
"From Firefox 68 to Firefox 84, https pages were not permitted to access http://localhost. This has been changed with [Bug 1488740](https://bugzil.la/1488740)."
May it be the reason?

**Comment by Feodor2** [comment]
Certainly this is not about a localhost, why would the page to mess with it.
This cosr sesureti stuff in 68 is outated, the site lilkely use its modern things, try disable csp.

**Comment by etsenberg** [comment]
> try disable csp
How?

**Comment by Feodor2** [comment]
security.csp.enable;false

**Comment by etsenberg** [comment]
> security.csp.enable;false

Great! Problem solved.
