### ISSUE TITLE
Browser based Chrome

### ISSUE THREAD

**Issue by hhihhio** [Feodor2/Mypal68#480]
Can you make a browser based Chrome 68 or 6x version? I want to use Chrome based browser for Windows XP & Vista without API or Extended Kernel but Chrome 6x or 84&8x seem suitable for weak old system. Supermium latest can't work on my 2GB RAM PC.

**Comment by hhihhio** [comment]
Current I use Mypal 68 64bit for Vista Home 64 bit, but some website can't load

**Comment by bluedragon-cairo** [comment]
Since Chrome is widely used by many people (though I don't), vulnerabilities get patched often, recently too. Two friends of mine got ransomware while using a youtube downloader site and they both used Chrome.

**Comment by bluedragon-cairo** [comment]
Also Firefox offers a lot of customizability, although it got severely limited after the stupid WebExtensions apocalypse, but still better customizability than Chrome. Older Firefox and Pale Moon which has XUL support is just amazing.

**Comment by bluedragon-cairo** [comment]
Pale Moon recently gained many speed optimizations in recent versions. Although it's still slower than Chrome, but still a lot better than the old Mypal 28.x era. Even YouTube Studio is usable these days.
