### ISSUE TITLE
68.14.3 - Неверное отображение некоторых локализованных сообщений

### ISSUE THREAD

**Issue by zanud** [Feodor2/Mypal68#482]
Обновил MyPal до 68.14.3. Посмотрел его потроха и обновил свой русский перевод до 68.14.3. Установил этот перевод, перезапустил MyPal, убедился, что он - как минимум - с новым переводом стартует.

Потом решил выйти из него и получил вот такое противоестественное сообщение:
![Ru1](https://github.com/user-attachments/assets/e42a148b-8bca-4370-9751-d80ea7c2bbb4)

Это при попытке выйти при одной открытой вкладке. Если выходить, когда открыто две вкладки, то сообщение нормальное:
![Ru2](https://github.com/user-attachments/assets/82efc41c-9197-43b8-ba27-1facd310646e)

Если вкладок пять и больше, то сообщение тоже нормальное (снимок делать не стал).

И это не проблема перевода - с родным американским языком картина аналогичная.
Выход при одной вкладке:
![En1](https://github.com/user-attachments/assets/cb99a370-cc87-4764-b109-42b22c6890c0)
Выход при двух и больше вкладок:
![En2](https://github.com/user-attachments/assets/217d93b4-7396-49aa-8733-e3fc0c10098a)

**Comment by Feodor2** [comment]
Таки не аналогичная, в англ правильно же.

**Comment by zanud** [comment]
Скажем так: не аналогичная, но всё равно неправильная.

1. **#** перед единицей говорит о том, что это placeholder, на место которого при выводе должен был быть подставлен параметр - но он не подставлен.
2. После **#1** написано "tabs", а не "tab". То есть, для вывода использована не первая часть сообщения (которая для единственного числа), а вторая, которая для множественного.
3. **;** в начале сообщения быть на должно было - это разделитель частей.

То есть, ошибка многогранней, чем кажется.

**Comment by Feodor2** [comment]
Ой да это не правильно, но терпимо, починю в следующей версии если не забуду, а почему на русск языке ещё больше не правильно?

**Comment by zanud** [comment]
Порылся по файлам языкового пакета. Похоже, что лажа только этим с предупреждением при выходе. Во всяком случае, в паре других мест (одно в браузере и одно в отладчике) всё нормально во всех случаях - независимо от языка и формы единственного/множественного числа.

> а почему на русск языке ещё больше не правильно?

А это уже не ко мне вопрос. В предыдущих версиях предупреждение при выходе с одной вкладкой не показывалось вовсе. Наверное, ты для его вывода добавил новые строчки в код и при этом не учёл, что с сообщениями, имеющими отдельные формы для множественного числа нужно работать особым образом.
Если я угадал, то просто посмотри, как оно выводилось при нескольких вкладках.

**Comment by zanud** [comment]
А ещё я не знаю, что сделает функция, готовящая сообщение к выводу, если ей имя сообщения передать, а число - нет. Она же на основе этого числа должна выбрать какой-то один вариант текста из нескольких. А числа-то и нет. Что она выдаст в результате?

Так что наблюдаемые странности могут и это своей причиной иметь.

**Comment by zanud** [comment]
Сегодня ("на свежую голову") ситуация чуть-чуть прояснилась: на самом деле в американском варианте мы видим не **";"** и вторую часть сообщения (для мн. числа), а, как и в русском варианте, всё сообщение целиком. Просто у них в этом сообщении нет(!) первой части (для ед. числа), оно содержит только часть для мн. числа (и разделитель перед ней):
> tabs.closeWarningMultiple=;You are about to close `#1` tabs. Are you sure you want to continue?

Там в американском файле `tabbrowser.properties` ещё несколько подобных сообщений есть, и все они без части для единственного числа. Т.е. никто ранее не собирался показывать это предупреждение при одной вкладке.

_(А в русском варианте предусмотрено и единственное число. Но это сообщение же не я переводил - оно целиком унаследовано из официального перевода Firefox.)_

**Comment by by-tndy** [comment]
Привет, можешь пожалуйста скинуть перевод? ибо с сайта мазилы видимо несовместим

**Comment by zanud** [comment]
@by-tndy:
https://disk.yandex.ru/d/WJYhe9A8AA03Hw
