### ISSUE TITLE
Spellchecking broken in right-click context menu (68.14.3b)

### ISSUE THREAD

**Issue by Yggdrax** [Feodor2/Mypal68#483]
When using the 'Check Spelling' option, you can no longer fix the underlined typos by right-clicking the word and choosing an option from the context menu, this feature used to work in 68.14.1

![spellcheck_contextmenu](https://github.com/user-attachments/assets/d1a4ee3b-29b6-4f0b-9b8b-25d14eec0af9)

Also, the option to enable and disable 'Check Spelling' from the right-click context menu isn't working either.

**Comment by Feodor2** [comment]
How it is supposed to work I checked 14.1 - 2 - 3 and no difference.

**Comment by Yggdrax** [comment]
> How it is supposed to work I checked 14.1 - 2 - 3 and no difference.

Whenever you made a typo, you could right click on the underlined word which would bring up the context menu that I showed on the first post, from there, in version 68.14.1b you could click on one of the options and it would replace the underlined word you typed with the one you clicked from that list, but it doesn't seem to work in 68.14.3b

![typo](https://github.com/user-attachments/assets/be3c11b2-b6d7-428b-b3dc-20eee2613d8d)

In the gif I attempt to replace 'whad' for 'what' and it doesn't work.

**Comment by K4sum1** [comment]
Can confirm it is broken.

![mypal text correction broken](https://github.com/user-attachments/assets/20d8f3c7-ff7b-4c68-bdde-9faa77d50f41)

**Comment by JimMP68User** [comment]
Ya - not working here either. Have to manually correct spelling now! 

Dell Optiplex 755, Windows Xp SP3, Mypal Ver 14.3b 

PS. Many imprivements with 14.3b are appreciated <smile>
