### ISSUE TITLE
68.14.3 issues still have not beeen fixed

### ISSUE THREAD

**Issue by Methen** [Feodor2/Mypal68#485]
Nothing has changed still does not work on Amazon character ai or pirate bay Will not open links when you click on them

On amazon you cant click on quantity or add to cart or other links

On pirate bay https://thepiratebay.org/index.html you have to right clink or the get this torrent and then you get The address wasn’t understood

Mypal doesn’t know how to open this address, because one of the following protocols (magnet) isn’t associated with any program or is not allowed in this context.

    You might need to install other software to open this address.

On character ai all it does is endlessly refresh over and over no matter  what you do.

**Comment by Yggdrax** [comment]
I believe this should go on the thread of not working sites? For Character AI you can use the  old website in the meantime (old.character.ai), it works just fine.

**Comment by Methen** [comment]
I do use hte old character ai site but I like to also like to have access to the newer site was not aware of they was a plaace for non working sites Know I have complained about this issues multiple times and nothing is ever fixed keep saying use to latest version of firefox instead of a older one but no one ever listens to me...
  ----- Original Message -----

**Comment by Feodor2** [comment]
Why do you thing it was fixed, did you read release notes, wait with others, or you may try to find what is exactly missing, then we will know more precisely what to do and estimate.

**Comment by Methen** [comment]
I have reported the errors multiple times over and over and the errors I have reported have not ever been fixed. it would seem to me that errors that were reported would be fixed in each update but that is just my way of thinking...



  ----- Original Message -----

**Comment by Feodor2** [comment]
You missed then, this browser make nobody except me, so I do when I have a time, and even when is the time it is other things to do. Reiteration the report is useless, if you not able investigate yourself just wait with others

**Comment by Methen** [comment]
Then perhaps you should request a little help with it ....
  ----- Original Message -----

**Comment by zanud** [comment]
> On pirate bay https://thepiratebay.org/index.html you have to right clink or the get this torrent and then you get The address wasn’t understood
> 
> Mypal doesn’t know how to open this address, because one of the following protocols (magnet) isn’t associated with any program or is not allowed in this context.

If I have no "magnet" links handler defined in the Mypal 68.14.3 settings, 1MB ("left") click on `"Get This Torrent"` shows a dialog window for selection of a desired application. After selection of it and clicking on "Remember my choice" checkbox, Mypal no more shows this dialog on subsequent magnet links, but instantly runs that application.

WRT 2MB ("right") click - no one of the link's context menu results in your message. Mainly they show the same handler selection dialog (except "Save link as..." which do nothing).

Looks like something is broken on your system.

**Comment by Methen** [comment]
On the original version of My pal you could manually add the torrent program
and the problem was solved my question was why was that feature remmoved in the latter versions of my pal making it impossible to add programs ? 
  ----- Original Message -----

**Comment by zanud** [comment]
> On the original version of My pal you could manually add the torrent program
> my question was why was that feature remmoved in the latter versions of my pal making it impossible to add programs ?

Which version do you mean as "original"? Right now I use the latest release (68.14.3), and program selection dialog is here (as I wrote in the previous message).

**Comment by zanud** [comment]
Can you reproduce your problem on a new profile?

**Comment by Methen** [comment]
29.30
  ----- Original Message -----

**Comment by zanud** [comment]
![magnet](https://github.com/user-attachments/assets/17aff7d4-574f-4206-a744-093ba783ef69)
This screenshot is created on a completely new profile.
As you see, everything is here.

**Comment by NS-Clone** [comment]
еще не  обновилсо
но на content process limit 4
умя новый рекорд потребления памяти
с сохранением работоспособности
![2024-07-26_185315_](https://github.com/user-attachments/assets/b1b1da31-5bcc-4594-883b-58208b0f6da7)

**Comment by zanud** [comment]
@NS-Clone:
Wrong place for your picture. Most probably, the right one is #466
