### ISSUE TITLE
Невозможно поменять язык на любой другой, кроме английского,

### ISSUE THREAD

**Issue by by-tndy** [Feodor2/Mypal68#486]
При установке локализации из аддонов мазилы, после перезагрузки браузера сразу краш с Ошибкой синтаксиса XML.
В принципе не особо английский мешает в самом браузере, но сайты всегда открываются на английском, и приходиться в ручную ставить другой язык. Есть какое то решение этой проблемы?

**Comment by NS-Clone** [comment]
> В принципе не особо английский мешает в самом браузере, но сайты всегда открываются на английском,

в "старом" фаирфоксе
можно поменять язык дето в about:config
весь гуй остаетсо английским
а вот например адоны начинают включать свою локализацию

**Comment by Feodor2** [comment]
#203 Да и русск новый там должен быть

**Comment by zanud** [comment]
> В принципе не особо английский мешает в самом браузере, но сайты всегда открываются на английском, и приходиться в ручную ставить другой язык. Есть какое то решение этой проблемы?

На выбор сайтами языка в первую очередь должен влиять порядок языков в перечне предпочитаемых языков в настройках браузера (Кнопка "Выбрать" справа от "Выберите язык, предпочитаемый вами для отображения веб-страниц"), но этот порядок задаётся пользователем, и установка языкового пакета на него не влияет.

Кроме списка предпочитаемых языков есть и куча других факторов, которые могут учитывать сайты при выборе языка - вплоть до языка интерфейса операционной системы.
