### ISSUE TITLE
Mypal 68.14.3b - stops responding if a language change is attempted when typing

### ISSUE THREAD

**Issue by IdleCommentator** [Feodor2/Mypal68#488]
Just "installed" version of the browser.
1. WinXP SP3 - has two input languages selected
2. When launched, Mypal 68.14.3b defaults to primary input language. Trying to change the input language to the secondary one (in this case - English) causes the browser to stop responding / hang, and it needs to be restarted.
3. The method of attempted language change does not matter - happens with every single one of them: hotkey (in this case shift+alt), manual, language switching program. All of them cause the browser to hang
4. Happens with any kind of input forms - browser address bar, search bars, website's input forms etc
5. Having both of input languages installed as a language in the browser does not help. It still stops responding, when language change is attempted.

In version 68.14.1b no such problems exist (version 68.14.2b I can't say - don't have that one saved)

**Comment by newbie-461** [comment]
I have the same problem, IME can freeze Mypal68.14.3b, but it works fine when using 68.14.2b.
