### ISSUE TITLE
duplicate

### ISSUE THREAD

**Issue by kiza124** [Feodor2/Mypal68#489]
Problem when trying to write a response to comments on the site https://club.dns-shop.ru/review when trying to change the language from English to another browser mypal 68.14.3b hangs. However, there is no such problem in the version mypal 68.14.2b.

**Comment by zanud** [comment]
I saw a lot of similar reports, but this never happened for me on any site (including https://club.dns-shop.ru).

There was a guess that this problem have some relation to video card driver. So it will be helpful, if you provide information about your system.

**Comment by kiza124** [comment]
But you can try this example:
https://club.dns-shop.ru/review/t-105-kuleryi-dlya-protsessorov/116182-obzor-kulera-id-cooling-is-55-black-nizkii-profil-znachit-nizk/#comment_4503343

**Comment by IP-CAM** [comment]
This Website is a plain overkill, but my Mypal 68.14.3b still worked on all pages.

**Comment by kiza124** [comment]
I'm glad it doesn't apply to everyone, but for me Mypal 68.14.3b didn't work, so I had to go back to Mypal 68.14.2b.
You asked about the video card in the computer - Asus GeForce 6200 128mb (AGP), driver 6.14.11.7516 from 02.05.2008. The computer runs under Win Xp SP3.

**Comment by kiza124** [comment]
But you wrote a "comment" on that site, and try writing a "response" there to other comments written by someone earlier. There, where there are already 10 responses.

**Comment by zanud** [comment]
Look closely at my screenshot. My input was under some comment, so it is a response to this comment. A form for a new comment is above all comments!

Moreover, for new comments and for responses to existed ones this page uses the exactly same HTML construction, so there should be no difference for Mypal reaction. Or your Mypal freezes on responses only? If so, this may be an important information for @Feodor2 for investigation the issue too.
