### ISSUE TITLE
XP Service Pack 2

### ISSUE THREAD

**Issue by INVorig** [Feodor2/Mypal68#49]
I was so happy to see, that you were able to create this new Version of mypal.

Sadly I have to report, that it is not starting at all, on my XP Professional with Service Pack 2 only
machine. The error message points to kernel32 "cannot get logical processor number"

I am writing this with mypal 29.3.0 on and running, but this browser stops working more and more every day.
I hope, that you are able to fix this in your new code. 
I am very thankful for all what you did with your mypal-project over the last years.

**Comment by NoNameNeeded2** [comment]
I think you need SP3

**Comment by Feodor2** [comment]
If you not able to install sp3 try the update kb959426.

**Comment by INVorig** [comment]
Thank you both very much for your quick reply. I already guessed, that it is an SP2 issue. And yes it is true, that I have reasons,
why not to install SP3 and I will absolutely give KB959426 a try. Thank you for this suggestion.

**Comment by avaxx** [comment]
You can try this, see the following link:
[https://app.box.com/s/u14x2uipwffy2pddvni0askphe7r3duh]
Both dlls are from One-Core-Api... Kernel32.dll is a wrapper, it adds some missing functions and uses Ntext.dll and your existing Kernel32.dll renamed to Kernelex.dll. You don't have to patch, manually replace or install anything. Just put Kernel32.dll and Mypal.exe.manifest in Mypal's folder and put a copy of your Kernel32.dll renamed to Kernelex.dll with Ntext.dll in the same folder or in Windows\System32. The manifest file tells the system that Mypal.exe should use Kernel32.dll from its own folder, instead of that one from Windows\System32. I'm not sure about your problem but without this I couldn't start Mypal68 on my XP SP2 too.
(Some things have changed, such redirection will not work with Kernel32.dll from One-Core-Api starting from version 2.1. Btw I don't recommend installing One-Core-Api, newer versions can even cause startup problem if installed on SP2.)

**Comment by INVorig** [comment]
Thanks again for even more answers. What I just did, was to replace the files kernel32.dll  secur32.dll with the ones from windowsxp-kb959426-x86-deu_76263d1e1f49d927517c49f2c570e5f3af84847c.exe out of the SP2GDR (2009) Folder. Windows runs fine, but the error when starting Mypal68 "GetLogicalProcessorInformation" persists. I think I will change them back to my original ones (2004). Just a few days ago I added successfully TLS 1.2 support to my Windows with even never files, but whenever it is possible I try to stick to the older ones. As I use this system only and permanently for everything, so I never know, what things might not work suddenly. I will look now into the suggestion of  avaxx and give it a try. Thank you all again.

**Comment by INVorig** [comment]
**avaxx**   your suggestion worked !  Thank you very much !
**Feodor2**  My first impression of your new work is pure amazement.  Speed is back, some sites, that didn't work anymore, work again, here on github page, I can access everything again, like for example the buttons over this writing field.
It feels very light and I cannot wait to see your future work. Now I will go on learning, what i can do with this new browser ..

**Comment by INVorig** [comment]
The Program would run good (much better than mypal 29.3.0) but I get randomly, nearly permanently a blue screen of death. Most often when closing the Program, or closing a tab, but also when I am just looking around in the options. Definitely every time when I try to install any addon.
==================================================
Dump File         : Mini042422-01.dmp
Crash Time        : 24.04.2022 17:43:44
Bug Check String  : KERNEL_MODE_EXCEPTION_NOT_HANDLED
Bug Check Code    : 0x1000008e
Parameter 1       : 0xc0000005
Parameter 2       : 0xbf81059f
Parameter 3       : 0xb06b4b20
Parameter 4       : 0x00000000
Caused By Driver  : win32k.sys
Caused By Address : win32k.sys+1059f
File Description  : Mehrbenutzer-Win32-Treiber
Product Name      : Betriebssystem Microsoft® Windows®
Company           : Microsoft Corporation
File Version      : 5.1.2600.2180 (xpsp_sp2_rtm.040803-2158)
Processor         : 32-bit
Crash Address     : win32k.sys+1059f
Stack Address 1   : win32k.sys+6fb8b
Stack Address 2   : win32k.sys+7012b
Stack Address 3   : win32k.sys+e52eb
Computer Name     : 
Full Path         : C:\WINDOWS\Minidump\Mini042422-01.dmp
Processors Count  : 4
Major Version     : 15
Minor Version     : 2600
Dump File Size    : 90.112
Dump File Time    : 24.04.2022 17:41:06
==================================================
it is not always the same message but it always points to win32k.sys. I tried both kernel32.dll files with the technique described by avaxx, the on of SP2 (2004) and the one from kb959426 (2009) with the same result. For now browsing is not really possible, only for a few minutes, when i am not changing any page. But when I shut down the program, I definitely have to use my pen to hard reset the blue screen of death.

**Comment by INVorig** [comment]
After i read through all crash-reports on this page, I tried these three options in about:config

dom.ipc.processCount      to   1
dom.ipc.processCount.webLargeAllocation   to   1
browser.tabs.remote.autostart      to   false

it runs much better now. I have a four core CPU and even though, the taskmanager shows only 1 process now,
all the four cores work nearly simultaneously. I did not feel any loss of speed, I felt quite the opposite.

I will fool around more, to see, if it is really stable now, or which option is of true importance to my system.
I was able to install one Addon now and I was also able to open about:memory.
So I do hope, that I can stay away from Blue Screen for now.

**Comment by NEO-SPECTRUMAN** [comment]
надо наверно этот новомодный 100500 процессный режим по дефолту бы отключить
кому надо пусть включают :)

**Comment by Feodor2** [comment]
@INVorig
However i suggest look for a specialist to install good winxp with sp3.

@NEO-SPECTRUMAN 
Я против, пользователей немогущих переустановить себе нормальный хр сп3 единицы, а без мультипроцесса очень тормозят новомодные сайты.

**Comment by INVorig** [comment]
So, I double checked. It was definitely only this one option, that caused the trouble:

browser.tabs.remote.autostart

Even I use 'only' SP2, I checked out about, when Firefox 68 was released. There was much talk about
the removal of this function and how much trouble it caused for all kind of systems, especially when there
was less then 4 GB RAM present. Many people gave up on Firefox at that point. Today, I checked on another
Computer on FF 99  and it seems to be common, that multi-process is enabled today. But back when FF68 was new, it was absolutely not common, and certainly not, when XP SP3 or SP2 were active. I started using XP, when there was no more chance for my win98SE and that was in 2007. So this was my start with XP and until today the same installation is still running and I only extend the files, that became absolutely necessary, to keep it running. When I found Mypal, my internet videos were revived. I have SP3 in my home just in case, but I don't feel, that the time is right just now. As I mentioned, I just got myself system wide TLS 1.2 support (on SP2), to keep my Outlook Express functioning. It looks, as if Mypal68 will also run now. So when the time comes, then I will replace just the absolutely necessary files. As I have Win7, Win8 and Win10 in the house, I know for sure, that I will never ever get any new Microsoft-System for myself. This XP, that I am using will be the last one in my life. Besides I have to admin all the other systems in the house, and I hate them all with all my heart.

**Comment by NoNameNeeded2** [comment]
The way you described it (4 cores) your computer should be perfectly suited to run XP with SP3.

Yes I know, you said you only update your system when it's absolutely necessary but Mypal68 was meant to run on XP with SP3, not with SP2.
So in order to avoid even more problems than the ones you already have, I think you should at least update to SP3 (TLS 1.2 can be used with SP3 too, not only with SP2).
Your computer should work perfectly fine with SP3, as far as I can tell.
Because whenever a new problem occurs, you'll never know if it's because of Mypal68 or because of the lack of SP3 on your system.

**Comment by NEO-SPECTRUMAN** [comment]
> @INVorig However i suggest look for a specialist to install good winxp with sp3.
> 
> @NEO-SPECTRUMAN Я против, пользователей немогущих переустановить себе нормальный хр сп3 единицы, а без мультипроцесса очень тормозят новомодные сайты.

ну ХРю х64 токо sp2
а на мультепроцессорносте вылетает не токо на сп2 судя по отзывам
так что нет никакой гаантии что все смогут добратся до about:config не бсоднуув
пользователей браузера то больше чем пользователей зареганых на гитхабахе
это только маленькая часть отзывов
в придачу без утсановки левого github-wc-polyfill
полььзователю ХРю на гитхаб даже невозможно попастть...

**Comment by NEO-SPECTRUMAN** [comment]
ну и работает не стабильно и вызывает BSOD-ы это разные вещи
несущие совершенно разные последствия
дисклеймер должен быть более подробным
с описанием что мультипроцессность у некоторых вызыывает BSOD
и что ее лучше отключить сразу
если падение системы категоричеески не допускаетсо

**Comment by NEO-SPECTRUMAN** [comment]
интересно можно ли обновить 32 битную часть в х64 ХРю
или там свои специальные 32 битные dll-ки

**Comment by NEO-SPECTRUMAN** [comment]
проверил на х64
на вид запустилось
![2022-04-26_102501](https://user-images.githubusercontent.com/88002487/165244326-885ae955-1c3d-4d61-b895-00eeb45260a2.png)

**Comment by INVorig** [comment]
I truly thank you all for your replies. Somehow you are all correct out of your point of views, There might come my day for SP3 but is still not today. The browser runs good, fast and stable now for me, and it is an improvement over my mypal 29.3.0.
 ... **solution** for my problem(s) solved by 

**avaxx**   to make it run on XPSP2
and if you experience ongoing BODs then use the option
 **browser.tabs.remote.autostart**   to   false
and it might run good and fast.

In my case I am satisfied, and very thankful for all your help and support.

-
( my system runs since 16 years daily, and it is used for everything, I like to show people, what can be done
 with the oldest possible soft- and hardware. I remotely do service to our house computers(Win7,Win8,WIn10) with this XPSP2. My home-cinema comes out of this XPSP2 + Soundblaster128 over PCI to beamer and audio-analog cable to my Amplifier from 1985 (with over 65000 using hours), and my sound-boxes of the early 90s (only Stereo). Everybody is impressed, to see, that this can be done (full HD) perfectly smooth. And that classic stereo sound can blow away modern equipment. I also use an old Nvidia driver (from  2004), because the newer ones don't fulfill my needs as good as this old one. Video-cutting and sound processing + perfect emulation of old stuff, with line perfect scanlines and perfect Hz and many other things. Only 2GB RAM by the way. My son plays MegaDrive+SegaCD(1) on real still perfectly running hardware on a classic Television with RGB: Or he plays classic dos games on real 6.22 DOS for example TombRaider on real hardware, with a Righteous3d + real old SB16 on a Pentium Machine. TR2 and TR3 run on my old win98SE, same machine. For some reason he has got crazy for emulating everthing on his W10, where I have to help him sometimes. Some things are not running on my XP and some other things run much better, than on his W10. Maybe you can understand now, that I could easily install some new system-software on another machine, but the fun is to keep the old running, as long and as classic as possible. One person told me once, I should open a museum. Maybe I could...  
So this is, why I absolutely will NOT risk my system, for multi-process, it runs as fast and good as the up to date chrome on my office PC or the FF99 on our WIn7, and now I try to make Mypal68 as beautiful and effective as my Mypal 29.3.0 is.)
