### ISSUE TITLE
Газпромбанк онлайн - ваш браузер устарел.

### ISSUE THREAD

**Issue by saboteur1000** [Feodor2/Mypal68#491]
Газпромбанк онлайн - ваш браузер устарел.
https://ib.online.gpb.ru/

**Comment by Feodor2** [comment]
Так увеличивай версию, потом проверяй, не надо было делать отделную тему.
Ещё проверить может только тот кто там зарегестрирован.

**Comment by saboteur1000** [comment]
Сорри, я что-то не помню как это делается. Какую строчку надо сделать, подскажите плиз?
