### ISSUE TITLE
A link with target="_blank" opens in a new window, not a new tab, when clicked

### ISSUE THREAD

**Issue by Sen-nin** [Feodor2/Mypal68#492]
If you have not noticed it yet, when a link with target="_blank" is clicked, it creates a new window and opens in it, not a new tab.

By the way this 68.14.3b displays websites like the following:

https://www.ac-illust.com/

https://www.photo-ac.com/

That is a truly great improvement. Thanks.

**Comment by zanud** [comment]
On my computer Mypal 68.14.3b opens links with target="_blank" in new tabs.

Do you have `"Open links in tabs instead of new windows"` (in Mypal settings) checked?

**Comment by Sen-nin** [comment]
I have that option checked. I always do. I tried another computer but I got the same results.

Because I run many websites, and I start my days by clicking on links on one of them. So I noticed the difference at once.

**Comment by Feodor2** [comment]
Yes I noticed this, fixed in the new version, which will be available tonight.
This is about I had removed CPOW stuff in the previous version, I decided it is useless and a burden, but browser ui still has left remnants of it at some places.

**Comment by zanud** [comment]
Now I am intrigued: why this do not happen for me? What triggers the error?
