### ISSUE TITLE
Faithful MyPal user with praise for wonderful browser and a site that gives me trouble

### ISSUE THREAD

**Issue by NinjaKittyBonks** [Feodor2/Mypal68#493]
Been using this browser and updating as releases come out, for about a year. Far better than the 7 years out of updates Chrome and Firefox I was using in tandem, to navigate my moderation work on YouTube. This browser works very well on nearly all sites, but one that I wish was better, is the LIVE chat of Rumble. 

Sometimes I cannot post in chat at all, but even when I can, once the chat window is "filled" with comments, the chat window does not scroll up. As people continue to chat comments, they are simply below the chat window and I am unable to moderate chat on that site. 

The only other issue that I would like improvement, would be the memory issue that bogs down until browser crashes and must "reset" to clear and function again. If any one has trick, extension or some relief for this issue, I would appreciate any input you can offer. 

Thanks

**Comment by Feodor2** [comment]
Good, but here this is not a chat, should have read the thing for newbies before making an issue.
Close as invalid

**Comment by NinjaKittyBonks** [comment]
I found the "READ HERE BEFORE MAKING COMMENT" on page 3. I have zero issues following rules, but that comment should have been PINNED at the top of page 1, not buried in page 3
