### ISSUE TITLE
This should be PINNED

### ISSUE THREAD

**Issue by NinjaKittyBonks** [Feodor2/Mypal68#494]
The LIVE chat window will fill up with comments and when new ones are created, the screen does not scroll up to show the latest one. As a result, the "post chat" dialog box is not visible any longer

https://rumble.com/ (any LIVE chat room)

Thanks, NKB's

**Comment by Feodor2** [comment]
Why, if nobody cares? to the not working sites wait with others

**Comment by NinjaKittyBonks** [comment]
I care. Why is it you have this comment section, when you simply act like a bully. I have moderated major websites, going back to 2010 and currently moderate 7 channels on YouTube and you are a lousy moderator.

**Comment by NS-Clone** [comment]
> I care.

another troll caring about yet one unknown site in wrong issue?
https://github.com/Feodor2/Mypal68/issues/228

**Comment by NinjaKittyBonks** [comment]
So Rumble is an "unknown site"..... really? So a troll is one who makes a
comment in the thread that says to post such comments within it?

You are a HORRIBLE moderator
