### ISSUE TITLE
No Video Play in Telegram WEB

### ISSUE THREAD

**Issue by sirrooster** [Feodor2/Mypal68#495]
Videos do not play
https://web.telegram.org/k/

**Comment by Feodor2** [comment]
Where on the given link is to be video? There no any hint a video at all, no matter this to the "not working sites".

**Comment by sirrooster** [comment]
There are many videos.
e.g. here-> https://t.me/FohCorona/41657

"no matter this to the "not working sites"."
When I go to "not working sites" and post "new issue" it appears here.
