### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by fastnetcom** [Feodor2/Mypal68#497]
calendar.google.com/calendar/u/0/r
![Google Calendar error](https://github.com/user-attachments/assets/56b0d747-aa05-410e-aa7d-039c14a7f362)

**Comment by newbie-461** [comment]
gfx.downloadable_fonts.enabled;true
gfx.downloadable_fonts.woff2.enabled;

Have you disabled the above configs?

**Comment by fastnetcom** [comment]
my settings
![fonts0](https://github.com/user-attachments/assets/9d4198a1-8c6a-4d92-8699-58dc3f02bb55)

**Comment by Feodor2** [comment]
To "not working sites"
