### ISSUE TITLE
These sites are clearly not displayed correctly by the mypal 68.14.4b browser

### ISSUE THREAD

**Issue by kiza124** [Feodor2/Mypal68#498]
https://www.kns.ru/product/materinskaya-plata-gigabyte-h610m-s2h-v2-ddr4/ - if you enter something in the search bar (for example, ASUS PRIME B760M-K D4) and press "Enter", an error message appears: "Bad Request. HTTP Error 400. The request is badly formed."

**Comment by kiza124** [comment]
I checked several more times - the site https://www.kns.ru/ does not open at all and displays the same error message - "Bad Request. HTTP Error 400. The request is badly formed."

**Comment by IP-CAM** [comment]
They both display perfectly in my Mypal v.68.14.4b (32-bit)
![kns](https://github.com/user-attachments/assets/520db7f3-7dcc-4aa8-9596-0b3e6bbe18cb)
