### ISSUE TITLE
Facebook games do not load.

### ISSUE THREAD

**Issue by cartdude54** [Feodor2/Mypal68#5]
This browser is awesome however if you like the games on facebook I could only get a few to load without crashing the browser or just getting a grey or black screen. Examples include uno and all versions of forest recsue would not load. I just thought I would let you know in case it can be fixed in a future update of the browser which by the way youve done a great job on!!

**Comment by Feodor2** [comment]
I think this because of no direrctX and webgl suppport.

**Comment by cartdude54** [comment]
Will Mypal 68 ever have directX or webgl support? just had a thought to ask.

**Comment by cartdude54** [comment]
In the new version of the browser the facebook games start to load properly then go into a black or grey screen on windows xp. However they all work great on a fully updated windows vista machine. I am using the 64 bit version of windows xp if that makes any difference? Nice improvements on the release as extentions install without having to close and reopen the browser!! Very good work as always thanks for making windows xp useful.
