### ISSUE TITLE
Missing Bookmarks in Linked Mypal.exe on the Desktop

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#50]
If I call MyPal directly from inside the MyPal Directory, I see the Bookmarks on the Browser Screen. But if I create a Link on my Windows Desktop, no Bookmarks exist, as you can see on the image below. How can this happen ? 

![MyPal_Start_Differences](https://user-images.githubusercontent.com/12776547/164914205-b3137d6b-4dd0-4c5d-979a-131cf16054f6.png)

**Comment by Feodor2** [comment]
what about other things settings extension and such?

**Comment by IP-CAM** [comment]
It's a virgin install, no special settings have been made. But it's a real secret to me, why a simple 'linked' access to the mypal.exe file hides the bookmarks in the layout.
