### ISSUE TITLE
Размытие страниц при пролистывании

### ISSUE THREAD

**Issue by SprintChannel** [Feodor2/Mypal68#500]
Началось это с версии 68.14.3b (предыдущие пропустил после 68.13.8). Думал, в следующей починится, но нет. На трех системах, относящихся почти к ретро (Sempron 2600+ и Athlon XP 2500+ на версии 68.14.3b 32-no-sse, Pentium 4 3.0 HT на версии 68.14.4b 32), один и тот же баг - при пролистывании любых сайтов в случайных местах начинает размываться визуал страницы. С чем связано - не знаю. Видеокарты, драйвера и прочее разные и точно рабочие. Так же встречал такое на Windows 2000 с KernelEx под VMware Workstation 12 на версии 68.14.4b 32. На более новых системах по типу Pentium D и Athlon 64 такого не замечал на версии 68.14.3b 32.

![Screenshot_1](https://github.com/user-attachments/assets/cd663866-3b8d-41e9-8cbd-698f0d0d704e)
![Screenshot_4](https://github.com/user-attachments/assets/06d2e0d7-07e4-49cd-b9cf-9de13c404448)
![image](https://github.com/user-attachments/assets/2b53c6a7-bd06-4373-8040-724fd527e356)

**Comment by Feodor2** [comment]
#426

**Comment by SprintChannel** [comment]
> #426

При чем здесь расширения... Это происходит на обычном чистом браузере
