### ISSUE TITLE
Can't see how to open the browser

### ISSUE THREAD

**Issue by dcimorse** [Feodor2/Mypal68#501]
I downloaded the Mypal68.zip file, unpacked it and moved the unpacked folder to my Windows XP Pro installation on virtual VMware machine, 
I am new to GitHub but assumed there was an ,exe or .ini file to open the app. Is there something else I need to do to open the browser?
Please let me know what I am missing.
Thanks,
Ken Gash
kgash@cox.net

**Comment by IP-CAM** [comment]
it's called:
**mypal.exe**

**Comment by dcimorse** [comment]
Thank you Ernie! The program works perfectly, I don't know how I missed the file. Kudos to Feodor for maintaining and upgrading this project.
    On Tuesday, August 20, 2024 at 11:45:06 AM PDT, Ernie ***@***.***> wrote:  
 
 


it's called:
mypal.exe
