### ISSUE TITLE
Login problems occur with the SSE version

### ISSUE THREAD

**Issue by Sen-nin** [Feodor2/Mypal68#503]
Hello. When you try to login somewhere with the SSE version of 14.4b...

1. you will get a blank in the text (input) areas.
2. you will not get login credential suggestions in some cases.

I confirmed it at Microsoft outlook logins and round cube web mail logins. As I tried to login to github.com today, I saw it here too.

At Microsoft outlook, I could not get suggestions for login credentials, either.

Also, Mypal crashes more frequently on ThinkPad T43 these days than before. I have yet to confirm it on ThinkPad X201.
In opinions of ordinary users like junior and senior high school students, it crashes "too often" as I use Mypal68 in class to show websites on a large screen and hear from their honest opinions directly. Mypal68 needs improvement in this respect too.

![login-problem-outlook-trimmed-and-erased](https://github.com/user-attachments/assets/213480c6-284f-4051-8961-9e988f9ac7aa)
![roundcube-login-trimmed-erased](https://github.com/user-attachments/assets/02cfdbf0-26e6-45fb-8dd5-5446fbb1d486)
![roundcube-login-credentials-entered-trimmed](https://github.com/user-attachments/assets/7b3f9e58-766f-43a2-9c53-3dac2325675e)

**Comment by Feodor2** [comment]
Is this not same as the #354? Why duplicate
Again you do not give links, how I suppose to check, okey I can type outlook.com and other what, and I see nothing wrong now on outlook, sse or not see it is the same
