### ISSUE TITLE
How do I get adobe flash to work on My pal

### ISSUE THREAD

**Issue by Methen** [Feodor2/Mypal68#509]
How do I get adobe flash to work om my pal ?

**Comment by newbie-461** [comment]
install mypal version before 68.14.1b
install NPAPI flash plugin
[web](https://web.archive.org/web/2020052117103/https://fpdownload.macromedia.com/pub/flashplayer/latest/help/install_flash_player.exe)

**Comment by Methen** [comment]
where do I get it at ?
  ----- Original Message -----

**Comment by Feodor2** [comment]
I remember flash was playing but that site is dead.
Give a site link for check the flash.
I tried plain swf file but it is failed, and before 68.14.1b too.

**Comment by newbie-461** [comment]
>  Give a site link for check the flash.

simple test page http://www.ultrasounds.com/
online flash games https://www.y8.com/tags/flash?order=rating

**Comment by Feodor2** [comment]
Okey it works before 14.3 version, I try to fix maybe next version, then why sfw files don't work on any version, I thong it should.

**Comment by Methen** [comment]
I still want to know what you need to do to ge ti to work someone gave me a down laod liink but it was not working  can come one give me a direct down load link to the correct file ?
  ----- Original Message -----

**Comment by Feodor2** [comment]
First please stop spam with that "original message..." shit
Next whats wrong with links already given above?

**Comment by Methen** [comment]
I was referring to the file you need to make the flash work not the links to test flash I have a flash chat for that...

**Comment by newbie-461** [comment]
> Okey it works before 14.3 version, I try to fix maybe next version, then why sfw files don't work on any version, I thong it should.

FYI, i made a PR  [#510](https://github.com/Feodor2/Mypal68/pull/510/commits/588ae14d799cd475a8cbfe0c23468937e39970e2)
it is able to play flash after I patched it
local swf file:// also works, i dont know if it is implemented in 68.14.x or blocked by HookProtectedMode

**Comment by Feodor2** [comment]
Look the very first links, there you get flash player, download and install, that's all. And of course take 14.2 and below version of the mypal.

**Comment by Feodor2** [comment]
@newbie-461 okey thanks I try this.

**Comment by newbie-461** [comment]
> I was referring to the file you need to make the flash work not the links to test flash I have a flash chat for that...

https://github.com/Feodor2/Mypal68/issues/509#issuecomment-2325435439
what version do you have installed? 
can you find Shockwave Flash on about:addons

**Comment by Methen** [comment]
68 13.7b
  ----- Original Message -----

**Comment by Methen** [comment]
which one there are several 
  ----- Original Message -----

**Comment by Feodor2** [comment]
Pretending that so stupid thus fail to install or check flash player, this is a troll stuff you know.
Also keep shiting with  ---- Original Message ----
