### ISSUE TITLE
MyPal Download Link 

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#51]
I assume, that many Visitors will try to download the Software by using the CODE Download ZIP Link, and so ending up with a giant 645 MegaByte Size unusable Download, instead of what they are expecting to get. I just figured to mention this, to avoid any surplus work for them

![MyPal_Download_link](https://user-images.githubusercontent.com/12776547/164981516-060dd898-c978-41a4-8935-71c1e4f552dd.png)

**Comment by NEO-SPECTRUMAN** [comment]
:rofl:

**Comment by spinalgr1990** [comment]
Here also you can .exe installers : 

1) 
MyPal 68.12.2b
https://www.mediafire.com/file/mo9re4awsadff8k/MyPal_68.12.2b_setup.exe

2)
MyPal_68.12.3b
https://www.mediafire.com/file/6smw4t8dhrjwrzl/MyPal_68.12.3b_setup.exe

**Comment by krzysiobal** [comment]
How to get already compild portable version for 68.12.5?

**Comment by IP-CAM** [comment]
That's the last Mypal Version;
https://github.com/Feodor2/Mypal68

**Comment by krzysiobal** [comment]
Am I blind or I don't see any way how to get the compiled version, like it was for 
mypal-68.12.2.en-US.win32.zip
and
mypal-68.12.3.en-US.win32.zip

**Comment by gdl-blue** [comment]
go to the releases section, download it, decompress it and run mypal.exe

**Comment by krzysiobal** [comment]
Can you please tell me where exactly to click to obtain the ZIP with binaries? BEcause when I click on the "68.12.5b" in releases page, it just reloads the same page.

**Comment by krzysiobal** [comment]
Screen shoot: https://obrazki.elektroda.pl/6263840400_1663887269.png

**Comment by win98se** [comment]
@krzysiobal Try this link: https://github.com/Feodor2/Mypal68/releases/download/68.12.5b/mypal-68.12.5.en-US.win32.zip

**Comment by krzysiobal** [comment]
Thank you! I was using the older mypal v28.17.0 and the download link for newest version wasn't displaying at all on the forementioned page

**Comment by win98se** [comment]
@krzysiobal You may try installing [this](https://github.com/JustOff/github-wc-polyfill) extension to your Mypal 28.17.0. It probably will fix the bugs you've encountered, but I only tested it on Mypal 29.3.0.
