### ISSUE TITLE
mypal 68.14.4b browser - the page is not displayed correctly, photos are not shown on the page

### ISSUE THREAD

**Issue by dimagit2024** [Feodor2/Mypal68#515]
https://www.mos.ru/city/projects/vote2024/candidate/?ysclid=m0v6e5te1r573084513 - the page is not displayed correctly, photos are not shown on the page

**Comment by zanud** [comment]
Я зашёл на страницу по ссылке. Сначала фотографий не было, но потом сами начали появляться.
Возможно, они сервером отдаются медленно.

А ещё это напомнило мне кое-что из моей практики сайтостроительства: когда на странице очень много картинок, то у сервера может произойти какой-то сбой и он присылает браузеру не все картинки, часть запросов просто остаётся без ответа. Браузеры, основанные на Firefox, в такой ситуации немного ждут, а потом перезапрашивают недостающее.

**Comment by zanud** [comment]
Потыкался в страницу ещё - нет, там не всё так просто: если фотографии хоть раз появились и осели в кэше, то дальше они стабильно показываются, но если их там ещё нет или если кэш удалить, то страница показывается без них и нужно много раз её обновлять (F5), прежде чем они появятся.

В веб-консоли ничего криминального нет. Единственное сообщение, которое могло бы означать что-то серьёзное (`"Uncaught TypeError: $(...).get(...) is undefined"`), присутствует даже тогда, когда фотографии показываются.

Но что вызывает подозрение и заставляет подозревать причастность браузера, так это то, что сообщения в консоли от раза к разу отличаются. И иногда серьёзно отличаются.

**Comment by Feodor2** [comment]
Так я обычно не рассматриваю такое - нет времени, тем более когда точно неизвестно что ему надо.
И не надо на каждый сайт тему отдельную делать, кидайте всё туда #228
