### ISSUE TITLE
Убийственная проблема при просмотре статей на Хабре

### ISSUE THREAD

**Issue by zanud** [Feodor2/Mypal68#516]
Я, конечно, напишу об этом и в #228, но решил также и отдельную тему создать.

Заходим в любую статью на Хабре (например, https://habr.com/ru/companies/embox/articles/256191/), видим нормальную веб-страницу. Начинаем проматывать её вниз-вниз-вниз, и когда уже почти добрались до самого конца, всё, кроме шапки и подвала, исчезает, и на экране огромными буквами пишется:

> Внутренняя ошибка
> 
> ReadableStream.prototype.getReader called on incompatible Proxy

(Для справки: в ройтамовской сборке IceApe этой проблемы нет.)

**Comment by NS-Clone** [comment]
есть такое мдо

**Comment by zanud** [comment]
Кстати, тот рыжий прямоугольник с 

> "The text was updated successfully, but these errors were encountered:"

который я вижу в каждой теме на Гитхабе, я, как оказалось, тоже вижу только в Mypal. IceApe его не показывает.

**Comment by Feodor2** [comment]
Не надо отдельную тему
