### ISSUE TITLE
Can't get more search engines

### ISSUE THREAD

**Issue by techguy16** [Feodor2/Mypal68#52]
When I go into the settings page and try to get more search engines, the link to get more search engines does not work. 
Can this please be fixed?

**Comment by NEO-SPECTRUMAN** [comment]
да добавьте ужо гугол по дефолту
серавно пользователям егго придетсо доставлять в 100% случаев

**Comment by NEO-SPECTRUMAN** [comment]
что примечательно в упор не видно офлайн способа установки поиска

**Comment by ScratchApps** [comment]
> When I go into the settings page and try to get more search engines, the link to get more search engines does not work. Can this please be fixed?

https://mycroftproject.com/search-engines.html

**Comment by NEO-SPECTRUMAN** [comment]
да и там у нас 100500 гуглов
выбирай любой :rofl:

**Comment by NEO-SPECTRUMAN** [comment]
а так еще по моему можно ставить поиск
из сохраненной html-ки с этого сайта

**Comment by ScratchApps** [comment]
> да и там у нас 100500 гуглов выбирай любой 🤣

Да там миллион гуглов и от сайта, и от пользователей, со всякими там поисками сайтов только на русском языке...

**Comment by NEO-SPECTRUMAN** [comment]
да и хз какой из них выбирать...

**Comment by ScratchApps** [comment]
> да и хз какой из них выбирать...

Я использую этот: https://mycroftproject.com/install.html?id=59831&basename=google-ru&icontype=ico&name=Google+%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F

**Comment by win98se** [comment]
Simpler step - Visit [this page](https://www.google.com/homepage/search/sp-firefox.html), then you can add the search engine by clicking on the icon of the current default, you'll see an option.

**Comment by IP-CAM** [comment]
Great Info, works well, thanks a lot!

**Comment by NEO-SPECTRUMAN** [comment]
а about:config-ом можно выпилить поиск из адрессной строки?

**Comment by techguy16** [comment]
> Simpler step - Visit [this page](https://www.google.com/homepage/search/sp-firefox.html), then you can add the search engine by clicking on the icon of the current default, you'll see an option.
> 
> For other search engines, [this is the original intended link in Firefox](https://addons.mozilla.org/en-US/firefox/extensions/category/search-tools/).

Thanks @win98se  for your answer. It worked.

Thank you all for answering.
