### ISSUE TITLE
dup

### ISSUE THREAD

**Issue by leksnet** [Feodor2/Mypal68#520]
https://www.eyeconic.com

Page doesn't load. Blank screen.

**Comment by zanud** [comment]
This site rejects any access (error 403 - Forbidden) from Russian, Ukrainian, Europian and USA IP addresses.
Judging from this, it does not work at all.

**Comment by leksnet** [comment]
US location. Firefox opens the page no problem from my location.

**Comment by zanud** [comment]
12 hours ago I successfully visited https://www.eyeconic.com/ via US-based anonymizer https://proxy-123.com/
Right now anonymizer does not allow me to repeat this visit, requiring waiting 12 hours more.

When I do not use proxy, or use any other proxy (even US-based), eyeconic.com returns error 403 (Forbidden):
![403](https://github.com/user-attachments/assets/fc1779c4-c950-4238-b865-04dfa28675be)
Perhaps, this server uses some list of known proxies and rejects them as well.

Try to use proxy-123.com yourself.
And also check the Network monitor: whether server returns error 403 to you or not.

**Comment by leksnet** [comment]
An old version of palemoon running on xp is also able to load page, but old mypal(29.3.0) is not?

**Comment by zanud** [comment]
This is how Mypal renders your site, accessing it via proxy-123.com:
![200](https://github.com/user-attachments/assets/ec4dde18-0065-47bc-b940-bac3c2834245)

And this is how it doing this via a random US-based proxy using spoofed `useragent` string:
![200-2](https://github.com/user-attachments/assets/5a54b126-3d8a-43d0-b710-4d7d08527967)

_(The used proxy was very slow, so the second screenshot was made "in process" - when not all page elements were loaded yet.)_

So, Mypal does not have problems with www.eyeconic.com - www.eyeconic.com does.

Do you know how to add a site-specific `useragent` override to Mypal settings?
