### ISSUE TITLE
duplicate

### ISSUE THREAD

**Issue by FlorianisonGitHub** [Feodor2/Mypal68#524]
This is what happens to Mypal 68 once you ran Supermium on Windows 2000 with Extended Kernel. Anyways to get a workaround once that happened?

Even though, before Supermium can be supported on Windows 2000, this bug must be fixed.

Reference, see https://github.com/Feodor2/Mypal68/issues/496
https://www.youtube.com/watch?v=-JLWhSQ9ifg

**Comment by JosefReisinger** [comment]
Does your DrWatson Log also show "Hardcoded Breakpoint" like mine?
Greetings Joe
