### ISSUE TITLE
View page info, media, right click, copy - gone

### ISSUE THREAD

**Issue by Frank4git** [Feodor2/Mypal68#525]
I run XP 32bit sp3.

In Mypal V68.14.2b (32bit)
Right click, view page info, media, right click. just  shows "select all"

In Mypal V29.3.0 (32bit)
Right click, view page info, media, right click. shows "select all" and "copy"
I still use this version of mypal just for the copy option.

**Comment by zanud** [comment]
Mypal 68.14.4b - "Copy" is present

**Comment by Frank4git** [comment]
Thanks updated to 68.14.4b
