### ISSUE TITLE
duplicate

### ISSUE THREAD

**Issue by hue4** [Feodor2/Mypal68#527]
Hi,

I've just installed the newest version.  When I scroll downwards on any website I get distorted elongated images, as in the enclosed gif.  This does not happen on previous versions, such as 68.13.0b or 68.12.5b.  
![screen image](https://github.com/user-attachments/assets/29d6420b-faaf-406d-901e-2cf7b7cdbc62)
![screen image](https://github.com/user-attachments/assets/62d769cd-405a-437e-95e8-f170901e1299)

Fix?

**Comment by Ariel-Schnee** [comment]
Try...

about:config

gfx.font_rendering.cleartype.use_for_downloadable_fonts false

gfx.canvas.azure.backends direct2d1.1,cairo,skia

gfx.content.azure.backends direct2d1.1,cairo,skia



---

Signature - SFW - https://www.fanficparadise.com/arielschnee/sig3.htm
Signature - NSFW - https://www.fanficparadise.com/arielschnee/sig3_NSFW.htm


  ----- Original Message ----- 
  From: hue4 
  To: Feodor2/Mypal68 
  Cc: Subscribed 
  Sent: Sunday, October 06, 2024 4:37 PM
  Subject: [Feodor2/Mypal68] 68.14.4b screen problem (Issue #527)



  Hi,

  I've just installed the newest version. When I scroll downwards on any website I get distorted elongated images, as in the enclosed gif. This does not happen on previous versions, such as 68.13.0b or 68.12.5b.
  screen.image.GIF (view on web)
  screen.image.GIF (view on web)

  Fix?

**Comment by gremlin4553** [comment]
gfx.font_rendering.cleartype.use_for_downloadable_fonts false
gfx.canvas.azure.backends  direct2d1.1,cairo,skia
gfx.content.azure.backends direct2d1.1,cairo,skia


Fix don't work :(
After adding the settings, the same error continues.

**Comment by RamonUnch** [comment]
Just disable hardware acceleration.
Or maybe try to disable layers.allow-d3d9-fallback in about:config.
In older versions it was set to false

**Comment by Half-Modern** [comment]
What kind of Windows this is? Buttons look weird.
Can you post `about:support` content (especially rendering part)?
