### ISSUE TITLE
navigator.geolocation gone. Совсем gone?

### ISSUE THREAD

**Issue by zanud** [Feodor2/Mypal68#529]
Мне в последние два года приходится часто лазить по сайтам, которые на своих страницах показывают посетителю интерактивные карты (от Google, Yandex, OpenStreetMap, 2GIS и др.). А в качестве начального положения карты они стараются выбрать окрестности меня.

В основном, проблем нет ("вычислю по IP-адресу"), но попадаются и такие варианты:
а) моими окрестностями сайт полагает центр Африки, а точка, откуда на них предлагается смотреть, находится где-то далеко-далеко, примерно на Марсе;
б) внутри DIV-а карты крутится колесо, индицирующее получение данных, но DIV остаётся пустым, сколько ни жди;
в) при попытке получить и отобразить карту браузер виснет со 100-процентной загрузкой
(причём "родительский" картографический сервис мне во всех этих случаях всё показывает без проблем).

И только изредка неспособный показать карту сайт сообщает в своё оправдание что-то осмысленное.

Вот сегодня, после того, как я ткнулся в ссылку выбора города, для которого хочу посмотреть информацию, сайт мне написал:

> Что-то пошло не так...
> 
> navigator.geolocation is undefined

Проверяю: действительно, в консоли обращение к navigator.geolocation возвращает undefined. И даже при наборе буковок в подсказочной менюшке слово "geolocation" отсутствует.

Но ведь navigator.geolocation существует со времён Firefox 3, и сейчас живёт и здравствует во всех браузерах, и никто от него отказываться не собирается. (Видать, потому и сайты подвоха не ожидают.) Куда же оно из Mypal делось? Выкошено с концами? Но тогда почему в настройках браузера в разделе "Приватность и защита" пункт "Местоположение" имеется  и там даже что-то настраивать можно?

**Comment by zanud** [comment]
Нинужон, говоришь. А в результате я, например, ищу редкое лекарство, с трудом нахожу его и... не могу купить, потому что аптечный сайт при оформлении заказа требует указать, в какой аптеке я собираюсь получить заказ. А для этого я должен на карте в аптеку ткнуться. А с картой - облом. Полный облом.

И так у меня не раз. И не на одном сайте.

Вот почему было вместо полного удаления объекта не оставить код, который просто возвращал бы какое-то фиксированное значение (в идеале, настраиваемое через about:config)?

_Вспомни себя с blur-ом._

**Comment by NS-Clone** [comment]
> Нинужон, говоришь.

для слежки за собой отовсюду используй хром :rofl:

**Comment by zanud** [comment]
> а так конешно до особо !"$R#%; сайтики
> потенциально могут отказатсо работать без скана паспорта

Уже, уже есть такие. Я даже имена некоторых из них знаю.

> и было бы полезно
> задавать координату для этого дела в about:config
> так бы и пациент выше мог бы вписать туда свой подъезд квартиру
> и нормальные люди бы могли вписать туда антарктиду

Именно это я и предложил.

> на заборе тоже много чего пишут
> ты всему веришь?

Я маньяк-параноик. Работа у меня такая.

> одних только фаирфоксных форков 100500шт

Да на здоровье. Хотите что-то добавить к функциональности базовой версии Firefox - добавляйте. Хотите что-то удалить - удаляйте. Но удалив - не претендуйте на соответствие этой версии. Строка useragent в запросе для того и нужна, чтобы сайт по ней мог определить, что браузер умеет, а что нет.

> вот иззо таких R $!@!
> пилятелю браузера нужно 24/7 обновлять браузер
> пилятелю адонов нада 24/7 обновлять адоны

С чего бы это? Если браузер заявляет, что он совместим с Firefox версии 78, то он не обязан поддерживать то, что появилось в версии 79 и более новых.

А что автору приходится всё повышать и повышать версию, с которой его браузер совместим, это вина не пользователей, а сайтоваятелей.

> у нас тут 2005 год если че

Год сейчас 2567, местами 5784, местами 1403, местами 4721, а совсем уж местами - 6. (И это я ещё не все места перечислил.)

> за одно мож пойти посмотреть телевизор
> который скриншотит каждую секунду чего ты смотришь
> а потом куда то отправляет

Ты в курсе, как работает геолокация в браузере? Я в курсе, поэтому если бы меня не заботило, кто что и куда отправляет, то предложил бы или вернуть прежний код, или урезать его до использования только IP-адреса (сайт-то его всё равно знает). Но поскольку я считаю, что _туда_ даже IP-адрес отправлять не стоит, то и предложил вариант с фиксированными координатами. Но не убивать API целиком!!! Потому что из-за этого доступ к сайтам ломается.

**Comment by NS-Clone** [comment]
> Строка useragent в запросе для того и нужна, чтобы сайт по ней мог определить, что браузер умеет, а что нет.

но к сожалению в 99.9999% случаев это строка используетсо для выдачи надписи посреди экрана
"ой ой ваш браузер устарел быстрей идите вна виндовс 11"
вместо самого сайтека
хотя сам сайтек в 99.9% при этом рабочий и так

**Comment by zanud** [comment]
Так во в нашем случае пусть лучше бы так и написал, чем попытался вызвать функцию браузера, которая в нём обещалась быть, но которую тупо удалили.

**Comment by NS-Clone** [comment]
> Но не убивать API целиком!!

вангую что там этих функций хоть жопой еж
а Feodor2-у нечего еще делать как тратить время на имитацию рабооту шпионских модулей

**Comment by zanud** [comment]
> вангую что там этих функций хоть жопой еж

Всего-то пара.

> а Feodor2-у нечего еще делать как тратить время на имитацию рабооту шпионских модулей

Ох, тяжёлая это работа - вернуть из функции константу.

> можно думать а не впилить ли что то на замену
> а не "ойой как можно быыло выпилить шпионское №;";!""

Вообще-то, "_как_ выпилить" стоило бы подумать, прежде чем выпиливать. Тем более, что ничего сложного в этом как видишь, нет. (Напоминаю о твоей хотелке с blur() - там ровно то же самое.)

> а так ятя не узнал
> через этот уехавший шрифт

> они в сговоре с M$-ZОG
> им надо чтоб ты быстрей купил вин15 под которую ты должен купить новый проц новую материнку новый бп и новый корпус

Ну вот как только они мне денег на покупку всего этого подкинут, так я тут же и сразу.

---------------------
Кстати, у тебя вчера-сегодня на Youtube никаких изменений не произошло?

**Comment by NS-Clone** [comment]
> (Напоминаю о твоей хотелке с blur() - там ровно то же самое.)

нуу я хотел выключатель :)

**Comment by zanud** [comment]
> нуу я хотел выключатель :)

Ага, только вот его перевод в состояние "выкл." не должен приводить к удалению функции из доступа, иначе сайты будут ломаться и ты сам же побежишь возвращать всё во "вкл".

**Comment by NS-Clone** [comment]
> А выключатель для геолокации в Mypal даже сейчас есть

вон там есть выключатель для всплывающщих окон
но окна все равно всплыывают...

**Comment by zanud** [comment]
> вон там есть даже выключатель для всплывающщих окон
> но окна все равно всплыывают...

У меня не всплывают, всё исправно режется.

**Comment by NS-Clone** [comment]
> У меня не всплывают, всё исправно режется

ну вот и у меня все прекрасно работает без геолокаций :)
и у Feodor2-а тоже

**Comment by zanud** [comment]
> ну вот и у меня все прекрасно работает без геолокаций :)

Ты, вроде, в России находишься. Сходи на https://auchan.ru и попробуй там в верхнем левом углу выбрать любой город, кроме дефолтной Москвы.

**Comment by Feodor2** [comment]
Да я не буду это включать поумолчанию как и гугел, вебтрц и прочее такое, но и вырезать это совсем необязятелно, включи себе да и всё, может урл ещё надо - ну возьми от лисы.

**Comment by zanud** [comment]
> Да я не буду это включать поумолчанию как и гугел, вебтрц и прочее такое

А никто и не просил. По умолчанию оно, с моей точки зрения, как раз и должно быть выключено. В настройках. Тех, которые "Приватность и защита" > "Разрешения" > "Местоположение".
Но в браузере при этом оно должно быть!

> но и вырезать это совсем необязятелно

Вот и я об этом. Однако сейчас оно именно что вырезано. Начисто.

> включи себе да и всё, может урл ещё надо - ну возьми от лисы.

Как? Сейчас обращение к `navigator.geolocation` возвращает `undefined`. То есть, объекта `navigator.geolocation` в браузере нет. Что я должен сделать, чтобы он появился?
