### ISSUE TITLE
MyPal 68.14.4b no longer supported G-mail.

### ISSUE THREAD

**Issue by vkshaw0807** [Feodor2/Mypal68#530]
![gmail-screenshot](https://github.com/user-attachments/assets/d6293ab3-ef4d-4017-9c56-1c6980eb640f)
I am using MyPal 68.14.4b.
The browser no longer supported G-mail.
Kindly help me with this problem.

**Comment by 1nikolas** [comment]
Can confirm

**Comment by Feodor2** [comment]
Did it refuse work at all? Try set higher user agent version.
Anyway this is for the not working sites.
