### ISSUE TITLE
Profile manager not working

### ISSUE THREAD

**Issue by Jasantes** [Feodor2/Mypal68#534]
Mypal.exe -p opens the browser directly, not the profile manager.

**Comment by zanud** [comment]
> Mypal.exe -p opens the browser directly, not the profile manager.

Should it? Neither "-h" nor "--help" promise this (because they are not exist too :smile:).

"mypal --ProfileManager" does work.

**Comment by Feodor2** [comment]
These things are the same as firefoxes

      "  -P <profile>       Start with <profile>."
      "  --profile <path>   Start with profile at <path>."
      "  --migration        Start with migration wizard."
      "  --ProfileManager   Start with ProfileManager."
      "  --no-remote        Do not accept or send remote commands; implies  --new-instance."
      "  --new-instance     Open new instance, not a new window in running instance."
      "  --UILocale <locale> Start with <locale> resources as UI Locale."
      "  --safe-mode        Disables extensions and themes for this session."

**Comment by zanud** [comment]
How to obtain a complete list of command line parameters from Mypal? `-?`, `-h`, `--help` do not work.

**Comment by Jasantes** [comment]
mypal.exe --ProfileManager doesn't work for me either.

Mypal 68.14 portable in Win7/32.

**Comment by zanud** [comment]
> `mypal.exe --ProfileManager` doesn't work for me either.

![PM](https://github.com/user-attachments/assets/c8442f66-df05-4b85-b2be-96383e502518)

> Mypal 68.14 portable in Win7/32.

What is "Mypal portable"? Is it Mypal processed by some utility? Or Mypal in portable mode? If the latter, then which one exactly? (there are 3 different ones)

**Comment by Jasantes** [comment]
mypal-68.14.4.en-US.win32 located in D:\ with a new profile in the app folder.
Works perfectly except the PM, which stopped working after a few days.

**Comment by zanud** [comment]
> mypal-68.14.4.en-US.win32 located in D:\ with a new profile in the app folder.

If "the app folder" is a subfolder of Mypal's folder, then how do you get Mypal to use this profile?

**Comment by Jasantes** [comment]
Part of Mypal folder:
![Capture](https://github.com/user-attachments/assets/8b21da6d-ff49-4c53-ba47-65019542e660)

**Comment by Jasantes** [comment]
Do you know Firefox?
about:profiles > Create a New Profile...

**Comment by zanud** [comment]
> This is really portable!

Nope. When you create a profile in this way, Mypal stores path to it into `%appdata%\Mypal68\profiles.ini`. And when you will launch Mypal on another system later, it will not find this profile automatically.

If you want a really portable way, you should either provide a `--profile` command line switch (see @Feodor2 message above), or use "pmprt.mod" or "pmundprt.mod" flag file.

**Comment by Jasantes** [comment]
Ok, I see it's similar to chrome.exe --user-data-dir= 
But the profile manager not workingis NOT SOLVED.

**Comment by zanud** [comment]
> But the profile manager not working is NOT SOLVED.

What happens when you use `mypal --ProfileManager`? Browser just opens window?
Does this happen on all your computers or only on one/some of them?

**Comment by Jasantes** [comment]
Just like I said, it opens Mypal directly, not PM.
But ATENTION: I solved it...
Just deleted pmprt.mod in browser folder!!!
That's amazing, because that file was empty, 0KB.

**Comment by zanud** [comment]
> Just deleted pmprt.mod in browser folder!!!

I mentioned this file yesterday. Because of https://github.com/Feodor2/Mypal68/wiki/Portable

> That's amazing, because that file was empty, 0KB.

Exactly as designed. It's a flag file, its content is irrelevant, but only its presence.

**Comment by Jasantes** [comment]
Thank you, something is always learned.
