### ISSUE TITLE
facebook messenger encryption 2024-10-30

### ISSUE THREAD

**Issue by dydydan** [Feodor2/Mypal68#537]
facebook messenger has updated the message encryption method a few days ago, 
and mypal 68.14.4b can not open the messages now.
my system is win xp pro 32-bit SP3.
please help, thank you!

**Comment by Feodor2** [comment]
Somebody to find what first version the firefox where it works.
I do not use facepooke never have an account

**Comment by dydydan** [comment]
> Somebody to find what first version the firefox where it works. I do not use facepooke never have an account

thanks a lot, Feodor2, for paying attention to this issue!
i am looking forward to hearing good news from you!

**Comment by dydydan** [comment]
i am using Firefox 115.15.0esr 32-bit on win7, and it has no problem with facebook messenger's encryption.
hope this information is helpful~

**Comment by Feodor2** [comment]
Not so much, find the first version, may go back for est 102-91-78- until it stop work, then move version forward until it begin to work, this will be the seeking version.

**Comment by dydydan** [comment]
i just tried **Firefox 69.0.3 32-bit** on win7, and it is working with facebook messenger's encryption.
anything else i can do to help?

**Comment by Feodor2** [comment]
Okey 69 is the first version, did you check 68?
Because I do not see differences regarding the encryption, may be it is not about this, what is the error actually?

**Comment by dydydan** [comment]
i didnt test 68 because i thought mypal is based on 68.
i will test firefox 68 tomorrow.
the actual problem is: whenever i try to open the message box, if the messages are encrypted, then message box keeps loading loading and loading, nothing shows up.
if the messages are not encrypted, mypal works well.

before 2024-10-30, some of the facebook messages are encrypted too, and mypal was handling the situation pretty good. 
on 2024-10-30, facebook upgraded the encryption algorithm and the problem started.

**Comment by dydydan** [comment]
test result for mypal68 on win7 -> it works, surprise!
![fb msg mypal68 win7 - yes 01](https://github.com/user-attachments/assets/7f532190-f783-4b1b-829f-8758916a1aeb)
![fb msg mypal68 win7 - yes 02](https://github.com/user-attachments/assets/19ba6b3b-0739-43db-b6e0-46944b4ad66b)

**Comment by dydydan** [comment]
test result for Firefox 68.12.0esr 32-bit on win7 -> it fails.

![fb msg FF68 win7 - no 01](https://github.com/user-attachments/assets/46e59a25-a05e-4352-8f72-13a3d9b03864)


![fb msg FF68 win7 - no 02](https://github.com/user-attachments/assets/063359ad-4b14-4fb9-8f15-2f599823e9a6)

**Comment by dydydan** [comment]
hello Feodor2, 
guess what, i just found out that the facebook messenger is working again on my XP's myapl68, so surprised and happy!!!
i have no idea why, it just works.
thank you very much for your time and effort trying to help on this issue.
Greatly appreciated!

**Comment by dydydan** [comment]
unfortunately the same problem happens again on my XP's myapl68,
but mypal68 on win7 is okay!
