### ISSUE TITLE
Search terms in URL bar

### ISSUE THREAD

**Issue by pachuco** [Feodor2/Mypal68#54]
A minor gripe.
Entering search term in URL bar always attempts to interpret it as URL, instead of turning it into a search with currently selected engine.

**Comment by Matiasgroen** [comment]
Try setting keyword.enabled in about:config to true.

**Comment by pachuco** [comment]
Ah yeah derp, my bad.

**Comment by win98se** [comment]
@Feodor2 I suggest this issue to be pinned because this is the most (if not, then one of the most) FAQ.
