### ISSUE TITLE
68.14.5b, close multiple tab warning can't disable?

### ISSUE THREAD

**Issue by jasonliul** [Feodor2/Mypal68#542]
When i close multiple tab, it always warning, change setting or change about:config,
all failed.

pull back to 68.14.4, all fine.

**Comment by Feodor2** [comment]
browser.warnOnQuit;false

**Comment by Feodor2** [comment]
Uh ups the checkbox in the warning window was broken yes.
but about:config works

**Comment by jasonliul** [comment]
> browser.warnOnQuit

This one works, thanks. :)
