### ISSUE TITLE
Page load fail

### ISSUE THREAD

**Issue by leksnet** [Feodor2/Mypal68#545]
Page starts to load then goes to blank screen...

https://www.kbtx.com/weather/cams/

.

**Comment by zanud** [comment]
2 @Feodor2

On my regular profile Mypal writes a few error messages to its Web console ("Can not load script file ...", a few exceptions, etc.).

But on a new clear profile there is only one of those errors: "Uncaught RangeError: Invalid timeZoneName", and source of this error is https://polyfill-fastly.io/v3/polyfill.min.js

**Comment by Feodor2** [comment]
anyway go to the corresponding issue
