### ISSUE TITLE
Повтор dup

### ISSUE THREAD

**Issue by NS-Clone** [Feodor2/Mypal68#548]
Mypal после 68.14.2 категорически отказывается востанавливать сессии на 1500 вкладок
один из процессов набираит 1.6Гб и браузер падает
68.14.5 даже стал просто запускаться раз в 5 медленее

и вот наконец то нашел причину 
(или может быть это работает только на 68.14.5 ибо вроде же уже когда то пытался отключать плагины)

add-on номер раз
Focus On Left Tab After Closing
[focus_on_left_tab_aft_closing-1.0.0.xpi.zip](https://github.com/user-attachments/files/18204687/focus_on_left_tab_aft_closing-1.0.0.xpi.zip)
с ним браузер долго стартует
и падает от 1.6Гб
(а сессия грузится минут 6 если грузитсо)

2 запуска без него и 1 запуск с ним (и падение)
![2024-12-20_031145](https://github.com/user-attachments/assets/596531e8-afe4-45be-84ce-75f8c3a9c4e4)

add-on номер джва
Open Tabs Next to Current
https://github.com/sblask-webextensions/webextension-open-tabs-next-to-current
[open_tabs_next_to_current-2.0.14.xpi.zip](https://github.com/user-attachments/files/18204706/open_tabs_next_to_current-2.0.14.xpi.zip)
изза него замедленная загрузка сессии
и большое потребление памяти при старте
но сам браузер не падает
и сессия грузитсо секунд 20...30

без него / сним
![2024-12-20_031327](https://github.com/user-attachments/assets/d0d6c9d6-b5a0-4dda-b9df-56973e43509d)

без этих двоих сессия на 1.5К вкладок
востанавливаетсо за 2 сек

чего происходит с бекапами пока наблюдаем
пока вроде бы сходу завелись

...
@Feodor2 
вощем нужна __НОРМАЛЬНАЯ__ работа с вкладками нативно
без левых аддонов
в чем проблема открывать вкладки ВСЕГДА вправо и закрывать ВСЕГДА влево?
как во всех нормальных софтах (до я знаю что есть куча ненормальных)

**Comment by zanud** [comment]
> в чем проблема открывать вкладки ВСЕГДА вправо и закрывать ВСЕГДА влево?

Может в том, что обязательно найдутся пользователи, которым это не удобно?

Меня, например, категорически не устраивает "закрывать ВСЕГДА влево". В большинстве случаев мне гораздо удобнее, когда после закрытия вкладки браузер переключается на ту, которая от неё справа.

(А в идеале хотелось бы иметь возможность рулить направлением "вправо/влево", удерживая нажатой какую-нибудь дополнительную управляющую клавишу в момент отдачи команды на закрытие.)

**Comment by NS-Clone** [comment]
> Но ведь это ты хочешь, чтобы вкладки всегда открывались на "+300" правее

глаза раззуй
я хочу ЛОГИЧНОЕ +1 И -1

**Comment by NS-Clone** [comment]
> мне после каждого закрытия придётся что-то жать (мышку или клавиатуру

я открываю 30+ страниц подряд
и ожидаю увидеть последне открытое
самой ближней вкладкой
мне что надо листать на 3 страницы вправо хрен знает куда?

**Comment by zanud** [comment]
> вот утя 1К вкладок
> тте надо закрыть парочку для освобождения рамы
> а ТЫ ЭТОГО НЕ МОЖЕШЬ сделоть
> тте надо сначала открыть прогрузить вкладоку сожрать рамы
> а потом только ее закрыть....
> и убирание крестиков это огромный шаг назад

Совершенно верно. При отсутствии крестика на вкладке приходится сначала активировать её (долго-нудно и с шансами вообще рухнуть) и только потом закрывать.
Но и гробить под крестик место, которого и так мало - тоже плохо. Особенно в случаях, когда у вкладок одного сайта начала названий одинаковые.
Поэтому я и предлагаю выход: показывать крестик на вкладке только когда сам указатель мыши уже наехал на эту вкладкой. Ведь когда мышь находится где-то в другом месте, на крестик ей не нажмёшь, а значит он в это время на экране не нужен.

**Comment by NS-Clone** [comment]
> Поэтому я и предлагаю выход: показывать крестик на вкладке только когда сам указатель мыши уже наехал на эту вкладкой.

ЭТО ЕЩЕ БОЛЬШОЕ ЗЛО
ты наводишь на вкладку чтобы перевести на нее фокус
АТУТ тте выскакивает ВНЕЗАПНО крестик
ИТЫ ЗАКРЫВАЕШЬ ВКЛАДКУ
а не все вкладки выдают подтверждения
и не все вкладки для развлечений
на некоторых что то 4 часа может щитатсо в облаке

**Comment by zanud** [comment]
> мне что надо листать на 3 страницы вправо хрен знает куда?

А я предпочитаю читать новооткрытые вкладки в том порядке, в котором открывал их.
Если я открыл их десятка полтора-ва, как я потом найду ту, которую открыл первой? Особенно если до этих "открытий" справа уже что-то было, и тоже в изрядном количестве.

Вот кстати, ты как в своих одновременно открытых 1500+ разбираешься? Как находишь нужную и переходишь на неё?

**Comment by zanud** [comment]
> ты наводишь на вкладку чтобы перевести на нее фокус
> АТУТ тте выскакивает ВНЕЗАПНО крестик
> ИТЫ ЗАКРЫВАЕШЬ ВКЛАДКУ

А по постоянно присутствующему крестику вот точно так же жмакнуть совсем невозможно?

**Comment by NS-Clone** [comment]
> Вот кстати, ты как в своих одновременно открытых 1500+ разбираешься? Как находишь нужную и переходишь на неё?

для дальних переходов пользуюсь менюшкой справа с вертикальным списком
ну и 1К вкладок лежат мертвым грузом дожидаясь своего времени
ибо им не место в закладках
но и нет времени их "проработать" и сохранить

**Comment by zanud** [comment]
> для дальних переходов пользуюсь менюшкой справа с вертикальным списком

Но ведь и этим списком при таких количествах пользоваться не реально. В нём же даже поиска нет.

**Comment by NS-Clone** [comment]
> > для дальних переходов пользуюсь менюшкой справа с вертикальным списком
> 
> Но ведь и этим списком при таких количествах пользоваться не реально. В нём же даже поиска нет.

он проскроливаетсо весь за 5 сек

**Comment by NS-Clone** [comment]
> > ты наводишь на вкладку чтобы перевести на нее фокус
> > АТУТ тте выскакивает ВНЕЗАПНО крестик
> > ИТЫ ЗАКРЫВАЕШЬ ВКЛАДКУ
> 
> А по постоянно присутствующему крестику вот точно так же жмакнуть совсем невозможно?

ты его хотябы видишь
а вот дергосмыкательный интерфейс не видно
терпеть ненавижу эти убигающие кнопки итд

**Comment by zanud** [comment]
> он проскроливаетсо весь за 5 сек

Быстро промотать-то не проблема. Как нужную строчку при этом выискать? Особенно с учётом того, что при большом количестве строк одно мелкое перемещение мышки может привести к тому, что куча строк проскочит, даже не показавшись на экране.

> ты его хотябы видишь

Ну, я же знаю, что он выскочит, и знаю где.

**Comment by NS-Clone** [comment]
> Особенно с учётом того,

1.5K вкладок еще можно
больше чем у меня врятли у кого то еще есть :)
да и 1,5К сессию уже браузер отказываетсо даже сохранять...

**Comment by zanud** [comment]
> да и 1,5К сессию уже браузер отказываетсо даже сохранять...

Ты на это много раз жаловался и ссылки даже на Bugzilla приводил. По одной или двум их них писалось, что проблема связана с тем, что у браузера ограничен размер буфера, куда помещаются данные о сессии перед их сжатием (в процессе сохранения файла).

А на размер этих данных влияет не только количество вкладок, но и то, что ты делал в браузере.
Вот тебе сценарий:
Закрыл ты браузер. Предыдущая сессия сохранилась в файл. Потом ты запустил браузер, поработал с какими-то вкладками, позакрывал их, загрузил прошлую сессию и закрыл браузер.
Всё, новый файл стал больше - в нём записаны не только те вкладки, которые были в браузере в момент его закрытия, но и те, которые ты закрыл.
И так с каждым разом, с каждым закрытием браузера содержимое файла всё увеличивается и увеличивается. Потому что сессия это не только открытые вкладки, но и закрытые, и другие закрытые окна с их вкладками, и тексты, введённые тобой на страницах (в том числе и закрытых) в поля ввода, и выбранные тобой галочки-кнопки, и вообще всё, что ты делал с момента начала сессии.

**Comment by NS-Clone** [comment]
не совсем
этож не 52
тут нету рабочего манагера сессий
я каждый запуск востанавливаю старую сессию
да и у закрытых вкладок есть время хранения
так что файл сессии не растет на дрожжах просто так

**Comment by zanud** [comment]
> я каждый запуск востанавливаю старую сессию
> да и у закрытых вкладок есть время хранения
> так что файл сессии не растет на дрожжах просто так

А вот это вопрос интересный. В далёком прошлом в Firefox можно было в настройках задать, через какое время удалять записи из истории посещений.
А сейчас в Mypal такой настройки нет.

**Comment by NS-Clone** [comment]
> А сейчас в Mypal такой настройки нет

что то такое есть в конфиге
НО даже если туда поставить 3+ секунды
файл сесси от этого нифига не худеет

**Comment by zanud** [comment]
> НО даже если туда поставить 3+ секунды
> файл сесси от этого нифига не худеет

Ну вот смотри: я открыл новую вкладку, открыл в ней какую-то страничку любого сайта, потом в этой же вкладке открыл любую другую, страничку, а потом зашёл в Журнал (историю посещений) и там удалил упоминания об этих двух только что посещённых страничках. И после этого удаления кнопка "Назад" у вкладки как была активной, так и осталась. И на предыдущую страничку с её помощью перейти можно.
И если я теперь вкладку закрою, то в пункте меню "Журнал" -> "Недавно закрытые вкладки" эта вкладка будет присутствовать.
И если я её через тот пункт меню восстановлю, то она восстановится со всей своей историей "Вперёд-Назад".

А если я не буду её восстанавливать, а просто закрою браузер, то эта закрытая вкладка со всей своей историей посещений и ещё кучей связанных с ней данных будет записана в файл сессии. И после последующего запуска браузера и восстановления сессии эта вкладка опять будет присутствовать в "Недавно закрытых вкладках".

А когда она из сессии удалится, я понятия не имею. Если у пунктов меню "Недавно закрытые вкладки" и "Недавно закрытые окна" есть ограничения на количество доступных в них элементов, то это и будет некоторой защитой от бесконечного разрастания файла сессии. А если таких ограничений нет, то вся эта радость так и будет бесконечно добавляться в файл, аж пока сессия не будет убита.

> а вот просто история посещений
> лучшо когда вечная
> вечно через 3 месяца что нить как понадобитсо
> и начинаешь рыть где же оно было

Ха, у меня в истории некоторые записи уже больше десяти лет хранятся. При том, что я историю чищу руками по несколько раз в день.
Хорошо, что у меня основной браузер Seamonkey, в нём окно истории куда как приятнее и удобнее устроено.

**Comment by NS-Clone** [comment]
> И если я её через тот пункт меню восстановлю, то она восстановится со всей своей историей "Вперёд-Назад".

не со всей
число шагов настраиваетсо в конфиге

**Comment by NS-Clone** [comment]
> > для дальних переходов пользуюсь менюшкой справа с вертикальным списком
> 
> Но ведь и этим списком при таких количествах пользоваться не реально. В нём же даже поиска нет.

вот в последних фаирфоксах было интересно

были отдельные наборы вкладок
вкладки можно было тематически групировать и переключатсо между ними
по моему их можно было по разному называть
у этих груп вкладок был превиев на которой было видно вкладки внутри группы
вкладки можно было перетягивать из одной группы в другую драгндропом
ляпота

прошло 6 лет и 50 версий
где этот функционал в этих хромоногихквантах?

**Comment by zanud** [comment]
> не со всей
> число шагов настраиваетсо в конфиге

А вот сколько шагов уложилось в эту настройку, столько и есть "вся её история".

Но напоминаю главное: эта вкладка давным-давно закрыта, ты её после восстановления не видишь, а место в файле она и все её данные занимают.

И то же самое происходит с каждой закрытой тобой вкладкой или окном: пока их можно восстановить через "Журнал" -> "Недавно закрытые вкладки"/"Недавно закрытые окна", при закрытии браузера они пишутся в файл сессии.

А ограничивают возможность такого восстановления параметры `browser.sessionstore.max_windows_undo` и browser.sessionstore.max_tabs_undo.

И ещё есть "срок жизни" - `browser.sessionstore.cleanup.forget_closed_after`. По умолчанию там 1209600000, только неизвестно в каких единицах. Если в миллисекундах, то это две недели. Но если в секундах...

**Comment by NS-Clone** [comment]
для перехода на левую вкладку
https://addons.mozilla.org/en-US/firefox/addon/select-after-closing-current/
и вроде бы не вешают браузер при загрузке сессии
