### ISSUE TITLE
[not an issue] i made another installer (don't really know why)

### ISSUE THREAD

**Issue by davide0033** [Feodor2/Mypal68#59]
i was bored so I "made" an installer similar to the firefox's one
(i checked it and i shoudn't give any false positive; if you want check it and if there are some false positive let me know): [link](https://mega.nz/file/525SRLhL#6WGcXQHjQ5R6ujezsW3s2cKw0GE66dUIWXv2V_q29EU)

**Comment by Matiasgroen** [comment]
Mega is known to be currently broken in Mypal68

**Comment by Feodor2** [comment]
Keep installer related here #28
