### ISSUE TITLE
Mypal68 - High memory usage

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal68#6]
The memory consumption is significantly higher with MyPal 68 than with MyPal 29.
Can this be optimized, or will this be like that?

**Comment by Feodor2** [comment]
Reduce multiprocess count in about:config - **dom.ipc.processCount** try 3
Default value of 8 may be too high at all.

**Comment by Anbima** [comment]
The memory usage does not change.
I only opened the Google Home.

dom.ipc.processCount = 3:
![dom ipc processCount_3](https://user-images.githubusercontent.com/49531928/162491291-95648e49-7bab-4f4a-9d5b-f39431df8c08.jpg)

dom.ipc.processCount = 8:
![dom ipc processCount_8](https://user-images.githubusercontent.com/49531928/162491289-d89686e8-5e8d-451a-a9e6-4dd570aebe2e.jpg)

**Comment by AroKol78** [comment]
try
`dom.ipc.processCount` `0` or `1`
and / or
try to disable multiprocessing (e10s)
`browser.tabs.remote.autostart` `false

**Comment by Feodor2** [comment]
@Anbima
> memory usage does not change
Yes, but it will change when you open many tabs, not sigifically though.
If even that memory is high for you try disable multiprocess at all 
**browser.tabs.remote.autostart;false** 
Nothing more.

disable multiprocess also may help with bsods

**Comment by Feodor2** [comment]
@Anbima
> memory usage does not change
Yes, but it will change when you open many tabs, not sigifically though.
If even that memory is high for you try disable multiprocess at all 
**browser.tabs.remote.autostart;false** 
Nothing more.

disable multiprocess also may help with bsods

**Comment by AroKol78** [comment]
`https://techdows.com/2019/08/multi-process-e10s-can-still-be-disabled-in-firefox-68-or-later-versions-here-is-how.html`
maybe you need yes 
`MOZ_FORCE_DISABLE_E10S` `1`

(I haven't studied the code yet)

**Comment by Feodor2** [comment]
about:config setting is enought
MOZ_FORCE_DISABLE_E10S 1 is redundant

**Comment by K4sum1** [comment]
I think this is specifically a fault of 68. I have no idea why Fedor2 went with specifically 68, it's the worst ESR version in recent history.

**Comment by win98se** [comment]
@K4sum1 In case you don't know, [he planned to start with 68 first, then 78 and 91, and finally choose one of them to continue the development.](https://github.com/Feodor2/Mypal/issues/46#issuecomment-1037449743)
Mypal68 is only the first step.
And you know things do get harder to achieve compatibility with Windows XP as many breaking changes may have been made from 68 to 78, and 78 to 91 as well.

**Comment by NEO-SPECTRUMAN** [comment]
а новом браузере есть browser.tabs.unloadOnLowMemory?
который упоминаетсо с 67-го Nightly

**Comment by NEO-SPECTRUMAN** [comment]
включил memory.free_dirty_pages
и субъективно такое чуства, что память утекает раза в 3 быстрее...
