### ISSUE TITLE
JavaScript Optional Chaining (?.) and Nullish Coalescing (??) support

### ISSUE THREAD

**Issue by roytam1** [Feodor2/Mypal68#60]
since fx68esr doesn't support these, you may need to backport from either from mozilla (see discussions in https://github.com/WaterfoxCo/Waterfox-Classic/issues/35 , https://github.com/WaterfoxCo/Waterfox-Classic/pull/101 , maybe also https://repo.palemoon.org/MoonchildProductions/UXP/issues/1658 and https://repo.palemoon.org/MoonchildProductions/UXP/issues/1894) or from seamonkey-2.53.12 (https://gitlab.com/seamonkey-project/seamonkey-2.53-mozilla/-/commits/2_53_12_final/js/src/frontend/)

**Comment by GreenReaper** [comment]
I ran into this when trying to load pgAdmin4, the vendor bundle uses code like `return(t.layerContainer??t.map)` and `n="popupVisible"in e?!!e.popupVisible:!!e.defaultPopupVisible,t.state={prevPopupVisible:n,popupVisible:n}`
