### ISSUE TITLE
Blue screen after MyPal 68 installation

### ISSUE THREAD

**Issue by chrischris888** [Feodor2/Mypal68#61]
@Feodor2

Dear Feodor2
First I appreciate the great speed and many options available in the new version, mostly the facebook messenger which is now working. However, minutes ago it just happened a new blue screen incident, (after opening more then 14 tabs on MyPal 68), and I catched it with the bluescreenview_setup.exe and I am attaching the file.
Also plug ins are not working or working just temporarily and then they cannot be changed from settings.

==================================================
Dump File         : Mini050422-01.dmp
Crash Time        : 04.05.2022 07:33:36
Bug Check String  : KERNEL_MODE_EXCEPTION_NOT_HANDLED
Bug Check Code    : 0x1000008e
Parameter 1       : 0xc0000005
Parameter 2       : 0xbf80fa77
Parameter 3       : 0xb06e9b08
Parameter 4       : 0x00000000
Caused By Driver  : win32k.sys
Caused By Address : win32k.sys+fa77
File Description  : Multi-User Win32 Driver
Product Name      : Microsoft® Windows® Operating System
Company           : Microsoft Corporation
File Version      : 5.1.2600.5512 (xpsp.080413-2105)
Processor         : 32-bit
Crash Address     : win32k.sys+fa77
Stack Address 1   : win32k.sys+df9e7
Stack Address 2   : win32k.sys+dff87
Stack Address 3   : win32k.sys+c146b
Computer Name     : 
Full Path         : C:\WINDOWS\Minidump\Mini050422-01.dmp
Processors Count  : 4
Major Version     : 15
Minor Version     : 2600
Dump File Size    : 98.304
Dump File Time    : 04.05.2022 07:34:32
==================================================

**Comment by andika207** [comment]
many users did suffer from BSOD.
be careful because our ''expert'' @win98se will try to convince you that the culprit is the multi process mode.

**Comment by chrischris888** [comment]
@andika207
Yersteday I made un upload of 1 GB file on youtube with MyPal68 and it was the only tab opened, and no other programs were opened during the upload ... in order to avoid any other possible factors who may generate BSOD, and exactly after the upload, WHEN I CLOSED the MyPal ... it crashed into blue screen.

The good news is that I got a message from Feodor2 and he said the problem IS SOLVABLE in the new future and that I should not worry much until the next upgrade version will be released.

So, I wrote back that until then I'll use 68 strictly for the Facebook chat (where it did not crash) and for everything else on the internet, I'll use the 29.3 version. So I have both of them installed.

Also, in the meantime, I am reading hundred of pages of blogs in order to find out if there is a chance to create a ramdisk for XP in order to make it use the unaddressed supplemental memory RAM for browser cache. It seems that the many XP experts are working hard to solve this and 99% is already solved ... except some problems with NVidia which does not recognize any PAE mode ... but there is a tricky way to change some path identifiers in the System folder in order to address the 32 bit to NVidia. But if they'll be any success in the future then, due to this amazing XP trick, the XP actually can be used on almost any moder machine and that would scare Microsoft if there'll be any success in thi direction.

**Comment by Feodor2** [comment]
@chrischris888 
Look #3 and do not make duplicate issues

**Comment by andika207** [comment]
>I am reading hundred of pages of blogs in order to find out if there is a chance to create a ramdisk for XP in order to make it use the unaddressed supplemental memory RAM for browser cache.

@chrischris888 RamDisk is so old school. don't you have a SSD ? 
if you want to unlock the 3GB RAM limit you have to patch XP kernel file

**Comment by INVorig** [comment]
I know, that people worship the multi process-mode here, But I took al look at the release of FF 68 and so many people reported issues with the multi-process-mode back then. For me this absolutely did the trick:
**browser.tabs.remote.autostart** to **false**
It runs now fast, nearly double speed than Mypal 29.3.0, no more BODs so far and with the lowest ever ram consumtion.
Even FF52/51 or Mypal 29.3.0 uses more. I don't see any reason why I should use multi-process-mode, when it makes only problems for me and renders my browser and system useless. In my normal way of browsing, I only use about 3 tabs, and that works fine. And XP use permanently all my 4 CPU Cores, so I cannot be faster.

**Comment by NEO-SPECTRUMAN** [comment]
> it makes only problems for me and renders my browser and system useless.

maybe it removes 2GB per process limit
and in future we will be forced to use it...

**Comment by andika207** [comment]
> For me this absolutely did the trick: **browser.tabs.remote.autostart** to **false**

@INVorig this is the string for multi process mode  **browser.tabs.remote.force-enable - true**

**Comment by andika207** [comment]
>I only use about 3 tabs, and that works fine. And XP use permanently all my 4 CPU Cores, so I cannot be faster.

@INVorig with 3 tabs you don't need the multi process feature and using the 4 CPU cores is meaningles if they are not working at 100%
