### ISSUE TITLE
Mypal68, 10 uses = 10 crashes (reboots)

### ISSUE THREAD

**Issue by jbclem** [Feodor2/Mypal68#62]
I like Mypal68, websites seem to load much quicker and snappier, and best of all on Kanopy.com I can play the movies.
But every time I've used Mypal68, it's found a way to crash, it doesn't show a blue screen but always reboots.  This occurs for various reasons, changing tabs, scrolling, moving the cursor to a different tab, and the few times where I've opened it and let it sit and not used it much...it's always crashed (rebooted) when I click on Exit.

When my Dell Optiplex 960 restarts, most times a window will pop up telling of a serious crash and asking me if I want to send certain files to Microsoft for analysis.  I've saved those files: manifest.txt, mini042922-01.dmp, and sysdata.xml so I'll try to attach them to this message, hoping they will be of some use.

No luck trying to drag and drop, or copy/paste the files.  I tried with Mypal 29 and now Firefox 54.9 esr.

**Comment by jbclem** [comment]
Forgot to mention my OS is WInXP sp3.

**Comment by win98se** [comment]
/dup #3

> it doesn't show a blue screen but always reboots

There must be blue screens but they're too fast for you to see before the system restarts by itself.

> manifest.txt, mini042922-01.dmp, and sysdata.xml

These three files are the indeed proofs of blue screen happenings; Additionally as stated in [README.md](https://github.com/Feodor2/Mypal68#readme), also use the BlueScreenView utility to collect data from those blue screens, then post them along with the files.

Also I recommend you to try the workaround stated at https://github.com/Feodor2/Mypal68/issues/3#issuecomment-1094060298.

**Comment by manfromarce** [comment]
For me, MyPal freezes and crashes when you open the menu or settings but neither the browser nor the system restarts.

**Comment by Feodor2** [comment]
#3

**Comment by jbclem** [comment]
Changing browser.tabs.remote.autostart to false fixed the above mentioned crash problem.  BluescreenView mentions win2k.sys as the causative driver...in all 5 crashes it's saved.

 Now there's a browser crash problem(not a computer crash) with amazon.com...that wasn't there in multi process mode.

What are the differences between Mypal 29, Mypal 68, and Firefox 52.9 esr that make the multiprocess mode so much more unstable in Mypal than in Firefox.  I don't ever remember having the bluescreen crash while using Firefox.

**Comment by win98se** [comment]
Firefox 52.x has multiprocess fully disabled and can't be enabled in any way under Windows XP; Mypal 29.x is based on old code that doesn't even include multiprocess feature.

**Comment by jbclem** [comment]
I have Firefox 52.9 esr running in multiprocess mode, with 4 processes running as we speak.  Sometimes an addon will switch it off, and that's how it was when I checked a few days ago.  I reset it in about:config and so far I'm back in multiprocess mode.  I don't remember having any crashing problem with it, but this time I'll keep an eye on it to make sure it stays in multiprocess mode.

**Comment by win98se** [comment]
> I have Firefox 52.9 esr running in multiprocess mode, with 4 processes running as we speak.

I wonder how do you manage to enable it **on Windows XP** - I don't get any second or more process in Task Manager.
![image](https://user-images.githubusercontent.com/11819816/167542738-607a103c-77f2-4580-b9d1-4ced4e4607d3.png)

**Comment by jbclem** [comment]
In about:config I have two entries:
browser.tabs.remote.force-enable  set to true
dom.ipc.processCount   set to 3

In about:support under Multiprocess Windows it sez:
2/2 (enabled by user)
in Task Manager there are 4 firefox.exe running 
I have 2 firefox windows open

**Comment by win98se** [comment]
I can reproduce your scenario now, I get 3 processes for 2 windows though.
All it needs is to fully close the browser then restarting it, instead of doing it from `about:profiles`; Also my `dom.ipc.processCount` is set to `8`.

**Comment by andika207** [comment]
LMAO so the ''expert'' @win98se who accuses others about BSOD didn't know it was possible to use multiprocesses with FF 52 ?

**Comment by andika207** [comment]
> **Firefox 52.x has multiprocess fully disabled and can't be enabled in any way under Windows XP**

pffffff..... no comments

**Comment by skipster1337** [comment]
> LMAO so the ''expert'' @win98se who accuses others about BSOD didn't know it was possible to use multiprocesses with FF 52 ?

Single process mode is literally _worse_, it doesn't bring any stability benefits from what I've seen and only makes the entire browser kick the bucket should one of your tabs crash. I haven't had a single BSOD happen with multiprocess, and the crashes / freezes I had were _**not**_ fixed by enabling single process mode.

**Comment by jbclem** [comment]
Although I would much prefer to use multiprocess mode, Mypal68 will crash everytime I use it in multiprocess mode.  In contrast, it hasn't crashed yet in single process mode.  What OS are you using?

**Comment by skipster1337** [comment]
> Although I would much prefer to use multiprocess mode, Mypal68 will crash everytime I use it in multiprocess mode. In contrast, it hasn't crashed yet in single process mode. What OS are you using?

I've mostly had it crash on XP.

**Comment by andika207** [comment]
> I haven't had a single BSOD happen with multiprocess, and the crashes / freezes I had were not fixed by enabling single process mode.

@skipster1337  neither did I have any BSOD with Serpent @roytam1 or Centaury @Feodor2
