### ISSUE TITLE
Win XP endless Repetition of Cloudflare Security Window

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal68#64]
Cloudflare does not seem to recognize MyPal as valid Browser, to enter the OpenCart Forum Pages, it only adds bulkloads of Entries in the History Section:

![MyPal_cloudflare_problem](https://user-images.githubusercontent.com/12776547/166907155-09c0c37e-1b23-477e-9236-849558d27e0c.png)

**Comment by AroKol78** [comment]
this is not a mypal specific problem.
this is a wider problem.
https://github.com/WaterfoxCo/Waterfox-Classic/issues/107

**Comment by IP-CAM** [comment]
In order to gain access, I installed Opera 36.0 for XP, to work with the Opencart Forum Site.

**Comment by NEO-SPECTRUMAN** [comment]
also on latest serpent52

**Comment by foxtrot-99** [comment]
before it seemed to work in new moon 28 but now is not working either.

**Comment by AroKol78** [comment]
I found it quickly (maybe need to report problems with MyPal68)

`https://community.cloudflare.com`
+
`/t/browser-integrity-check-broken/381029`
`/t/locked-threads-without-a-solution/381829`
`/t/cloudflare-is-blocking-waterfox-based-on-user-agent/382097`
`/t/customers-not-notified-of-changes-in-browser-support/382034`

`https://www.ghacks.net/2022/05/05/fix-pale-moon-browser-not-passing-cloudflares-checking-your-browser-verification/`
`https://forum.palemoon.org/viewtopic.php?f=70&t=28227`

**Comment by AroKol78** [comment]
> you’re using an out of date browser.

from `/t/older-versions-of-firefox-unable-redirect-to-the-target-page/382193`

>  I installed Opera 36.0 for XP, to work with the Opencart Forum Site.

on my part, the behavior of CF does not look nice, ...

**Comment by NEO-SPECTRUMAN** [comment]
Cloudflare was fixed this shit?

**Comment by IP-CAM** [comment]
Well, the Opencart.com Forum Site now seems to accept the MyPal Browser again.

**Comment by andika207** [comment]
> also on latest serpent52 too

@NEO-SPECTRUMAN I don't remember what site I got stuck in with the cloudfare loop because I rarely see this message poping up on Serpent browser @roytam1
Sometimes you only need to press F5 or wait a little more to work this out. RT is a ruzzian site

<a href='https://postimg.cc/2bwRmy7D' target='_blank'><img src='https://i.postimg.cc/2ypzQBqV/Snap-Crab-No-Name-2022-5-15-2-23-46-No-00.png' border='0' alt='Snap-Crab-No-Name-2022-5-15-2-23-46-No-00'/></a>
