### ISSUE TITLE
Compa's README should be considered

### ISSUE THREAD

**Issue by arsespec** [Feodor2/Mypal68#65]
https://github.com/Feodor2/Mypal68/blob/3470cec6c8df09b790e3727a92c0d62da0603c1b/README.md

Compa used a garbage password on this account that he's used elsewhere, so I managed to get into this account. He's a worthless transphobic piece of shit but he sure has a neat way of documenting things, I'll give him that. Maybe he's somewhat useful after all...

Not gonna lie, this README is actually really well formulated and should probably be included in the repository. It's better than the existing one anyways which is riddled with grammatical errors and other things.

**Comment by Feodor2** [comment]
I wait others eanglish speakers opinion on this.

**Comment by pachuco** [comment]
What does the above have anything to do with trains? I do not understand.

**Comment by pachuco** [comment]
Ah yeah, this is definitely cleaner, but it's a bit outdated(does not include info on what to do with crashes and xpsp2). Should be updated.
Actually, good idea.

**Comment by Feodor2** [comment]
Heh, others then dosnt know english good?

**Comment by pachuco** [comment]
I'll chip in some changes when I get home.

**Comment by baluw** [comment]
> https://github.com/Feodor2/Mypal68/blob/3470cec6c8df09b790e3727a92c0d62da0603c1b/README.md
> 
> Compa used a garbage password on this account that he's used elsewhere, so I managed to get into this account. He's a worthless transphobic piece of shit but he sure has a neat way of documenting things, I'll give him that. Maybe he's somewhat useful after all...
> 
> Not gonna lie, this README is actually really well formulated and should probably be included in the repository. It's better than the existing one anyways which is riddled with grammatical errors and other things.

And to you, is being transphobic a good enough reason to hack somebody's account? 

If yes, fix your priorities ASAP.

**Comment by pachuco** [comment]
I got off me lazy bumarse and combined OP's readme changes with Feodor original.
https://github.com/pachuco/Mypal68/blob/main/README.md

Let me know how it goes.

**Comment by CompileDesu** [comment]
> > https://github.com/Feodor2/Mypal68/blob/3470cec6c8df09b790e3727a92c0d62da0603c1b/README.md
> > Compa used a garbage password on this account that he's used elsewhere, so I managed to get into this account. He's a worthless transphobic piece of shit but he sure has a neat way of documenting things, I'll give him that. Maybe he's somewhat useful after all...
> > Not gonna lie, this README is actually really well formulated and should probably be included in the repository. It's better than the existing one anyways which is riddled with grammatical errors and other things.
> 
> And to you, is being transphobic a good enough reason to hack somebody's account?
> 
> If yes, fix your priorities ASAP.

Troons will be troons.
