### ISSUE TITLE
Browser freezes when trying to open menu

### ISSUE THREAD

**Issue by skipster1337** [Feodor2/Mypal68#68]
Trying to open the menu on the right sometimes can freeze the browser, while other times it works fine. I've had this happen on Windows 7 and 8.1, both on 68.12.1 and 68.12.2.
![Windows 7 Professional x64-2022-05-17-14-44-09](https://user-images.githubusercontent.com/91155070/168803723-f612cc39-fdab-45f6-8b68-897ae1a064b5.png)
I'm not sure what logs to attach so please let me know.

**Comment by win98se** [comment]
If this problem also happens to you on Windows XP (probably plus Vista) then it also might be a problem, but on these two OSes you can just use vanilla Firefox instead I guess.

**Comment by win98se** [comment]
I have the similar bug on 68.12.3b, it seems the profile folder has corrupted; Renaming the profile folder and let it to remake one solves it (but the downsides are to reconfigure everything).

**Comment by skipster1337** [comment]
Was the profile folder from an older version? I cleared my profile folder before downloading 68.12.3 and the bug _seems_ to be gone on my laptop running Windows 8.1. I will do more testing on more computers later.

**Comment by skipster1337** [comment]
Clean install of Mypal 68.12.3 on Windows 7 with no profile folder prior, never crashed a single time when opening the menu. Safe to say the bug is fixed.

**Comment by win98se** [comment]
> Was the profile folder from an older version?

No, it was a new profile made in 68.12.3b and used for just about 15 mins at that time.
I suspected myself playing too much with the configuration options and addons broke it, and remaking another new profile solved it.

Good to see another issue solved.
