### ISSUE TITLE
Video-Page of Bitchute.com

### ISSUE THREAD

**Issue by INVorig** [Feodor2/Mypal68#69]
The videos on bitchute.com can only be played by embed code. The Video-playback-page is inaccessible.
It stays in this condition: 
![image](https://user-images.githubusercontent.com/90109483/168901211-3b2b4636-b413-4dbb-b764-3596e4f81d8c.png)
To clarify: This issue is ported over from Firefox 68
The issue is present in Mypal 68, Mypal 29.3.0, latest PaleMoon, Firefox 68 ...
But the page is working in, for example Firefox  99 ...

I hope you can create a fix for this page.

Kind regards,

**Comment by sirrooster** [comment]
Same problem for me.
www.bitchute.com
