### ISSUE TITLE
Why not post browser source on github?

### ISSUE THREAD

**Issue by skipster1337** [Feodor2/Mypal68#7]
I see that you now use mega for the Mypal downloads, why so? Wouldn't uploading the source code on the github repo, and browser downloads on releases page work better? Just asking.

**Comment by Feodor2** [comment]
Later. No time to do repo errands now.

**Comment by skipster1337** [comment]
Very smart. You can upload it when you feel like it's the time.

**Comment by Yardanico** [comment]
That technically violates Firefox's license though :shrug:

**Comment by MTlabs** [comment]
> That technically violates Firefox's license though 🤷

Here we go again.. The download link for the source code is next to normal download link. Firefox license state that the code must be in public git repo or what?

**Comment by NEO-SPECTRUMAN** [comment]
>Here we go again.. 

FCKYOU!

**Comment by MTlabs** [comment]
> > Here we go again..
> 
> FCKYOU!

Calm down. I was just quoting and responding to the comment before me (which is now deleted for some reason). You should probably learn to read first before you start malding.

**Comment by skipster1337** [comment]
No need to get angry or insult people here. There is no problem with how the source is shared, mozilla themselves won't come to shut down this repo like the guys at PM did. I just suggested to put the source on the repo itself for convenience.

**Comment by NEO-SPECTRUMAN** [comment]
> to get angry

im not native english speaker
i decided that another one tobin appeared

**Comment by tomoyo576i** [comment]
I'm not even taking sides with this, but I'm pretty sure violating software licencing laws is illegal whether you consider the product to be useful to the community or not, disregarding past history with Pale Moon software developers.

I doubt the Mozilla Foundation would be as blunt as Moonchild Productions' crew to the point of downright unprofessional, however I also don't think they'd be particularly pleased with an individual taking a copy of their source, modifying it, and not releasing the source code (particularly when there are already public binaries available).

The GPL and MPL are both are pretty similar in that they don't permit 'private' forks of their software (i.e. closed-source/nonfree), unlike say MIT or most of the BSD licences (except the most restrictive variations of the latter).

There are multiple instances of companies and individuals getting into legal trouble for mixing code with incompatible licences, modifying GPL/MPL-licenced software without providing the source code... and if the maintainer of Mypal wants to go down that road again, all the meanwhile stirring up more childish drama that just isn't needed, then so be it.

At the end of the day, I'm just here stating my opinion (and likely wasting my breath doing so) from a mostly-outside perspective on the matter (and with a likelihood of being flamed from terminally-online teenagers with Picrew/anime profile pictures who hang about on Discord and Twitter all day while whining that they miss the old internet, despite never actually having experienced traditional message board culture outside of maybe posting one or two things on a large forum.)

**Comment by skipster1337** [comment]
> I'm not even taking sides with this, and I don't have a professional degree or anything when it comes to this, but I'm pretty sure violating software licencing laws is illegal regardless of whether you consider the product to be useful to the community or not, and that is disregarding past history with Pale Moon software developers. The MPL is the MPL (or whatever licence a piece of software uses) and by using a piece of software you are bound to its terms and conditions legally, as it is a legal document. The same logic can also be applied with websites and their TOS/Privacy Policies.
> 
> Don't like it, don't use it.
> 
> I doubt the Mozilla Foundation would be as blunt as Moonchild Productions' crew to the point of downright unprofessional, however I also don't think they'd be particularly pleased with an individual taking a copy of their source, modifying it, and not releasing the source code (particularly when there are already public binaries available).
> 
> The GPL and MPL are both are pretty similar in that they don't permit 'private' forks of their software (i.e. closed-source/nonfree), unlike say MIT or most of the BSD licences (except the most restrictive variations of the latter).
> 
> There are multiple instances of companies and individuals getting into legal trouble for mixing code with incompatible licences, modifying GPL/MPL-licenced software without providing the source code... and if the maintainer of Mypal wants to go down that road again, all the meanwhile stirring up more childish drama that just isn't needed, then so be it.
> 
> At the end of the day, I'm just here stating my opinion (and likely wasting my breath doing so) from a mostly-outside perspective on the matter - and with a very strong likelihood of being flamed from terminally-online teenagers with shitty Picrew profile pictures who hang about on Discord and Twitter all day and don't know what 'taking anyone else's opinion into consideration' even means; just acting like a herd of sheep and copying everything their favourite YouTube influencers or Discord/Twitter shitposters and/or roleplayers do in the hopes of being famous.

Fairly true response, albeit put together a bit rudely. Your definition of 'twitter kids' is scarily accurate as well. However there was probably no need to come up with that.
Either way I doubt that Mypal violates the MPL currently, as the readme clearly links to the source code for the current version of the binaries, which you need to be either blind or 'inclined to legally wreak havoc' to not find. Sure it doesn't really make sense to do it like that but I'm sure feodor will publish the code properly, eventually.

**Comment by MTlabs** [comment]
The link for the source code is available next to download link. I really don't know what you want him to do. When the old MyPal source code was hosted in Github repo, they said that it was wrong. The source code is now hosted in a way that it exactly corresponds with the released version and he is wrong again?

**Comment by tomoyo576i** [comment]
I am an idiot, and didn't see the 'Source' link. I guess I owe Feodor2 and you guys an apology for making assumptions.

However it shouldn't take too much effort to simply throw the latest source tree and set up the Git VCS from the command line.

**Comment by Feodor2** [comment]
So i have uploaded the source here - rejoice.
As i understand now:
1. I am obliged put the link to the source and it is not matter what site - that was done.
2. The source is not to contain mozilla firefox logos icons and other such graphics - that was done, but please check too, i do not know all places where it can be another firefox picture.

Looking for other advises.

**Comment by IP-CAM** [comment]
Latest Mypal68 Version can be found here now:
https://github.com/Feodor2/Mypal68
