### ISSUE TITLE
DeviantArt is refusing to load

### ISSUE THREAD

**Issue by mina354** [Feodor2/Mypal68#74]
The website DeviantArt is refusing to load on Mypal 68. Tested on a clean profile. It loads in Mypal 29.3.0 and Firefox 52.9.0 ESR too.
![image](https://user-images.githubusercontent.com/87821255/169699590-d694313e-5313-45dc-a847-59e866fda289.png)
![image](https://user-images.githubusercontent.com/87821255/169699980-d72142b4-e975-4360-b5a8-1a911206604f.png)

**Comment by NoNameNeeded2** [comment]
it's strange that it works with Firefox 52 because with Firefox 68 it doesn't, just like with Mypal68.

**Comment by greyrat116** [comment]
layout.css.resizeobserver.enabled true

**Comment by mina354** [comment]
@greyrat116 Thanks for the solution, it made DeviantArt load again.
