### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by FurblandChannel** [Feodor2/Mypal68#76]
Does this have auto updating functionality and if not are you planning to add it?

**Comment by NEO-SPECTRUMAN** [comment]
NO ONE needs auto updating

**Comment by GreenReaper** [comment]
No need to be rude. Clearly at least one person is curious, but they did not say that they actually wanted it, just that they wondered if it did or was going to exist. Perhaps they share your own view. It does have "check for updates" on Help/About.

**Comment by NEO-SPECTRUMAN** [comment]
m$ share only own view too
and billions of n00bs are excited
n00bs opinion does not matter

**Comment by FurblandChannel** [comment]
Mind you, I’m asking on behalf of my grandpa who would like a modern browser for his XP computer that auto updates.

**Comment by NEO-SPECTRUMAN** [comment]
+1 to grandpa

**Comment by FurblandChannel** [comment]
(issue closed due to one guy being toxic. thanks NEO-SPECTRUMAN, you ruined it for everyone.)

**Comment by NEO-SPECTRUMAN** [comment]
> (issue closed due to one guy being toxic. thanks NEO-SPECTRUMAN, you ruined it for everyone.)

after Feodor2 will makes stable releases again
he maybe add auto updates again

@FurblandChannel do not forget
in ukraine NOW WAR

**Comment by FurblandChannel** [comment]
I am aware, now please stop responding to this topic. I closed it.
