### ISSUE TITLE
VirusTotal doesn't work anymore

### ISSUE THREAD

**Issue by AstroSkipper** [Feodor2/Mypal68#78]
The website virustotal.com changed its interface and doesn't work anymore. Maybe it can be fixed. All old browsers like New Moon 28 and Mypal 29 don't work anymore either.

**Comment by AstroSkipper** [comment]
> oficial light version exist https://www.virustotal.com/old-browsers/ im using it last n years

I already knew that. The problem is the API has broken too. Tools like VirusTotal Uploader don't work anymore. The browsers New Moon 28, Mypal 29, Serpent and so on, don't work anymore with new interface and API. Strange is that old Firefox 52.9.0esr can load this new interface.

**Comment by AstroSkipper** [comment]
In Firefox 52.9.0esr no light version is needed. It can load this new interface, scans uploaded files and shows the results. And https://www.virustotal.com/old-browsers/ is working in all browsers without spoofing. Therefore I don't understand your suggestion. Anyway in **Mypal 68** the site **virustotal.com** with its **new interface** is **not working**.

**Comment by Feodor2** [comment]
I do not use it because of it has been became gogelized, but from the ru-board fellows saw **dom.moduleScripts.enabled;fals**  helps, beware it also may help to break other site.

**Comment by AstroSkipper** [comment]
> I do not use it because of it has been became gogelized, but from the ru-board fellows saw **dom.moduleScripts.enabled;fals** helps, beware it also may help to break other site.

Setting **dom.moduleScripts.enabled** to **false** leads to loading of the new interface, a file can be uploaded, but the results (**Checking hash**) can't be shown. Therefore **no solution**. But anyway, thanks for the hint!

**Comment by AstroSkipper** [comment]
Unfortunately, the new interface of **VirusTotal** doesn't work properly, again. Setting **dom.moduleScripts.enabled** to **false**, leads to loading of the new interface, a file can be uploaded, the service seems to check the hash, **but** the results of checking are **not** shown anymore.

Cheers, AstroSkipper [![pcwut.gif](https://i.postimg.cc/qR1tnnGR/pcwut.gif)](https://postimg.cc/XGy76rmS)
