### ISSUE TITLE
Crash on Sketchfab webgl

### ISSUE THREAD

**Issue by pachuco** [Feodor2/Mypal68#8]
https://sketchfab.com/
This site crashes browser tab upon trying to render webgl.

**Comment by Feodor2** [comment]
Certainly webgl require directx which is not supported yet on winxp
Seems it uses another stuff which is easier to add - i shall try.

**Comment by pachuco** [comment]
does opengl work?

**Comment by Feodor2** [comment]
Yes, look #376, but crash upon closing the browser, though seems harmless
