### ISSUE TITLE
Again no donation link or DASH address

### ISSUE THREAD

**Issue by L3P3** [Feodor2/Mypal68#84]
I already donated to your DASH number. I hope you got it.

Now, how can I support you again for this project? The readme does not have DASH Address.

Thanks )))

**Comment by Feodor2** [comment]
Yes, thanks i got there, Today i looked into it and seems it still works, so you may donate again.
XetK1TDBqVAyqnTJUd65g9Pi1HcQEtFF2c

**Comment by pachuco** [comment]
I am tempted to donate, but I saw "cryptocurrency" on DASH site, and now I am reluctant to touch DASH with a 10 foot pole.

**Comment by L3P3** [comment]
Yes, DASH is a cryptocurrency. Reason is that in area where Feodor2 lives, there is no good way to receive money via bank. Or has it changed already? Where are you Feodor2?

**Comment by Feodor2** [comment]
Yes the chance that money will be stolen by criminals bank is greater, i do not like crypto too i shall think about another way.

**Comment by 1badapple** [comment]
Any updates on accepting crypto? Or any crypto alternative worth considering?

**Comment by Feodor2** [comment]
Still that dash only.

**Comment by Trancer03** [comment]
Что такое "DASH site"?

**Comment by Trancer03** [comment]
I've installed "coinomi", and "**Buy**" option is unclickable! Can someone help me?

**Comment by Trancer03** [comment]
Друг, я тебе помогу собрать пять тысяч долларов!

**Comment by Trancer03** [comment]
I found out how to buy, but there is no option for Dash currency despite that I've crated a Dash wallet on "coinomi"!

**Comment by Trancer03** [comment]
They said that the Desktop version of the wallet doesn't support buying, so they've given me a link on their domain to purchase it in the browser.
They've told me at Customer Support that Dash is under maintenance. They said that I could still buy it, but it wouldn't show up in my wallet (I guess until it passes maintenance). Thus, there should be an option for Dash on the website, but there is NONE!

**Comment by Trancer03** [comment]
**Coinomi** is the only wallet that will work on my **macOS Sierra**, so I have no other options! Can someone help me with that **coinomi** crap?

**Comment by Trancer03** [comment]
I've tried **Guarda** on my Linux computer, and Dash is available there, but it says: "_Unfortunately, we couldn't find a reliable partner to process the purchase with such parameters. Please, select another cryptocurrency and try again._"

**Comment by Feodor2** [comment]
Just please stop spam.

**Comment by Trancer03** [comment]
I'm sorry, Feodor2, I'm just trying to allude to you that there are a lot of issues with dash. It would be great if you could also use any other currency!

**Comment by Feodor2** [comment]
Who really want donate did it without an issue, so i do not trust you, please pass by.

**Comment by Trancer03** [comment]
I sincerely want to help, but you making me a pariah! Look at my profile, I've donated before to a similar cause.
It's fine that you don't want to accept any other currency, you will just have to wait until it starts working or until I'll figure it out. I'm totally new to all this!

**Comment by Trancer03** [comment]
Я тебе не указ, делай как хочешь! Просто я видел в этой дискусии у тебя уже спрашивали:
> Any updates on accepting crypto? Or any crypto alternative worth considering?
Наверное у них были тоже проблемы с Dash!

**Comment by Trancer03** [comment]
Я тебе послал первую экспериментальную порцию! Дай знать, получил-ли?

**Comment by Trancer03** [comment]
Why didn't anyone tell me that I can buy any currency then exchange it to Dash!?

**Comment by Trancer03** [comment]
It's a freaking gamble - I've lost 25% of the money, but I'm the man of my word!

**Comment by Trancer03** [comment]
It's a freaking gamble - I've lost 25% of the money, but I'm the man of my word!

**Comment by Trancer03** [comment]
Фёдор, ты деньги получил или где?!

**Comment by jonm58** [comment]
👀👀👀

**Comment by Feodor2** [comment]
Yes i have received, thank you.

**Comment by Trancer03** [comment]
Деньги будут! Я пидсрался.

**Comment by Trancer03** [comment]
Ищейки дяди Сэма меня ебут в сухую!

**Comment by Trancer03** [comment]
Ищейки дяди Сэма рвут мне жопу в сухую!

**Comment by jonm58** [comment]
> Ищейки дяди Сэма рвут мне жопу в сухую!

IRS moment

**Comment by Trancer03** [comment]
I am in reference to how cryptocurrency is controlled in U.S. by BIG BROTHER!

**Comment by Trancer03** [comment]
Фёдор, I'm sorry, I blew it! I have the money, but I can't put up with fascist totalitarian control of cryptocurrency in U.S.

**Comment by L3P3** [comment]
@Trancer03 stop annoying people. DASH is decentral and open source, not controlled by any state! Also "fascist totalitarian" is extremistic bullshit, come down. Could we close this thread?

@Feodor2 Better put your DASH address directly in Readme and close this.

**Comment by jonm58** [comment]
> Фёдор, I'm sorry, I blew it! I have the money, but I can't put up with fascist totalitarian control of cryptocurrency in U.S.

Cryptocurrency is decentralized, I think you are talking about Cryptocurrency exchanges Lol

**Comment by Feodor2** [comment]
@Trancer03 Yes this in not a chat, do not post irrelevant shit.

**Comment by Trancer03** [comment]
Does any of you live is U.S.?
Are you familiar with KYC (Know Your Customer) policy?
They want the picture of your state ID (front and back), picture of your passport, your Social Security Number, bio-metrical scan of your face, and your selfie holding all of these documents! They say that government obligates them to do that. How would you call that?!?

**Comment by jonm58** [comment]
@Feodor2 please Lock conversation

**Comment by jonm58** [comment]
> Does any of you live is U.S.? Are you familiar with **KYC** (Know Your Customer) policy? They want the picture of your **state ID** (front and back), picture of your **passport**, your **Social Security Number**， **bio-metrical scan of your face**, and your **selfie** holding all of these documents just to purchase ANY currency! They say that government obligates them to do that. How would you call that?!?

Please respect USA’s financial **security** policy

**Comment by Ariel-Schnee** [comment]
I live in the USA. I have never, ever, not even once encounter such a thing anywhere. And I'm in m 50s.



---

Signature - SFW - https://www.fanficparadise.com/arielschnee/sig3.htm
Signature - NSFW - https://www.fanficparadise.com/arielschnee/sig3_NSFW.htm


  ----- Original Message -----

**Comment by jonm58** [comment]
Ah, Trancer03's fake news. No one can lock down a conversation?

**Comment by Trancer03** [comment]
> I live in the USA. I have never, ever, not even once encounter such a thing anywhere. And I'm in m 50s.
> […](#)
> --- Signature - SFW - https://www.fanficparadise.com/arielschnee/sig3.htm Signature - NSFW - https://www.fanficparadise.com/arielschnee/sig3_NSFW.htm
> ----- Original Message ----- From: Trancer03 To: Feodor2/Mypal68 Cc: Subscribed Sent: Friday, May 03, 2024 5:24 PM Subject: Re: [Feodor2/Mypal68] Again no donation link or DASH address (Issue #84) Does any of you live is U.S.? Are you familiar with KYC (Know Your Customer) policy? They want the picture of your state ID (front and back), picture of your passport, your Social Security Number, bio-metrical scan of your face, and your selfie holding all of these documents! They say that government obligates them to do that. How would you call that?!? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I'm talking about cryptocurrency, boss!

**Comment by Trancer03** [comment]
> I live in the USA. I have never, ever, not even once encounter such a thing anywhere. And I'm in m 50s.

I'm talking about cryptocurrency, boss!

**Comment by Trancer03** [comment]
Фёдор, I've sent you the last bit of the money that I was able to get without verification. Now my only option are ATMs, but the fee is 20% in them!

**Comment by Trancer03** [comment]
> I live in the USA. I have never, ever, not even once encounter such a thing anywhere. And I'm in m 50s.

If you're so smart, why won't you try to donate?!
I don't appreciate all the disrespect I've gotten on this thread and believe you owe me an apology!

**Comment by Ariel-Schnee** [comment]
What donation? What are you talking about? I have no idea what you mean. Apologize? For what?

I do not like your hostile tone. You are being rude. Stop it.

Disrespect? You are the one showing disrespect. You're so rude.



---

Signature - SFW - https://www.fanficparadise.com/arielschnee/sig3.htm
Signature - NSFW - https://www.fanficparadise.com/arielschnee/sig3_NSFW.htm


  ----- Original Message -----

**Comment by jonm58** [comment]
@Feodor2 please Lock conversation!!!!!

**Comment by Trancer03** [comment]
> What donation? What are you talking about? I have no idea what you mean. Apologize? For what? I do not like your hostile tone. You are being rude. Stop it. Disrespect? You are the one showing disrespect. You're so rude.

I don't know where you popped out from, but this thread is for donation! They treat me as a pariah in this conversation despite that I try to donate, and I believe THEY owe me an apology.

**Comment by Trancer03** [comment]
From the day 1 I've started to post in this conversation tying to donate, I've got nothing, but disrespect and not a bit of help. Despite that, I probably gave more money to the cause then any of you, and that's why I believe you owe me an apology!

**Comment by jonm58** [comment]
> I've probably given more money to the cause then any of you, and that's why I believe you owe me an apology!

plz stop donation war

**Comment by Trancer03** [comment]
Stop treating me like shit!

**Comment by jonm58** [comment]
> Stop treating me like shit!

No one here treats you like shit anymore, please calm down

@Feodor2 please lock the conversation, everyone here needs to calm down.

**Comment by Trancer03** [comment]
Do you know that I've lost nearly 40% of the money trying to figure out how cryptocurrency works?

**Comment by jonm58** [comment]
Normal, very normal for a currency that has no national credibility.

The consequence of decentralization is that everything is your own responsibility, no one is responsible for you when the cryptocurrency is gone

**Comment by Trancer03** [comment]
That's fine, but I can't buy anymore without KYC verification with the payment partners, with both of which (**Simplex** and **Guardarian**) I've skrewed up and can't use their services anymore!

**Comment by jonm58** [comment]
We shall think about another way.(gold?silver?)

**Comment by Trancer03** [comment]
I think any traditional way of transferring the funds would be better because I know a person who sends the money to her son in Ukraine here in the States, and I'm more than positive that she is NOT using cryptocurrency!

**Comment by Trancer03** [comment]
> No one here treats you like shit anymore

So you admitting you all were?!! Do you know how much stress you've caused me? This is not right. There is such thing as "Golden Rule", it says "Treat others the way you want to be treated"!

**Comment by Ariel-Schnee** [comment]
I just replied to an email I got in my inbox stating that you had to do ridiculous things to buy anything in the US. I stated that I had never encountered such a thing. I'm really sorry I ever replied to that email.:(



---

Signature - SFW - https://www.fanficparadise.com/arielschnee/sig3.htm
Signature - NSFW - https://www.fanficparadise.com/arielschnee/sig3_NSFW.htm


  ----- Original Message -----

**Comment by Trancer03** [comment]
No Problem!

**Comment by Trancer03** [comment]
No Problem, I should've said "cryptocurrency" instead of "currency", but I had no idea how this emailing feature works!

**Comment by Trancer03** [comment]
Next time try to read into it and find out where the email comes from before responding!

**Comment by Trancer03** [comment]
@jonm58 Laughs the one who laughs last! (Russian proverb)

**Comment by jonm58** [comment]
> @jonm58 Laughs the one who laughs last! (Russian proverb)

Nahezu wörtlich: "Wer zuletzt lacht, lacht am besten." (german proverb)

**Comment by Trancer03** [comment]
Фёдор, я тебе ещё немного выслал! Получил?

**Comment by Trancer03** [comment]
Друг, я тебе ещё выслал! Пожалуйста, ответь что ты жив и получил деньги!

**Comment by Trancer03** [comment]
@Feodor2 Фёдор, ответь пожалуйста, получил-ли ты деньги, чтобы я знал, что я не шлю в никуда?

**Comment by Trancer03** [comment]
@Feodor2 Я купил Dash по курсу ¬38$. К моменту когда я смог тебе послать, Dash стал полсти вверх. Если ты это учёл, ты должен получить приблизительно в 2 раза больше, чем я потратил!
Я бы на твоём месте ссал бы кипятком, а ты молчишь, как-будто тебе деньги не нужны!

**Comment by Trancer03** [comment]
@Feodor2 Я купил Dash по курсу около 38$. К тому моменту, как я тебе смог послать, Dash стал полсти вверх. Если ты это учёл, ты должен получить почти в 2 раза больше, чем я потратил!
Я бы на твоём месте ссал бы кипятком, но ты молчишь, как-будто тебе деньги не нужны!

**Comment by Trancer03** [comment]
@Feodor2 Я купил Dash по курсу около 38$. К тому моменту, как я тебе смог выслать, Dash стал полсти вверх. Если ты это учёл, ты должен получить почти в 2 раза больше, чем я потратил!
Я бы на твоём месте ссал бы кипятком, но ты молчишь, как-будто тебе деньги не нужны!

**Comment by Feodor2** [comment]
Ну отлично же, не надо волноваться. Это из-за твоего спама темы пришлось закрыть и она вышла из отслеживания. Дя просно я не проверяю каждый день и так.

**Comment by Trancer03** [comment]
Я очень сожалею и прошу прощения!
Я вышлю тебе ещё когда Dash опять упадёт.

**Comment by Trancer03** [comment]
Я очень сожалею и прошу прощения!
Я вышлю тебе ещё, когда Dash опять упадёт.

**Comment by Trancer03** [comment]
Дорогой друг, я ещё выслал! Посмотри по обстоятельствам когда снимать.

**Comment by Trancer03** [comment]
@jonm58 Stop hating, parasite!

**Comment by Trancer03** [comment]
С Новым годом! Я тебе ещё выслал.

**Comment by Trancer03** [comment]
С Новым годом! Я тебе ещё выслал.
Спасибо за твой честный и бескорыстный труд!

**Comment by Trancer03** [comment]
Я ещё выслал. Ответь, что получал всё!

**Comment by Trancer03** [comment]
@Feodor2, jackpot!
Посмотри в свой кошелёк!

**Comment by Trancer03** [comment]
Фёдор, пока не снимай если ещё не снял, оно скоро должно пойти вверх!

**Comment by Trancer03** [comment]
Дорогой друг, скажи пожалуйста, снял ли ты деньги? Я надеюсь, что пока нет!

**Comment by Trancer03** [comment]
@Feodor2, ты даже мне спасибо не скажешь?

**Comment by Trancer03** [comment]
@Feodor2, скажи сколько тебе нужно денег?

**Comment by luxxle** [comment]
> I've had a user ask about changing their default search engine in MyPal to Luxxle.
> 
> Tried to make an extension to do so, but every time it says "corrupted".
> 
> I'd be happy to donate to the project if someone could help explain how to change the default search engine in MyPal to Luxxle.
> 
> [https://luxxle.com/luxsearch?q={query}](https://luxxle.com/luxsearch?q=%7Bquery%7D)
> 
> [https://luxxle.com/autocomplete?q={query}](https://luxxle.com/autocomplete?q=%7Bquery%7D)
> 
> Feel free to email the team as well at [info@luxxle.com](mailto:info@luxxle.com)

Wanted to circle back around on this?

**Comment by Trancer03** [comment]
Hopefully there will be more money after New Year!

**Comment by Trancer03** [comment]
I've miscalculated and blew it this month, I'm sorry!
As soon as Dash will go down, there will be more money.

**Comment by Trancer03** [comment]
First portion of money's there!

**Comment by Trancer03** [comment]
Друг, посмотри в кошелёк!

**Comment by Trancer03** [comment]
Фёдор, как ты там?
