### ISSUE TITLE
Use on Windows XP x64 Professional broken for me

### ISSUE THREAD

**Issue by GrandAdmiralThrawn** [Feodor2/Mypal68#85]
I am currently using XP x64 with all updates applied, see info below. Currently, MyPal68 is only available as a 32-bit build, so that's what I downloaded. There is no crash or anything, but the browser does not render any content, not even its own GUI!

So all I get is a frame with no content inside. I can drag & move the window if I click where the title bar would be. I can even terminate the browser when I click where the "x" would be, so it appears to be working. It just cannot render any elements inside its window.

After 2-3 times of launching it, it cannot even create that anymore and will not have "Move" or "Resize" active on its context menu, indicating it's not even getting to the point where the WS_THICKFRAME GDI window style should be set.

OS: Windows XP Professional x64 Edition SP2
Patchlevel: Including all freely available Server 2003 R2 x64 updates
CPU: Xeon X5690
RAM: 48G
GPU: nVidia GeForce GTX Titan Black
GPU driver: 355.98 (newer versions do not support custom resolutions, which I require)
Res: 3840x1600x24@40Hz

**Comment by nguyenthienminh** [comment]
Huh, not for me seemingly. Seems like the current build just magically fixed the issue for some reason...

**Comment by GrandAdmiralThrawn** [comment]
> Huh, not for me seemingly. Seems like the current build just magically fixed the issue for some reason...

You're right! I'm currently writing this with the most current version at this time (68.12.4b), running on the XP x64 installation mentioned in my report. Also cross-tested it on a XP x64 VM of mine, where it also worked.

Didn't expect this to get fixed this quickly! :)

**Comment by enigma131** [comment]
Is working here too on Xp 64, real machine.
