### ISSUE TITLE
 Mypal68 wordpress.com Unsupported

### ISSUE THREAD

**Issue by tam35** [Feodor2/Mypal68#86]
![world](https://user-images.githubusercontent.com/1906077/170818480-e903cd7d-e294-414a-8a36-0ee22ef372b9.png)
WordPress support removed XP support
I installed mypal68 as a hope, the room did not run

**Comment by Feodor2** [comment]
I consider this is not important, for now i am botherin with crashes, bsods and direct9. 
The wordpress all evil indeed, It always put every new piece of script on intent to break older browser while most upgprade.
I myself used wordpress but i did not upgrade, site still works good.

If you come here for winxp browser, may be you do care that your site works on older browser then, so drop wordpress or use older version.

**Comment by visionhelp** [comment]
Wordpress offers "Continue loading the page anyway", but does not work ! 
Parallel I use New Moon 28.10.6a1 (32bit) (2022-06-02) "palemoon-28.10.6a1 -xpmod", which is now a new updated version. The versions before have been all reliable, except of (german) TV videos. Which does now work in thanks this Mypal 68.12.4b (32bit). Great. (And even faster.)

**Comment by Feodor2** [comment]
I setup server myself, though not simple, but  i can not to care of the update and so do with all i want what i want.

**Comment by visionhelp** [comment]
Wordpress saying "Unsupported Browser": just asking, please, what does let recognize Wordpress this "Unsupported Browser" ? 

In rare cases with NewMoon and PaleMoon (both for XP) I receive this message, too. In very rare. (Sorry, just to mention, please.) But usual the offer to ´ignore´ does let the sites go on, work.

**Comment by visionhelp** [comment]
If welcome, if from interesst: wordpress with ´mypal 68.13.1b en´ works well. 
(From updates within wordpress I do not know anything, sorry.)

**Comment by Feodor2** [comment]
Ignore the spammer

**Comment by visionhelp** [comment]
Feodor2. 
Have been long away from here. From several reasons. 
So answered some questions points here fast. 
Spamming is not my intention. 
Did download the version ´mypal 68.13.1b en 32bit´ and I am glad the things now work well. 
(If ths mis-placed now here, one word, please, and I delete it again.) 

To Your question to me there https://github.com/Feodor2/Mypal/issues/88, which You closed and I cannot answer there: 
Browser and Mail are the two things, that are important for me to run on XP. 
Loosing Mail, as now already this long time, is forcing me to - think much more about XP - have to leave XP. 
The alternative was to try a solution to this. But without knowing, which effort this topic is/was going to. 
There seams to be a solution, but had to go to XP from outside to the not running XP to be able to set in registry the ´XP-EMBedded (under WPA)´ to ´1´. Sorry, the not necessary this for here again also. 
The effort I had to stop, and You asked me: "why" this here. But I´ve been gone, and could not answer, and can´t now not there, from being closed. 
If You are convinced, this is not a topic for here, OK. 

(Just an idea: what about a forum outside of github, for such questions ?) 
Please, sorry again the effort this topic. 
And thanks for Your great work ! 
(Perhaps I now will use OEClassic or Thunderbird, still thinking about as possibility ..., OE6 I know so well, so would still prefer this. 
Thanks for reading. The interesst.)
