### ISSUE TITLE
uBlock

### ISSUE THREAD

**Issue by ghost** [Feodor2/Mypal68#9]
Спасибо Федор за сборку Firefox 68. Замечательная работа!
Хотел узнать, только у меня падает расширение uBlock Origin? А вот Adguard 3.6.17 работает нормально https://addons.mozilla.org/firefox/addon/adguard-adblocker/versions/

**Comment by grof017** [comment]
The same here with uBlock origin. NoScrypt and uMatrix works. Don't have any other issues for now,

**Comment by NoNameNeeded2** [comment]
uBlock seems to work fine for me.

**Comment by Anbima** [comment]
Install uBlock from:
https://addons.mozilla.org/de/firefox/addon/ublock-origin/

**Comment by Feodor2** [comment]
I think other extensions may break, epecialy same purpose, check with sole ublock only.

**Comment by skipster1337** [comment]
uBlock does indeed crash when I try to add custom filter lists in its settings. The tab crashes with the message "Gah! Your tab just crashed." and the extension becomes unusable in that its menu no longer comes up and the settings page is broken.
It used to work fine before and I could add custom filter lists properly, but something happened and now it does not work. I cleared the cache multiple times too.

**Comment by skipster1337** [comment]
I have switched to Adguard 3.6.17 and it works flawlessly. It is stable and does not crash, does not bring down the browser either. It also passes canyoublockit's Extreme test, which is great!

**Comment by grof017** [comment]
[98e4_appcompat.txt](https://github.com/Feodor2/Mypal68/files/8462614/98e4_appcompat.txt)               
Maybe this can help to solve problem with uBlock enabled ? Here is crash log.

**Comment by Feodor2** [comment]
@grof017
Nothing usefull sorry

I use latest ublock from firefox addons site - works all good, so do you really use one ublock without another such?

**Comment by Feodor2** [comment]
New information: ublock fails on older without sse3 cpus and winxp, but good on vista+ cpu whatever - needs further investigations.

**Comment by Feodor2** [comment]
Yeah it is hardware depended, today i do not realize why
The most recent and working. ublock i have found is 1.16.6

**Comment by skipster1337** [comment]
Wonderful, I installed 1.16.2 from the uBlock releases page on GitHub and it works perfectly.
https://github.com/gorhill/uBlock/releases/download/1.16.2/uBlock0.webext.xpi
Interestingly newer versions of uBlock didn't work well on my laptop despite it having SSE3, I guess it's just too low powered.
