### ISSUE TITLE
Updating Mypal-68 creates a new profile

### ISSUE THREAD

**Issue by gdl-blue** [Feodor2/Mypal68#92]
Every time I update Mypal-68, it creates a new profile. I have to go to about:profiles and launch my old profile

**Comment by IP-CAM** [comment]
thanks for pointing me to the right Solution ....

**Comment by win98se** [comment]
Would like to know what were your exact steps for updating Mypal68. I updated Mypal68 for 3 versions (68.12.2b, 68.12.3b, 68.12.4b) and much many times, such things doesn't happen to me though.

**Comment by IP-CAM** [comment]
Well, I don't update the Browser, I rename the old MyPal Browser Folder, and create a new installation. Then, I use the **about:profiles** command, to set the 'former' User Profile, to so have all the Settings, Passwords, e.t.c., as used in the former MyPal installation again.

**Comment by Feodor2** [comment]
Anyway i suggest make a copy profile for backup.
