### ISSUE TITLE
d3d9 hardware acceleration test

### ISSUE THREAD

**Issue by NoNameNeeded2** [Feodor2/Mypal68#93]
How will I know if d3d9 hardware acceleration works now in Mypal?
How can I test it?

**Comment by Feodor2** [comment]
In thw toubleshooting you will see
![image](https://user-images.githubusercontent.com/19492771/173233774-77d23ea9-f71f-403f-9195-8f5806df1158.png)
But how to evaluate real acceleraion i do not know myself, i watch the cpu load on heavy graphics site if its lower than without hwacc enabled than it works.

You all welcome to prompt better method.

**Comment by NoNameNeeded2** [comment]
It only says Basic in my case.

I don't know if it's because it's running in a virtual machine (VMWAre)...

**Comment by Feodor2** [comment]
https://github.com/Feodor2/Mypal68/issues/32#issuecomment-1100843166
Actually 4 is for dxva2 which is installed with .net4

**Comment by NoNameNeeded2** [comment]
Hmm...
None of the settings seem to work for me.
Except for the webgl stuff, which seems to work a little bit when I set webgl.force-enabled to enabled.
But that also seems to work in the last Mypal version, that's nothing new.

Anyway, I'll try Mypal on a real computer some day.
