### ISSUE TITLE
2 errors (in Options): setting update, adding search engine

### ISSUE THREAD

**Issue by visionhelp** [Feodor2/Mypal68#94]
(XP Prof. (Corporate) SP3) 

(By the way.) great: german (online) TV ((public) channels, the sound NOW does work, it doesn´t in NewMoon 27.10.0, 
not in ´palemoon-28.10.6a1 -xpmod´. 
The sound mostly as half as slow, as sound is in slow motion, but video itself OK. At least the videos from the Mediathek(s). But often not at all, if Live or Mediathek): the entire video.
(And having: github not working ALL well. But also now in Mypal68.) 
Thank you very much. 

Error: 
Options - ´Check for updates but choose to install´ - message: Write Failure 
´Unable to save preference. Could not write to file: $path´ 
 I prefer basically to download the complete new version, please. An option to download the full updated version would be very great, for me. 
 (A direct link to a download - in update notification - would be enough.)

Error:
Search engines add (search) does not work, no reaction. 
(I want to add https://www.ecosia.org/) 

Thanks in advance.

**Comment by Legendary-Candice-Joe** [comment]
Until Feodor fixes this, then heres what you can do for the search engines. If you install firefox on a windows 7 or 10 computer, click the add search engines button and copy the link to like a text file or something on a usb. You can use the extentions page for firefox just fine. But yeah this is a annoying.

**Comment by win98se** [comment]
You can do it with the separate search bar enabled -
![image](https://user-images.githubusercontent.com/11819816/173270889-a7574ecf-65c3-4492-9f35-9133195b9ca0.png)
P/S: Although it shows Windows 7 here, it should work as is as well in Windows XP.

When you visit ecosia\.org, Mypal68 will detect a new search engine so that you can add it and make it as default.

---

For the auto-update related settings, I doubt Feodor2 had done anything on it, because Mypal68 is feature-incomplete yet.

**Comment by visionhelp** [comment]
Thanks. 
Legendary-Candice-Joe
The search engine I added to the start-page (Top Sites), for now. (The search bar, right near address bar, it disturbs me there and not needing it I do not like to use and I did remove.) 
win98se
Thanks the pic. 
The auto-update setting:I can imagine, that it is an other effort, different to update automatically, than to be just noticed "an update is available" plus the further steps, but more there I really do not know. 
But this the more than not being helpful for me is: not may deny updates automatically.

**Comment by Feodor2** [comment]
Please one issue for one error,  i should have put this in the readme.
#52 about search
#82 NOT WORKING SITES LIST

So about update
Yes, this is a bug, but not to bother autoupdate is not set and do not work therefore.
I shall fix it later.,

**Comment by visionhelp** [comment]
Feodor2
OK. Sorry. 
Good to know, auto-update is set but does not work, thanks. 
The link the search engine I now have in/as ´Top Sites´, in ´Highlights´, in ´Bookmarks´. This is OK already, for me.

**Comment by visionhelp** [comment]
(With 68.13.1b, 2 (first tests) big german TV-channels do work now. Great.) 
My search engine (ecosia.org) is on Top-Sites, with other links, very great so, better than having just only one search engine site for start.
Auto-update: I prefer just a note about a new version, but then just directly with noted the link to http://www.mypal-browser.org/, for seperate download. 
Thank You very much.
