### ISSUE TITLE
Unresponsive Scripts on YouTube

### ISSUE THREAD

**Issue by robotman5XP** [Feodor2/Mypal68#97]
![mypalissuemaybe](https://user-images.githubusercontent.com/106999446/173701125-5f4b7961-c2d4-489f-9cf3-10e1f35b967b.PNG)

so i sometimes get this twice when i try to watch a YouTube video i always click continue and its fine afterwards.  Everything was working just fine on YouTube until this issue very recently.. dunno what i can do to fix.

**Comment by ChuckBartowski91** [comment]
This happens to me on other sites too

**Comment by dainiusb** [comment]
Same happens on Firefox 68.0 for me, I just click stop script and nothing seems to break.

**Comment by AroKol78** [comment]
try to downgrade the user-agent version for yt to 62
`general.useragent.override.youtube.com`

**Comment by neptune-ringgs** [comment]
@AroKol78 Thanks it works, I changed it to Firefox 59
