### ISSUE TITLE
How to add Mypal68 to CCleaner?

### ISSUE THREAD

**Issue by UnDeseo** [Feodor2/Mypal68#99]
I would like to know if it is possible to make MyPal68 work with CCleaner

**Comment by AstroSkipper** [comment]
You can set custom paths for cleaning in CCleaner's settings. Or you have to edit the file winapp2.ini loaded by CCEnhancer.

Cheers, AstroSkipper [![ecrire-ordi.gif](https://i.postimg.cc/g0mccjP2/ecrire-ordi.gif)](https://postimg.cc/1871J9tk)

**Comment by UnDeseo** [comment]
ty, do you explain how to use Ccenhancer with Mypal 68?

**Comment by visionhelp** [comment]
Feel as knowing nothing: CCleaner, how to add which path/es (of mypal to clean) to CCleaner where, please ? 
In ´settings´ -> ´user-defined´ I can imagine. 
(Thanks in advance.)
